##
# Makefile to build generic Daemon container image with Docker
##

CONTAINER_TYPE_FRIENDLY := Daemon
DOCKER_PROJECT          := daemon
TARBALL                 := ../../opennms-assemblies/daemon/target/*daemon*.tar.gz
TAR_STRIP_COMPONENTS    := 1

include ../common.mk
