// Allow GitHub image rendering
:imagesdir: ../../images

=== Overview

The Kafka Producer feature allows events, alarms and nodes from _{opennms-product-name}_ to be forwarded to Kafka.

These objects are stored in different topics and the payloads are encoded using link:https://developers.google.com/protocol-buffers/[Google Protocol Buffers], making it easy to consume from a variety of languages.
See `opennms-kafka-producer.proto` in the corresponding source distribution for the model definitions.

==== Events

The Kafka Producer listens for all events on the event bus and forwards these to a Kafka topic.
The records are keyed by event UEI and contain a GPB encoded model of the event.

By default, all events are forwarded to a topic named `events`.

The name of the topic used can be configured, and an optional filtering expression can be set to help control which events are sent to the topic.

==== Alarms

The Kafka Producer listens for changes made to the current set of alarms and forwards the resulting alarms to a Kafka topic.
The records are keyed by alarm reduction key and contain a GPB encoded model of the alarm.
When an alarm is deleted, a `null` value is sent with the corresponding reduction key.
Publishing records in this fashion allows the topic to be used as a link:https://docs.confluent.io/current/streams/concepts.html#ktable[KTable].

By default, all alarms (and subsequent updates) are forwarded to a topic named `alarms`.

The name of the topic used can be configured, and an optional filtering expression can be set to help control which alarms are sent to the topic.

==== Nodes

If an event or alarm being forwarded reference a node, then the corresponding node is also forwarded.
The records are keyed by "node criteria" (see bellow) and contain a GPB encoded model of the alarm.
A caching mechanism is in place to help avoid forwarding nodes that have been successfully forwarded, and have not changed since.

The name of the topic used can be configured.

IMPORTANT: The node topic is not intended to include all of the nodes in the system, it only includes records for nodes that relate to events or alarms that have been forwarded.

===== Node Criteria

The node criteria is a string representation of the unique identifier for a given node.
If the node is associated with a foreign source (fs)  and foreign id (fid), the node criteria resulting node criteria will be the name of the foreign source, followed by a colon (:) and then the foreign id i.e. (fs:fid).
If the node is not associated with both a foreign source and foreign id, then the node id (database id) will be used.

=== Enabling the Kafka Producer

The Kafka Producer is not enabled by default and can be enabled as follows.

First, login to the Karaf shell of your _{opennms-product-name}_ instance and configure the Kafka client settings to point to your Kafka broker.
See link:https://kafka.apache.org/10/documentation.html#producerconfigs[Producer Configs] for a complete list of available options.

[source]
----
$ ssh -p 8101 admin@localhost
...
admin@opennms()> config:edit org.opennms.features.kafka.producer.client
admin@opennms()> config:property-set bootstrap.servers 127.0.0.1:9092
admin@opennms()> config:update
----

Next, install the `opennms-kafka-producer` feature from that same shell using:
[source]
----
admin@opennms()> feature:install opennms-kafka-producer
----

In order to ensure that the feature continues to be installed as subsequent restarts, add `opennms-kafka-producer` to the `featuresBoot` property in the `${OPENNMS_HOME}/etc/org.apache.karaf.features.cfg`

=== Configuring the Kafka Producer

The Kafka Producer exposes the following options to help fine tune its behavior.

[options="header, autowidth"]
|===
| Name                    | Default Value        | Description
| `eventTopic`            | `events`             | Name of the topic used for events.
                                                   Set this to an empty string to disable forwarding events.
| `alarmTopic`            | `alarms`             | Name of the topic used for alarms.
                                                   Set this to an empty string to disable forwarding alarms.
| `nodeTopic`             | `nodes`              | Name of the topic used for nodes.
                                                   Set this to an empty string to disable forwarding nodes.
| `eventFilter`           | (none)               | A Spring SpEL expression (see bellow) used to filter events.
                                                   Set this to an empty string to disable filtering, and forward all events.
| `alarmFilter`           | (none)               | A Spring SpEL expression (see bellow) used to filter alarms.
                                                   Set this to an empty string to disable filtering, and forward all alarms.
| `nodeRefreshTimeoutMs`  | `300000` (5 minutes) | Number of milliseconds to wait before looking up a node in the database again.
                                                   Increase this to improve accuracy at the cost of additional database look ups.
|===

==== Filtering

Filtering can be used to selectively forward events and/or alarms to the Kafka topics.

Filtering is performed using a Spring SpEL expression link:https://docs.spring.io/spring/docs/4.2.9.RELEASE/spring-framework-reference/html/expressions.html[SpEL] which is evaluated against each object to determine if it should be forwarded.
The expression must return a boolean value i.e. `true` or `false`.

===== Enabling Event Filtering

To enable event filtering, set the value of the `eventFilter` property to a valid SpEL expression.

[source]
----
$ ssh -p 8101 admin@localhost
...
admin@opennms()> config:edit org.opennms.features.kafka.producer
admin@opennms()> config:property-set eventFilter 'getUei().equals("uei.opennms.org/internal/discovery/newSuspect")'
admin@opennms()> config:update
----

In the example above, the filter is configured such that only events with the given UEI are forwarded.
Consult the source code of the `org.opennms.netmgt.xml.event.OnmsEvent` class in your distribution for a complete list of available properties.

===== Enabling Alarm Filtering

To enable alarm filtering, set the value of the `alarmFilter` property to a valid SpEL expression.

[source]
----
$ ssh -p 8101 admin@localhost
...
admin@opennms()> config:edit org.opennms.features.kafka.producer
admin@opennms()> config:property-set alarmFilter 'getTTicketId() != null'
admin@opennms()> config:update
----

In the example above, the filter is configured such that only alarms that are associated with a ticket id are forwarded.
Consult the source code of the `org.opennms.netmgt.model.OnmsAlarm` class in your distribution for a complete list of available properties.

===== Configuring Topic Names

By default three topics are created i.e. `events`, `alarms`, `nodes`.
To change these, you can use:

[source]
----
$ ssh -p 8101 admin@localhost
...
admin@opennms()> config:edit org.opennms.features.kafka.producer
admin@opennms()> config:property-set eventTopic ""
admin@opennms()> config:property-set nodeTopic "opennms-nodes"
admin@opennms()> config:update
----

In the example above, we disable event forwarding by setting an empty topic name and change the node topic name to `opennms-nodes`.
