##
# Makefile to build Alarmd container image with Docker
##

CONTAINER_TYPE_FRIENDLY := Alarmd
DOCKER_PROJECT          := alarmd
TARBALL                 := ../../opennms-assemblies/alarmd/target/*alarmd*.tar.gz
TAR_STRIP_COMPONENTS    := 1

include ../common.mk
