
[[ga-notifications-introduction]]
= Notifications

{page-component-title} uses notifications to inform users about events that happen in the network.
Notifications allow you to keep track of your network status without having to log in and look at the UI.

Notifications are commonly sent through email or a pager message, but mechanisms also exist for the following:

* Browser-based desktop notifications
* Arbitrary HTTP GET and POST operations
* Arbitrary external commands
* Asterisk call origination
* IRCcat Internet Relay Chat bot
* SNMP traps
* Slack, Mattermost, and other API-compatible team chat platforms
* Twitter, GNU Social, and other API-compatible microblog services
* User-provided scripts in any JSR-223 compatible language
* XMPP

xref:reference:daemons/daemon-config-files/notifd.adoc[Notifd] creates and sends notifications according to configured rules when selected events occur in {page-component-title}.
For more information on configuring rules, see xref:operation:quick-start/notifications.adoc[Notifications] in the Quick Start section.

For a thorough understanding of notifications, you should be familiar with these core concepts:

* Events and UEIs
* Users, Groups, and On-Call Roles
* Duty Schedules
* Destination Paths
* Notification Commands

For more information on these core concepts, see xref:operation:deep-dive/notifications/concepts.adoc[Concepts] in the Deep Dive section.
