
// Allow GitHub image rendering
:imagesdir: ../../../images

[[ga-threshd-introduction]]
_{opennms-product-name}_ has the ability to monitor the performance of a managed entity's resource(s) by using various thresholding techniques.
These techniques, or algorithms, can be used applied against any metric data (telemetry) that has been gathered such as: CPU Load, Bandwidth, Disk space, etc. and, when triggered, causes Alarms to be generated.
There are a few basic thresholding algorithms available within OpenNMS:

* High
* Low
* Absolute Value
* Relative Change

=== Thresholding Service

The Thresholding Service is the component responsible for maintaining the state of performance metrics and generating alarms from these when thresholds are triggered (fired) or cleared (sdf).

The thresholding services listens for and visits performance metrics _after_ they are peristed in the time series database.

The state of the thresholds are held in memory and pushed to persistent storage when changed.

==== Distributed Thresholding with Sentinel

Thresholding for streaming telemetry (TODO LINK) is supports on Sentinel (TODO) when using Newts. Sessions are sticky. Protocols supporting sequence IDs.

=== Shell Commands

```
admin@opennms> opennms-threshold-states:enumerate 
Index   State Key
1       23-127.0.0.1-hrStorageIndex-hrStorageUsed / hrStorageSize * 100.0-/home/jesse/git/opennms/target/opennms-25.0.0-SNAPSHOT/share/rrd/snmp-RELATIVE_CHANGE
2       23-127.0.0.1-if-ifHCInOctets * 8 / 1000000 / ifHighSpeed * 100-/home/jesse/git/opennms/target/opennms-25.0.0-SNAPSHOT/share/rrd/snmp-HIGH
3       23-127.0.0.1-node-((loadavg5 / 100) / CpuNumCpus) * 100.0-/home/jesse/git/opennms/target/opennms-25.0.0-SNAPSHOT/share/rrd/snmp-HIGH
4       23-127.0.0.1-if-ifInDiscards + ifOutDiscards-/home/jesse/git/opennms/target/opennms-25.0.0-SNAPSHOT/share/rrd/snmp-HIGH
```


```
admin@opennms> opennms-threshold-states:details 1
multiplier=1.333
lastSample=64.77758166043765
previousTriggeringSample=28.862826722171075
interpolatedExpression='hrStorageUsed / hrStorageSize * 100.0'
```

```
admin@opennms> opennms-threshold-states:details 2
exceededCount=0
armed=true
interpolatedExpression='ifHCInOctets * 8 / 1000000 / ifHighSpeed * 100'
```

```
admin@opennms> opennms-threshold-states:clear 2
```

```
admin@opennms> opennms-threshold-states:clear-all 
Clearing all thresholding states....done
```
