/*
 * Licensed to The OpenNMS Group, Inc (TOG) under one or more
 * contributor license agreements.  See the LICENSE.md file
 * distributed with this work for additional information
 * regarding copyright ownership.
 *
 * TOG licenses this file to You under the GNU Affero General
 * Public License Version 3 (the "License") or (at your option)
 * any later version.  You may not use this file except in
 * compliance with the License.  You may obtain a copy of the
 * License at:
 *
 *      https://www.gnu.org/licenses/agpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.  See the License for the specific
 * language governing permissions and limitations under the
 * License.
 */
package org.opennms.netmgt.trapd;

import static org.opennms.core.utils.InetAddressUtils.str;

import java.net.InetAddress;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.opennms.core.utils.InetAddressUtils;
import org.opennms.netmgt.config.api.EventConfDao;
import org.opennms.netmgt.dao.api.InterfaceToNodeCache;
import org.opennms.netmgt.dao.api.MonitoringLocationDao;
import org.opennms.netmgt.events.api.EventConstants;
import org.opennms.netmgt.model.events.EventBuilder;
import org.opennms.netmgt.model.events.snmp.SyntaxToEvent;
import org.opennms.netmgt.snmp.SnmpObjId;
import org.opennms.netmgt.snmp.SnmpResult;
import org.opennms.netmgt.snmp.SnmpValue;
import org.opennms.netmgt.xml.event.AlarmData;
import org.opennms.netmgt.xml.event.Event;
import org.opennms.netmgt.xml.event.ManagedObject;
import org.opennms.netmgt.xml.event.Parm;
import org.opennms.netmgt.xml.event.UpdateField;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class EventCreator {
	
	private static final Logger LOG = LoggerFactory.getLogger(EventCreator.class);

    private final InterfaceToNodeCache cache;
    private final EventConfDao eventConfDao;

    public EventCreator(InterfaceToNodeCache cache, EventConfDao eventConfDao) {
        this.cache = Objects.requireNonNull(cache);
        this.eventConfDao = Objects.requireNonNull(eventConfDao);
    }

    public Event createEventFrom(final TrapDTO trapDTO, final String systemId, final String location, final InetAddress trapAddress) {
        LOG.debug("{} trap - trapInterface: {}", trapDTO.getVersion(), trapDTO.getAgentAddress());

        // Set event data
        final InetAddress sourceTrapAddress = Optional.ofNullable(trapDTO.getTrapAddress())
                .orElse(trapAddress);

        final EventBuilder eventBuilder = new EventBuilder(null, "trapd");
        eventBuilder.setTime(new Date(trapDTO.getCreationTime()));
        eventBuilder.setCommunity(trapDTO.getCommunity());
        eventBuilder.setSnmpTimeStamp(trapDTO.getTimestamp());
        eventBuilder.setSnmpVersion(trapDTO.getVersion());
        eventBuilder.setSnmpHost(str(sourceTrapAddress));
        eventBuilder.setInterface(sourceTrapAddress);
        eventBuilder.setHost(InetAddressUtils.toIpAddrString(trapDTO.getAgentAddress()));

        // Handle trap identity
        final TrapIdentityDTO trapIdentity = trapDTO.getTrapIdentity();
        if (trapIdentity != null) {
            LOG.debug("Trap Identity {}", trapIdentity);
            eventBuilder.setGeneric(trapIdentity.getGeneric());
            eventBuilder.setSpecific(trapIdentity.getSpecific());
            eventBuilder.setEnterpriseId(trapIdentity.getEnterpriseId());
            eventBuilder.setTrapOID(trapIdentity.getTrapOID());
        }

        // Handle var bindings
        for (SnmpResult eachResult : trapDTO.getResults()) {
            final SnmpObjId name = eachResult.getBase();
            final SnmpValue value = eachResult.getValue();
            eventBuilder.addParam(SyntaxToEvent.processSyntax(name.toString(), value));
            if (EventConstants.OID_SNMP_IFINDEX.isPrefixOf(name)) {
                eventBuilder.setIfIndex(value.toInt());
            }
        }

        // Resolve Node id and set, if known by OpenNMS
        resolveNodeId(location, sourceTrapAddress )
                .ifPresent(eventBuilder::setNodeid);

        // If there was no systemId in the trap message, assume that
        // it was generated by this system. Eventd will fill in the
        // systemId of the local system if it remains null here.
        if (systemId != null) {
            eventBuilder.setDistPoller(systemId);
        }

        // Match trap to event definition and apply UEI, severity, and alarm-data.
        // In the monolith, EventExpander (Eventd) applies these fields downstream.
        // In standalone daemon containers without Eventd, we must apply them here
        // so events arrive on Kafka fully formed for alarmd to process.
        final Event event = eventBuilder.getEvent();
        final org.opennms.netmgt.xml.eventconf.Event econf = eventConfDao.findByEvent(event);
        if (econf == null || econf.getUei() == null) {
            event.setUei("uei.opennms.org/default/trap");
        } else {
            event.setUei(econf.getUei());

            if (econf.getSeverity() != null) {
                event.setSeverity(econf.getSeverity());
            }

            if (econf.getAlarmData() != null) {
                applyAlarmData(event, econf.getAlarmData());
            }
        }
        return event;
    }

    /**
     * Copy alarm-data from the eventconf definition to the runtime event, expanding
     * parameter tokens in reduction-key and clear-key templates.
     */
    private static void applyAlarmData(Event event, org.opennms.netmgt.xml.eventconf.AlarmData econfAlarmData) {
        AlarmData alarmData = new AlarmData();
        alarmData.setAlarmType(econfAlarmData.getAlarmType());
        alarmData.setReductionKey(expandParms(econfAlarmData.getReductionKey(), event));
        alarmData.setAutoClean(econfAlarmData.getAutoClean());
        alarmData.setX733AlarmType(econfAlarmData.getX733AlarmType());
        alarmData.setX733ProbableCause(econfAlarmData.getX733ProbableCause());
        alarmData.setClearKey(expandParms(econfAlarmData.getClearKey(), event));

        List<org.opennms.netmgt.xml.eventconf.UpdateField> updateFieldList = econfAlarmData.getUpdateFields();
        if (!updateFieldList.isEmpty()) {
            List<UpdateField> updateFields = new ArrayList<>(updateFieldList.size());
            for (org.opennms.netmgt.xml.eventconf.UpdateField econfUpdateField : updateFieldList) {
                UpdateField eventField = new UpdateField();
                eventField.setFieldName(econfUpdateField.getFieldName());
                eventField.setUpdateOnReduction(econfUpdateField.getUpdateOnReduction());
                updateFields.add(eventField);
            }
            alarmData.setUpdateField(updateFields);
        }

        org.opennms.netmgt.xml.eventconf.ManagedObject econfMo = econfAlarmData.getManagedObject();
        if (econfMo != null) {
            ManagedObject mo = new ManagedObject();
            mo.setType(econfMo.getType());
            alarmData.setManagedObject(mo);
        }

        event.setAlarmData(alarmData);
    }

    /** Pattern matching %token% placeholders in reduction-key/clear-key templates. */
    private static final Pattern PARM_PATTERN = Pattern.compile("%([^%]+)%");

    /**
     * Lightweight parameter expansion for alarm-data reduction-key and clear-key
     * templates. Handles the tokens commonly used in eventconf alarm-data:
     * %uei%, %nodeid%, %interface%, %dpname%, %parm[#N]%, %parm[name]%.
     *
     * This is a simplified version of EventExpander's expandParms() that avoids
     * the heavy dependencies of AbstractEventUtil (Spring, Hibernate, etc.).
     */
    static String expandParms(String template, Event event) {
        if (template == null) {
            return null;
        }
        Matcher m = PARM_PATTERN.matcher(template);
        StringBuilder sb = new StringBuilder();
        while (m.find()) {
            String token = m.group(1);
            String replacement = resolveToken(token, event);
            m.appendReplacement(sb, Matcher.quoteReplacement(replacement != null ? replacement : ""));
        }
        m.appendTail(sb);
        return sb.toString();
    }

    private static String resolveToken(String token, Event event) {
        switch (token) {
            case "uei":
                return event.getUei();
            case "nodeid":
                return event.getNodeid() != null ? String.valueOf(event.getNodeid()) : "";
            case "interface":
                return event.getInterface() != null ? event.getInterface() : "";
            case "dpname":
                return event.getDistPoller() != null ? event.getDistPoller() : "";
            case "severity":
                return event.getSeverity() != null ? event.getSeverity() : "";
            case "source":
                return event.getSource() != null ? event.getSource() : "";
            case "host":
                return event.getHost() != null ? event.getHost() : "";
            case "snmphost":
                return event.getSnmphost() != null ? event.getSnmphost() : "";
            default:
                // Handle %parm[#N]% (1-based parameter index)
                // and %parm[name]% (named parameter)
                if (token.startsWith("parm[") && token.endsWith("]")) {
                    String parmRef = token.substring(5, token.length() - 1);
                    return resolveParm(parmRef, event);
                }
                return "";
        }
    }

    private static String resolveParm(String parmRef, Event event) {
        List<Parm> parms = event.getParmCollection();
        if (parms == null || parms.isEmpty()) {
            return "";
        }
        // %parm[#N]% — 1-based index
        if (parmRef.startsWith("#")) {
            try {
                int index = Integer.parseInt(parmRef.substring(1)) - 1;
                if (index >= 0 && index < parms.size()) {
                    return parms.get(index).getValue().getContent();
                }
            } catch (NumberFormatException e) {
                // fall through
            }
            return "";
        }
        // %parm[name]% — lookup by parameter name
        for (Parm parm : parms) {
            if (parmRef.equals(parm.getParmName())) {
                return parm.getValue() != null ? parm.getValue().getContent() : "";
            }
        }
        return "";
    }

    private Optional<Integer> resolveNodeId(String location, InetAddress trapAddress) {
        // If there was no location in the trap message, assume that
        // it was generated in the default location
        if (location == null) {
            return cache.getFirstNodeId(MonitoringLocationDao.DEFAULT_MONITORING_LOCATION_ID, trapAddress);
        }
        return cache.getFirstNodeId(location, trapAddress);
    }
}
