/*******************************************************************************
 * This file is part of OpenNMS(R).
 *
 * Copyright (C) 2004-2014 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2014 The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is a registered trademark of The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OpenNMS(R) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with OpenNMS(R).  If not, see:
 *      http://www.gnu.org/licenses/
 *
 * For more information contact:
 *     OpenNMS(R) Licensing <license@opennms.org>
 *     http://www.opennms.org/
 *     http://www.opennms.com/
 *******************************************************************************/

/* Generated By:JJTree: Do not edit this line. ParseMibTreeConstants.java */

public interface ParseMibTreeConstants
{
  public int JJTSTART = 0;
  public int JJTMIBBEGIN = 1;
  public int JJTIMPORTS = 2;
  public int JJTMODULEIDENTITY = 3;
  public int JJTDECLOID = 4;
  public int JJTEVENTS = 5;
  public int JJTTRAPTYPE = 6;
  public int JJTTABLESEQUENCEOF = 7;
  public int JJTINDEXOFTABLE = 8;
  public int JJTASSIGNMENT = 9;
  public int JJTSEQUENCEOFVARSORTEXTCONVENTION = 10;
  public int JJTTABLEOIDVARS = 11;
  public int JJTTEXTCONVENTION = 12;
  public int JJTIDENTIFIERINSEQUENCEOFVARS = 13;
  public int JJTEND = 14;
  public int JJTEXPRESSION = 15;
  public int JJTIDENTIFIER = 16;
  public int JJTOBJECTIDENTIFIER = 17;
  public int JJTPARENT = 18;
  public int JJTCHILDTEXTIDENTIFIER = 19;
  public int JJTCHILDNUMERICIDENTIFIER = 20;
  public int JJTMULTIPLEOIDS = 21;
  public int JJTSIZEDECLARATION = 22;
  public int JJTINTEGER = 23;
  public int JJTPARTIALOID = 24;
  public int JJTGETTYPEIDENTIFIER = 25;
  public int JJTGETACCESSIDENTIFIER = 26;


  public String[] jjtNodeName = {
    "Start",
    "MibBegin",
    "Imports",
    "ModuleIdentity",
    "DeclOID",
    "Events",
    "TrapType",
    "TableSequenceOf",
    "IndexOfTable",
    "Assignment",
    "SequenceOfVarsOrTextConvention",
    "TableOidVars",
    "TextConvention",
    "IdentifierInSequenceOfVars",
    "End",
    "Expression",
    "Identifier",
    "ObjectIdentifier",
    "Parent",
    "ChildTextIdentifier",
    "ChildNumericIdentifier",
    "MultipleOids",
    "SizeDeclaration",
    "Integer",
    "PartialOID",
    "GetTypeIdentifier",
    "GetAccessIdentifier",
  };
}
