
= Total Bytes Transferred by Interface Report

This report provides a summary of the total number of bytes transferred by each interface whose category matches the one specified.
The data is listed over a specified time period.

The report provides the following data for each interface:

* Bytes received.
* Bytes transmitted.
* Total bytes in and out.

You can customize this report with a company logo (approximately 195px by 50px) in the header and footer.

== Parameters

.Report customization parameters
[options="autowidth"]
|===
| Field | Description   | Default Value

| Surveillance Category
| One or more node tags to include in the report.
To select multiple tags, use wildcards as described below.
If no tags match the entered string, the report will have no data.
| Routers

| Start Date
| The starting date for the data contained in this report.
| _7 days before today_

| End Date
| The end date for the data contained in this report.
If the end date is later than the `Start Date`, the report will have no data.
| _Today_
|===

include::standard-text-fields.adoc[]
