
= Develop Custom Event Receiver

The event receiver listens for messages from an AMQP target and forwards them onto the internal event bus of _{product-title}_.
Messages are sent to a _Camel_ processor, which can filter or transform these, before being sent onto the event bus.

The event forwarer exposes the following properties via the `org.opennms.features.amqp.eventreceiver` pid:

[options="header"]
|===
| Property      | Default                                                         | Description
| connectionUrl | amqp://guest:guest@onms/test?brokerlist=\'tcp://127.0.0.1:5672' | Used by the AMQPConnectionFactory. See http://people.apache.org/~grkvlt/qpid-site/qpid-java/qpid-client/apidocs/org/apache/qpid/jms/ConnectionURL.html[ConnectionURL]
 for a full list of options.
| source        | amqp:OpenNMS-Queue                                              | Source queue or topic. See http://camel.apache.org/amqp.html[AMQP] for details.
| processorName | default-event-receiver-processor                                | Name `org.apache.camel.Processor` used to filter and/or format the events.
|===

The default processor, the `default-event-receiver-processor`, expects the message bodies to contain XML strings which are it unmarshalls to events.

== Setup

Start by logging into a Karaf shell.

Update the properties with your deployment specific values:

[source]
----
config:edit org.opennms.features.amqp.eventreceiver
config:property-set connectionUrl amqp://guest:guest@onms/test?brokerlist=\'tcp://127.0.0.1:5672\'
config:property-set source amqp:OpenNMS-Queue
config:property-set processorName default-event-receiver-processor
config:update
----

Install the feature:

[source]
----
feature:install opennms-amqp-event-receiver
----

== Debugging

You can get detailed information on the Camel route using:

[source]
----
camel:route-info receiveEvent
----
