
[[ga-events-event-definition]]
= Event Definition

[[ga-events-anatomy-of-an-event]]
== Anatomy of an event

Events are structured historical records of things that happen in {page-component-title} and the nodes, interfaces, and services it manages.
Every event has a number of fixed fields and zero or more parameters.

.Mandatory Fields
UEI (Unique Event Identifier)::
    A string uniquely identifying the event's type.
    UEIs are typically formatted in the style of a URI, but the only requirement is that they start with the string `uei.`.
Event Label::
    A short, static label summarizing the gist of all instances of this event.
Description::
    A long-form description of all instances of this event.
    HTML formatting can be used to format the body of the event text.
Log Message::
    A long-form log message describing this event, optionally including expansions of fields and parameters so that the value is tailored to the event at hand.
    The possible options for this setting are:
    logndisplay:::
        Both log the event in the database and display it in the Web UI.
    logonly:::
        Log the event in the database, but do not display it.
    suppress:::
        Neither log the event in the database or display it.
    donotpersist:::
        Do not log the event in the database, but still send it to daemons that are listening for this type of event, such as being used to generate notifications.
        Note that eventd and alarmd don't process this type of events.
    discardtraps:::
        This only applies to traps coming in via trapd.
        This will cause trapd to discard the trap without creating an event.
        Other daemons that are listening for this type of event will not receive this event.
Severity::
    A severity for this event type.
    Possible values range from `Cleared` to `Critical`.
Event ID::
    A numeric identifier used to look up a specific event in the {page-component-title} system.

.Notable Optional Fields
Operator Instruction::
    A set of instructions for an operator to respond appropriately to an event of this type.
Alarm Data::
    If this field is provided for an event, {page-component-title} will create, update, or clear alarms for events of that type according to the alarm-data specifics.
