
// Allow GitHub image rendering
:imagesdir: ../../../images

==== FtpMonitor

The FtpMonitor is able to validate ftp connection dial-up processes.
The monitor can test ftp server on multiple ports and specific login data.

The service using the FtpMonitor is _up_ if the FTP server responds with return codes between 200 and 299.
For special cases the service is also marked as _up_ for 425 and 530.


===== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.FtpMonitor`
| Remote Enabled | `true`
|===

===== Configuration and Usage

.Monitor specific parameters for the FtpMonitor.
[options="header, autowidth"]
|===
| Parameter              | Description                                                                                 | Required | Default value
| `retry`                | Number of attempts to get a valid FTP response/response-text                                | optional | `0`
| `port`                 | A list of TCP ports to which connection shall be tried.                                     | optional | `20`,`21`
| `password`             | This parameter is meant to be used together with the `user` parameter to perform basic
                           authentication. This parameter specify to password to be used. The `user` and `password`
                           parameters are ignored when the `basic-authentication` parameter is defined.                | optional | `empty string`
| `userid`               | This parameter is meant to be used together with the `password` parameter to perform
                           basic authentication. This parameter specify to user ID to be used. The `userid` and
                           `password` parameters are ignored when the `basic-authentication` parameter is defined.     | optional | `-`
|===

This monitor implements the <<ga-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

===== Examples

Some example configuration how to configure the monitor in the 'poller-configuration.xml'
[source, xml]
----
<service name="FTP" interval="300000" user-defined="false" status="on">
 <parameter key="retry" value="1"/>
 <parameter key="timeout" value="3000"/>
 <parameter key="port" value="21"/>
 <parameter key="userid" value=""/>
 <parameter key="password" value=""/>
</service>

<service name="FTP-Customer" interval="300000" user-defined="false" status="on">
 <parameter key="retry" value="1"/>
 <parameter key="timeout" value="3000"/>
 <parameter key="port" value="21"/>
 <parameter key="userid" value="Customer"/>
 <parameter key="password" value="MySecretPassword"/>
</service>

<monitor service="FTP" class-name="org.opennms.netmgt.poller.monitors.FtpMonitor"/>
<monitor service="FTP-Customer" class-name="org.opennms.netmgt.poller.monitors.FtpMonitor"/>
----

===== Hint

*Comment from FtpMonitor source*

Also want to accept the following ERROR message generated by some FTP servers following a QUIT command without a previous successful login:
"530 QUIT : User not logged in. Please login with USER and PASS first."

Also want to accept the following ERROR message generated by some FTP servers following a QUIT command without a previously successful login:
"425 Session is disconnected."

See also: http://tools.ietf.org/html/rfc959
