
// Allow GitHub image rendering
:imagesdir: ../../../images

==== JDBCMonitor

The _JDBCMonitor_ checks that it is able to connect to a database and checks if it is able to get the database catalog from that database management system (DBMS).
It is based on the http://www.oracle.com/technetwork/java/javase/jdbc/index.html[JDBC] technology to connect and communicate with the database.
This monitor implements <<ga-service-assurance-monitors-placeholder-substitution-parameters, placeholder substitution in parameter values>>.

===== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.JDBCMonitor`
| Remote Enabled | true
|===

===== Configuration and Usage

.Monitor specific parameters for the JDBCMonitor
[options="header, autowidth"]
|===
| Parameter  | Description                                                        | Required | Default value | Placeholder substitution
| `driver`   | JDBC driver class to use                                           | required | `org.postgresql.Driver` | No
| `url`      | JDBC Url to connect to.                                            | required | `jdbc:postgresql://:OPENNMS_JDBC_HOSTNAME/opennms` | Yes
| `user`     | Database user                                                      | required | `postgres` | Yes
| `password` | Database password                                                  | required | `empty string` | Yes
| `retries`  | How many retries should be performed before failing the test       | optional | `0` | No
|===

NOTE: The _OPENNMS_JDBC_HOSTNAME_ is replaced in the _url_ parameter with the IP or resolved hostname of the interface the monitored service is assigned to.

This monitor implements the <<ga-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

===== Provide the database driver

The _JDBCMonitor_ is based on _JDBC_ and requires a JDBC driver to communicate with any database.
Due to the fact that {opennms-product-name} itself uses a PostgreSQL database, the PostgreSQL JDBC driver is available out of the box.
For all other database systems a compatible JDBC driver has to be provided to {opennms-product-name} as a _jar-file_.
To provide a JDBC driver place the _driver-jar_ in the `opennms/lib` folder of your {opennms-product-name}.
To use the _JDBCMonitor_ from a remote poller, the _driver-jar_ has to be provided to the _Remote Poller_ too.
This may be tricky or impossible when using the _Java Webstart Remote Poller_, because of code signing requirements.


===== Examples

The following example checks if the PostgreSQL database used by {opennms-product-name} is available.

[source, xml]
----
<service name="OpenNMS-DBMS" interval="30000" user-defined="true" status="on">
  <parameter key="driver" value="org.postgresql.Driver"/>
  <parameter key="url" value="jdbc:postgresql://OPENNMS_JDBC_HOSTNAME:5432/opennms"/>
  <parameter key="user" value="opennms"/>
  <parameter key="password" value="opennms"/>
</service>

<monitor service="OpenNMS-DBMS" class-name="org.opennms.netmgt.poller.monitors.JDBCMonitor" />
----
