
// Allow GitHub image rendering
:imagesdir: ../../../images

==== JDBCStoredProcedureMonitor

The _JDBCStoredProcedureMonitor_ checks the result of a stored procedure in a remote database.
The result of the stored procedure has to be a boolean value (representing true or false).
The service associated with this monitor is marked as up if the stored procedure returns true and it is marked as down in all other cases.
It is based on the http://www.oracle.com/technetwork/java/javase/jdbc/index.html[JDBC] technology to connect and communicate with the database.

===== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.JDBCStoredProcedureMonitor`
| Remote Enabled | false
|===

===== Configuration and Usage

.Monitor specific parameters for the JDBCStoredProcedureMonitor
[options="header, autowidth"]
|===
| Parameter          | Description                                                        | Required | Default value
| `driver`           | JDBC driver class to use                                           | required | `org.postgresql.Driver`
| `url`              | JDBC Url to connect to.                                            | required | `jdbc:postgresql://:OPENNMS_JDBC_HOSTNAME/opennms`
| `user`             | Database user                                                      | required | `postgres`
| `password`         | Database password                                                  | required | `empty string`
| `retries`          | How many retries should be performed before failing the test       | optional | `0`
| `stored-procedure` | Name of the database stored procedure to call                      | required | `-`
| `schema`           | Name of the database schema in which the stored procedure is       | optional | `test`
|===

NOTE: The _OPENNMS_JDBC_HOSTNAME_ is replaced in the _url_ parameter with the IP or resolved hostname of the interface the monitored service is assigned to.

This monitor implements the <<ga-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

===== Provide the database driver

The _JDBCStoredProcedureMonitor_ is based on _JDBC_ and requires a _JDBC driver_ to communicate with any database.
Due to the fact that {opennms-product-name} itself uses a _PostgreSQL_ database, the _PostgreSQL JDBC driver_ is available out of the box.
For all other database systems a compatible _JDBC driver_ has to be provided to {opennms-product-name} as a _jar-file_.
To provide a _JDBC driver_ place the _driver-jar_ in the `opennms/lib` folder of your {opennms-product-name}.
To use the _JDBCStoredProcedureMonitor_ from a remote poller, the _driver-jar_ has to be provided to the _Remote Poller_ too.
This may be tricky or impossible when using the _Java Webstart Remote Poller_, because of code signing requirements.


===== Examples

The following example checks a stored procedure added to the _PostgreSQL_ database used by {opennms-product-name}.
The stored procedure returns true as long as less than 250000 events are in the events table of {opennms-product-name}.

.Stored procedure which is used in the monitor
[source, sql]
----
CREATE OR REPLACE FUNCTION eventlimit_sp() RETURNS boolean AS
$BODY$DECLARE
num_events integer;
BEGIN
	SELECT COUNT(*) into num_events from events;
	RETURN num_events > 250000;
END;$BODY$
LANGUAGE plpgsql VOLATILE NOT LEAKPROOF
COST 100;
----

[source, xml]
----
<service name="OpenNMS-DB-SP-Event-Limit" interval="300000" user-defined="true" status="on">
  <parameter key="driver" value="org.postgresql.Driver"/>
  <parameter key="url" value="jdbc:postgresql://OPENNMS_JDBC_HOSTNAME:5432/opennms"/>
  <parameter key="user" value="opennms"/>
  <parameter key="password" value="opennms"/>
  <parameter key="stored-procedure" value="eventlimit_sp"/>
  <parameter key="schema" value="public"/>
</service>

<monitor service="OpenNMS-DB-SP-Event-Limit" class-name="org.opennms.netmgt.poller.monitors.JDBCStoredProcedureMonitor"/>
----
