[[poller-jmx-monitor]]
==== JmxMonitor

The JMX monitor allows to test service availability of Java applications.
The monitor offers the following functionalities:

* test the application's connectivity via JMX
* existence of management beans
* test the status of a single or multiple management beans and evaluate their value

===== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.Jsr160Monitor`
| Remote Enabled | `true`
|===

===== Configuration and Usage

.Monitor specific parameters for the JmxMonitor
[options="header, autowidth"]
|===
| Parameter               | Description                                                 | Required | Default value
| `retry`                 | Number of attempts to get a response.                       | optional | `3`
| `timeout`               | Time in milliseconds to wait for a response.                | optional | `?`
| `port`                  | Destination port where the JMX requests shall be sent.      | optional | from `jmx-config.xml`
| `beans.<variable>`      | Defines a mbeans objectname to access. ´<variable>´ name is +
                            arbitrary.                                                  | optional | `-`
| `tests.<variable>`      | Tests a mbeans attribute value. ´<variable>´ name is +
                            arbitrary.                                                  | optional | `-`
|===

===== Examples

.Test if a JMX connection can be established
[source, xml]
----
<service name="JMX-Connection-Test" interval="300000" user-defined="false" status="on">
  <parameter key="retry" value="3"/>
  <parameter key="timeout" value="3000"/>
  <parameter key="port" value="18980"/>
</service>
<monitor service="JMX-Connection-Test" class-name="org.opennms.netmgt.poller.monitors.JmxMonitor"/>
----

.Test a specific management bean for a value
[source, xml]
----
<service name="JMX-BeanValue-Test" interval="300000" user-defined="false" status="on">
  <parameter key="retry" value="3"/>
  <parameter key="timeout" value="3000"/>
  <parameter key="port" value="18980"/>
  <parameter key="beans.connected" value="org.opennms.workflow:name=client.onms.connected"/>
  <parameter key="tests.isConnected" value="connected.get(&quot;Value&quot;) == true"/>
</service>
<monitor service="JMX-BeanValue-Test" class-name="org.opennms.netmgt.poller.monitors.Jsr160Monitor"/>
----

CAUTION: Reserved XML characters like *>*, *<*, *"* need to be escaped.
