
// Allow GitHub image rendering
:imagesdir: ../../../images

==== OpenManageChassisMonitor

The _OpenManageChassis_ monitor tests the status of a _Dell_ chassis by querying its _SNMP_ agent.
The monitor polls the value of the node's _SNMP OID_ .1.3.6.1.4.1.674.10892.1.300.10.1.4.1 (MIB-Dell-10892::chassisStatus).
If the value is _OK_ (3), the service is considered available.

As this monitor uses _SNMP_, the queried nodes must have proper _SNMP_ configuration in _snmp-config.xml_.

===== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.OpenManageChassisMonitor`
| Remote Enabled | false
|===

===== Configuration and Usage

.Monitor specific parameters for the OpenManageChassisMonitor
[options="header, autowidth"]
|===
| Parameter | Description                                                        | Required | Default value
| `port`    | The port to which connection shall be tried.                       | optional | from `snmp-config.xml`
|===

This monitor implements the <<ga-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

===== Examples

[source, xml]
----
<!-- Overriding default SNMP config -->
<service name="OMA-Chassis" interval="300000" user-defined="false" status="on">
  <parameter key="retry" value="3"/>
  <parameter key="timeout" value="5000"/>
</service>

<monitor service="OMA-Chassis" class-name="org.opennms.netmgt.poller.monitors.OpenManageChassisMonitor" />
----

===== Dell MIBs

_Dell MIBs_ can be found link:ftp://ftp.us.dell.com/sysman[here].
Download the _DCMIB<version>.zip_ or _DCMIB<version>.exe_ file corresponding to the version of your _OpenManage_ agents.
The latest one should be good enough for all previous version though.
