
// Allow GitHub image rendering
:imagesdir: ../../../images

==== PercMonitor

This monitor tests the status of a _PERC RAID_ array.

The monitor first polls the _RAID-Adapter-MIB::logicaldriveTable_ (1.3.6.1.4.1.3582.1.1.2) to retrieve the status of the _RAID_ array you want to monitor.
If the value of the status object of the corresponding _logicaldriveEntry_ is not 2, the array is degraded and the monitor further polls the _RAID-Adapter-MIB::physicaldriveTable_ (1.3.6.1.4.1.3582.1.1.3) to detect the failed drive(s).

IMPORTANT: This monitor requires the outdated persnmpd software to be installed on the polled nodes. 
           Please prefer using <<OmsaStorageMonitor>> monitor where possible.

===== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.PercMonitor`
| Remote Enabled | false (relies on SNMP configuration)
|===

===== Configuration and Usage

.Monitor specific parameters for the PercMonitor
[options="header, autowidth"]
|===
| Parameter        | Description                         | Required | Default value
| `array`          | The RAID array you want to monitor. | optional | `0.0`
| `port`           | The UDP port to connect to          | optional | `from snmp-config.xml`
|===

This monitor implements the <<ga-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

===== Examples

[source, xml]
----
<!-- Monitor 1st RAID arrays using configuration from snmp-config.xml -->
<service name="PERC" interval="300000" user-defined="false" status="on" />

<monitor service="PERC" class-name="org.opennms.netmgt.poller.monitors.PercMonitor" />
----
