= Grpc Exporter
:description: Learn how the gRPC Exporter enables {page-component-title} to forward the status of monitored services to external applications.

The Grpc Exporter feature allows {page-component-title} to forward the status of all monitored services to external applications via the gRPC protocol.

These objects are encoded using link:https://developers.google.com/protocol-buffers/[Google Protocol Buffers (GPB)].
See `monitored-services.proto` in the corresponding source distribution for the model definitions.

== Configure gRPC Exporter

[source, karaf]
----
$ ssh -p 8101 admin@localhost
...
admin@opennms()> config:edit org.opennms.features.grpc.exporter
admin@opennms()> config:property-set host bsm.onmshs.local:1440 <1>
admin@opennms()> config:property-set tls.cert.path /opt/opennms/etc/tls.cert <2>
admin@opennms()> config:property-set tls.enabled false <3>
admin@opennms()> config:property-set snapshot.interval 3600 false <4>
admin@opennms()> config:update
----

<1> Set the hostname of the external gRPC application.
<2> Configure the path to the TLS certificate.
<3> TLS is enabled by default. For testing purposes, it can be disabled by setting this value to false.
<4> Set the interval (in seconds) at which the complete snapshot of services will be sent to the gRPC server.

== Enable gRPC Exporter

Install the `opennms-grpc-exporter` feature from the same shell using:

[source, karaf]
----
feature:install opennms-grpc-exporter
----

To ensure the feature is installed on subsequent restarts, add `opennms-grpc-exporter` to a file in featuresBoot.d:
[source, console]
----
echo "opennms-grpc-exporter" | sudo tee ${OPENNMS_HOME}/etc/featuresBoot.d/grpc-exporter.boot
----