
= SameSite Cookie Attribute

The SameSite Cookie Attribute was introduced to control access to cookies and helps to prevent various XSS- and CSRF-attacks.
This attribute tells browsers how to handle first- or third-party cookies and identifies whether or not to allow a cookie to be accessed.

OpenNMS ships with the most secure configuration *strict* for its session cookie.
This means, that the session cookie will not be sent for any cross-site request.
There may be environments where a user want to relax this enforcement by setting the SameSite attribute to *lax*.

== Relaxing the SameSite Attribute enforcement policy

In order to change the enforcement policy, you need to alter the file `$OPENNMS_HOME/jetty-webapps/opennms/WEB-INF/web.xml`.

[source, xml]
----
<session-config>
  <cookie-config>
    <http-only>true</http-only>
    <comment>__SAME_SITE_STRICT__</comment> <1>
  </cookie-config>
  <session-timeout>-1</session-timeout>
</session-config>
----
<1> Replace `__SAME_SITE_STRICT__` with `__SAME_SITE_LAX__` to change the enforcement policy to *lax*.

