
// Allow GitHub image rendering
:imagesdir: ../../../images

=== Classification Engine

The _Classification Engine_ applies a set of user- and/or system-defined rules to each flow to classify it.
This allows users to group flows by applications, e.g. if all traffic to port 80 is marked as `http`.

In order to classify a flow, a rule can be defined.
A rule defines at least a name, which the flow is classified with, and additional parameters which must match for a successful classification.

==== Rule definition
A rule has the following parameters:
Name		mandatory, the name the flow is classified with, e.g. `http`
dstPort		optional, the dstPort of the flow must match this port (may be a range or list of ports, e.g. 80,8080,8980, or 8000-9000)
dstAddress 	optional, the dstAddress of the flow must match this address. May contain wildcards
srcPort		optional, the srcPort of the flow must match this port (see dstPort for more details)
srcAddress	optional, the srcAddress of the flow must match this address (see dstAddress for more details)
exporterFilter	optional	the exporter of the flow must match this criteria. It supports all capabilities of the _Filter API_ (TODO add link)
Protocol	optional	the ip protocol of the flow must match this criteria.

Even if all fields are optional, at least one must be defined. A list of pre-defined rules (TODO add link to IANA rules) already exist. New rules can be defined using the _Classification UI_ (TODO add link to ui, maybe screenshot?)

==== Rule Priority
User-defined rules always have a higher priority than the pre-defined rules.
For example, if the user defines a new rule, `http` with a `dstPort` of `8980` that rule has a higher priority than the pre-defined rule `www-alt`.

The priorities are as follows:
	Field			priority
srcAddress		9
dstAddress		9
srcPort			3
dstPort			3
Protocol		1
exportFilter		1

This means a rule with a srcAddress or dstAddress has always a higher priority than a rule with a src or dst port, etc.

In detail, the priority is calculated as follows:
https://github.com/OpenNMS/opennms/blob/bdac58683457352b71af11a63c3118eb8b887f6b/features/flows/classification/persistence/api/src/main/java/org/opennms/netmgt/flows/classification/persistence/api/RuleDefinition.java#L52-61

NOTE:   At the moment it is not possible to manually define a priority.
        This may be implemented at a later time.
        See issue https://issues.opennms.org/browse/HZN-1265.

==== Example
TODO
