
// Allow GitHub image rendering
:imagesdir: ../../images

_Enhanced Linkd (Enlinkd)_ has been designed to discover connections between nodes using data generated by various link discovery protocols and accessible via SNMP.
_Enlinkd_ gathers this data on a regular interval and creates a snapshot of a device's neighbors from its perspective by SNMP Data Collectors. 
_Enlinkd_ consolidate the collected Data by Bridge Domain Discovery and Topologies Updater.

_Enlinkd-Bridge Domain Discovery_ use the data gathered by Bridge and IpNetToMedia collectors to
provide Bridge Broadcast Domain layout. The Bridge Forwarding Table provided by the single nodes display information about mac address learned on which bridge port, this is what the Bridge consider a Connection: this is not very useful so Bridge Discovery will perform domain calculation to assign to every mac address the port where the device that holds it is effective connected (Or the known nearest bridge port).

_Enlinkd-Updaters_, for every supported discovery protocol, use the provided Topologies Update API to provide connections information to other OpenNMS service and daemon via OnmsTopologyDao. The provided topologies are used in topology-map and for sending TopologyMessage via Kafka Producer.

The connections discovered by _Enlinkd_ collectors and by Bridge Domain Discovery are called _Links_.
The term _Link_, within the context of _Enlinkd_, is not synonymous with the term "link" when used with respect to the network OSI _Layer 2_ domain, whereby a link only indicates a _Layer 2_ connection.
A _Link_ in context of _Enlinkd_ is a more abstract concept and is used to describe any connection between two _{opennms-product-name} Nodes_.
These _Links_ are discovered based on information provided by an agent's understanding of connections at the OSI _Layer 2_, _Layer 3_, or other OSI layers.

The Topologies discovered by _Enlinkd-Updaters_ are made of _Vertices_ and _Edges_.

The following sections describe the _Enlinkd_ daemon and its configuration.
Additionally, the supported _Link discovery_ implementations will be described as well as a list of the SNMP MIBs that the SNMP agents must expose in order for _EnLinkd_ to gather _Links_ between _Nodes_.
FYI: Detailed information about a node's connections (discovered _Links_) and supporting link data can be seen on the _Node detail page_ within the _{opennms-product-name}_ Web-UI.

[[ga-enlinkd-daemon]]
=== Enlinkd Daemon

Essentially each _Enlinkd-Collector_ asks each device the following question: "What is the network topology from your point of view", this will provide local topology discovery features.

The _Enlinkd-Discovery_ does attempt to discover bridge domain _Links_ with the data coming from all collected _Bridge Forwarding Tables_.

The _Enlinkd-Updaters_ does attempt to discover global _OnmsTopology_ doing correlation with the data coming from all node discovered _Links_.

For large environments the behavior of _Enlinkd_ can be configured.
During the _EnLink_ discovery process informational and error output is logged to a global log file.

.Global log and configuration files for _Enlinkd_
[options="header, autowidth"]
|===
| File                        | Location             | Description
| `enlinkd-configuration.xml` | `$OPENNMS_HOME/etc`  | Global configuration for the daemon process
| `enlinkd.log`               | `$OPENNMS_HOME/logs` | Global _Enlinkd_ log file
| `log4j2.xml`                | `$OPENNMS_HOME/etc`  | Configuration file to set the log level for _Enlinkd_
|===

.Configuration file for _Enlinkd_
[source, xml]
----
<?xml version="1.0" encoding="ISO-8859-1"?>
<enlinkd-configuration threads="5" 
                     initial_sleep_time="60000"
                     rescan_interval="86400000" 
                     use-cdp-discovery="true"
                     use-bridge-discovery="true"
                     use-lldp-discovery="true"
                     use-ospf-discovery="true"
                     use-isis-discovery="true"
                     topology_interval="30000"
                     bridge_topology_interval="300000"
                     max_bft="100"
                     discovery-bridge-threads="1"
                     />
----

.Descriptione for global configuration parameter
[options="header, autowidth"]
|===
| Attribute              | Type      | Default    | Description
| `threads`              | _Integer_ | `5`        | Number of parallel threads used by _Collectors_,  _Updaters_ and _Discovery_.
| `initial_sleep_time`   | _Integer_ | `60000`    | Time in milliseconds to wait for start _Collectors_  after {opennms-product-name} is started.
| `rescan_interval`      | _Integer_ | `86400000` | Interval in milliseconds for _Collectors_.
| `topology_interval`    | _Integer_ | `30000`   | Interval in milliseconds for _Updaters_.
| `bridge_topology_interval`    | _Integer_ | `300000`   | Interval in milliseconds for _Discovery_.
| `max_bft`              | _Integer_ | `100`      | the max number of bft stored in memory for _Discovery_. 
| `discovery-bridge-threads`| _Integer_ | `1`   | the number of threads used for _Discovery_.
| `use-cdp-discovery`    | _Boolean_ | `true`     | Enable or disable discovery based on _CDP_ information.
| `use-bridge-discovery` | _Boolean_ | `true`     | Enable or disable discovery based on the _Bridge_ information.
| `use-lldp-discovery`   | _Boolean_ | `true`     | Enable or disable discovery based on _LLDP_ information.
| `use-ospf-discovery`   | _Boolean_ | `true`     | Enable or disable discovery based on _OSPF_ information.
| `use-isis-discovery`   | _Boolean_ | `true`     | Enable or disable discovery based on _IS-IS_ information.
|===

The _Discovery_ for bridge first start is scheduled at _initial_sleep_time + bridge_topology_interval_.
The _Updaters_ first start are scheduled at _0L_.
Configuration changes are applied by restarting OpenNMS and Enlinkd. It is also possible to send an Event to Enlinkd reloading the configuration. An Event can be sent on the CLI or the Web User Interface.	

.Send configuration reload event on CLI

[source, shell]
----
cd $OPENNMS_HOME/bin
./send-event.pl uei.opennms.org/internal/reloadDaemonConfig --parm 'daemonName Enlinkd'
----


NOTE: If multiple protocols are enabled, the links will be discovered for each enabled discovery protocol.
      The topology WebUI will visualize _Links_ for each discovery protocol.
      For example if you start _CDP_ and _LLDP_ discovery, the WebUI will visualize a _CDP Link_ and an _LLDP Link_.
