
// Allow image rendering
:imagesdir: ../../images

[[gd-docs-include-source]]
=== Code Snippets

You can include code snippets, configuration- or source code files in the documentation.
You can enable syntax highlighting by providing the given language parameter, this will work on source code or configuration.

[[gd-docs-explicit]]
==== Explicitly defined in the document

WARNING: be careful to use this kind of code snippets as sparsely as possible.
Code becomes obsolete very quickly, archaic usage practices are detrimental.

if you do wish to include snippets use the following method:

.This is a sample configuration explicitly in the documentation
[source,xml]
----
<service name="DNS" interval="300000" user-defined="false" status="on">
  <parameter key="retry" value="2" />
  <parameter key="timeout" value="5000" />
  <parameter key="port" value="53" />
  <parameter key="lookup" value="localhost" />
  <parameter key="fatal-response-codes" value="2,3,5" /><!-- ServFail, NXDomain, Refused -->
  <parameter key="rrd-repository" value="/opt/opennms/share/rrd/response" />
  <parameter key="rrd-base-name" value="dns" />
  <parameter key="ds-name" value="dns" />
</service>
----

If there's no suitable syntax highlighter for the code used just omit the language: +[source]+.

Currently the following syntax highlighters are enabled:

* Bash
* Groovy
* Java
* JavaScript
* Python
* XML

For other highlighters that could be added see https://code.google.com/p/google-code-prettify/.

[[gd-docs-include]]
==== Included from an example file

You can include source or configuration from an external file.
In this way you can provide a working example configuration maintaining doc and example at the same time.
The procedure and rules are the same as with images, the path is relative to the *.adoc file where the file to be used is included.

.Include complete external file
 [source,xml]
 ----
 include::../configs/wmi-config.xml[]
 ----

This is how it's rendered:

[source,xml]
----
include::../configs/wmi-config.xml[]
----

[[gd-docs-include-parts]]
==== Include parts of a file

If you want to include just a specific segment of a large configuration file, you can assign tags that indicate to AsciiDoc the section that is to be included.
In this example just the service definition of the _ICMP monitor_ should be included.

In the 'poller-configuration.xml' tag the section in the following manner:

[source,xml]
----
...
<rrd step="300">
  <rra>RRA:AVERAGE:0.5:1:2016</rra>
  <rra>RRA:AVERAGE:0.5:12:1488</rra>
  <rra>RRA:AVERAGE:0.5:288:366</rra>
  <rra>RRA:MAX:0.5:288:366</rra>
  <rra>RRA:MIN:0.5:288:366</rra>
</rrd>
<!-- # tag::IcmpServiceConfig[] -->
<service name="ICMP" interval="300000" user-defined="false" status="on">
  <parameter key="retry" value="2" />
  <parameter key="timeout" value="3000" />
  <parameter key="rrd-repository" value="/opt/opennms/share/rrd/response" />
  <parameter key="rrd-base-name" value="icmp" />
  <parameter key="ds-name" value="icmp" />
</service>
<!-- # end::IcmpServiceConfig[] -->
<service name="DNS" interval="300000" user-defined="false" status="on">
  <parameter key="retry" value="2" />
  <parameter key="timeout" value="5000" />
  <parameter key="port" value="53" />
...
----

.Include this tagged part in the documentation using the _tag_ parameter
 [source,xml]
 ----
 include::../configs/poller-configuration.xml[tags=IcmpServiceConfig]
 ----

.This is how it rendered
[source,xml]
include::../configs/poller-configuration.xml[tags=IcmpServiceConfig]

NOTE: Spaces and tabs are taken from the original file.
