--
-- OPENNMS-MIB       module definition
--

-- Copyright (C) 2005 by The OpenNMS Group, Inc.


-- Version 1.0 - 2005-01-13: 	The main purpose of this first version of
--				the OpenNMS MIB is to instrument the values
--				passed in the trap sent by scriptd in the
--				example configuration file.

OPENNMS-MIB DEFINITIONS ::= BEGIN
IMPORTS
   OBJECT-TYPE FROM RFC-1212
   DisplayString FROM RFC1213-MIB
   enterprises FROM RFC1155-SMI
   TRAP-TYPE FROM RFC-1215
   TimeTicks FROM RFC1155-SMI
   IpAddress FROM RFC1155-SMI;

OpenNMS				OBJECT IDENTIFIER
							::= { enterprises 5813 }

OpenNMS-traps			OBJECT IDENTIFIER
							::= { OpenNMS 1 }

OpenNMS-data			OBJECT IDENTIFIER
							::= { OpenNMS 20 }

OpenNMS-events			OBJECT IDENTIFIER
							::= { OpenNMS-data 1 }

OpenNMS-event-dbid		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the database ID for the event."
	::= { OpenNMS-events 1 }

OpenNMS-event-distPoller	OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the distributed poller name for the event."
	::= { OpenNMS-events 2 }

OpenNMS-event-create-time	OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the time the event was created in the database."
	::= { OpenNMS-events 3 }

OpenNMS-event-master-station	OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the name of the master station for the event."
	::= { OpenNMS-events 4 }

OpenNMS-event-uei		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the Unique Event Identifier (UEI) for the event."
	::= { OpenNMS-events 6 }

OpenNMS-event-source		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the source of the event, such as Capsd."
	::= { OpenNMS-events 7 }

OpenNMS-event-nodeid		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the Node ID for the event."
	::= { OpenNMS-events 8 }

OpenNMS-event-time		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the time the event occurred."
	::= { OpenNMS-events 9 }

OpenNMS-event-host		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the host for the event."
	::= { OpenNMS-events 10 }

OpenNMS-event-interface		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the interface for the event."
	::= { OpenNMS-events 11 }

OpenNMS-event-snmphost		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the SNMP host for the event."
	::= { OpenNMS-events 12 }

OpenNMS-event-service		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the service name for the event."
	::= { OpenNMS-events 13 }

OpenNMS-event-descr		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the description of the event."
	::= { OpenNMS-events 16 }

OpenNMS-event-severity		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the severity of the event."
	::= { OpenNMS-events 18 }

OpenNMS-event-pathoutage	OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the path outage information for the event."
	::= { OpenNMS-events 19 }

OpenNMS-event-operinst		OBJECT-TYPE
	SYNTAX		DisplayString
	ACCESS		read-only
	STATUS		mandatory
	DESCRIPTION 	"This is the operator instructions for the event."
	::= { OpenNMS-events 20 }

OpenNMS-Generic-Trap		TRAP-TYPE
	ENTERPRISE OpenNMS-traps
	VARIABLES {
		OpenNMS-event-dbid,
		OpenNMS-event-distPoller,
		OpenNMS-event-create-time,
		OpenNMS-event-master-station,
		OpenNMS-event-uei,
		OpenNMS-event-source,
		OpenNMS-event-nodeid,
		OpenNMS-event-time,
		OpenNMS-event-host,
		OpenNMS-event-interface,
		OpenNMS-event-snmphost,
		OpenNMS-event-service,
		OpenNMS-event-descr,
		OpenNMS-event-severity,
		OpenNMS-event-pathoutage,
		OpenNMS-event-operinst
		}
	DESCRIPTION 
	"This is the definition of the generic OpenNMS trap sent from the
        scriptd process. Key variables are uei (which tells what type
        of OpenNMS event this was), interface (the IP address of the interface
	that caused the event) and severity."
	::= 1

END





