
[[upgrade]]
= Upgrade {page-component-title}

This section outlines the steps to follow to upgrade to a newer version of {page-component-title}.
You may need to complete additional steps to upgrade in a more complex setup (running more than one OpenNMS instance, database migration requirements, age of current version, and so on).

A basic upgrade of one instance can take about an hour.
This time varies, and will be longer depending on how customized and complex your setup is.

[[byb_upgrade]]
== Before you begin

There are a number of tasks you should complete before starting an upgrade:

ifeval::["{page-component-title}" == "Meridian"]
* Check the https://meridian.opennms.com/[release notes] for breaking changes in each release between your current version and the version you want to upgrade to.
Address any issues that might affect you.
endif::[]

ifeval::["{page-component-title}" == "Horizon"]
* Check the https://vault.opennms.com/docs/opennms/releases/index.html[release notes] for breaking changes in each release between your current version and the version you want to upgrade to.
Address any issues that might affect you.
+
NOTE: Release notes for versions 28 and later are not available at the vault docs link (above) at this time.
Please check the branches on https://github.com/OpenNMS/opennms/releases[GitHub] for those release notes.
endif::[]

* Stop OpenNMS and PostgreSQL services.
* xref:operation:admin/housekeeping/introduction.adoc#prune-events[Prune unneeded events].
* Back up your database. (same day/state)
* Back up RRD files. (same day/state)
* Back up the `$\{OPENNMS_HOME}/etc` directory. (same day/state)
* <<events-table,Assess the events table size>>.
Especially important if you have a particularly large network with lots of events.
* xref:deployment:upgrade/diff.adoc#run_diff[Identify the configuration files] you have changed to determine what you need to migrate as part of an upgrade.

[[events-table]]
== Assess Events Table Size
If, after xref:operation:admin/housekeeping/introduction.adoc#prune-events[pruning unneeded events], you still have a large number of events, you may need to increase the amount of memory passed to the OpenNMS install tool.
For example, if you have 250k events, you will need almost 600MB of heap.
When you upgrade and have the available memory, choose a large value to pass to the install, as in the following:

[source, console]
----
${OPENNMS_HOME}/bin/install -Xms1024m -Xmx2048m -dis
----
