
// Allow GitHub image rendering
:imagesdir: ../../images

The telemetry daemon (_telemetryd_) provides an extensible framework that can be used to handle sensor pushed to _{opennms-product-name}_.

_telemetryd_ allows operators to define a series of protocols, each of which has at least one listener, and at least one adapter.
A listener is responsible for receiving sensor data from some external source.
This may include listening for packets from a UDP socket, retrieving messages from an MQTT topic, etc...
An adapter is responsible for processing the byte streams dispatched by the listeners.
For example, this may include decoding a specific JSON format, persisting metrics and/or generating events.

The framework does not make any assumption about the data about being received or processed, leaving this up to the listener and adapter implementations.

Listeners may run on either _{opennms-product-name}_ or _Minion_, whereas adapters run exclusively on _{opennms-product-name}_.
If a listener is running on _Minion_, the received messages will be automatically dispatched to the associated adapter(s) running in _{opennms-product-name}_.

=== Supported protocols

We provide built-in support for a number of protocols.
Follow the instructions bellow for enabling these.

==== Junos Telemetry Interface (JTI)

To enable support for Junos Telemetry Interface (JTI), edit `${OPENNMS_HOME}/etc/telemetryd-configuration.xml` and change the following line:

```
<protocol name="JTI" description="Junos Telemetry Interface (JTI)" enabled="false">
```

to:

```
<protocol name="JTI" description="Junos Telemetry Interface (JTI)">
```

Apply the changes without restarting by sending a `reloadDaemonConfig` event:

```
${OPENNMS_HOME}bin/send-event.pl -p 'daemonName Telemetryd' uei.opennms.org/internal/reloadDaemonConfig
```

By default, this will open a UDP socket bound to `0.0.0.0:50000` to which JTI messages can be forwarded.

==== Minion

To enable the listener on Minion:

[source]
----
$ ssh -p 8201 admin@localhost
...
admin@minion()> config:edit org.opennms.features.telemetry.listeners-udp-50000
admin@minion()> config:property-set name JTI
admin@minion()> config:property-set class-name org.opennms.netmgt.telemetry.listeners.udp.UdpListener
admin@minion()> config:property-set listener.port 50000
admin@minion()> config:update
----

NOTE: The protocol must also be enabled on _{opennms-product-name}_ for the messages to be processed.

=== Listener Reference

==== UDP Listener

The UDP listener can be used to open a simple UDP socket and build messages from the received packets.

===== Facts

[options="autowidth"]
|===
| Class Name          | `org.opennms.netmgt.telemetry.listeners.udp.UdpListener`
| Supported on Minion | `Yes`
|===

===== Parameters

.Listener specific parameters for the UdpListener
[options="header, autowidth"]
|===
| Parameter        | Description                                                       | Required | Default value
| `host`           | IP address on which to bind the UDP port                          | optional | `0.0.0.0`
| `port`           | UDP port number on which to listen                                | optional | `50000`
| `maxPacketSize`  | Maximum packet size in bytes (anything greater will be truncated) | optional | `8096`
|===

=== Adapter Reference

==== JTI Adapter

The JTI adapter is used to handle _Junos Telemetry Interface_ payloads.
Messages are decoded using the published protobuf specifications and forwarded to a JSR-223 compatible script (i.e. Beanshell or Groovy) for further processing.
Using the script extension you can extract the desired metrics from the JTI messages and persist the results as time series data.

===== Facts

[options="autowidth"]
|===
| Class Name          | `org.opennms.netmgt.telemetry.adapters.jti.JtiGpbAdapter`
|===

===== Parameters

.Adapter specific parameters for the JtiGpbAdapter
[options="header, autowidth"]
|===
| Parameter        | Description                                                       | Required | Default value
| `script`         | Full path to the script used to handle the JTI messages           | required | (none)
|===

===== Scripting

The script will be invoked for every JTI message that is received and succesfully decoded.

The following globals will be passed to the script:

.Globals passed to the script
[options="header, autowidth"]
|===
| Parameter  | Description                                                    | Type
| `agent`    | The agent (node) against which the metrics will be associated  | `org.opennms.netmgt.collection.api.CollectionAgent`
| `builder`  | Builder in which the resources and metrics should be added     | `org.opennms.netmgt.collection.support.builder.CollectionSetBuilder`
| `msg`      | Decoded JTI message from which the metrics should be extracted | `org.opennms.netmgt.telemetry.adapters.jti.proto.TelemetryTop`
|===
