.Install OpenJDK 11 JRE runtime
[source, console]
----
sudo dnf -y install java-11-openjdk-headless
----

////
Repo: Horizon Sentinel
////
ifeval::["{page-component-title}" == "Horizon"]
.Add repository and import GPG key
[source, console]
----
sudo dnf -y install https://yum.opennms.org/repofiles/opennms-repo-stable-rhel8.noarch.rpm
sudo rpm --import https://yum.opennms.org/OPENNMS-GPG-KEY
----
endif::[]

////
Repo: Meridian Sentinel
////
ifeval::["{page-component-title}" == "Meridian"]
.Add repository and import GPG key
[source, console]
----
cat << EOF | sudo tee /etc/yum.repos.d/opennms-meridian.repo
[meridian]
name=Meridian for Red Hat Enterprise Linux and CentOS
baseurl=https://REPO_USER:REPO_PASS@meridian.opennms.com/packages/2021/stable/rhel8<1>
gpgcheck=1
gpgkey=http://yum.opennms.org/OPENNMS-GPG-KEY
EOF

sudo rpm --import https://yum.opennms.org/OPENNMS-GPG-KEY
----
<1> Replace the `REPO_USER` and `REPO_PASS` with your Meridian subscription credentials.
endif::[]

.Installing the of {page-component-title} Sentinel
[source, console]
----
ifeval::["{page-component-title}" == "Horizon"]
sudo dnf -y install opennms-sentinel
endif::[]
ifeval::["{page-component-title}" == "Meridian"]
sudo dnf -y install meridian-sentinel
endif::[]
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
     After upgrade, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
     For this reason, it is recommended to exclude the {page-component-title} packages from update except when you are planning on performing an upgrade.

.Disable auto updates for {page-component-title} Sentinel
[source, console]
----
ifeval::["{page-component-title}" == "Horizon"]
sudo dnf config-manager --disable opennms-repo-stable-*
endif::[]
ifeval::["{page-component-title}" == "Meridian"]
sudo dnf config-manager --disable meridian
endif::[]
----

.Verify directory structure with the tree command
[source, console]
----
sudo dnf -y install tree
tree /opt/sentinel -L 1
----

.Directory structure after successful installation
[source, output]
----
/opt/sentinel
├── bin
├── COPYING
├── deploy
├── etc
├── lib
└── system
----

.Enable {page-component-title} Sentinel on system boot and start immediately
[source, console]
----
sudo systemctl enable --now sentinel
----
