=== BSFMonitor
This monitor runs a Bean Scripting Framework http://commons.apache.org/proper/commons-bsf/[BSF] compatible script to determine the status of a service.
Users can write scripts to perform highly custom service checks. 
This monitor is not optimized for scale. 
It's intended for a small number of custom checks or prototyping of monitors.

==== BSFMonitor vs SystemExecuteMonitor
The BSFMonitor avoids the overhead of fork(2) that is used by the SystemExecuteMonitor.
BSFMonitor also grants access to a selection of OpenNMS internal methods and classes that can be used in the script.


==== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.BSFMonitor`
| Remote Enabled | false
|===

==== Configuration and Usage

.Monitor specific parameters for the BSFMonitor
[options="header, autowidth"]
|===
| Parameter         | Description                                           | Required | Default value

| `file-name`       | Path to the script file.                              | required | `-`
| `bsf-engine`      | The BSF Engine to run the script in, like: +
                      `Bean Shell` - `bsh.util.BeanShellBSFEngine` +
                      `Groovy` - `org.codehaus.groovy.bsf.GroovyEngine`  +
                      `Jython` - `org.apache.bsf.engines.jython.JythonEngine` | required | `-`
| `run-type`        | one of `eval` or `exec`                               | optional | `eval`
| `lang-class`      | The BSF language class, like `groovy` or `beanshell`. | optional | `file-name extention is interpreted by default`
| `file-extensions` | comma separated list                                  | optional | `-`
|===


.Beans which can be used in the script
[options="header, autowidth"]
|===
| Variable     | Type                           | Description
| `map`        | Map<String, Object>            | The _map_ contains all various parameters passed to the monitor
                                                  from the service definition it the 'poller-configuration.xml' file.
| `ip_addr`    | String                         | The IP address that is currently being polled.
| `node_id`    | int                            | The Node ID of the node the _ip_addr_ belongs to.
| `node_label` | String                         | The Node Label of the node the _ip_addr_ and service belongs to.
| `svc_name`   | String                         | The name of the service that is being polled.
| `bsf_monitor`| BSFMonitor                     | The instance of the _BSFMonitor_ object calling the script. 
                                                  Useful for logging via its 
                                                  +log(String sev, String fmt, Object... args)+ method.
| `results`    | HashMap<String, String>        | The script is expected to put its results into this object.
                                                  The status indication sould be set into the entry with key _status_.
                                                  If the status is not _OK_, a key _reason_ should contain a description of the problem.
| `times`      | LinkedHashMap<String, Number>  | The script is expected to put one or more response times into this object.
|===

Additionally every parameter added to to service definition in 'poller-configuration.xml' is available as a _String_ object in the script.
The key attribute of the parameter respresents the name of the _String_ object and the value attribute represents the value of the _String_ object.

NOTE: Please keep in mind, that these parameters are also accessible via the _map_ bean.

CAUTION: Avoid non-character names for parameters to avoid problems in the script languages.  

==== Response Codes
The script has to provide a status code that represents the status of the associated service.
The following status codes are defined:

.Status Codes
[options="header, autowidth"]
|===
| Code  | Description
| `OK`  | Service is available
| `UNK` | Service status unknown
| `UNR` | Service is unresponsive
| `NOK` | Service is unavailable
|===

==== Response time tracking
By default the _BSFMonitor_ tracks the whole time the script file consumes as the response time.
If the response time should be persisted the response time add the following parameters:

RRD response time tracking at the _poller-configuration.xml_ Service
[source, xml]
----
<!-- where in the filesystem response times are stored -->
<parameter key="rrd-repository" value="/opt/opennms/share/rrd/response" />

<!-- name of the rrd file -->
<parameter key="rrd-base-name" value="minimalbshbase" />

<!-- name of the data source in the rrd file -->
<!-- by default "response-time" is used as ds-name -->
<parameter key="ds-name" value="myResponseTime" />
----

It is also possible to return one or many response times directly from the script.
To add custom response times or override the default one, add entries to the _times_ object.
The entries are keyed with a _String_ that names the datasource and have as values a number that represents the response time.
To override the default response time datasource add an entry into _times_ named _response-time_.

==== Timeout and Retry
The BSFMonitor does not perform any timeout or retry processing on its own.
If retry and or timeout behavior is required, it has to be implemented in the script itself.

==== Requirements for the script (run-types)
Depending on the _run-type_ the script has to provide its results in different ways.
For minimal scripts with very simple logic _run-type_ _eval_ is the simple option.
Scripts runing in _eval_ mode have to return a _String_ matching one of the _Status Codes_.

If your script is more than a one-liner, _run-type_ _exec_ is essentially required.
Scripts running in _exec_ mode need not return anything, but they have to add a "status" entry with a _Status Code_ to the _results_ object.
Additionally, the _results_ object can also carry a "reason":"message" entry that is used in non "OK" states.

==== Minimal Examples

===== Minimal Bean Shell Example
BeanShell Example _poller-configuration.xml_
[source, xml]
----
<service name="MinimalBeanShell" interval="300000" user-defined="true" status="on">
  <parameter key="file-name"  value="/tmp/MinimalBeanShell.bsh"/>
  <parameter key="bsf-engine" value="bsh.util.BeanShellBSFEngine"/>
</service>

<monitor service="MinimalBeanShell" class-name="org.opennms.netmgt.poller.monitors.BSFMonitor" />
----

BeanShell Example _MinimalBeanShell.bsh_ Script file
[source, java]
----
bsf_monitor.log("ERROR", "Starting MinimalBeanShell.bsf", null);
File testFile = new File("/tmp/TestFile");
if (testFile.exists()) {
  return "OK";
} else {
  results.put("reason", "file does not exist");
  return "NOK";
}
----


===== Minimal Groovy Example
To use the Groovy language an additional library is required.
Copy a compatible _groovy-all.jar_ into to opennms lib folder and restart OpenNMS.
That makes Groovy available for the BSFMonitor.

Groovy Example _poller-configuration.xml_ with default _run-type_ _eval_
[source, xml]
----
<service name="MinimalGroovy" interval="300000" user-defined="true" status="on">
  <parameter key="file-name"  value="/tmp/MinimalGroovy.groovy"/>
  <parameter key="bsf-engine" value="org.codehaus.groovy.bsf.GroovyEngine"/>
</service>

<monitor service="MinimalGroovy" class-name="org.opennms.netmgt.poller.monitors.BSFMonitor" />
----

Groovy Example _MinimalGroovy.groovy_ Script file for _run-type_ _eval_
[source, java]
----
bsf_monitor.log("ERROR", "Starting MinimalGroovy.groovy", null);
File testFile = new File("/tmp/TestFile");
if (testFile.exists()) {
  return "OK";
} else {
  results.put("reason", "file does not exist");
  return "NOK";
}
----


Groovy Example _poller-configuration.xml_ with _run-type_ _exec_
[source, xml]
----
<service name="MinimalGroovy" interval="300000" user-defined="true" status="on">
  <parameter key="file-name"  value="/tmp/MinimalGroovy.groovy"/>
  <parameter key="bsf-engine" value="org.codehaus.groovy.bsf.GroovyEngine"/>
  <parameter key="run-type" value="exec"/>
</service>

<monitor service="MinimalGroovy" class-name="org.opennms.netmgt.poller.monitors.BSFMonitor" />
----

Groovy Example _MinimalGroovy.groovy_ Script file for _run-type_ _exec_
[source, java]
----
bsf_monitor.log("ERROR", "Starting MinimalGroovy", null);
def testFile = new File("/tmp/TestFile");
if (testFile.exists()) {
  results.put("status", "OK")
} else {
  results.put("reason", "file dose not exist");
  results.put("status", "NOK");
}
----

===== Minimal Jython Example
To use the Jython (Java implementiton of Python) language an additional library is required.
Copy a compatible _jython-x.y.z.jar_ into the opennms lib folder and restart OpenNMS.
That makes Jython available for the BSFMonitor.

Jython Example _poller-configuration.xml_ with _run-type_ _exec_
[source, xml]
----
<service name="MinimalJython" interval="300000" user-defined="true" status="on">
  <parameter key="file-name"  value="/tmp/MinimalJython.py"/>
  <parameter key="bsf-engine" value="org.apache.bsf.engines.jython.JythonEngine"/>
  <parameter key="run-type" value="exec"/>
</service>

<monitor service="MinimalJython" class-name="org.opennms.netmgt.poller.monitors.BSFMonitor" />
----

Jython Example MinimalJython Script file for _run-type_ _exec_
[source, python]
----
from java.io import File

bsf_monitor.log("ERROR", "Starting MinimalJython.py", None);
if (File("/tmp/TestFile").exists()):
        results.put("status", "OK")
else:
        results.put("reason", "file does not exist")
        results.put("status", "NOK")
----

NOTE: We have to use _run-type_ _exec_ here because Jython chokes on the _import_ keyword in _eval_ mode.

NOTE: As proft that this is really Python, notice the substitution of Python's _None_ value for Java's _null_ in the log call.



===== Additional examples

The following example references all beans that are exposed to the script, including a custom parameter.

Groovy Example _poller-configuration.xml_
[source, xml]
----
<service name="MinimalGroovy" interval="30000" user-defined="true" status="on">
  <parameter key="file-name"  value="/tmp/MinimalGroovy.groovy"/>
  <parameter key="bsf-engine" value="org.codehaus.groovy.bsf.GroovyEngine"/>
  
  <!-- custom parameters (passed to the script) -->
  <parameter key="myParameter" value="Hello Groovy" />

  <!-- optional for response time tracking -->
  <parameter key="rrd-repository" value="/opt/opennms/share/rrd/response" />
  <parameter key="rrd-base-name" value="minimalgroovybase" />
  <parameter key="ds-name" value="minimalgroovyds" />
</service>

<monitor service="MinimalGroovy" class-name="org.opennms.netmgt.poller.monitors.BSFMonitor" />
----

Groovy Example Bean referencing Script file
[source, java]
----
bsf_monitor.log("ERROR", "Starting MinimalGroovy", null);

//list of all available objects from the BSFMonitor
Map<String, Object> map = map;
bsf_monitor.log("ERROR", "---- map ----", null);
bsf_monitor.log("ERROR", map.toString(), null);

String ip_addr = ip_addr;
bsf_monitor.log("ERROR", "---- ip_addr ----", null);
bsf_monitor.log("ERROR", ip_addr, null);

int node_id = node_id;
bsf_monitor.log("ERROR", "---- node_id ----", null);
bsf_monitor.log("ERROR", node_id.toString(), null);

String node_label = node_label;
bsf_monitor.log("ERROR", "---- node_label ----", null);
bsf_monitor.log("ERROR", node_label, null);

String svc_name = svc_name;
bsf_monitor.log("ERROR", "---- svc_name ----", null);
bsf_monitor.log("ERROR", svc_name, null);

org.opennms.netmgt.poller.monitors.BSFMonitor bsf_monitor = bsf_monitor;
bsf_monitor.log("ERROR", "---- bsf_monitor ----", null);
bsf_monitor.log("ERROR", bsf_monitor.toString(), null);

HashMap<String, String> results = results;
bsf_monitor.log("ERROR", "---- results ----", null);
bsf_monitor.log("ERROR", results.toString(), null);

LinkedHashMap<String, Number> times = times;
bsf_monitor.log("ERROR", "---- times ----", null);
bsf_monitor.log("ERROR", times.toString(), null);

// reading a parameter from the service definition
String myParameter = myParameter;
bsf_monitor.log("ERROR", "---- myParameter ----", null);
bsf_monitor.log("ERROR", myParameter, null);

// minimal example
def testFile = new File("/tmp/TestFile");
if (testFile.exists()) {
  bsf_monitor.log("ERROR", "Done MinimalGroovy ---- OK ----", null);
  return "OK";
} else {
  
  results.put("reason", "file does not exist");
  bsf_monitor.log("ERROR", "Done MinimalGroovy ---- NOK ----", null);
  return "NOK";
}
----

