
// Please keep first line an empty line to make sure, the ToC can be build correctly
=== BSFMonitor
This monitor runs a Bean Scripting Framework http://commons.apache.org/proper/commons-bsf/[BSF] compatible script to determin the status of a service.
Users can write there own scripts to performe highly custom service checks. This monitor is not optimiced for scale. It's intedet for a small amount of custom checks or prototying of monitors.

==== BSFMonitor vs SystemExecuteMonitor
The BSFMonitor avoides the overhead of fork(2) that is used by the SystemExecuteMonitor.
BSFMonitors also grand access to a selection of OpenNMS internal methods and classes that can be used in the script.


==== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.BSFMonitor`
| Remote Enabled | `false`
|===

==== Configuration and Usage

.Monitor specific parameters for the BSFMonitor
[options="header, autowidth"]
|===
| Parameter         | Description                                    | Required | Default value

| `file-name`       | Path to the script file.                              | required | `-`
| `lang-class`      | The BSF language class, like `groovy` or `beanshell`. | optional | `file-name extention is interpreted by default`

| `bsf-engine`      | The BSF Engine to run the script in, linke +
                      `bsh.util.BeanShellBSFEngine` or  +
                      `?groovy?`                                            | required | `-`
| `file-extensions` | comma seperated list                                  | optional | `-`
| `run-type`        | one of those `eval` or `exec`                         | optional | `eval`


// There is no retry of timeout in the BSFMonitor code....
// There are also no dedicated retry or timeout parameters handed over to the script, just the parameter map it self.
| `retry`          | text                                                   | optional | `-`
| `timeout`        | text                                                   | optional | `-`



|===


.Bean which can be used in the script
[options="header, autowidth"]
|===
| Variable     | Type                           | Description
| `map`        | Map<String, Object>            | The _map_ contains all various parameters passed to the monitor +
                                                  from the service definition it the _poller-configuration.xml_ file.
| `ip_addr`    | String                         | The IP address that is currently being polled.
| `node_id`    | int                            | The Node ID of the node the _ip_addr_ belongs to.
| `node_label` | String                         | The Node Label of the node the _ip_addr_ and service belongs to.
| `svc_name`   | String                         | The name of the service that is being polled.
| `bsf_monitor`| BSFMonitor                     | The instance of the _BSFMonitor_ object calling the script. +
                                                  Useful for logging via its +
                                                  log(String sev, String fmt, Object... args) method.
| `result`     | HashMap<String, String>        | The script is ecpected to put it results into this object. +
                                                  The status indication sould be set into the entry with key _status_. +
                                                  If the status is not _OK_, a key _reason_ shoud contain a +
                                                  description of the problem.
| `times`      | LinkedHashMap<String, Number>  | The script is expected to put one or more response times into this object.
|===

==== Minimal Examples


===== Minimal Bean Shell Example
BeanShell Example PollerConfig
[source, xml]
----
<service name="MinimalBeanShell" interval="300000" user-defined="true" status="on">
  <parameter key="file-name"  value="/tmp/MinimalBeanShell.bsh"/>
  <parameter key="bsf-engine" value="bsh.util.BeanShellBSFEngine"/>
</service>

<monitor service="MinimalBeanShell" class-name="org.opennms.netmgt.poller.monitors.BSFMonitor" />
----

BeanShell Example MinimalBeanShell Script file
[source, java]
----
bsf_monitor.log("ERROR", "Starting MinimalBeanShell.bsf", null);
File testFile = new File("/tmp/TestFile");
if (testFile.exists()) {
  return "OK";
} else {
  results.put("reason", "file dose not exist");
  return "NOK";
}
----


===== Minimal Groovy Example
To use the Groovy language an additional library is required. Copy a _groovy-all.jar_ into to opennms lib folder and restart OpenNMS.
That makes Groovy avalible for the BSFMonitor.

Groovy Example PollerConfig
[source, xml]
----
<service name="MinimalBeanShell" interval="300000" user-defined="true" status="on">
  <parameter key="file-name"  value="/tmp/MinimalBeanShell.bsh"/>
  <parameter key="bsf-engine" value="bsh.util.BeanShellBSFEngine"/>
</service>

<monitor service="MinimalBeanShell" class-name="org.opennms.netmgt.poller.monitors.BSFMonitor" />
----

Groovy Example MinimalGroovy Script file
[source, java]
----
bsf_monitor.log("ERROR", "Starting MinimalGroovy.groovy", null);
File testFile = new File("/tmp/TestFile");
if (testFile.exists()) {
  return "OK";
} else {
  results.put("reason", "file dose not exist");
  return "NOK";
}
----
