=== HttpPostMonitor

If it is required to hTTP POST any arbitrary content to a remote URI, the HttpPostMonitor can be used.
One usecase is to HTTP POST to a SOAP endpoint.

==== Monitor facts

[options="autowidth"]
|===
| Class Name | `org.opennms.netmgt.poller.monitors.HttpPostMonitor`
| Remote Enabled | `false`
|===

==== Configuration and Usage

.Monitor specific parameters for the {monitorname}
[options="header, autowidth"]
|===
| Parameter | Description                                    | Required | Default value
| `payload` | The body of the POST, for example properly escaped XML. | required | `-`
| `auth-password` | The password to use for HTTP BASIC auth. | optional | `-`
| `auth-username` | The username to use for HTTP BASIC auth. | optional | `-`
| `banner` | A string that is match against the response of the HTTP POST. +
             If the output contains the banner, the service is determined as UP. +
             Specify a regex by starting with "~". | optional | `-`
| `charset` | The character set tu use during the POST. | optional | `UTF-8`
| `mimetype` | The mimetype set tu use during POST. | optional | `text/xml`
| `port` | The port for the POST. | optional | `80`
| `scheme` | The connection scheme to use. | optional | `http`
| `usesslfilter` | Controls if the SSL certificate must be correct. | optional | `false`
| `uri` | The uri to use during the POST. | optional | `/`
|===

==== Examples
[source, xml]
----
<service name="MyServlet" interval="300000" user-defined="false" status="on">
  <parameter key="banner" value="Hello"/>
  <parameter key="port" value="8080"/>
  <parameter key="uri" value="/MyServlet">
  <parameter key="payload" value="World"/>
  <parameter key="retry" value="1"/>
  <parameter key="timeout" value="30000"/>
</service>
----

Would construct a POST that would look like the following.
[source, xml]
----
POST /MyServlet HTTP/1.1
Content-Type: text/xml; charset=utf-8
Host: ip_addr_of_interface:8080
Connection: Keep-Alive

World
----
