
=== JDBCMonitor

The JDBCMonitor checks that it is able to connect to a Database and checks if it is able to get the database catalog from that databasemanagementsystem.
It is based on the http://www.oracle.com/technetwork/java/javase/jdbc/index.html[JDBC] technology to connect and communicate with the database.

==== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.JDBCMonitor`
| Remote Enabled | true
|===

==== Configuration and Usage

.Monitor specific parameters for the JDBCMonitor
[options="header, autowidth"]
|===
| Parameter  | Description                                                        | Required | Default value
| `driver`   | JDBC-Driver class to use                                           | required | `com.sybase.jdbc2.jdbc.SybDriver`
| `url`      | JDBC-Url to connect to.                                            | required | `jdbc:sybase:Tds:OPENNMS_JDBC_HOSTNAME/tempdb`
| `user`     | Database user                                                      | required | `sa`
| `password` | Database password                                                  | required | (empty)
| `timeout`  | Timeout in ms for the database-connection                          | optional | `3000`
| `retries`  | How many retries should be performed before failing the test       | optional | `0`
|===

NOTE: The _OPENNMS_JDBC_HOSTNAME_ is replaced in the _url_ parameter the IP or resolved hostname of the interface the monitored service is assigned to. 

==== Provide the database driver

The JDBCMonitor is based on _JDBC_ and requires a JDBC-Driver to communicate with any database.
Due to the fact that OpenNMS it self is using a Postgrsql Database, the Postgresql JDBC-Driver is available out of the box.
For all other database-systems a compatible JDBC-Driver has to be provided to OpenNMS as a _jar-file_.
To provide a JDBC-Driver place the _driver-jar_ in the `lib-folder` of your OpenNMS.
To use the JDBC-Monitor from a Remote-Poller, the _driver-jar_ has to be provided to the Remote-Poller too.


==== Examples
The following example checks if the Postgresql database used by OpenNMS is available.

[source, xml]
----
<service name="OpenNMS_DBMS" interval="30000" user-defined="true" status="on">
  <parameter key="driver" value="org.postgresql.Driver"/>
  <parameter key="url" value="jdbc:postgresql://OPENNMS_JDBC_HOSTNAME:5432/opennms"/>
  <parameter key="user" value="opennms"/>
  <parameter key="password" value="opennms"/>
</service>

<monitor service="OpenNMS_DBMS"       class-name="org.opennms.netmgt.poller.monitors.JDBCMonitor" />
----
