
// Please keep first line an empty line to make sure, the ToC can be build correctly
=== OmsaStorageMonitor

With OmsaStorageMonitor you are able to monitor your Dell OpenManaged servers RAID array status.

==== Monitor facts

[options="autowidth"]
|===
| Class Name | `org.opennms.netmgt.poller.monitors.OmsaStorageMonitor`
| Remote Enabled | `I don't know`
|===

==== Configuration and Usage

Monitor specific parameters for the OmsaStorageMonitor
[options="header, autowidth"]
|===
| Parameter           | Description                                              | Required | Default value
| `virtualDiskNumber` | The disk index of your RAID array                        | required | `-`
| `retry`             | Amount of attempts opening a connection and try +
                        to get the greeting banner before the service goes down. | optional | `-`
| `timeout`           | Time (in milliseconds) to wait before receiving the +
                        SNMP response.                                           | optional | `-`
|===


==== Examples
Some example configuration how to configure the monitor in the `poller-configuration.xml`
[source, xml]
----
<service name="OMSA_Storage_Disk_1" interval="300000"
  user-defined="false" status="on">
 <parameter key="retry" value="3"/>
 <parameter key="timeout" value="6000"/>
 <parameter key="virtualDiskNumber" value="1"/>
</service>
<service name="OMSA_Storage_Disk_2" interval="300000"
  user-defined="false" status="on">
 <parameter key="retry" value="3"/>
 <parameter key="timeout" value="6000"/>
 <parameter key="virtualDiskNumber" value="1"/>
</service>

<monitor service="OMSA_Storage_Disk_1" class-name="org.opennms.netmgt.poller.monitors.OmsaStorageMonitor"/>
<monitor service="OMSA_Storage_Disk_2" class-name="org.opennms.netmgt.poller.monitors.OmsaStorageMonitor"/>
----

.This section is optional and give some specific hints
==== Hints

* The monitored system needs a specific snmp configuration to get a working datacollection. Not sure, if it is required for monitoring RAID status.
[source]
----
Allow Systems Management Data Engine SNMP to connect to snmpd using SMUX
smuxpeer .1.3.6.1.4.1.674.10892.1
----
* You'll need to know the maximum number of possible logical disks you have in your environment. + 
For example: If you have 3 RAID arrays, you need 3 service poller.
