
// Please keep first line an empty line to make sure, the ToC can be build correctly
=== OmsaStorageMonitor

With OmsaStorageMonitor you are able to monitor your http://de.community.dell.com/techcenter/systems-management/w/wiki/438.dell-openmanage-server-administrator-omsa.aspx[Dell OpenManaged] servers RAID array status.

You'll need to know the maximum number of possible logical disks you have in your environment. + 
For example: If you have 3 RAID arrays, you need 3 service poller.

Additional listing with the OIDs the monitor is using:

[options="header, autowidth"]
|===
| Name                                          | OID
| virtualDiskRollUpStatus                       | `.1.3.6.1.4.1.674.10893.1.20.140.1.1.19`
| arrayDiskLogicalConnectionVirtualDiskNumber   | `.1.3.6.1.4.1.674.10893.1.20.140.3.1.5`
| arrayDiskNexusID                              | `.1.3.6.1.4.1.674.10893.1.20.130.4.1.26`
| arrayDiskLogicalConnectionArrayDiskNumber     | `.1.3.6.1.4.1.674.10893.1.20.140.3.1.3`
| arrayDiskState                                | `1.3.6.1.4.1.674.10893.1.20.130.4.1.4`
|===

Additional listing for the interpretation of the diskstatus values:
[options="header, autowidth"]
|===
| Value | Status
| `1`     | Ready
| `2`     | Failed
| `3`     | Online
| `4`     | Offline
| `6`     | Degraded
| `7`     | Recovering
| `11`    | Removed
| `15`    | Resynching
| `24`    | Rebuilding
| `25`    | noMedia
| `26`    | Formating
| `28`    | Running Diagnostics
| `35`    | Initializing
|===

==== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.OmsaStorageMonitor`
| Remote Enabled | `false`
|===

==== Configuration and Usage

Monitor specific parameters for the OmsaStorageMonitor
[options="header, autowidth"]
|===
| Parameter           | Description                                              | Required | Default value
| `virtualDiskNumber` | The disk index of your RAID array                        | optional | `1`
| `retry`             | Amount of attempts opening a connection and try 
                        to get the greeting banner before the service goes down. | optional | `from snmp-config.xml`
| `timeout`           | Time (in milliseconds) to wait before receiving the 
                        SNMP response.                                           | optional | `from snmp-config.xml`
| `port`              | The TCP port OpenManage is listening                     | optional | `from snmp-config.xml`
|===


==== Examples
Some example configuration how to configure the monitor in the `poller-configuration.xml`.

The RAID array monitor for your first array (*virtualDiskNumber = 1*) could look like this one:
[source, xml]
----
<service name="OMSA_Storage_Disk_1" interval="300000"
  user-defined="false" status="on">
 <parameter key="retry" value="3"/>
 <parameter key="timeout" value="6000"/>
 <parameter key="virtualDiskNumber" value="1"/>
</service>
<monitor service="OMSA_Storage_Disk_1" class-name="org.opennms.netmgt.poller.monitors.OmsaStorageMonitor"/>
----

If there is more than one RAID array to monitor you need an additional configuration. In this case *virtualDiskNumber = 2*. And so on...
[source, xml]
----
<service name="OMSA_Storage_Disk_2" interval="300000"
  user-defined="false" status="on">
 <parameter key="retry" value="3"/>
 <parameter key="timeout" value="6000"/>
 <parameter key="virtualDiskNumber" value="2"/>
</service>
<monitor service="OMSA_Storage_Disk_2" class-name="org.opennms.netmgt.poller.monitors.OmsaStorageMonitor"/>
----


