
==== OpenManageChassisMonitor

The OpenManageChassis monitor tests the status of a Dell chassis by querying its SNMP agent.
The monitor polls the value of the node's SNMP OID .1.3.6.1.4.1.674.10892.1.300.10.1.4.1 (MIB-Dell-10892::chassisStatus).
If the value is _OK_ (3), the service is considered available.

As this monitor uses SNMP, the queried nodes must have proper SNMP configuration in _snmp-config.xml_.

===== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.OpenManageChassisMonitor`
| Remote Enabled | false
|===

===== Configuration and Usage

.Monitor specific parameters for the OpenManageChassisMonitor
[options="header, autowidth"]
|===
| Parameter | Description                                                        | Required | Default value
| `port`    | The port to which connection shall be tried.                       | optional | `from snmp-config.xml`
| `retry`   | Number of polls to attempt.                                        | optional | `from snmp-config.xml`
| `timeout` | Time (in milliseconds) to wait before receiving the SNMP response. | optional | `from snmp-config.xml`
|===

===== Examples

[source, xml]
----
<!-- Overriding default SNMP config -->
<service name="OMA-Chassis" interval="300000" user-defined="false" status="on">
  <parameter key="retry" value="3"/>
  <parameter key="timeout" value="5000"/>
</service>

<monitor service="OMA-Chassis" class-name="org.opennms.netmgt.poller.monitors.OpenManageChassisMonitor" />
----

===== Dell MIBs

Dell MIBs can be found link:ftp://ftp.us.dell.com/sysman[here].
Download the DCMIB<version>.zip or DCMIB<version>.exe file corresponding to the version of your OpenManage agents.
The latest one should be good enough for all previous version though.
