=== Pop3Monitor
The POP3 monitor tests for POP3 service availability on a node.
The monitor first tries to establish a TCP connection on the specified port.
If a connection is established, a service banner should have been received.
The monitor makes sure the service banner is a valid POP3 banner (ie: starts with "+OK").
If the banner is valid, the monitor sends a _QUIT_ POP3 command and makes sure the service answers with a valid response (ie: a response that starts with "+OK").
The service is considered available if the service's answer to the _QUIT_ command is valid.

==== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.Pop3Monitor`
| Remote Enabled | true
|===

==== Configuration and Usage

.Monitor specific parameters for the Pop3Monitor
[options="header, autowidth"]
|===
| Parameter            | Description                                                                                | Required | Default value
| `port`               | TCP port to connect to.                                                                    | optional | `110`
| `retry`              | Number of attempts to get a response.                                                      | optional | `0`
| `strict-timeout`     | Boolean                                                                                    | optional | `false`
| `timeout`            | Timeout (in milliseconds) for the underlying socket's _connect_ and _read_ operations.     | optional | `3000`
|===

==== Examples
[source, xml]
----
<service name="POP3" interval="300000" user-defined="false" status="on">
  <parameter key="retry" value="2"/>
  <parameter key="timeout" value="3000"/>
  <parameter key="rrd-repository" value="/var/lib/opennms/rrd/response"/>
  <parameter key="rrd-base-name" value="pop3"/>
  <parameter key="ds-name" value="pop3"/>
</service>
<monitor service="POP3" class-name="org.opennms.netmgt.poller.monitors.Pop3Monitor"/>
----
