
// Please keep first line an empty line to make sure, the ToC can be build correctly
=== StrafePingMonitor

The StrafePing monitor performs multiple ICMP echo (ping) requests and stores the response-time of each as well as the packet loss, in an RRD file. Credit is due to Tobias Oetiker, as this graphing feature is an adaptation of the http://oss.oetiker.ch/smokeping/[SmokePing] tool that he developed. 

==== Monitor facts

[options="autowidth"]
|===
| Class Name | `org.opennms.netmgt.poller.monitors.StrafePingMonitor`
| Remote Enabled | don't know
|===

==== Configuration and Usage

.Monitor specific parameters for the {monitorname}
[options="header, autowidth"]
|===
| Parameter           | Description                                                 | Required | Default value
| `timeout`           | How long (in milliseconds) to wait before assuming that a 
                        packet has not responded                                    | optional | `from snmp-config.xml`
| `retry`             | The number of retries to attempt when a packet fails to 
                        respond in the given timeout                                | optional | `from snmp-config.xml`
| `ping-count`        | The number of pings to attempt each interval                | required | `20`
| `failure-ping-count`| The number of pings that need to fail for the service to
                        be considered down                                          | required | `20`
| `wait-interval`     | How long (in milliseconds) to wait between each ICMP
                        echo-request packet                                         | required | `50`
| `rrd-repository`    | The location to write RRD data
                        (generally, you will not want to change this from the
                        default $OPENNMS_HOME/share/rrd/response)                   | required | `/opt/opennms/share/rrd/response`
| `rrd-base-name`     | The name of the RRD file to write
                        (minus the extension, .rrd or .jrb)                         | required | `strafeping`
|===


==== Examples
Some example configuration how to configure the monitor in the `poller-configuration.xml`
[source, xml]
----
<package name="strafer" >
   <filter>IPADDR != '0.0.0.0'</filter>
   <include-range begin="0.0.0.1" end="255.255.255.255"/>
   <rrd step="300">
     <rra>RRA:AVERAGE:0.5:1:2016</rra>
     <rra>RRA:AVERAGE:0.5:12:1488</rra>
     <rra>RRA:AVERAGE:0.5:288:366</rra>
     <rra>RRA:MAX:0.5:288:366</rra>
     <rra>RRA:MIN:0.5:288:366</rra>
   </rrd>
   <service name="StrafePing" interval="300000" user-defined="false" status="on">
     <parameter key="retry" value="0"/>
     <parameter key="timeout" value="3000"/>
     <parameter key="ping-count" value="20"/>
     <parameter key="failure-ping-count" value="20"/>
     <parameter key="wait-interval" value="50"/>
     <parameter key="rrd-repository" value="/usr/share/opennms/share/rrd/response"/>
     <parameter key="rrd-base-name" value="strafeping"/>
   </service>
   <downtime interval="30000" begin="0" end="300000"/>     
   <downtime interval="300000" begin="300000" end="43200000"/> 
   <downtime interval="600000" begin="43200000" end="432000000"/>  
   <downtime begin="432000000" delete="true"/>         
 </package>
 <monitor service="StrafePing" class-name="org.opennms.netmgt.poller.monitors.StrafePingMonitor"/>
----

