
==== XmpMonitor

The XMP monitor tests for XMP service/agent availability by
establishing an XMP session and querying (usually) the target agent's
sysObjectID variable contained in the Core MIB.  The service is
considered available when the session attempt succeeds and the agent
returns its sysObjectID without error.

===== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.XmpMonitor`
| Remote Enabled  | false
|===

===== Configuration and Usage

These parameters can be set in the XMP service entry in
collectd-configuration.xml and will override settings from
xmp-config.xml.  Also, don't forget to add an entry in
response-graph.properties so that response values will be graphed.

.Monitor specific parameters for the XmpMonitor
[options="header, autowidth"]
|===
| Parameter     | Description                                            | Required | Default value
| `timeout`     | Time in milliseconds to wait for a successful session. | optional | `5000`
| `authenUser`  | The authenUser parameter for use with the XMP session. | optional | `xmpUser`
| `port`        | TCP port to connect to for XMP session establishment| optional | `5270`
| `mib`         | Name of MIB to query | optional | `core`
| `object`      | Name of MIB object to query | optional | `sysObjectID`

|===

===== Examples

collectd-configuration.xml

[source, xml]
----
<service name="XMP" interval="300000" user-defined="false" status="on">
  <parameter key="timeout" value="3000"/>
  <parameter key="rrd-repository" value="/opt/opennms/share/rrd/response"/>
  <parameter key="rrd-base-name" value="xmp"/>
  <parameter key="ds-name" value="xmp"/>
</service>
<monitor service="XMP" class-name="org.opennms.netmgt.poller.monitors.XmpMonitor"/>
----

response-graph.properties

[source, xml]
----
reports=icmp, \
xmp, \ . . . .

report.xmp.name=XMP
report.xmp.columns=xmp
report.xmp.type=responseTime, distributedStatus
report.xmp.command=--title="XMP Response Time" \
 --vertical-label="Seconds" \
 DEF:rtMills={rrd1}:xmp:AVERAGE \
 DEF:minRtMills={rrd1}:xmp:MIN \
 DEF:maxRtMills={rrd1}:xmp:MAX \
 CDEF:rt=rtMills,1000,/ \
 CDEF:minRt=minRtMills,1000,/ \
 CDEF:maxRt=maxRtMills,1000,/ \
 LINE1:rt#0000ff:"Response Time" \
 GPRINT:rt:AVERAGE:" Avg  \\: %8.2lf %s" \
 GPRINT:rt:MIN:"Min  \\: %8.2lf %s" \
 GPRINT:rt:MAX:"Max  \\: %8.2lf %s\\n"
----
