////
Repo and install: OpenNMS Horizon
////

ifeval::["{page-component-title}" == "Horizon"]
.Add repository and import GPG key
[source, console]
----
sudo dnf -y install https://yum.opennms.org/repofiles/opennms-repo-stable-rhel8.noarch.rpm
sudo rpm --import https://yum.opennms.org/OPENNMS-GPG-KEY
----

.Install {page-component-title} with all built-in dependencies
[source, console]
----
sudo dnf -y install opennms
----
endif::[]

////
Repo and install: OpenNMS Meridian
////

ifeval::["{page-component-title}" == "Meridian"]
.Add repository and import GPG key
[source, console]
----
cat << EOF | sudo tee /etc/yum.repos.d/opennms-meridian.repo
[meridian]
name=Meridian for Red Hat Enterprise Linux and CentOS
baseurl=https://REPO_USER:REPO_PASS@meridian.opennms.com/packages/2021/stable/rhel8<1>
gpgcheck=1
gpgkey=http://yum.opennms.org/OPENNMS-GPG-KEY
EOF

sudo rpm --import https://yum.opennms.org/OPENNMS-GPG-KEY
----
<1> Replace the `REPO_USER` and `REPO_PASS` with the credentials received from your OpenNMS subscription

.Install {page-component-title} with all built-in dependencies
[source, console]
----
sudo dnf -y install meridian
----
endif::[]

If you want time series trending and forecast functions you must install the link:https://www.r-project.org/[R project] packages.
The additional download size for packages is ~390 MB.

.Install R-core packages for time series trending and forecasting (optional)
[source, console]
----
sudo dnf -y install epel-release
sudo dnf -y install R-core
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
     After upgrade, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
     We recommend that you exclude the {page-component-title} packages from update except when you plan to perform an upgrade.

ifeval::["{page-component-title}" == "Horizon"]
.Disable auto updates for OpenNMS {page-component-title}
[source, console]
----
sudo dnf -y install yum-utils
sudo dnf config-manager --disable opennms-repo-stable-*
----
endif::[]

ifeval::["{page-component-title}" == "Meridian"]
.Disable auto updates for OpenNMS {page-component-title}
[source, console]
----
sudo dnf -y install yum-utils
sudo dnf config-manager --disable meridian
----
endif::[]

.Verify directory structure with the tree command
[source, console]
----
sudo dnf -y install tree
tree /opt/opennms -L 1
----

.Directory structure after successful installation
[source, output]
----
/opt/opennms
├── bin
├── contrib
├── data
├── deploy
├── etc
├── jetty-webapps
├── lib
├── logs -> /var/log/opennms
├── share -> /var/opennms
└── system
----
