.Add repository and import GPG key
[source, console]
----
sudo dnf -y install https://yum.opennms.org/repofiles/opennms-repo-stable-rhel8.noarch.rpm
sudo rpm --import https://yum.opennms.org/OPENNMS-GPG-KEY
----

.Install {page-component-title} with all built-in dependencies (optional)
[source, console]
----
sudo dnf -y install opennms
----

TIP: This is optional. If you want time series trending and forecast functions you must install the link:https://www.r-project.org/[R project] packages.
     The additional download size for packages is ~390 MB.

.Install R package for trending and forcasting
[source, console]
----
sudo dnf -y install epel-release
sudo dnf -y install R-core
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades while it runs.
     After upgrade, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
     We recommend that you exclude the {page-component-title} packages from update except when you plan to perform an upgrade.

.Disable auto updates for OpenNMS {page-component-title}
[source, console]
----
sudo dnf config-manager --disable opennms-repo-stable-*
----

.Verify directory structure with the tree command
[source, console]
----
sudo dnf -y install tree
tree /opt/opennms -L 1
----

.Directory structure after successful installation
[source, output]
----
/opt/opennms
├── bin
├── contrib
├── data
├── deploy
├── etc
├── jetty-webapps
├── lib
├── logs -> /var/log/opennms
├── share -> /var/opennms
└── system
----
