net.sf.jasperreports.extension.registry.factory.charts=net.sf.jasperreports.charts.ChartsExtensionsRegistryFactory

net.sf.jasperreports.extension.registry.factory.jackson.mapping=net.sf.jasperreports.jackson.util.JacksonMappingExtensionsRegistryFactory
net.sf.jasperreports.extension.jackson.mapping.chart=net.sf.jasperreports.charts.JRChart

net.sf.jasperreports.extension.registry.factory.deserialization.whitelist=net.sf.jasperreports.engine.util.StandardDeserializationClassWhitelistExtension
net.sf.jasperreports.deserialization.class.whitelist.jasperreports.charts=\
	net.sf.jasperreports.charts.JR*,\
	net.sf.jasperreports.charts.base.JRBase*,\
	net.sf.jasperreports.charts.fill.ChartTemplateImage,\
	net.sf.jasperreports.charts.renderers.JCommonDrawableRendererImpl,\
	net.sf.jasperreports.charts.type.*Enum,\
	net.sf.jasperreports.charts.util.*,\
	net.sf.jasperreports.components.spiderchart.*,\
	net.sf.jasperreports.components.spiderchart.type.*
net.sf.jasperreports.deserialization.class.whitelist.jasperreports.jfreechart=\
	org.jfree.chart.JFreeChart,\
	org.jfree.chart.PaintMap,\
	org.jfree.chart.StrokeMap,\
	org.jfree.chart.LegendItemSource,\
	org.jfree.chart.axis.*,\
	org.jfree.chart.block.*,\
	org.jfree.chart.labels.*,\
	org.jfree.chart.plot.*,\
	org.jfree.chart.plot.dial.*,\
	org.jfree.chart.renderer.*Renderer*,\
	org.jfree.chart.renderer.category.*,\
	org.jfree.chart.renderer.xy.*,\
	org.jfree.chart.text.*,\
	org.jfree.chart.title.*Title,\
	org.jfree.chart.ui.*,\
	org.jfree.chart.util.*,\
	org.jfree.data.Range,\
	org.jfree.data.RangeType,\
	org.jfree.data.DefaultKeyedValues,\
	org.jfree.data.DefaultKeyedValues2D,\
	org.jfree.data.category.DefaultCategoryDataset,\
	org.jfree.data.gantt.*,\
	org.jfree.data.general.*,\
	org.jfree.data.time.*,\
	org.jfree.data.xy.*,\
	org.jfree.text.TextBlockAnchor,\
	org.jfree.ui.*,\
	org.jfree.util.*
