
= Business Service Daemon

The calculation of the operational status of the BS is driven by the Business Service Monitoring Daemon (bsmd).
The daemon tracks the operational status of all BS and sends events in case of operational status changes.

To calculate the operational status, use the reduction key associated with a business service.
The reduction key is obtained from an alarm generated by {page-component-title}.
This means that the alarm's reduction key of a defined business service must not change afterwards.
Otherwise bsmd is not able to calculate the operational status correctly.
This also applies for removing the alarm data from events associated to business services.
In addition the child type "IP Service" from the Business Service Configuration Page requires the following events with the default reduction keys being defined:
 * uei.opennms.org/nodes/nodeLostService
 * uei.opennms.org/nodes/nodeDown
 * uei.opennms.org/nodes/interfaceDown

Every time the you change the configuration of a business service, you must reload the daemon's configuration.
This includes changes like the name of the business service or its attributes as well as changes regarding the reduction keys, contained business services or IP services.
The bsmd configuration can be reloaded with the following mechanisms:

* Click the Reload Daemon button in the Business Service Editor
* Send the reloadDaemonConfig event using `send-event.pl` or use the WebUI in Manually Send an Event with parameter `daemonName bsmd`
* Use the ReST API to perform a `POST` request to `/opennms/api/v2/business-services/daemon/reload`

If the reload of the configuration is done an event of type `uei.opennms.org/internal/reloadDaemonConfigSuccessful` is fired.

.Example reloading bsmd configuration from CLI
[source,shell]
----
$\{OPENNMS_HOME}/bin/send-event.pl -p 'daemonName bsmd' uei.opennms.org/internal/reloadDaemonConfig
----

.Example reloading bsmd configuration through ReST POST
[source,shell]
----
curl -X POST -u admin:admin -v http://localhost:8980/opennms/api/v2/business-services/daemon/reload
----
