
// Allow GitHub image rendering
:imagesdir: ../../../images

==== JdbcCollector

The _JdbcCollector_ is used to collect performance data via _JDBC_ drivers.
Attributes are retrieved using _SQL_ queries.

===== Collector Facts

[options="autowidth"]
|===
| Class Name            | `org.opennms.netmgt.collectd.JdbcCollector`
| Package               | core
| Supported on Minion   | `Yes` (see limitations)
|===

====== Limitations on _Minion_

When running on _Minion_ the data sources in `opennms-datasources.xml` cannot be referenced.
Instead, the _JDBC_ connection settings need be set using the service parameters instead.

Also, the _JDBC_ driver must be properly loaded in the _Minion_ container.
By default, only the _JDBC_ driver for _PostgreSQL_ is available.

===== Collector Parameters

.Collector specific parameters for the JdbcCollector
[options="header, autowidth"]
|===
| Parameter              | Description                                                                    | Required | Default value
| `collection`           | The name of the _JDBC Collection_ to use                                       | required | (empty)
| `data-source`          | Use an existing datasource defined in opennms-datasources.xml                  | optional | NO_DATASOURCE_FOUND
| `driver`               | Driver class name                                                              | optional | org.postgresql.Driver
| `url`                  | _JDBC_ URL                                                                     | optional | jdbc:postgresql://:OPENNMS_JDBC_HOSTNAME/opennms
| `user`                 | _JDBC_ username                                                                | optional | postgres
| `password`             | _JDBC_ password                                                                | optional | (empty string)
|===

===== JDBC Collection Configuration

_JDBC Collections_ are defined in the `etc/jdbc-datacollection-config.xml`.

Here is a snippet providing a collection definition named `opennms-stats`:

[source, xml]
----
<jdbc-collection name="opennms-stats">
  <rrd step="300">
    <rra>RRA:AVERAGE:0.5:1:2016</rra>
    <rra>RRA:AVERAGE:0.5:12:1488</rra>
    <rra>RRA:AVERAGE:0.5:288:366</rra>
    <rra>RRA:MAX:0.5:288:366</rra>
    <rra>RRA:MIN:0.5:288:366</rra>
  </rrd>
  <queries>
    <query name="opennmsQuery" ifType="ignore">
      <statement data-source="opennms">
        <queryString>select count(*) as event_count from events;</queryString>
      </statement>
      <columns>
        <column name="event_count" data-source-name="event_count" alias="event_count" type="GAUGE"/>
      </columns>
    </query>
  </queries>
</jdbc-collection>
----

Once added to `etc/jdbc-datacollection-config.xml` you can test it using the `collect` command available in the _Karaf Shell_:

[source]
----
collection:collect org.opennms.netmgt.collectd.JdbcCollector 127.0.0.1 collection=opennms-stats data-source=opennms
----

To test this same collection on _Minion_ you must specify the _JDBC_ settings as service attributes, for example:

[source]
----
collection:collect -l MINION org.opennms.netmgt.collectd.JdbcCollector 127.0.0.1 collection=opennms-stats driver=org.postgresql.Driver url=jdbc:postgresql://localhost:5432/opennms user=opennms password=opennms
----
