--
-- Licensed to The OpenNMS Group, Inc (TOG) under one or more
-- contributor license agreements.  See the LICENSE.md file
-- distributed with this work for additional information
-- regarding copyright ownership.
--
-- TOG licenses this file to You under the GNU Affero General
-- Public License Version 3 (the "License") or (at your option)
-- any later version.  You may not use this file except in
-- compliance with the License.  You may obtain a copy of the
-- License at:
--
--      https://www.gnu.org/licenses/agpl-3.0.txt
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
-- either express or implied.  See the License for the specific
-- language governing permissions and limitations under the
-- License.
--

--SET DATABASE SQL SYNTAX PGS;
--CREATE SEQUENCE OPENNMSNXTID START WITH 2;
--CREATE SEQUENCE NODENXTID START WITH 2;
--CREATE SEQUENCE SERVICENXTID START WITH 2;
--CREATE SEQUENCE EVENTSNXTID START WITH 2;
--CREATE SEQUENCE ALARMSNXTID START WITH 2;
--CREATE SEQUENCE MEMONXTID START WITH 2;
--CREATE SEQUENCE OUTAGENXTID START WITH 2;
--CREATE SEQUENCE NOTIFYNXTID START WITH 2;
--CREATE SEQUENCE VULNNXTID START WITH 2;
--CREATE SEQUENCE CATNXTID START WITH 2;
--CREATE SEQUENCE USERNOTIFNXTID START WITH 2;
--CREATE SEQUENCE MAPNXTID START WITH 2;
--CREATE SEQUENCE REPORTNXTID START WITH 2;
--CREATE SEQUENCE REPORTCATALOGNXTID START WITH 2;
