
=== Run with Docker

Modern infrastructure allows you to deploy and run workloads in containers.
With _{opennms-product-name}_ we provide and publish container images on link:https://hub.docker.com/u/opennms[DockerHub].

==== Objectives

* Run and configure a _Minion_ in, and connect it to, the _{opennms-product-name}_ instance using environment variables
* Introduce a reference with all available configuration and mount conventions for more advanced setups

==== Before you begin

You must have at least the following components installed:

* Current stable _Docker_ release installed, e.g., installed from link:https://docs.docker.com/[Docker Documentation]
* Current stable _Docker Compose_ installed, e.g., installed from link:https://docs.docker.com/compose/install/[Docker Compose instructions]
* You should have a basic knowledge of _Docker_, _Docker Compose_ with networking, persisting files and mounting directories
* _{opennms-product-name}_ is configured to accept connections via _ActiveMQ_ and a Minion user with _ROLE_MINION_ 
* The _Minion_ can connect to _{opennms-product-name}_ with port `61616/TCP` for _ActiveMQ_ and _REST_ on port `8980/TCP`

==== Quickstart service stack

// No section numbers for step-by-step guide
:!sectnums:

===== Step 1: Create service stack with a Minion

Create a project directory with `mkdir opennms-minion` and create a `docker-compose.yml` file in that directory with the following content:

[source,yaml]
----
---
version: '3'

services:  
  minion:
    image: opennms/minion:25.2.0
    container_name: minion<1>
    environment:
      - TZ=Europe/Berlin<2>
      - MINION_ID=my-minion<3>
      - MINION_LOCATION=my-location<4>
      - OPENNMS_BROKER_URL=failover:tcp://horizon-instance:61616<5>
      - OPENNMS_BROKER_USER=minion-user<6>
      - OPENNMS_BROKER_PASS=minion-password
      - OPENNMS_HTTP_URL=http://horizon-instance:8980/opennms<7>
      - OPENNMS_HTTP_USER=minion-user<8>
      - OPENNMS_HTTP_PASS=minion-password
    command: ["-f"]
    ports:<9>
      - "8201:8201/tcp"
      - "162:1162/udp"
----
<1> Friendly container name
<2> Time zone for the _Minion_
<3> A defined identifier for this _Minion_. If not set, a unique user identifier (_UUID_) will be generated
<4> The name of the location of the _Minion_ and the connection to the _ActiveMQ_ broker running in _{opennms-product-name}_
<5> _ActiveMQ_ broker endpoint from _{opennms-product-name}_
<6> Authentication for ActiveMQ broker
<7> _REST_ endpoint to connect to the _{opennms-product-name}_ instance
<8> Authentication for the _REST_ endpoint
<9> Publish ports for SSH access to the _Karaf Shell_ and listen for _SNMP Traps_ forwarding to an internal unprivileged port

NOTE: In this example we haven't set credentials to connect the _Minion_ via _REST_ and the _ActiveMQ Message Broker_.
      The _Minion_ will fall back and uses the default admin/admin credentials for the communication.
      Permissions for _ActiveMQ_ and _REST_ are assigned with the role _ROLE_MINION_ on the _{opennms-product-name}_ instance.

===== Step 2: Start the service stack and test the functionality

[source,shell]
----
cd opennms-minion
docker-compose up -d
----

===== Step 3: Run _Minion_ health check

.Log in to the _Minion Karaf Shell_ and run the health check
[source, shell]
----
ssh admin@localhost -p 8201

admin@minion> health:check
Verifying the health of the container

Connecting to OpenNMS ReST API   [ Success  ]
Verifying installed bundles      [ Success  ]
Connecting to JMS Broker         [ Success  ]

=> Everything is awesome
----

NOTE: The default admin password for the _Minion Karaf Shell_ is _admin_.

===== Step 4: Verify status in the administrative Web UI

* Log in as admin in the _{opennms-product-name}_ web interface
* _Configure OpenNMS -> Manage Minions_. The _Minion_ should be registered and the status should be _up_
* Verify if _Minion_ is provisioned automatically by going to _Info -> Nodes_ and select the _Minion_. The services _JMX-Minion_, _Minion-Heartbeat_ and _Minion-RPC_ should be _up_ and provisioned on the local loop-back interface

// Enable section numbers
:sectnums:
