
= Scheduled Outages

Scheduled outages let you suppress notifications and pause status polling, threshold checking, and data collection during a specified time period.
To configure scheduled outages in {page-component-title}, click the *gear* symbol at the top-right of the page and, under Service Monitoring, select *Configure Scheduled Outages*.

== Create a scheduled outage

When you define a scheduled outage, you must set the following options:

. Name.
. Nodes to include.
. Node interfaces to include.
. Outage type (daily, weekly, monthly, custom).
. Date and time for the outage.
. Suppression settings (all notifications, status polling, threshold checking, data collection).

During the scheduled outage, any nodes and interfaces matching the outage definition are suppressed.

== Editing Outage

You can create a scheduled outage in the {page-component-title} web UI:

. Click the *gear* symbol at the top-right of the page.
. Under Service Monitoring, select *Configure Scheduled Outages*.
. Type a name for the outage in the *New Name* box and click the *add* symbol.
. Under Node Labels, select a node to include in the scheduled outage and click *Add*.
. Under Interfaces, select a node interface to include in the scheduled outage and click *Add*.
** Alternatively, you can click *Select All Nodes and Interfaces* to include all nodes and interfaces in your monitored environment.
. Under Outage Type, select a recurrence schedule (*Specific*, *Daily*, *Weekly*, *Monthly*).
. Set a date and time for the outage.
The available date and time settings depend on the recurrence schedule you choose:
** *Specific:* Set a specific date and time period.
This type of scheduled outage occurs only once during the specified period of time.
** *Daily:* Set a time period during which a daily outage will occur.
** *Weekly:* Set the day of the week and the time period during which a weekly outage will occur.
** *Monthly:* Set the day of the month and the time period during which a monthly outage will occur.
. Click *Add Outage*.
. Under Applies To, select the functions that the outage will suppress:
** *Notifications:* Suppress all or no notifications.
** *Status Polling:* Include or exclude specific systems from status polling during the outage.
** *Threshold Checking:* Include or exclude specific systems from threshold checking during the outage.
** *Data Collection:* Include or exclude specific systems from data collection during the outage.
. Click *Save*.
