"C:\progra~1\OpenNMS Remote Poller\bin\poller" //US//OpenNMSRemotePoller ^
--DisplayName="OpenNMS Remote Poller" ^
--Description="OpenNMS Remote Poller - Headless Version - http://opennms.org" ^
--StartMode exe ^
--StopMode exe ^
--ServiceUser=.\rpoller ^
--ServicePassword=opennms ^
--StartImage="c:\Program Files\Java\jre1.6.0_07\bin\javaws.exe" ^
--StartParams="-Xnosplash#http://172.16.56.1:8980/opennms/webstart/headless.jnlp" ^
--StopImage="c:\Program Files\Java\jre1.6.0_07\bin\javaws.exe" ^
--LogLevel=DEBUG ^
--LogPath="c:\Program Files\OpenNMS\logs\remote-poller" ^
--LogPrefix=procrun.log ^
--Startup=auto ^
--StdOutput="c:\Program Files\OpenNMS\logs\remote-poller\output.log" ^
--StdError="c:\Program Files\OpenNMS\logs\remote-poller\error.log"