
= CitrixMonitor

This monitor tests if a Citrix(R) Server or XenApp Server(R) is providing the Independent Computing Architecture (ICA) protocol on TCP 1494.
The monitor opens a TCP socket and tests the greeting banner returns with ICA; otherwise, the service is unavailable.

== Monitor facts

[cols="1,7"]
|===
| Class Name
| `org.opennms.netmgt.poller.monitors.CitrixMonitor`
|===

== Configuration and use

.Optional monitor-specific parameter for the CitrixMonitor
[options="header"]
[cols="1,3,2"]
|===
| Parameter
| Description
| Default

| port
| TCP port where the ICA protocol
| 1494
|===

This monitor implements the <<reference:service-assurance/introduction.adoc#ref-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

WARNING: If you use session reliability to configure the MetaFrame Presentation Server Client, the TCP port is 2598 instead of 1494.
         Find more information on http://support.citrix.com/article/CTX104147[CTX104147].
         It is not verified if the monitor works in this case.

== Examples

The following example configures {page-component-title} to monitor the ICA protocol on TCP 1494 with two retries and waiting five seconds for each retry.
[source, xml]
----
<service name="Citrix-TCP-ICA" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2" />
    <parameter key="timeout" value="5000" />
</service>

<monitor service="Citrix-TCP-ICA" class-name="org.opennms.netmgt.poller.monitors.CitrixMonitor" />
----
