
= DeviceConfigMonitor

This Monitor tries to retrieve config from the network device and will show corresponding status based on whether config retrieval succeeded or not.

== Monitor Facts

[cols="1,7"]
|===
| Class Name
| `org.opennms.features.deviceconfig.monitors.DeviceConfigMonitor`
|===

== Configuration and Use

.Monitor specific parameters for the DeviceConfigMonitor
[cols="1,3,1"]
|===

| Parameter
| Description
| Default value

3+| *Required*

| script-file
| Script file that needs to be used to retrieve config.
| `-`

3+| *Optional*

| config-type
| If Device has multiple configs, config-type should be specified with each service.
| default

| schedule
| Schedule for fetching config in the form of cron expression.
| 0 0 0 * * ?

|===


== Examples

example configuration on how to configure the DeviceConfigMonitor in the `poller-configuration.xml`.

[source, xml]
----
<parameter key="schedule" value="${requisition:dcb:schedule|0 0 0 * * ?}"/>
<parameter key="script-file" value="${requisition:script-file|juniper-vsrx-default}.dcb"/>
----

== Schedule and interval

For Device Config Monitor service, interval is configured to be 300secs and schedule is a cron expression. Default
cron expression runs every 24 hrs at 12.00am (0 0 0 * * ?). Monitor retrieves the Device config when the next trigger
from schedule falls within the interval.
