
= DeviceConfigMonitor

This monitor tries to retrieve configuration from the network device and shows the status of that retrieval (success, failed, and so on).

== Monitor Facts

[cols="1,7"]
|===
| Class Name
| `org.opennms.features.deviceconfig.monitors.DeviceConfigMonitor`
|===

== Configuration and Use

.Monitor-specific parameters for the DeviceConfigMonitor
[cols="1,3,1"]
|===

| Parameter
| Description
| Default value

3+| *Required*

| script-file
| Script file to use to retrieve configuration.
| -

3+| *Optional*

| config-type
| If device has multiple configurations, specify the config-type with each service.
| default

| schedule
| Schedule to fetch configuration, in the form of cron expression.
| `0 0 0 * * ?`
The default cron expression runs every 24 hrs at 12:00 a.m.


|===


== Examples

Example for how to configure the DeviceConfigMonitor in the `poller-configuration.xml`.

[source, xml]
----
<parameter key="schedule" value="${requisition:dcb:schedule|0 0 0 * * ?}"/>
<parameter key="script-file" value="${requisition:dcb:script-file|juniper-vsrx-default}.dcb"/>
----

== Schedule and interval

The service uses an interval of 300 seconds and a cron expression for the schedule.
The default cron expression runs every 24 hrs at 12:00 a.m. (`0 0 0 * * ?`).
The monitor checks every 300 seconds (interval) for the next trigger time in the cron schedule.
It retrieves the configuration only when the next trigger time matches the current time (current time must be greater than the trigger time).
For example, if the monitor checks at 11:59 p.m., but the trigger time is 12:00 a.m., the monitor will retrieve the configuration at the next check interval at 12:04 a.m.