
= PercMonitor

This monitor tests the status of a PERC RAID array.

The monitor first polls the RAID-Adapter-MIB::logicaldriveTable (1.3.6.1.4.1.3582.1.1.2) to retrieve the status of the RAID array you want to monitor.
If the status object value of the corresponding logicaldriveEntry is not 2, the array is degraded and the monitor further polls the RAID-Adapter-MIB::physicaldriveTable (1.3.6.1.4.1.3582.1.1.3) to detect the failed drive(s).

IMPORTANT: This monitor requires the outdated persnmpd software to be installed on the polled nodes.
           Please use the <<service-assurance/monitors/OmsaStorageMonitor.adoc#,OmsaStorageMonitor>> where possible.

== Monitor facts

[cols="1,7"]
|===
| Class Name
| `org.opennms.netmgt.poller.monitors.PercMonitor`
|===

== Configuration and use

.Optional monitor-specific parameters for the PercMonitor
[options="header"]
[cols="1,3,2"]
|===
| Parameter
| Description
| Default

| array
| The RAID ar
ray you want to monitor.
| 0.0

| port
| The UDP port to connect to.
| From snmp-config.xml
|===

This monitor implements the <<reference:service-assurance/introduction.adoc#ref-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

== Examples

[source, xml]
----
<!-- Monitor 1st RAID arrays using configuration from snmp-config.xml -->
<service name="PERC" interval="300000" user-defined="false" status="on" />

<monitor service="PERC" class-name="org.opennms.netmgt.poller.monitors.PercMonitor" />
----
