
[[threshold-create]]
= Create a Threshold

. Click the gear icon in the top-right.
. Under *Performance Measurement*, choose *Configure Thresholds*.
.. A screen with a list of preconfigured threshold groups appears.
We will work with *netsnmp*.
For information on how to create a threshold group, see xref:thresholds/thresh-group.adoc#threshold-group[Create a Threshold Group].
. Click *Edit* beside the *netsnmp* group.
. Click *Create New Threshold* at the bottom of the *Basic Thresholds* area of the screen.
. Set the following information and click *Save*:

[options="header"]
[cols="1,3,2"]
|===

| Field
| Description
| Default

| Type
| Triggers an event when the data source value equals or exceeds the threshold value, and re-arms when it equals or drops below the re-arm value.
| high

| Datasource
| Name of the data source you want to threshold against.
For this tutorial, we have provided the data source for logged-in users.
For information on how to determine a metric's data source, see xref:thresholds/datasource.adoc#datasource-determine[Determine the data source].
| hrSystemNumUsers


| Datasource label
| Optional text label.
Not required for this tutorial.
| leave blank

| Value
| The value above which we want to trigger an event.
In this case, we want to trigger an event when the number of logged-in users exceeds two.
| 2

| Re-arm
| The value below which we want the system to re-arm.
In this case, once the number of logged-in users falls below two.
| 2

| Trigger| The number of consecutive times the threshold value can occur before the system triggers an event.
Since our default polling period is 5 minutes, a value of 3 means {page-component-title} would create a threshold event if there are more than 2 users for 15 minutes.
| 3

| Description
| Optional text to describe your threshold.
| leave blank

| Triggered UEI
| A custom unique event identifier (UEI) sent into the events system when the threshold is triggered.
A custom UEI for each threshold makes it easier to xref:notifications/introduction.adoc#ga-notifications-introduction[create notifications].
If left blank, it defaults to the standard thresholds UEIs.
| leave blank

| Re-armed UEI
| A custom unique event identifier (UEI) sent into the events system when the threshold is re-armed.
| leave blank

|===

[[threshold-test]]
== Test the threshold

To test the threshold we just created, log a second person into the node you are monitoring.
Navigate to the *Events* page.
You should see an event that indicates your threshold triggered when more than one user logged in.

Log out the second user.
The *Events* page should indicate that the system has re-armed.

[[thresh-cpu]]
== Create a threshold for CPU use
This procedure describes how to create an expression-based threshold when the five-minute CPU load average metric reaches or goes above 70% for two consecutive measurement intervals.
Expression-based thresholds are useful when you need to threshold on a percentage, not the actual value of the data collected.

NOTE: Expression-based thresholds work only if the data sources in question are in the same directory.

. Click the gear icon in the top-right.
. Under *Performance Measurement*, choose *Configure Thresholds*.
. Click *Edit* beside the *netsnmp* group.
. Click *Create New Expression-based Threshold*.
. Fill in the following information:

+

[options="header"]
[cols="1,3,3"]
|===

| Field
| Description
| Default

| Type
| Triggers an event when the data source value equals or exceeds the threshold value, and re-arms when it equals or drops below the re-arm value.
| high

| Expression
| Divides the five-minute CPU load average by 100 (to obtain the effective load average\*), which is then divided by the number of CPUs.
This value is then multiplied by 100 to provide a percentage.

(* SNMP does not report in decimals, which is why the expression divides the loadavg5 by 100.)
| ((loadavg5 / 100) / CpuNumCpus) * 100

| Datasource type
| The type of data source from which you are collecting data.
| node

| Datasource label
| Optional text label.
Not required for this tutorial.
| leave blank

| Value
| Trigger an event when the five-minute CPU load average goes above 70%.
| 70

| Re-arm
| Re-arm the system when the five-minute CPU load average drops below 50%.
| 50

| Trigger
| The number of consecutive times the threshold value can occur before the system triggers an event.
In this case, when the five-minute CPU load average goes above 70% for two consecutive polling periods.
| 2

| Description
| Optional text to describe your threshold.
| Trigger an alert when the five-minute CPU load average metric reaches or goes above 70% for two consecutive measurement intervals.

| Triggered UEI
| A custom unique event identifier (UEI) sent into the events system when the threshold is triggered.
A custom UEI for each threshold makes it easier to xref:notifications/introduction.adoc#ga-notifications-introduction[create notifications].
If left blank, it defaults to the standard thresholds UEIs.
| leave blank

| Re-armed UEI
| A custom unique event identifier (UEI) sent into the events system when the threshold is re-armed.
| leave blank

|===

. Click *Save*.