
// Allow GitHub image rendering
:imagesdir: ../../images

[[ga-ticketing-jira]]
=== JIRA Ticketing Plugin

The _JIRA Ticketing Plugin_ is used to create JIRA Issues in response to _OpenNMS_ alarms.

[[ga-ticketing-jira-setup]]
==== Setup

First, you'll need to install the `opennms-plugin-ticketer-jira` package for your system.
The JIRA ticketing plugin and it's dependencies are not part of the core packages.

Now, in order to enable the plugin start by setting following property in `${OPENNMS_HOME}/etc/opennms.properties`:

[source]
----
opennms.ticketer.plugin=org.opennms.netmgt.ticketd.OSGiBasedTicketerPlugin
----

Configure the plugin options by setting the following properties in `${OPENNMS_HOME}/etc/jira.properties`:

[options="header, autowidth"]
|===
| Name            | Description
| `jira.host`     | JIRA Server Url
| `jira.username` | Username
| `jira.password` | Password
| `jira.project`  | Project Code
| `jira.type`     | Issue Type ID to use when opening new issues
| `jira.resolve`  | Name of the transition to use when resolving issues
| `jira.reopen`   | Name of the transition to use when re-opening issues
|===

NOTE: See https://confluence.atlassian.com/display/JIRA050/Finding+the+Id+for+Issue+Types for determining the appropriate issue type id.

Next, add `jira-troubleticketer` to the `featuresBoot` property in the `${OPENNMS_HOME}/etc/org.apache.karaf.features.cfg`

Restart _OpenNMS_.

When _OpenNMS_ has started again, login to the _Karaf Shell_ and install the feature:

[source]
----
features:install jira-troubleticketer
----

The plugin should be ready to use. When troubleshooting, consult the following log files:

* ${OPENNMS_HOME}/data/log/karaf.log
* ${OPENNMS_HOME}/logs/trouble-ticketer.log
