
[[ga-events-sources-snmp-traps]]
= SNMP Traps

OpenNMS {page-component-title} can receive and process SNMP traps/informs from SNMP-capable devices out of the box.
It receives SNMP traps via the trapd service daemon, which is enabled by default.

IMPORTANT: Disabling `trapd` renders {page-component-title} incapable of receiving SNMP traps.

{page-component-title} transforms these traps into events according to preconfigured rules included by default and those created by users.

== Before you begin
There are a few tasks you must complete before OpenNMS can receive SNMP traps:

. Configure the port on which OpenNMS can receive SNMP traps (see xref:deployment:core/getting-started.adoc#receive-snmp-traps[Receive SNMP Traps/Informs]).
. Ensure that SNMP-capable devices on your network are configured tp send traps to OpenNMS.

[[trap-config]]
== SNMP Trap Configuration: How To

Configure SNMP traps to customize the types of trap information you receive and the conditions under which you receive it. ##or ONMS converts it to event?##
For example, you may want to see an event only when a device is down, or when a combination of criteria are met (give examples).
OpenNMS converts these traps to events only when the conditions you define are met.

There are several ways to configure {page-component-title} to customize the events you receive and see:

* Determine what problem you are trying to solve (for example, I want to know X about my Cisco router)
* Manually send the corresponding event to OpenNMS server and see how OpenNMS handles it (see x-reference to the send-event.adoc file)
* Configure the event to meet your requirements
** <<trap-def-create, Create trap definitions>> to specify criteria for when OpenNMS creates an event
** Define varbinds for further granularity on the conditions for creating an event

[[trap-def-create]]
=== Create event definition for an SNMP trap
{page-component-title} includes event definitions for traps from many vendors' equipment.
Use the `mask` tag to match SNMP traps in `eventconf.xml`.
See xref:events:anatomy-events.adoc[Anatomy of an Event] for details on event structure.

The following example shows a Cisco Systems event for their C3800 device.
Parts of it look similar to the internally generated events, with the main difference being the `mask` block.
This block consists of <maskelement> tags, and the event will match only if all of the defined tags are met.

.Cisco systems event
[source, xml]
----
<event>
  <mask>
    <maskelement>
      <mename>id</mename>
      <mevalue>.1.3.6.1.4.1.9.9.70.2</mevalue>
    </maskelement>
    <maskelement>
      <mename>generic</mename>
      <mevalue>6</mevalue>
    </maskelement>
    <maskelement>
      <mename>specific</mename>
      <mevalue>17</mevalue>
    </maskelement>
  </mask>
  <uei>http://uei.opennms.org/vendor/Cisco/traps/ciscoC3800SysAggregateStatusChange</uei>
  <event-label>CISCO-C3800-MIB defined trap event: ciscoC3800SysAggregateStatusChange</event-label>
  <descr>&#38lt;p&#38gt;Notification that the aggregate status of a node
         has changed.&#38lt;/p&#38gt;&#38lt;table&#38gt;
         &#38lt;tr&#38gt;&#38lt;td&#38gt;&#38lt;b&#38gt;
         c3800SysNextTrapSeqNum&#38lt;/b&#38gt;</td&#38gt;&#38lt;td&#38gt;%parm[#1]%
         &#38lt;/td&#38gt;&#38lt;td&#38gt;&#38lt;p;&#38gt;</p&#38gt;&#38lt;/td;&#38gt;&#38lt;/tr&#38gt;&#38lt;tr&#38gt;&#38lt;td&#38gt;&#38lt;b&#38gt;
         sysName&#38lt;/b&#38gt;&#38lt;/td&#38gt;&#38lt;td&#38gt;%parm[#2]%
         &#38lt;/td&#38gt;&#38lt;td&#38gt;&#38lt;p;&#38gt;&#38lt;/p&#38gt;&#38lt;/td;&#38gt;&#38lt;/tr&#38gt;&#38lt;tr&#38gt;&#38lt;td&#38gt;&#38lt;b&#38gt;
         c3800SysTrapSeverity&#38lt;/b&#38gt;&#38lt;/td&#38gt;&#38lt;td&#38gt;%parm[#3]%
         &#38lt;/td&#38gt;&#38lt;td&#38gt;&#38lt;p;&#38gt;
         clear(1) minor(2) major(3)&#38lt;/p&#38gt;
         &#38lt;/td;&#38gt;&#38lt;/tr&#38gt;&#38lt;tr&#38gt;&#38lt;td&#38gt;&#38lt;b&#38gt;
         c3800SysAggregateStatus&#38lt;/b&#38gt;&#38lt;/td&#38gt;&#38lt;td&#38gt;%parm[#4]%
         &#38lt;/td&#38gt;&#38lt;td&#38gt;&#38lt;p;&#38gt;
         clear(1) minor(2) major(3)</p>
         &#38lt;/td;&#38gt;&#38lt;/tr&#38gt;&#38lt;/table&#38gt;
  </descr>
  <logmsg dest='logndisplay'><p>Cisco Event: C3900: Node Status has changed.</p></logmsg>
  <severity>Indeterminate</severity>
</event>
----

This particular event will match an SNMP trap whose enterprise OID (id) is equal to ".1.3.6.1.4.1.9.9.70.2", its generic trap value is enterprise specific (6), and its specific trap value is 17.

Possible <mename> values include the following:
* uei
* source
* host
* snmphost
* nodeid
* interface
* service
* id
* specific (Vendor-specific error conditions and error codes. Refer to the associated MIB for details.)
* generic (fixed, universal SNMP trap types)
** Coldstart or Warmstart
** Linkup or Linkdown
** Authentication fails
** egpNeighborloss (Agent cannot communicate with its EGP (Exterior Gateway Protocol) peer.)
* community

You can use the "%" symbol to indicate a wildcard in the mask values.
For example, to match all Cisco events, you could use the following:

[source, xml]
----
<mask>
  <maskelement>
    <mename>id</mename>
    <mevalue>.1.3.6.1.4.1.9.%</mevalue>
  </maskelement>
</mask>
----

Note: The order in which events are listed in the eventconf.xml file is extremely important. The search will stop with the first event definition that matches the given event.

Thus if the above code with the wildcard was listed before the more specific ciscoC3800SysAggregateStatusChange event, the latter event would never be generated. Also note that the wildcard is simply a substring match.
If an event was generated from a Cisco device with the Enterprise OID of ".1.3.6.1.4.1.9" it would not match this event, as there is no trailing ".".
If the trailing "." is left off, care must be taken so that a trap with an OID of ".1.3.6.1.4.1.99" is listed before the ".1.3.6.1.4.1.9%" event or else it will match the more generic event.




== Trap value representation

When octet strings are translated into event parameters, OpenNMS first attempts to treat them as character encodings.
If all bytes in the string are valid UTF-8 or ISO-8859-1 characters, the string is stored as these characters.
If this is not possible, the value is encoded as a Base64 string.

== Traps forwarded via proxy

When SNMP traps are forwarded through a proxy using SNMPv2c or SNMPv3, preserving the original source IP address is a challenge due to the lack of an `agent-addr` field in the `TRAP-V2` PDU used in those protocol versions.
https://tools.ietf.org/html/rfc3584#page-42[RFC 3584] defines an optional varbind `snmpTrapAddress (.1.3.6.1.6.3.18.1.3.0)` that can be added to forwarded traps to convey the original source IP address.

To configure {page-component-title} to honor `snmpTrapAddress` when present, set `use-address-from-varbind="true"` in the top-level element of `$\{OPENNMS_HOME}/etc/trapd-configuration.xml` and restart {page-component-title}.

.Configuration example for using RFC 3584 helper varbinds in forwarded traps
[source, xml]
----
<trapd-configuration snmp-trap-port="1162"<1>
                     new-suspect-on-trap="false"<2>
                     use-address-from-varbind="true" /><3>
----
<1> Set the SNMP trap daemon listening port to 1162/udp
<2> Don't create new nodes when receiving a SNMP Trap with an unknown source IP address
<3> Try using the identifier source IP address from the `snmpTrapAddress` varbind instead of the UDP source IP address

