
[[ga-events-sources-snmp-traps]]
= SNMP Traps

OpenNMS {page-component-title} can receive and process SNMP traps/informs from SNMP-capable devices out of the box.
It receives SNMP traps via the trapd service daemon, which is enabled by default.

IMPORTANT: Disabling `trapd` renders {page-component-title} *incapable* of receiving SNMP traps.

{page-component-title} transforms these traps into events according to preconfigured rules included by default and those created by users.

== Before you begin
There are a few tasks you must complete before OpenNMS can receive SNMP traps:

. Configure the port on which OpenNMS can receive SNMP traps (see xref:deployment:core/getting-started.adoc#receive-snmp-traps[Receive SNMP Traps/Informs]).
. Ensure that SNMP-capable devices on your network are configured tp send traps to OpenNMS.

[[trap-config]]
== SNMP Trap Configuration: How To

Configuring SNMP traps lets you customize the types of trap information you receive and the conditions under which you receive you receive it. ##or ONMS converts it to event?##
For example, you may want to see an event only when a device is down, or when a combination of criteria are met (give examples).
OpenNMS converts these traps to events only when the conditions you define are met.

There are several ways to configure {page-component-title} to customize the events you receive and see:

* Determine what problem you are trying to solve (i.e., I want to know X about my Cisco router)
* Manually send the corresponding event to OpenNMS server and see how OpenNMS handles it
* Then configure the event to meet your requirements

* Manually send events to determine watch them come in as undefined events, then use the recorded data to generate event definitions (when there aren't MIBs available to import)

Audit the default Management Information Base (MIB) files and comment out the ones you do not need.
* Import MIB files that are not included in OpenNMS that you do need.
* Create trap definitions to specify criteria for when OpenNMS creates an event
** Define varbinds for further granularity on the conditions for creating an event

=== Edit 


included by default and customized by users through Management Information Base (MIB) files and event configuration.

By default, {page-component-title} includes

OpenNMS uses the `mask` tag to match SNMP traps in `eventconf.xml`.

===
unformatted events - no MIB file




{page-component-title} includes event definitions for traps from many vendors' equipment.

== Trap value representation

When octet strings are translated into event parameters, OpenNMS first attempts to treat them as character encodings.
If all bytes in the string are valid UTF-8 or ISO-8859-1 characters, the string is stored as these characters.
If this is not possible, the value is encoded as a Base64 string.

== Traps forwarded via proxy

When SNMP traps are forwarded through a proxy using SNMPv2c or SNMPv3, preserving the original source IP address is a challenge due to the lack of an `agent-addr` field in the `TRAP-V2` PDU used in those protocol versions.
https://tools.ietf.org/html/rfc3584#page-42[RFC 3584] defines an optional varbind `snmpTrapAddress (.1.3.6.1.6.3.18.1.3.0)` that can be added to forwarded traps to convey the original source IP address.

To configure {page-component-title} to honor `snmpTrapAddress` when present, set `use-address-from-varbind="true"` in the top-level element of `$\{OPENNMS_HOME}/etc/trapd-configuration.xml` and restart {page-component-title}.

.Configuration example for using RFC 3584 helper varbinds in forwarded traps
[source, xml]
----
<trapd-configuration snmp-trap-port="1162"<1>
                     new-suspect-on-trap="false"<2>
                     use-address-from-varbind="true" /><3>
----
<1> Set the SNMP trap daemon listening port to 1162/udp
<2> Don't create new nodes when receiving a SNMP Trap with an unknown source IP address
<3> Try using the identifier source IP address from the `snmpTrapAddress` varbind instead of the UDP source IP address

