
// Allow GitHub image rendering
:imagesdir: ../../../images

This section describes how to model and configure _Business Services_ and the dependency graph to build hierarchies.

The _Business Service Monitoring_ has the following components:

* _BSMD_: The component to calculate the status for the _Business Service Hierarchy_
* _Business Service Editor_: Component in the admin web application which allows you to create, update or delete _Business Services_
* _Topology View for Business Services_: Visual representation of the _Business Service Hiearchy_ as a component of the _Topology User Interface_.
* _BSM ReST API_: ReST based API to create, update or query _Business Services_ with external applications

The following sections describe the usage and components of _BSM_ in more detail.

=== Business Service Definition


A _Business Service_ is the building block which represents a high level _BS_ in the organization, e.g. a web portal for placing orders or something like the Wireless network access in a Hotel.
The _Operational Status_ of a specific _BS_ it is calculated by _Edges_ which is a set of _Alarms_ defined with _Reduction Keys_.
A _Reduction Key_ is used to generate an _Alarm_, e.g. from a specific monitored service, threshold, SNMP trap or Syslog related _Alarm_.

The _BS_ is defined with the following components:

* _Business Service Name_: Arbitrary name of the _BS_
* _Reduce Function_: Function to aggregate the _Operational Status_ for this _BS_ with optional configuration parameter, e.g. _Highest Severity_
* _Edges_: A set of _Reduction Keys_ which is used to calculate the _Operational Status_ of the _BS_
* _Attributes_: Additional key value pair which can be assigned to a specific _BS_

----

The _Business Service_ is modeled through a _Business Service Definition_ and is a composition of _Reduction Keys_.
A _Reduction Key_ is used to generate an _Alarm_, e.g. from a specific monitored service, threshold, SNMP trap or Syslog related _Alarm_.
The _BS_ is defined with the following components:

* _Business Service Name_: Arbitrary name of the _BS_
* _Reduce Function_: Function to aggregate the _Operational Status_ for this _BS_ with optional configuration parameter, e.g. _Highest Severity_
* _Edges_: A set of _Reduction Keys_ which is used to calculate the _Operational Status_ of the _BS_
* _Attributes_: Additional key value pair which can be assigned to a specific _BS_

==== Reduce Functions

A _Reduce Function_ is used to aggregate the _Operational Status_ for the _BS_.
The _Alarm Severity_ from the _Edges_ are used as input for the _Reduce Function_.
For this operation the following _Reduce Functions_ are available:

.Status calculation _Reduce Functions_
[options="header, autowidth"]
|===
| Name                      | Description
| `Highest Severity`        | Uses the value of the highest severity, _Weight_ is ignored.
| `Threshold`               | Uses the highest severity found more often than the given threshold, e.g. 0.26 can also be seen as 26%, which means at least 2 of 4 _Alarms_ need to be raised to change the _BS_.
| `Highest Severity Above`  | Uses the highest severity only if it is greater or equal than the given threshold severity, _Weight is ignored.
|===

The following table shows the status calculation with _Edges_ assigned to an _IP Service_.
The _IP-Service_ is driven by the monitoring of the _ICMP_ service for three Web Server.
In the table below you find a configuration where _Web Server 3_ is weighted 3 times higher than the other and a threshold of 0.33 (33%) is configured.

.Example for status calculation using the Threshold function
[options="header, autowidth"]
|===
| Name       | Weight | Weight Factor | Input Severity | Operational Status | Critical | Major | Minor | Warning | Normal
| Web-ICMP-1 |   1    |     0,2       |    Critical    |      Critical      |    0,2   |  0,2  |  0,2  |   0,2   |  0,2
| Web-ICMP-2 |   1    |     0,2       |     Normal     |       Normal       |    0     |  0    |  0    |   0     |  0,2
| Web-ICMP-3 |   3    |     0,6       |    Warning     |      Warning       |    0     |  0    |  0    |   0,6   |  0,6
| Total      |        |     1,0       |                |                    |    0,2   |  0,2  |  0,2  |   0,8   |  1
| Percentage |        |     100%      |                |                    |    20%   |  20%  |  20%  |   80%   |  100%
|===

The _Operational Status Severity_ is evaluated from left to right, the first value higher then the configured _Threshold_ is used.
In this case the _Operational Status_ is set to _Warning_ because the first threshold which exceeds _33%_ is _Warning_ with _80%_.

==== Edges

The _BS_ dependency graph has _Edges_ which are represented through a _Reduction Key_.
It allows to model any kind of an _Alarm_ as an _input_ for a _BS_.
As _Edges_ the following types can be used:

* _Child Service_: Another already defined _Business Service_ where the current _BS_ depends on
* _IP Service_: Represents an alarm based on a monitored _IP Service_ and is defined by a set of _Reduction Keys_ for _nodeLostService_, _interfaceDown_ and _nodeDown_
* _Reduction Key_: Set a user defined custom _Reduction Key_ for any _Alarm_, e.g. _SNMP Trap_ or _Threshold_ based Alarm

===== Edge with Child Services

The _Child Service_ represents is any other defined _BS_ and is used to model a _BS_ dependency.

IMPORTANT: The _BS dependency graph_ is a directed circle free graph definition.
           A _BS_ can be only selected once as dependency in a given _BS Hierarchy_.

===== Edge with IP Services

The _IP Service_ is a predefined set of _Reduction Keys_ which allows easily to assign a specific _Monitored Service_ to the given _BS_.
As an example you have multiple Servers with a _Monitored Service_ _SMTP_ and you want to model a _BS_ named _Mail Communication_.
If just the _Reduction Key_ for a _nodeLostService_ is assgined, the _BS_ would not be affected in case the _IP Interface_ or the whole _Node_ goes down.
_OpenNMS_ generates _Alarms_ with different _UEI_ which needs to be assigned to the _BS_ as well.
To make it easier to model this use case the _IP Service_ generates the following _Reduction Keys_ automatically:

* `uei.opennms.org/nodes/nodeLostService:%nodeId%:%ipAddress%:%serviceName%`: Matches _Alarms_ when the given _Monitored Service_ goes down
* `uei.opennms.org/nodes/interfaceDown:%nodeId%:%ipAddress%`: Matches _Alarms_ when the given _IP Interface_ of the _Monitored Service_ goes down
* `uei.opennms.org/nodes/nodeDown:%nodeId%`: Matches _Alarms_ when the given _Node_ of the _Monitored Service_ goes down

===== Edges with custom Reduction Keys

If the _Operational Status_ of a _BS_ is be based from any other generated _Alarm Severity_ based on the _Reduction Key_.
The _Reduction Key_ as an _Edge_ has the following parameter:

* _Reduction Key_: The _Reduction Key_ in syntax of _Alarm Parameter_ enclosed with `%` and separated with `:`, e.g. `%uei.opennms.org/nodes/nodeLostService%:%nodeId%:%ipAddress%`
* _Friendly Name_: An arbitrary name for this _Edge_
* _Map Function_: The associated _Map Function_ for this _Edge_
* _Weight_: The _Weight_ for this _Edge_ is evaluated in case multiple _Edges_ for the _BS_ are defined

===== Map Functions

The mapping defines which _Severity_ is used to calculate the _Operational Status_ of the _BS_ and is defined in _Map Functions_ listed below:

.Calculation of the _Operational Status_ with _Map Functions_
[options="header, autowidth"]
|===
| Name       | Description
| `Identity` | Use the same _Severity_ as _Operational Status_ of the _BS_
| `Increase` | Increase the _Severity_ by one level and use it as _Operational Status_ of the _BS_
| `Decrease` | Decrease the _Severity_ by one level and use it as _Operational Status_ of the _BS_
| `SetTo`    | Set the _Operational Status_ to a constant _Severity_ value
| `Ignore`   | The input of the _Edge_ is ignored for _Operational Status_ calcualation
|===

==== Attributes

Each _Business Services_ can contain a key value pair as additional attributes.
It allows to enrich the _BS_ with additional information.
The _Attributes_ can be used in further workflows e.g. generating _Notifications_ or _BS_ related _Alarms_.



=== Business Service Daemon

The calculation of the _Operational Status_ of the _BS_ is driven by the _Business Service Daemon_ (bsmd).
It is responsible for tracking the operational status of all _BS_ and for sending events in case of operational status changes.
Every time the configuration of a _Business Service_ is changed a reload of the daemon's configuration is required.
This includes changes like the name of the _Business Service_ or its attributes as well as changes regarding the _Reduction Keys_, contained _Business Services_ or _IP Services_.
The _bsmd_ configuration can be reloaded with the following mechanisms:

* Click the _Reload Daemon_ button in the _Business Service Editor_
* Send the _reloadDaemonConfig_ event using `send-event.pl` or use the WebUI in _Manually Send an Event_ with parameter `daemonName bsmd`
* Use the ReST API to perform a `POST` request to `/opennms/api/v2/business-services/daemon/reload`

If the reload of the configuration is done an event of type `uei.opennms.org/internal/reloadDaemonConfigSuccessful` is fired.

.Example reloading bsmd configuration from CLI
[source,shell]
----
$OPENNMS_HOME/bin/send-event.pl -p 'daemonName bsmd' uei.opennms.org/internal/reloadDaemonConfig
----

.Example reloading bsmd configuration through ReST POST
[source,shell]
----
curl -X POST -u admin:admin -v http://localhost:8980/opennms/api/v2/business-services/daemon/reload
----
