
// Allow GitHub image rendering
:imagesdir: ../../../images

OpenNMS provides a very powerful and fine grained service assurance layer based on the Poller Daemon.
The service assurance layer monitors and tracks the status of nodes, interfaces and services.
Events, alarms and outages are used to track and describe the status of the managed elements.
The status of a managed element can be determined based on events, alarms and outages.
This approach treats every element of the system individually.
There is no concept of relations between different nodes or relations between services in the service assurance layer.

The Business Service Monitoring (BSM) feature adds the ability to model relations between managed elements.
It composes many managed elements into hierarchically structured Business Services.
A business service represents a high level status view of all its managed elements.
Business services provide a high level view on several managed elements.
The Business Service Monitoring feature does not affect the service assurance layer at all.
The alarm status of the managed elements is provided by the service assurance layer.
Business Services determine the status of the contained managed elements based on the alarm status provided by the service assurance layer.
The alarm status of the contained managed elements is correlated by the Business Service into its own operational status.
The operational status of a Business Service can be checked at any time.
If the operational status of a Business Service is changing corresponding events are fired.


=== Business Service Definition
Business Services can contain attributes, reduction keys, references to monitored services or other Business Services.


==== Reduction keys
Business Services are built to correlate the alarm based status of managed elements into its operational status.
Business Services can contain a list of reduction keys that are used to identify the relevant alarms to correlate.
Reduction keys can be added to Business Services as plain text.


==== Monitored services / IP Services
Business Services can contain references to monitored services (node/interface/service combination).
A referenced monitored service is called IP Service in the Business Service.
IP Services in a Business Service are interpreted as two reduction keys:

* `uei.opennms.org/nodes/nodeLostService::%nodeID%:%ipAddress%:%serviceName%`
This reduction key matches the alarms fired if the monitored service goes down.
* `uei.opennms.org/nodes/interfaceDown::%nodeID%:%ipAddress%`
This reduction key matches the alarms fired if the interface with the given ip address on the node goes down.
* `uei.opennms.org/nodes/nodeDown::%nodeID%`
This reduction key matches the alarms fired if the entire node providing the monitored service goes down.


==== Business Services
Business Services can contain other Business Services.
This offers the ability to create hierarchically structures of Business Services.
To determine the status of a contained Business Service its operational status is used by the containing Business Service.


==== Attributes
Each Business Services can contain a set of key/value attributes.


=== Operational Status
Every Business Service maintains an operational status that represents the overall status of the contained elements.
The set of status for the operational status is defined by the OpenNMS severities.
The operational status of a Business Service is correlated in two steps.

First the status of each contained element is mapped to the Business Service.
For reduction keys and IP Services the status is based on their alarm status.
For contained Business Services the operational status is used.
The mapping can be performed in one of the _Map Functions_ listed below.

.State calculation _Map Functions_
[options="header, autowidth"]
|===
| Name       | Description
| `Identity` | Uses the severity `as-is`
| `Increase` | Increases the severity one level
| `Decrease` | Decreases the severity one level
| `Set To`   | Uses a constant severity
| `Ignore`   | Ignores the severity of the managed element
|===

The list of mapped status are then reduced into the operational status of the Business Service.
For the reduction the following _Reduce Functions_ are available.

.State calculation _Reduce Functions_
[options="header, autowidth"]
|===
| Name            | Description
| `Most Critical` | Uses the value of the most critical severity.
| `Threshold`     | Uses the highest severity found more often than the given threshold.
|===


==== Operational Status changes
If a Business Service changes its operational status, an OpenNMS event is fired.
The event is of the type `uei.opennms.org/bsmd/serviceOperationalStatusChanged`.
The log message of the event contains the name of the Business Service.
Additionally the previous operational status and the new operational status are included.
This event has no node, interface or service associated.
It also does not contain a reduction key to cause any alarms.


==== Business Service Daemon
Internally the Business Service Monitoring features is driven by the Business Service Daemon (Bsmd).
It is responsible for tracking the operational status of all Business Services and sending events in case of operational status changes.
Every time the configuration of a Business Service is changed a reload of the Bsmd configuration is required.
This includes changes like the name of the Business Service or its attributes as well as changes regarding the reduction keys, contained Business Services or IP Services.

A config reload is always initiated by an `uei.opennms.org/internal/reloadDaemonConfig` event with the parameter `daemonName` set to `bsmd`.
If the reload of the config is done an `uei.opennms.org/internal/reloadDaemonConfigSuccessful` event is fired.

.Options to trigger the config reload event
* Use the `Reload` button on the `Manage Business Services` page in the admin section of the WebUI
* Send the  `reloadDaemonConfig` event directly to trigger the reload
* Use the send-event script
[source,shell]
----
$OPENNMS_HOME/bin/send-event.pl -p 'daemonName bsmd' uei.opennms.org/internal/reloadDaemonConfig
----
* Use the `Manually Send an Event` page of the WebUI located in the admin section to send the event

* Use the Rest-API to perform a `POST` request to `opennms/api/v2/business-services/daemon/reload`

=== Rest-API
The Rest-API is described in the OpenNMS Developers Documentation.
