
= Ticketing
:description: Learn how the ticketer plugin helps {page-component-title} create and update tickets in external systems based on new or resolved alarms.

The ticketing integration lets {page-component-title} create and update tickets in external systems in response to new or resolved alarms.

To activate the ticketing integration, configure the following settings in a `.properties` file in `$\{OPENNMS_HOME}/etc/opennms.properties.d`:

[cols="2,3,1"]
|===
| Property  | Description   | Default Value

| opennms.ticketer.plugin
| The plugin implementation to use.
Each ticketer integration should define which value to set.
The `NullTicketerPlugin` does nothing when attempting to create, update, or delete tickets.
| NullTicketerPlugin

| opennms.alarmTroubleTicketEnabled
| Defines if the integration is enabled.
If enabled, various links to control the issue state appear on the alarm details page.
| false

| opennms.alarmTroubleTicketLinkTemplate
| A template to generate a link to the issue (for example, `\http://issues.opennms.org/browse/$\{id}`).
| $\{id}
|===

== Supported ticketers

For information on supported ticketers and how to configure them, see xref:reference:ticketing/introduction.adoc[].
