
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-ts-newts]]
== Newts

link:http://newts.io/[Newts] is a time-series data store based on link:http://cassandra.apache.org/[Apache Cassandra].
_Newts_ is a persistence strategy, that can be used as an alternative to link:http://www.opennms.org/wiki/JRobin[JRobin] or link:http://oss.oetiker.ch/rrdtool/[RRDtool].

IMPORTANT: It is currently not supported to initialize the _Newts_ keyspace from _Microsoft Windows Server_ operating system.
           _Microsoft Windows_ based _Cassandra_ server can be part of the cluster, but keyspace initialization is only possible using a _Linux-_based system.

[[gi-setup-cassandra]]
=== Setting up Cassandra

It is recommended to install _Cassandra_ on a dedicated server, but is also possible to run a node on the _{opennms-product-name}_ server itself.
This installation guide describes how to set up a single _Cassandra_ instance for evaluating and testing _Newts_.
These steps are not suitable for a high performance production _Cassandra Cluster_.
For further information see link:https://wiki.apache.org/cassandra/GettingStarted[Cassandra Getting Started Guide].
If you already have a running cluster you can skip this section.
