.Install GnuPG and add OpenNMS repository GPG key
[source, console]
----
sudo apt -y install curl gnupg ca-certificates
curl -fsSL https://debian.opennms.org/OPENNMS-GPG-KEY | sudo gpg --dearmor -o /usr/share/keyrings/opennms.gpg
----

.Add and update apt repository
[source, console]
----
echo "deb [signed-by=/usr/share/keyrings/opennms.gpg] https://debian.opennms.org stable main" | sudo tee /etc/apt/sources.list.d/opennms.list
sudo apt update
----

NOTE: You can safely ignore the message about conflicting distributions (expected stable but got opennms-xx).

.Installing the of {page-component-title} Sentinel
[source, console]
----
sudo apt -y install opennms-sentinel
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
     After upgrade, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
     For this reason, it is recommended to exclude the {page-component-title} packages from update except when you are planning on performing an upgrade.

[source, console]
----
sudo apt-mark hold opennms-sentinel
----

.Verify directory structure with the tree command
[source, console]
----
sudo apt -y install tree
tree /opt/sentinel -L 1
----

.Directory structure after successful installation
[source, output]
----
/opt/sentinel
├── bin
├── data -> /var/lib/sentinel/data
├── deploy -> /var/lib/sentinel/deploy
├── etc -> /etc/sentinel
├── lib
└── system
----

.Enable {page-component-title} Sentinel on system boot and start immediately
[source, console]
----
sudo systemctl enable --now sentinel
----
