
[[flows-remote]]
= Distributed/remote flows

Add a Minion to collect flows data from hard-to-reach or remote locations.

== Before you begin

Make sure you do the following:

* set up a xref:operation:flows/basic.adoc#flows-basic[basic] flows environment
* xref:deployment:minion/install.adoc#install-minion[install one or more Minions] on your system

== Configure a listener on a Minion

In this example, we enable a generic listener for the NetFlow v5 protocol on Minion.

IMPORTANT: NetFlow v5 uses the generic UDP listener, but other protocols require a specific listener.
See the examples in `$OPENNMS_HOME/etc/telemetryd-configuration.xml`, or <<reference:telemetryd/listeners/introduction.adoc#ref-listener, Telemetryd Listener Reference>> for details.

To enable and configure a listener for NetFlow v5 on Minion, connect to the Karaf Console and set the following properties:

[source, console]
----
$ ssh -p 8201 admin@localhost
...
admin@minion()> config:edit --alias udp-8877 --factory org.opennms.features.telemetry.listeners
admin@minion()> config:property-set name Netflow-5
admin@minion()> config:property-set class-name org.opennms.netmgt.telemetry.listeners.UdpListener
admin@minion()> config:property-set parameters.port 8877
admin@minion()> config:property-set parsers.0.name Netflow-5-Parser
admin@minion()> config:property-set parsers.0.class-name org.opennms.netmgt.telemetry.protocols.netflow.parser.Netflow5UdpParser
admin@minion()> config:update
----

TIP: If using a configuration management, you can create and use the properties file as startup configuration in `$MINION_HOME/etc/org.opennms.features.telemetry.listeners-udp-8877.cfg`.

[source, console]
----
name = Netflow-5
class-name = org.opennms.netmgt.telemetry.listeners.UdpListener
parameters.port = 8877
parsers.0.name Netflow-5-Parser
parsers.0.class-name org.opennms.netmgt.telemetry.protocols.netflow.parser.Netflow5UdpParser
----

NOTE: The associated protocol, in this case `Netflow-5`, must also be enabled on {page-component-title} for the messages to be processed.

In some scenarios the exporter's address is altered due to network address translation.
In this case you can use node metadata to identify the exporter.
Use the `metaDataNodeLookup` parameter to specify a context-key pair in the form of `context:key` for the lookup.

The value used for the lookup corresponds to the following fields from the various protocols:

[options="header, autowidth"]
|===
| Property     | Description
| NetFlow v5   | engineId
| NetFlow v9   | sourceId
| IPFix        | observationDomainId
| SFlow        | agent_address:sub_agent_id
| BMP          | bgpId
|===