
= Time Series Storage

{page-component-title} stores performance data in a time series storage, JRobin by default.
For different scenarios you may want to use a different time series storage.
The following implementations are installed by default:

.Supported time series databases
[width="100%", cols="1,4"]
|===
| JRobin
| JRobin is a clone of RRDTool written in Java.
It does not fully cover the latest feature set of RRDTool and is the default when you install {page-component-title}.
Data is stored on the local file system of the{page-component-title} node.
Depending on I/O capabilities it works well for small- to medium-size installations.

| RRDTool
| RRDTool is actively maintained and the de-facto standard for time series data.
Data is stored on the local file system of the {page-component-title} node.
Depending on I/O capabilities it works well for small- to medium-size installations.

| Newts
| link:http://opennms.github.io/newts/[Newts] is a database schema for link:http://cassandra.apache.org[Cassandra].
The time series is stored on a dedicated Cassandra cluster, which gives growth flexibility and lets time series data persist in a large scale.
|===

You can use time series storage integrations with plugins based on our OpenNMS Integration API (OIA).
Several plugins are available as a replacement for the ones shipped with OpenNMS {page-component-title} (see xref:time-series-storage/timeseries/ts-integration-layer.adoc#ts-integration-layer[time series integration layer]).

This section describes how to configure {page-component-title} to use RRDTool and Newts.

CAUTION: The way data is stored in different time series databases makes it extremely hard to migrate from one technology to another.
You cannot prevent data loss when you switch from one to another.

== Running two time series writes in parallel

The default time series strategy [rrd,newts,integration] is used for both read/write by default.
It is possible to add another time series write in parallel to the default strategy.

== Writing to newts in parallel

You can enable writing to newts without having `newts` as default time series strategy.

.Create a file to load the `opennms-newts` feature.
[source, console]
----
sudo vi etc/featuresBoot.d/newts.boot
----

.Add feature and save the file
[source, newts.boot]
----
opennms-newts
----

.Restart {page-component-title} Core instance to apply the changes
[source, console]
----
sudo systemctl restart opennms
----

== Writing to Time Series Integration Plugin in parallel

You can enable writing to any time series integration plugin in parallel without having `integration` as default time series strategy.


.Create a file to load the `opennms-timeseries-api` feature.
[source, console]
----
sudo vi etc/featuresBoot.d/timeseries.boot
----

.Add feature and save the file
[source, timeseries.boot]
----
opennms-timeseries-api
----

.Restart {page-component-title} Core instance to apply the changes
[source, console]
----
sudo systemctl restart opennms
----

