
[[time-series-storage]]
= Time Series Database

{page-component-title} stores performance data in a time series database (JRobin by default).
For different scenarios you may want to use a different time series database.
The following implementations are installed by default:

.Supported time series databases
[width="100%", cols="1,4"]
|===
| JRobin
| JRobin is a clone of RRDTool written in Java and is the default time series database when you install {page-component-title}.
It does not fully cover the latest feature set of RRDTool.
Data is stored on the local file system of the {page-component-title} node.
Depending on I/O capabilities, it works well for small- to medium-size installations.

| RRDTool
| RRDTool is actively maintained and the de-facto standard for time series data.
Data is stored on the local file system of the {page-component-title} node.
Depending on I/O capabilities it works well for small- to medium-size installations.

| Newts
| link:http://opennms.github.io/newts/[Newts] is an OpenNMS database schema for link:http://cassandra.apache.org[Cassandra].
The time series is stored on a dedicated Cassandra cluster, which gives growth flexibility and lets time series data persist in a large scale.

| OpenNMS Time Series DB
| The OpenNMS Group now provides a limited availability cloud-hosted time series database to store performance metrics that {page-component-title} collects from the devices it monitors.
The Time Series DB lets you move the most storage-intensive component of your network management system off-premises, for a smaller {page-component-title} footprint and improved redundancy.
For additional information, see xref:time-series-storage/timeseries/hosted-tss.adoc[OpenNMS Time Series DB].
|===

This chapter describes how to configure {page-component-title} to use RRDTool, Newts, and the OpenNMS Time Series DB.

== Time series database plugins

You can use time series database integrations with plugins based on our OpenNMS Plugin API (formerly OIA).
Several plugins are available as a replacement for the ones shipped with OpenNMS {page-component-title} (see xref:time-series-storage/timeseries/ts-integration-layer.adoc#ts-integration-layer[time series integration layer]).

CAUTION: The way data is stored in different time series databases makes it extremely hard to migrate from one technology to another.
You cannot prevent data loss when you switch from one to another.

== Run two time series writes in parallel

The default time series strategy (RRD, Newts, integration) is used for both read/write by default.
You can add another time series write in parallel to the default strategy.
This additional time series database may be used for validation purposes or as a backup time series before moving from one time series to another.

== Write to Newts in parallel

You can enable writing to Newts without it being the default time series strategy.

.Create a file to load the `opennms-newts` feature.
[source, console]
----
sudo vi etc/featuresBoot.d/newts.boot
----

.Add feature and save the file
[source, newts.boot]
----
opennms-newts
----

.Restart {page-component-title} Core instance to apply the changes
[source, console]
----
sudo systemctl restart opennms
----

== Write to Time Series Integration Plugin in parallel

You can enable writing to any time series integration plugin in parallel without having integration as the default time series strategy.


.Create a file to load the `opennms-timeseries-api` feature.
[source, console]
----
sudo vi etc/featuresBoot.d/timeseries.boot
----

.Add feature and save the file
[source, timeseries.boot]
----
opennms-timeseries-api
----

.Restart {page-component-title} Core instance to apply the changes
[source, console]
----
sudo systemctl restart opennms
----
