ifeval::["{page-component-title}" == "Horizon"]
include::../../repos/rhel-centos/horizon-rhel9.adoc[]
endif::[]

ifeval::["{page-component-title}" == "Meridian"]
include::../../repos/rhel-centos/meridian-rhel9.adoc[]
endif::[]

.Install {page-component-title} with all built-in dependencies
[source, console, subs="attributes"]
----
sudo dnf -y install {package-prefix}
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
After upgrading, OpenNMS {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
We recommend excluding the {page-component-title} packages from updates except when you plan to perform an upgrade.
If you have a minimal system installed, you may need to install the config manager with `sudo dnf install 'dnf-command(config-manager)'`.

.Disable auto updates for OpenNMS {page-component-title}
[source, console]
----
ifeval::["{page-component-title}" == "Horizon"]
sudo dnf config-manager --disable opennms-repo-stable-*
endif::[]
ifeval::["{page-component-title}" == "Meridian"]
sudo dnf config-manager --disable meridian
endif::[]
----
