.Create a configuration file gRPC settings

[source, console]
----
sudo vi etc/opennms.properties.d/grpc.properties
----

.Enable the OSGi the generic strategy
[source, grpc.properties]
----
org.opennms.core.ipc.strategy=osgi
----

.Create a file to install gRPC features on startup
[source, shell]
----
sudo vi etc/featuresBoot.d/grpc.boot
----

.Add the gRPC server features
[source, grpc.boot]
----
opennms-core-ipc-grpc-server
----

.Apply the changes with restarting {page-component-title} Core instance
[source, console]
----
sudo systemctl restart opennms
----

NOTE: The gRPC server is listening on port `8990/tcp` by default.
      You can verify if the port is listening with `ss -lnpt = :8990`

TIP: This optional, if you want to enable TLS for gRPC you have to provide certificate files and enable it.
     The commands for TLS are described below.

.Connect to the Karaf Shell
[source, karaf]
----
ssh -p 8101 admin@localhost
----

.Configure TLS and certificate parameters
[source, karaf]
----
config:edit org.opennms.core.ipc.grpc.client
config:property-set tls.enabled true<1>
config:property-set trust.cert.filepath /custom-path/ca.crt<2>
config:property-set client.cert.filepath /custom-path/client.crt<3>
config:property-set client.private.key.filepath /custom-path/client.pem<4>
config:update<5>
----

<1> Enable TLS for the gRPC server 
<2> Set the path to your CA certificate file
<3> Set the path to your client certificate file
<4> Set the path client certificate key file
<5> Save and update the configuration

.Apply the changes with restarting {page-component-title} Core instance
[source, console]
----
sudo systemctl restart opennms
----

TIP: This is optional and you can set a maximum message size for gRPC.
     The maxium size has to be the same on the Minion as well.

.Configure maximum message size for gRPC in the Karaf Shell
[source, karaf]
----
config:edit org.opennms.core.ipc.grpc.client
config:property-set max.message.size 10485760
config:update
----
