.Create a configuration file for Kafka settings
[source, console]
----
sudo vi etc/opennms.properties.d/kafka.properties
----

.Configure Kafka
[source, kafka.properties]
----
org.opennms.core.ipc.strategy=kafka<1>
org.opennms.core.ipc.sink.initialSleepTime=60000<2>
org.opennms.core.ipc.sink.kafka.bootstrap.servers=my-kafka-ip-1:9092,my-kafka-ip-2:9092<3>
org.opennms.core.ipc.rpc.kafka.bootstrap.servers=my-kafka-ip-1:9092,my-kafka-ip-2:9092<4>
org.opennms.core.ipc.twin.kafka.bootstrap.servers=my-kafka-ip-1:9092,my-kafka-ip-2:9092<5>
----

<1> Use Kafka for remote producer calls (RPC).
<2> Ensure that messages are not consumed from Kafka for Sink until the system has fully initialized. Default is 60 seconds.
<3> Connect to the following Kafka nodes and adjust the IPs or FQDNs with the Kafka port (9092) accordingly.
<4> Connect to the following Kafka nodes and adjust the IPs or FQDNs with the Kafka port (9092) accordingly.
<5> Connect to the following Kafka nodes and adjust the IPs or FQDNs with the Kafka port (9092) accordingly.

NOTE: If you set more than one Kafka node as `bootstrap.servers`, the driver attempts to connect to the first entry.
      If that is successful, the client discovers and knows the whole broker topology.
      The other entries are used only if the connection to the first entry fails.

.Restart the {page-component-title} Core instance to apply the changes
[source, console]
----
sudo systemctl restart opennms
----
