.Create a configuration file for Kafka settings
[source, console]
----
sudo vi etc/opennms.properties.d/kafka.properties
----

.Configure Kafka
[source, kafka.properties]
----
org.opennms.core.ipc.rpc.strategy=kafka<1>
org.opennms.core.ipc.rpc.kafka.bootstrap.servers=my-kafka-ip-1:9092,my-kafka-ip-2:9092<2>
org.opennms.core.ipc.sink.strategy=kafka<3>
org.opennms.core.ipc.sink.initialSleepTime=60000<4>
org.opennms.core.ipc.sink.kafka.bootstrap.servers=my-kafka-ip-1:9092,my-kafka-ip-2:9092<5>
----

<1> Use Kafka for remote producer calls (RPC).
<2> Connect to the following Kafka nodes and adjust the IPs or FQDNs with the Kafka port (9092) accordingly.
<3> Use Kafka as message sink.
<4> Ensure that messages are not consumed from Kafka until the system has fully initialized. Default is 60 seconds.
<5> Connect to the following Kafka nodes and adjust the IPs or FQDNs with the Kafka port (9092) accordingly.

NOTE: If you set more than one Kafka node as `bootstrap.servers`, the driver attempts to connect to the first entry.
      If that is successful, the client discovers and knows the whole broker topology.
      The other entries are used only if the connection to the first entry fails.

.Restart the {page-component-title} Core instance to apply the changes
[source, console]
----
sudo systemctl restart opennms
----
