package org.opennms.netmgt.ticketd;
import org.opennms.netmgt.model.OnmsAlarm;
import org.opennms.netmgt.model.OnmsNode;
import org.opennms.netmgt.model.OnmsCategory;
import org.opennms.api.integration.ticketing.Ticket;

dialect "mvel"

global Ticket ticket;

#
# Set tickets defaults
#

rule "TicketDefaults"
salience 100
 when
  $alarm : OnmsAlarm()
 then
  ticket.summary = $alarm.logMsg
  ticket.details = $alarm.description
  ticket.user = "admin"
end

#
# Overwrite defaults with custom logic
#

rule "AssignNodeDownOnRoutersToJesse"
 when
    $alarm : OnmsAlarm( uei == "uei.opennms.org/nodes/nodeDown" )
 then
    ticket.user = "Jesse"
    ticket.summary = "Not Test Logmsg"
    ticket.details = "Not Test Description"
end
