
== Run with Docker

Modern infrastructure allows you to deploy and run workloads in containers.
With _{opennms-product-name}_ we provide and publish container images on link:https://hub.docker.com/u/opennms[DockerHub].

NOTE: We don't install all available plugins in our published Docker image.
      If you want ot customize and maintain your own image, you can find the _Dockerfiles_ in our link:https://github.com/OpenNMS/opennms/tree/develop/opennms-container[source repository].

=== Objectives

* Run _{opennms-product-name}_ using _Docker Compose_ with a basic setup and _PostgreSQL_ on your local system as a quickstart
* Persist RRD files from _{opennms-product-name}_ and _PostgreSQL_ in a volume
* Run and configure a _Minion_ in the stack and connect it to the _{opennms-product-name}_ instance using environment variables
* Introduce a reference with all available configuration and mount conventions for more advanced setups

=== Before you begin

It is required you have at least the following components installed:

* Current stable _Docker_ release installed, e.g. installed from link:https://docs.docker.com/[Docker Documentation]
* Current stable _Docker Compose_ installed, e.g. installed from link:https://docs.docker.com/compose/install/[Docker Compose instructions]
* You should have a basic knowledge about _Docker_, _Docker Compose_ with networking, persisting files and mounting directories

=== Quickstart service stack

// No section numbers for step-by-step guide
:!sectnums:

==== Step 1: Create service stack for PostgreSQL and _{opennms-product-name}_

The first section describes how to setup _{opennms-product-name}_ service stack in a `docker-compose.yml` file.
Create a project directory withg `mkdir opennms-horizon` and create inside a `docker-compose.yml` file with the following content:

[source,yaml]
----
---
version: '3'

volumes:
  data-postgres: {}<1>
  data-opennms: {}<2>

services:
  database:<3>
    image: postgres:12<4>
    container_name: database<5>
    environment:<6>
      - TZ=Europe/Berlin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:<7>
      - data-postgres:/var/lib/postgresql/data
    healthcheck:<8>
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 3

  horizon:
    image: opennms/horizon:25.0.0<9>
    container_name: horizon
    environment:<10>
      - TZ=Europe/Berlin
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OPENNMS_DBNAME=opennms
      - OPENNMS_DBUSER=opennms
      - OPENNMS_DBPASS=opennms
    volumes:
      - data-opennms:/opt/opennms/share/rrd<11>
      - ./overlay:/opt/opennms-overlay<12>
    command: ["-s"]
    ports:<13>
      - "8980:8980/tcp"
      - "8101:8101/tcp"
      - "61616:61616/tcp"
    healthcheck:<14>
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp" ]
      interval: 1m
      timeout: 5s
      retries: 3
  
  minion:
    image: opennms/minion:25.0.0
    container_name: minion
    environment:
      - TZ=Europe/Berlin
      - MINION_ID=my-minion<15>
      - MINION_LOCATION=my-location<16>
      - OPENNMS_BROKER_URL=failover:tcp://horizon:61616<16>
      - OPENNMS_HTTP_URL=http://horizon:8980/opennms<16>
    command: ["-f"]
    ports:<17>
      - "8201:8201/tcp"
      - "162:1162/udp"
----
<1> Volume definition to persist permanently the _PostgreSQL_ database
<2> Volume definition to persist permanently the _RRD_ files from _{opennms-product-name}_
<3> Service name `database` for the _PostgreSQL_ instance
<4> Image reference for the vanilla _PostgreSQL_ Docker image with a fixed version
<5> Friendly container name
<6> Environment variables to initialize a postgres user with a password.
<7> Assign volume to persist the _PostgreSQL_ database
<8> Create a health check for the _PostgreSQL_ database
<9> Image reference for the _{opennms-product-name}_ container image using the latest stable version
<10> Setup a data base connection using the `postgres` root user and initialize an `opennms` database with user and credentials
<11> Assign the volume to persist the _RRD_ files permanently
<12> Mount the configuration files to make them accessible in a local directory
<13> Publish ports for the web user interface, _Karaf Shell_ and _ActiveMQ_
<14> Create a health check against the login page from _{opennms-product-name}_
<15> A defined identifier for this _Minion_, if not set a UUID will be generated
<16> The name of the location the _Minion_ and the connection to the _ActiveMQ_ broker running in _{opennms-product-name}_
<17> Publish ports for SSH access to the _Karaf Shell_ and listen for _SNMP Traps_ forwarding to an internal un-privileged port

NOTE: In this example we haven't set credentials to connect the _Minion_ via _REST_ and the _ActiveMQ Message Broker.
      The _Minion_ will fall back and uses the default admin/admin credentials for the communication.

==== Step 2: Start the service stack and test the functionality

[source,shell]
----
cd opennms-horizon
docker-compose up -d
----

NOTE: The startup and download can take a while, you can use the `docker-compose ps` command and wait until the health check for the `horizon` service is `up (healthy)`.
      After download and startup verify if you can access the web user interface with going to http://localhost:8980.

==== Step 3: Configure _ActiveMQ_ using the overlay directory convention

.Obtain the ActiveMQ default configuration and persist it in the overlay directory so you can change it 
----
mkdir overlay/etc && cd overlay/etc
docker cp $(docker ps -qf name=horizon):/opt/opennms/etc/opennms-activemq.xml .
----

==== Step 4:

.Enable listening on all interfaces for _ActiveMQ_
----
vi opennms-activemq.xml
----

.Uncomment the following line to allow external TCP connections
----
<!-- Uncomment this line to allow external TCP connections -->
<!--
    WARNING: Access to port 61616 should be firewalled to prevent unauthorized injection
             of data into OpenNMS when this port is open.
-->
<transportConnector name="openwire" uri="tcp://0.0.0.0:61616?useJmx=false&amp;maximumConnections=1000&amp;wireformat.maxFrameSize=104857600"/>
----

==== Step 5: Restart _{opennms-product-name}_

----
docker-compose stop horizon
docker-compose up -d
----

==== Step 6: Run _Minion_ health check

.Login in to the _Minion Karaf Shell_ and run the health check
[source, shell]
----
ssh admin@localhost -p 8201

admin@minion> health:check
Verifying the health of the container

Connecting to OpenNMS ReST API   [ Success  ]
Verifying installed bundles      [ Success  ]
Connecting to JMS Broker         [ Success  ]

=> Everything is awesome
----

NOTE: The default admin password for the _Minion Karaf Shell_ is _admin_.

==== Step 7: Verify status in the administrative Web UI

* Login as admin
* _Configure OpenNMS -> Manage Minions_, the _Minion_ should be registered and the Status should be _up_
* Verify if _Minion_ is provisioned automatically going to _Info -> Nodes_ and select the _Minion_, the services _JMX-Minion_, _Minion-Heartbeat_ and _Minion-RPC_ should be _up_ and provisioned on the local loopback interface

// Enable section numbers
:sectnums:
