package org.opennms.features.correlator
import org.opennms.netmgt.xml.event.Event

declare org.opennms.netmgt.xml.event.Event
    @role(event)
end

rule "Anything Very New"
when
    $e : Object()
then
    System.out.println("object in rule: " + $e);
end

rule "Any Event Rule"
when
    $e : Event()
then
    System.out.println("event in rule: " + $e.getDescr());
end

rule "Some Events Rule"
when
    $e : Event(descr == "This event is sent by the WebUI when a user has successfully authenticated")
then
    System.out.println("WebUI login success in rule: " + $e);
end