[[restore]]
= Restore OpenNMS {page-component-title} 

This section describes a basic restore process for a default OpenNMS {page-component-title} xref:deployment:core/getting-started.adoc#getting-started-core[installation].
OpenNMS {page-component-title} binaries, logs, RRD archives, configurations and the database will be restored.

NOTE: In this example the backup storage path is `/tmp` for demonstration purposes.
Please be aware that `/tmp` is not persisted, as most operating systems will delete the content at bootup.

[[restore-objectives]]
== Objectives

* Restore backup of OpenNMS {page-component-title} components
* Install PostgreSQL database and restore backup
* Install OpenJDK 
* Create systemd OpenNMS service unit

[[restore-requirements]]
== Requirements

* The backups that were made in [[backup-debian-ubuntu]]
* System user with administrative permissions (sudo)
* Internet access to download and install OpenJDK and PostgreSQL
NOTE: PostgreSQL link:https://www.postgresql.org/about/news/announcing-apt-archivepostgresqlorg-2024/[archive repository] provides also older PostgreSQL versions
* Database password for `opennms` and `postgres` user

== Restore backups

[{tabs}]
====
CentOS/RHEL 8::
+
--
include::centos-rhel8/restore-centos-rhel8.adoc[]
--

ifeval::["{page-component-title}" == "Horizon"]
Debian/Ubuntu::
+
--
include::debian-ubuntu/restore-debian-ubuntu.adoc[]
--
endif::[]
====

