Enable tracing with Jaeger on Core instance by installing the `opennms-core-tracing-jaeger` feature and creating a configuration file with the Jaeger specific settings.

NOTE: Configurations has to be made in the `etc` directory relative to the {page-component-title} Core home directory.
      Depending on your operating system the home directory is in `/usr/share/opennms` for Debian/Ubuntu or `/opt/opennms` for CentOS/RHEL.

.Create a file to load the tracing feature on startup
[source, console]
----
sudo vi etc/featuresBoot.d/jaeger.boot
----

.Add the Jaeger feature and save the file
[source, jaeger.boot]
----
opennms-core-tracing-jaeger
----

NOTE: Uninstalling the `opennms-core-tracing-jaeger` feature at runtime is not yet supported.
      To disable tracing with Jaeger, remove the reference from the features boot file and restart the Core.

.Create a configuration file for tracing settings
[source, console]
----
sudo vi etc/opennms.properties.d/jaeger.properties
----

.Configure tracing with Jaeger
[source, jaeger.properties]
----
org.opennms.core.tracer=jaeger<1>
JAEGER_SERVICE_NAME=core-instance<2>
JAEGER_AGENT_HOST=my-jaeger-host<3>
----

<1> Set Jaeger as the tracing implementation
<2> Set a name for this service which identifies the {page-component-title} Core server in Jaeger
<3> Replace the `my-jaeger-host` with your Jaeger instance where you collect the tracing information

TIP: Available configuration options are listed in the link:https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/README.md[Jaeger Core Readme].

Restart _{page-component-title}_ Core server to apply the changes.

[source, console]
----
sudo systemctl restart opennms
----
