
// Allow GitHub image rendering
:imagesdir: ../../images

[[ga-collectd-configuration]]
=== Configuring _Collectd_ 

The _collectd-configuration.xml_ file defines the nodes, services and parameters on which _collectd_ collects metrics. 
It also specifies the list of available collectors. 

The file is located in `$OPENNMS_HOME/etc/collectd-configuration.xml`.

Edit the _collectd-configuration.xml_ file to:

* <<ga-edit-collectd-config, set the thread pool>>
* <<collection-packages.adoc, configure collector packages>>
* <<collection-packages.adoc#ga-collector-list-edit, specify collectors to use>>

In addtion to editing the _collectd-configuration.xml_, you need to <<collectors.adoc,configure collectors>> for the protocols from which you want to collect data by editing the configuration files associated with them.

#TODO: Do we need a graphic of the file with the sections highlighted?#

[[ga-thread-pool-edit]]
==== Setting the Thread Pool

A globally defined thread attribute limits the number of threads the data collection process uses in parallel. 
Increase or decrease this value based on your network and the size of your server by changing the value in `$OPENNMS_HOME/etc/collectd-configuration.xml`:

[source, xml]
----
<collectd-configuration
        threads="50">
----