
[[doc-guideline-introduction]]
== Introduction
This document is for people want to contribute in writing documentation in the OpenNMS project.
The software is free and open source and contribution any kind is welcome.
To keep the documenation consistent we created some guide lines.

[[community-docs-overall-flow]]
== Overall Flow ==

Each (sub)project represents a part of the documentation, which will produce a HTML output in the file system.
The output is generated in the `target/generated` sources folder.
Asciidoc documents have the +.asciidoc+ file extension.

Note that different ways to add documentation works best for different cases:

* Tutorials and How To's should be published on the http://wiki.opennms.org[OpenNMS Wiki].
For example you want to describe how to use the Net-SNMP agent and the SNMP monitor from OpenNMS to solve a special use case with OpenNMS.

* The documentation you can find in the source code can be characterized as a non-emotional technical documentation which explains concepts in detail and should be complete.

== File Structure in 'opennms-doc' ==

[options="header", cols="e,d"]
|========================
| Directory          | Contents
| guide-doc/         | module with this overview documentation
| guide-user/        | module with the guide for people how to use and configure OpenNMS
| guide-admin/       | module with the guide for administrators optimizing and running OpenNMS
| guide-development/ | module with the guide for people who want to develop within OpenNMS
| guide-install/     | module with the guide how to install OpenNMS on different operating systems
| releasenotes/      | module with the changelog and release notes
|========================
