
[[doc-guidelines-reviewing]]
== Reviewing a Documentation Contribution
Reviews help to improve the quality of a piece of code or documentation.
Just getting somebody elses opinion helps to get an idea if something useful.
As a reviewer keep in mind, you are looking in a result, somebody spent free time and effort in the contribution.
Treat contributions with respect.
Open _Pull Requests_ in the OpenNMS repository can be found here: https://github.com/OpenNMS/opennms/pulls.

To merge a _Pull Request_ you need commit permissions to the OpenNMS repository, i.e. _OGP_ or members of the OpenNMS Group.

You have basically two possibilities as a reviewer to change something:

* You don't change anything, everything is perfect and you just merge the pull request
* There are changes necessary, in this case comment the lines in the pull request directly and follow up the conversation there
* Bigger conceptual changes necessary or information out of reach for the contributor, you can provide a pull request back and give
  the contributor a change working your additional information in.
* Reject the pull request, cause it is not possible for any reason to get the code in the official code base.

=== Step 1: Formal check, is everything there

Every Pull Request requires a comment with the following content:

* Comment with the backlink to the JIRA issue and a Todo list for the review, see below

[source]
----
http://issues.opennms.org/browse/NMS-6698

Todo Review:
- [ ] Typo and grammar
- [ ] Formatting and conventions
- [ ] Content
----

* The JIRA issue is in status "Resolved"

=== Step 2: Review for criterias

. Check for typos and grammar
. Check <<doc-guidelines-conventions, Conventions for text formatting>>
. Check if the contribution is complete and technical correct

NOTE: You can't know everything.
It will happen, somebody documents a behavior somebody doesn't know.
Don't hesitate to ask in the OpenNMS mailing list or IRC channels to clearify issues.
If nobody knows the correct behavior, make a warning note and merge it.
A bug can be created if the described behavior doesn't work.

=== Step 3: Merge contribution to offical code base

. Merge the pull request
. Change JIRA status from _Resolved_ to _Closed_
. Check if the build in Bamboo and the deployment was ok
