[[ga-database-report-add-custom-report]]
== Add a custom report

To add a new JasperReport report to the local {page-component-title} report repository, do the following:

Create a new entry in the `$OPENNMS_HOME/etc/database-reports.xml` file.

[source, xml]
-----
<report
  id="MyReport" <1>
  display-name="My Report" <2>
  online="true" <3>
  report-service="jasperReportService" <4>
  description="This is an example description. It shows up in the web ui when creating an online report"  <5>
/>
-----
<1> A unique identifier
<2> The name of the report. Appears in the web UI.
<3> Defines if this report can be executed on demand, otherwise only scheduling is possible.
<4> The report service implementation to use. In most cases this is `jasperReportService`.
<5> A description of the report. Appears in the web UI.

In addition, create a new entry in the `$OPENNMS_HOME/etc/jasper-reports.xml` file.

[source, xml]
-----
<report
  id="MyReport" <1>
  template="My-Report.jrxml" <2>
  engine="jdbc" <3>
/>
-----
<1> The identifier defined in the previous step. This identifier must exist in `$OPENNMS_HOME/etc/database-reports.xml`.
<2> The name of the template. The template must be located in `$OPENNMS_HOME/etc/report-templates`.
<3> The engine to use. It is either `jdbc` or `null`.
