
// Allow GitHub image rendering
:imagesdir: ../../images

[[ga-events-eif]]
=== Receiving IBM Tivoli Event Integration Facility Events

_OpenNMS_ can be configured to receive _Events_ sent using the https://www.ibm.com/support/knowledgecenter/SSSHTQ_7.3.1/com.ibm.netcool_OMNIbus.doc_7.3.1/omnibus/wip/eifsdk/concept/kaa24487.html[Tivoli Event Integration Facility].
These EIF events are translated into OpenNMS events using preconfigured rules. The resulting UEI are anchored in the `uei.opennms.org/vendor/IBM/EIF/` namespace, with the name of the EIF https://www.ibm.com/support/knowledgecenter/SSSHTQ_7.3.1/com.ibm.netcool_OMNIbus.doc_7.3.1/omnibus/wip/eifsdk/concept/ecoemst16.html[event class] appended.

A sample event configuration for the OMEGAMON_BASE class is included with OpenNMS.

[[ga-events-eif-configuring]]
==== Configuring
First check that your _OpenNMS_ installation supports this feature.
If it does there should be a `${OPENNMS_HOME}/etc/org.opennms.features.eif-adapter.cfg` file.

Now open the file, review its content and make sure to apply the correct settings depending on your environment.

The following table describes all settings and possible values.

[options="header, autowidth"]
|===
| Parameter              | Default          |  Description
|`interface`  | 0.0.0.0          | The IP interface on which to listen for EIF events (required).
|`port`       | 1828        | The TCP port on which to listen for EIF events (required).
|===

Once you are sure everything is correctly configured you can activate the _EIF_ adapter by loging into the _OSGi_ console and installing the feature.

._OSGi_ login and installation of the _EIF_ adapter
[source, shell]
----
ssh admin@localhost -p 8101
features:install eif-adapter
----

You can check the routes status with the `camel:*` commands and/or inspect the log with `log:tail` for any obvious errors.
The feature has a trace level logging that can be used to trace operations.

NOTE: http://karaf.apache.org/manual/latest/#_using_the_console[documentation] on using the _OSGi_ console embedded in _OpenNMS_ and the relative http://camel.apache.org/karaf.html[camel commands].

You should now be able to configure your EIF forwarders to send to this destination, and their events will be translated into OpenNMS Events and written to the _event bus_.

[[ga-events-eif-troubleshooting]]
==== Troubleshooting

If events are not reaching _OpenNMS_, check whether the event source (_EIF Forwarder_) is correctly configured.
Check your event destination configuration. In particular review the `HOSTNAME` and `PORT` parameters. Also check that your situations are configured to forward to that EIF destination.

If those appear to be correct verify that the _EIF Forwarder_ can communicate with _OpenNMS_ over the configured port (default 1828).

Review the OSGi log with `log:tail` or the `camel:*` commands.
