
// Allow GitHub image rendering
:imagesdir: ../../images

Events are central to the operation of the {opennms-product-name} platform, so it's critical to have a firm grasp of this topic.

IMPORTANT: Whenever something in {opennms-product-name} appears to work by magic, it's probably events working behind the curtain.

[[ga-events-anatomy-of-an-event]]
=== Anatomy of an Event

Events are structured historical records of things that happen in {opennms-product-name} and the nodes, interfaces, and services it manages.
Every event has a number of fixed *fields* and zero or more *parameters*.

.Mandatory Fields
UEI (Universal Event Identifier)::
    A string uniquely identifying the event's type.
    UEIs are typically formatted in the style of a URI, but the only requirement is that they start with the string `uei.`.
Event Label::
    A short, static label summarizing the gist of all instances of this event.
Description::
    A long-form description describing all instances of this event.
Log Message::
    A long-form log message describing this event, optionally including expansions of fields and parameters so that the value is tailored to the event at hand.
Severity::
    A severity for this event type.
    Possible values range from `Cleared` to `Critical`.
Event ID::
    A numeric identifier used to look up a specific event in the {opennms-product-name} system.

.Notable Optional Fields
Operator Instruction::
    A set of instructions for an operator to respond appropriately to an event of this type.
Alarm Data::
    If this field is provided for an event, {opennms-product-name} will create, update, or clear *alarms* for events of that type according to the alarm-data specifics.
    For more about alarms and how they relate to events, see <<alarms-introduction>>.

[[ga-events-sources-of-events]]
=== Sources of Events

Events may originate within {opennms-product-name} itself or from outside.

Internally-generated events can be the result of the platform's monitoring and management functions (_e.g._ a monitored node becoming totally unavailable results in an event with the UEI `uei.opennms.org/nodes/nodeDown`) or they may act as inputs or outputs of housekeeping processes.

The following subsections summarize the mechanisms by which externally-created events can arrive.

==== SNMP Traps

If SNMP-capable devices in the network are configured to send *traps* to {opennms-product-name}, these traps are transformed into events according to pre-configured rules. The `Trapd` service daemon, which enables {opennms-product-name} to receive SNMP traps, is enabled by default.

IMPORTANT: Disabling the `Trapd` service daemon will render {opennms-product-name} *incapable* of receiving SNMP traps.

Event definitions are included with {opennms-product-name} for traps from many vendors' equipment.

==== Syslog Messages

Syslog messages sent over the network to {opennms-product-name} can be transformed into events according to pre-configured rules.

IMPORTANT: The `Syslogd` service daemon, which enables {opennms-product-name} to receive syslog messages over the network, must be enabled for this functionality to work. This service daemon is *disabled* by default.
    
==== TL1 Autonomous Messages

Autonomous messages can be retrieved from certain TL1-enabled equipment and transformed into events.

IMPORTANT: The `Tl1d` service daemon, which enables {opennms-product-name} to receive TL1 autonomous messages, must be enabled for this functionality to work. This service daemon is *disabled* by default.

==== XML-TCP
Any application or script can create custom events in {opennms-product-name} by sending properly-formatted XML data over a TCP socket.

==== ReST

Posting an event in XML format to the appropriate endpoint in the {opennms-product-name} ReST API will cause the creation of a corresponding event, just as with the XML-TCP interface.

==== IBM Tivoli Event Integration Facility

_OpenNMS_ can be configured to receive _Events_ sent using the https://www.ibm.com/support/knowledgecenter/SSSHTQ_7.3.1/com.ibm.netcool_OMNIbus.doc_7.3.1/omnibus/wip/eifsdk/concept/kaa24487.html[Tivoli Event Integration Facility].
These EIF events are translated into OpenNMS events using preconfigured rules. The resulting UEI are anchored in the `uei.opennms.org/vendor/IBM/EIF/` namespace, with the name of the EIF https://www.ibm.com/support/knowledgecenter/SSSHTQ_7.3.1/com.ibm.netcool_OMNIbus.doc_7.3.1/omnibus/wip/eifsdk/concept/ecoemst16.html[event class] appended.

A sample event configuration for the `OMEGAMON_BASE` class is included with OpenNMS.

.*Configuring the EIF Adapter*
Once _OpenNMS_ is started and the _Karaf_ shell is accessible, you can install the _EIF Adapter_ feature and configure it to listen on a specific interface and port.

NOTE: By default the _EIF Adapter_ is configured to listen on TCP port 1828 on all interfaces.

._OSGi_ login, installation, and configuration of the _EIF Adapter_
[source]
----
[root@localhost /root]# $ ssh -p 8101 admin@localhost
...
opennms> features:install eif-adapter
opennms> config:edit org.opennms.features.eifadapter
opennms> config:propset interface 0.0.0.0
opennms> config:propset port 1828
opennms> config:update
----

You can check the routes status with the `camel:*` commands and/or inspect the log with `log:tail` for any obvious errors.
The feature has a trace level logging that can be used to trace operations.

NOTE: link:$$http://karaf.apache.org/manual/latest/#_using_the_console$$[Documentation] on using the _OSGi_ console embedded in _OpenNMS_ and the related http://camel.apache.org/karaf.html[camel commands].

NOTE: Features installed through the Karaf shell persist only as long as the `${OPENNMS_HOME}/data` directory remains intact. To enable the feature more permanently, add it to the `featuresBoot` list in `${OPENNMS_HOME}/etc/org.apache.karaf.features.cfg`.

You should now be able to configure your EIF forwarders to send to this destination, and their events will be translated into OpenNMS Events and written to the _event bus_.

.*Troubleshooting*

If events are not reaching _OpenNMS_, check whether the event source (_EIF Forwarder_) is correctly configured.
Check your event destination configuration. In particular review the `HOSTNAME` and `PORT` parameters. Also check that your situations are configured to forward to that EIF destination.

If those appear to be correct verify that the _EIF Forwarder_ can communicate with _OpenNMS_ over the configured port (default 1828).

Review the OSGi log with `log:tail` or the `camel:*` commands.

[[ga-events-event-bus]]
=== The Event Bus

At the heart of {opennms-product-name} lies an *event bus*.
Any {opennms-product-name} component can _publish_ events to the bus, and any component can _subscribe_ to receive events of interest that have been published on the bus.
This publish-subscribe model enables components to use events as a mechanism to send messages to each other.
For example, the provisioning subsystem of {opennms-product-name} publishes a _node-added_ event whenever a new node is added to the system.
Other subsystems with an interest in new nodes subscribe to the _node-added_ event and automatically receive these events, so they know to start monitoring and managing the new node if their configuration dictates.
The publisher and subscriber components do not need to have any knowledge of each other, allowing for a clean division of labor and lessening the programming burden to add entirely new {opennms-product-name} subsystems or modify the behavior of existing ones.
