
// Allow GitHub image rendering
:imagesdir: ../../images

[[ga-events-forwarding-elastic]]
=== Forwarding Events to Elasticsearch

_OpenNMS_ can be configured to forward all _Events_ and _Alarms_ to https://www.elastic.co/products/elasticsearch[Elasticsearch] for indexing, long time archiving, plotting with _Grafana_ and browsing with _Kibana_.

NOTE: _Elasticsearch_ is not intended as a replacement for _PostgreSQL_ which is still a required component to run _OpenNMS_.

First check that your _OpenNMS_ installation supports this feature.
If it does there should be a `${OPENNMS_HOME}/etc/org.opennms.features.elasticsearch.eventforwarder.cfg` file.

Now open the file, review its content and make sure to apply the correct settings depending on your environment.

The following table describes all settings and possible values.

[options="header, autowidth"]
|===
| Parameter              | Default          |  Description
|`elasticsearchCluster`  | opennms          | The name of the _Elasticsearch_ cluster as specified in the _Elasticsearch_ configuration file (required).
|`elasticsearchIp`       | localhost        | the _TransportClient_ remote host ip to use.
                                              Has the same meaning as the ip options of the http://camel.apache.org/elasticsearch.html[camel-elasticsearch] component
|`logEventDescription`   | false            | Whether to forward the event description to _Elasticsearch_.
                                              The reason it is off by default is that it is usually some standard, generic, repetitive and possibility long text which will grow the index without adding useful information.
|`cache_max_ttl`         | 0                | The number of minutes the node information is kept in the cache.
                                              Set to `0` to disable (which is the default and is generally safe because the cache knows when to refresh itself, by intercepting nodeUpdated and similar events)
|`cache_max_size`        | 10000            | The number of node information entries to be kept in the cache before eviction start.
                                              Set to `0` to disable.
|===

The first two (`elasticsearchCluster` and `elasticsearchIp`) settings are the most likely to require changing.
If unsure do not change the remaining three.

Once you are sure everything is correctly configured you can activate the _Elasticsearch_ forwarder by log into the _OSGi_ console and install the feature.

._OSGi_ login and installation of the _Elasticsearch_ forwarder
[source, shell]
----
ssh admin@localhost -p 8101
features:install opennms-elasticsearch-event-forwarder
----

You can check the routes status with the `camel:*` commands and/or inspect the log with `log:tail` for any obvious errors.
The feature has a trace level logging that can be used to trace operations.

NOTE: http://karaf.apache.org/manual/latest/users-guide/console.html[documentation] on using the _OSGi_ console embedded in _OpenNMS_ and the relative http://camel.apache.org/karaf.html[camel commands].

If all goes well events and alarms will be pushed in realtime into _Elasticsearch_.
You should now be able to view the events and graph them with https://www.elastic.co/products/kibana[Kibana].

If you have never used _Kibana_ before you should probably start with _Kibana 3_ which is simpler.
_Kibana 4_ is more powerful, but harder to get started with.

[[ga-events-forwarding-elastic-basic-config]]
==== A basic Elasticsearch configuration

This section describes to get a minimal working configuration with _OpenNMS_ and _Elasticsearch_.
Install _Elasticsearch_ on the same host as _OpenNMS_ and edit the `elasticsearch.yml` as follows:

.Example configuration for _Elasticsearch_
[source]
----
cluster.name: opennms
network.host: 127.0.0.1
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["127.0.0.1"]
----

NOTE: Running _OpenNMS_ and _Elasticsearch_ on the same host is not recommended for production or busy environments.

[[ga-events-forwarding-elastic-troubleshooting]]
==== Troubleshooting

If events are not reaching _Elasticsearch_ check if _OpenNMS_ is correctly configured, in particular review the `elasticsearchCluster` and `elasticsearchIp` parameters.

If those appear to be correct verify that _OpenNMS_ can communicate with _Elasticsearch_ over port 9300.

Review the OSGi log with `log:tail` or the `camel:*` commands.
