
[[rest-api-acknowledgements]]
= Acknowledgements

NOTE: the default offset is 0, the default limit is 10 results.
To get all results, use `limit=0` as a parameter on the URL (i.e., `GET /acks?limit=0`).

== GETs (Reading Data)

[options="header", cols="5,10"]
|===
| Resource      | Description
| `/acks`       | Get a list of acknowledgements.
| `/acks/count` | Get the number of acknowledgements. (Returns plaintext, rather than XML or JSON.)
| `/acks/\{id}` | Get the acknowledgement specified by the given ID.
|===

== POSTs (Setting Data)

[options="header", cols="5,10"]
|===
| Resource | Description
| `/acks`  | Creates or modifies an acknowledgement for the given alarm ID or notification ID. 
To affect an alarm, set an `alarmId<` parameter in the URL-encoded POST body. To affect a notification, set `notifyId` instead. 
An `action` parameter is also required, and may be one of `ack`, `unack`, `clear`, or `esc` (escalate).
|===

== Use examples with curl
.Acknowledge notification #3
[source, bash]
----
curl -u 'admin:admin' -X POST -d notifId=3 -d action=ack http://localhost:8980/opennms/rest/acks
----

.Escalate alarm #42
[source, bash]
----
curl -u 'admin:admin' -X POST -d alarmId=42 -d action=esc http://localhost:8980/opennms/rest/acks
----
