= Sentinel
:description: Scale your network monitoring with OpenNMS Sentinel and support streaming telemetry with OpenNMS Newts on RHEL, CentOS, Debian, and Ubuntu.

[[objectives]]
== Objectives

* Setting up a {page-component-title} Sentinel running on one of the following <<./system-requirements.adoc#operating-systems-sentinel, Operating Systems>>
* Secure access with encrypted passwords to the Karaf shell
* Sentinel can be configured with the Karaf Shell from th

Sentinel provides scalability for data processing of flows and streaming telemetry received by one or more Minions.
It also supports thresholding for streaming telemetry if you are using OpenNMS xref:deployment:time-series-storage/newts/introduction.adoc#ga-opennms-operation-newts[Newts].
If you need to scale processing capacity for flow and/or streaming telemetry, you need Sentinel.

As your flow and streaming telemetry volumes increase, additional Sentinel instances can be deployed to meet your processing needs.

In most cases, you can disable adapters and listeners in {page-component-title} that are also run by a Sentinel instance.

This section describes how to install Sentinel components.
