
= Advanced Alarm Search
:description: List and description of search criteria in {page-component-title} for advance alarm searches.

When searching your environment's alarms list, you may want to customize your query to narrow your search.
The {page-component-title} Alarm List page has a button to filter your searches based on different criteria:

[cols="1,3"]
|===
| Criteria  | Description

| Alarm Text Contains
| Performs a `substring` filter on both the log message and the description. +
To negate this search, prefix the input text with an exclamation mark (`!`).
This returns only results that do not contain the provided input text.

| TCP/IP Address Like
| Performs an `IPLIKE` search on the provided IP address. +
To negate this search, prefix the input text with an exclamation mark (`!`).
This returns only results that do not satisfy the `IPLIKE` function.

| Node Label Contains
| Performs a `substring` filter on the node label. +
To negate this search, prefix the input text with an exclamation mark (`!`).
This returns only results that do not contain the provided input text.

| Severity
| Filters alarms based on their severity.
This option is a multi-select checkbox. +
Select the <<deep-dive/events/event-configuration.adoc#severities, severities>> that you want to filter by.
By default, they are unselected; this returns all alarms.
Selecting one or more severities restricts your search results to those selected.

| Service
| Filters alarms based on their service.
This option is a multi-select checkbox. +
Select the services that you want to filter by.
By default, they are unselected; this returns all alarms.
Selecting one or more services restricts your search results to those selected.

| Alarm Type
| Include only alarms, only situations, or both.

| Category
| Filters alarms based on the nodes category. +
To negate this search, select *Negate Category*.
This returns only results that do not match the selected category.

| Filter for Alarms After First Event
| Select a timestamp to show alarms after the time of the alarm's first event.

| Filter for Alarms Before First Event
| Select a timestamp to show alarms before the time of the alarm's first event.

| Filter for Alarms After Last Event
| Select a timestamp to show the alarms after the time of the alarm's last event.

| Filter for Alarms Before Last Event
| Select a timestamp to show alarms before the time of the alarm's last event.
|===
