
= Enable the Kafka Producer
:description: Learn how to enable the Kafka Producer to let {page-component-title} forward events, alarms, nodes, topologies, and metrics to Kafka.

The Kafka Producer is disabled by default and can be enabled as follows.

First, log in to the Karaf shell of your {page-component-title} instance and configure the Kafka client settings to point to your Kafka server(s).
See link:https://kafka.apache.org/documentation/#producerconfigs[Producer Configs] for a complete list of available options.

.Connect to Karaf shell
[source, console]
----
ssh -p 8101 admin@localhost
----

.Configure the Kafka producer client
[source, karaf]
----
config:edit org.opennms.features.kafka.producer.client
config:property-set bootstrap.servers kafka-server-ip:9092 <1>
config:update
----
<1> Set the Kafka server IP or hostname by replacing the kafka-server-ip and port of an existing Kafka cluster that you want to connect to.
    Add multiple hosts in a comma-separated list; for example, `kafka-server-1:9092,kafka-server-2:9092`

Next, install the `opennms-kafka-producer` feature from that same shell using:

[source, karaf]
----
feature:install opennms-kafka-producer
----

To ensure that the feature continues to be installed on subsequent restarts, add `opennms-kafka-producer` to a file in `featuresBoot.d`:
[source, console]
----
echo "opennms-kafka-producer" | sudo tee ${OPENNMS_HOME}/etc/featuresBoot.d/kafka-producer.boot
----
