
[[reset-admin-password]]
= Reset the Web UI Admin Password
:description: Learn how to reset your OpenNMS Admin password on the command line.

This section explains how to set the web UI admin password using the {page-component-title} installation script.

After you install {page-component-title}, the web UI admin user's password is set to `admin` by default.
As long as this password remainds unchanged, you will be prompted to change this password everytime you sign in to the {page-component-title} web UI.

You can also change the password by using the *Change Password* option in the UI any time you are logged in.
In the case of a forgotten password or deployment scenarios that require users to set this password on installation, you can use the {page-component-title} installation script to reset this password.

You need to add the option ` -R` (or `--reset-webui-password`) and provide the password to set as an argument.

.This example skips the upgrade tasks and sets the web UI admin password to "foobar":
[source, shell]
sudo /usr/share/opennms/bin/install -S -R foobar

