
[[getting-started-core]]
= Installation and Configuration
:description: Install and configure the OpenNMS {page-component-title} Core instance including PostgreSQL set up on RPM, DEB, and Docker environments.

This section explains how to install and configure a new {page-component-title} Core instance.
ifeval::["{page-component-title}" == "Horizon"]
The goal of this section is to deploy a OpenNMS {page-component-title} Core instance, the PostgreSQL database and store the JRobin time series data on a single node.

TIP: If you want a quick evaluation of OpenNMS Horizon on a bare metal system or a virtual machine, you can check out our https://github.com/opennms-forge/opennms-install[quick install scripts].
endif::[]
ifeval::["{page-component-title}" == "Meridian"]
The goal of this section is to deploy a OpenNMS {page-component-title} Core instance, the PostgreSQL database and store the RRDtool time series data on a single node.
endif::[]

== Requirements

The following components and settings are required to set up a new {page-component-title} instance:

ifeval::["{page-component-title}" == "Meridian"]
* Credentials to access the Meridian repositories.
endif::[]
* A Linux physical server, or a virtual machine running a <<./system-requirements.adoc#operating-systems-core, supported Linux operating system>>.´
* Internet access to download the installation packages.
* A working DNS server, and a localhost and server name that resolve properly.
* A system user with administrative permissions (`sudo`) to perform installation. On Debian, you must install and configure `sudo` yourself.
See the https://wiki.debian.org/sudo/[Debian Wiki] for more information.
ifeval::["{page-component-title}" == "Horizon"]
* To run services in Docker, you need https://docs.docker.com/compose/install[Docker Compose] for the service stacks from our examples.
*
endif::[]
* With SELinux enabled, you need a policy that permits sending ICMP echo requests as an unprivileged user, see xref:reference:configuration/selinux.adoc[].
* Use a time synchronization protocol in your environment, see knowledgebase article link:https://opennms.discourse.group/t/ensure-time-synchronization-for-your-opennms-components/159[Ensure time synchronization for your OpenNMS components].
* The system locale should support the characters set `UTF-8`.

Follow these steps if your system locale is not set to UTF-8:

[{tabs}]
====
RPM::
+
--
.Installing language packages
[source, console]
----
sudo dnf install langpacks-en glibc-all-langpacks -y
----

.Set the locale to english US using UTF-8
[source, console]
----
sudo localectl set-locale LANG=en_US.UTF-8
----

.Verify if the locale is set
[source, console]
----
localectl
----
--
ifeval::["{page-component-title}" == "Horizon"]
DEB::
+
--
.Installing language packages
[source, console]
----
sudo apt -y install language-pack-en
----

.Set the locale to english US using UTF-8
[source, console]
----
sudo localectl set-locale LANG=en_US.UTF-8
----

.Verify if the locale is set
[source, console]
----
sudo localectl
----
--
endif::[]
====


[[setup-postgresql]]
== Set up PostgreSQL

[{tabs}]
====
RPM::
+
--
include::rpm/postgresql.adoc[]
--

ifeval::["{page-component-title}" == "Horizon"]

DEB::
+
--
include::deb/postgresql.adoc[]
--

Docker::
+
--
include::docker/postgresql.adoc[]
--
endif::[]
====

[[install-core-instance]]
== Install the core instance

IMPORTANT: For security reasons, {page-component-title} is designed to run within an organization's protected intranet.
Do not expose the web console or sign in pages directly to the Internet without appropriate isolation controls (for example, a VPN with multifactorial authentication).

[{tabs}]
====
RPM::
+
--
include::rpm/install-core.adoc[]
--

ifeval::["{page-component-title}" == "Horizon"]

DEB::
+
--
include::deb/install-core.adoc[]
--

Docker::
+
--
include::docker/core.adoc[]
--
endif::[]
====

[[set-up-core-instance]]
== Set up the core instance

[{tabs}]
====
RPM::
+
--
include::rpm/initialize-core.adoc[]
--

ifeval::["{page-component-title}" == "Horizon"]
DEB::
+
--
include::deb/initialize-core.adoc[]
--

Docker::
+
--
include::docker/initialize.adoc[]
--
endif::[]
====

[[ga-data-choices]]
== First-time sign in

After you start the {page-component-title} core services, you can access the web application at `\http://core-instance-ip:8980/opennms`.
The default user credentials are as follows:

* *Username:* `admin`
* *Password:* `admin`

When you try to sign in with these credentials, {page-component-title} prompts you to change your password.
Although you also have the option to skip this action and sign in with default the credentials, we strongly recommend that you change the `admin` account's password to a secure one.

. Type your current password.
. Type your new password and confirm it.
. Click *Change Password*.

== Change password after first sign in

To change your account's password after the first time you sign in, follow these steps:

. On the top menu bar, click menu:Admin[Change Password].
. Type your current password and new password in the appropriate fields.
. Confirm your new password, and click *Submit*.

The password is updated.

We encourage you to use {page-component-title} with individual user accounts instead of using only the `admin` account.
If all users have individual accounts, you can see who is completing tasks (for example, clearing or acknowledging alarms).
For information on how to create personalized user accounts, see xref:operation:quick-start/users.adoc#create-user[Create a new user] in the Quick Start guide.

[[usage-statistics]]
=== Usage statistics

The first time you sign in, {page-component-title} notifies you that it collects anonymized usage statistics and publishes them to https://stats.opennms.com.
Consent to share collected usage statistics is assumed by default.

The OpenNMS Group uses this information to help determine product use and to improve the {page-component-title} software.
We do not share it with third parties, and we will not use it for sales purposes.

Click *Learn More* to view the xref:operation:deep-dive/admin/configuration/usage-statistics.adoc[information that we collect and share].
This also hides the notification.

Click *Dismiss* to simply hide the notification.
You can view the usage statistics at any time on the admin page.

NOTE: Admin users can xref:operation:deep-dive/admin/configuration/usage-statistics.adoc#disable-data-collection[opt out of sharing the statistics] at any time.

== First monitored node

The default configuration will discover a single node with an interface `127.0.0.1` and detect services exposed on the loopback interface, including the `OpenNMS-JVM` service.
Nodes with this service have JMX-based data collection performed on Java JVM statistics such as heap memory and open file handles.

== Related topics

* xref:operation:deep-dive/admin/configuration/startup.adoc[]
* xref:reference:configuration/selinux.adoc[]
* xref:reference:configuration/receive-snmp-traps.adoc[]
* xref:reference:configuration/install-jdbc-driver.adoc[]

== Next steps

See the xref:operation:quick-start/introduction.adoc[Quick Start guide] for more information on setting up and configuring your {page-component-title} instance.
