
[[native-installation-core]]
= Native Installation
:description: Install and configure OpenNMS instance including PostgreSQL setup on CentOS/RHEL, Debian/Ubuntu, and Docker.

This section explains how to install and configure a new {page-component-title} instance on a single node, including the following tasks:

. Install PostgreSQL and initialize the database directory
. Install Eclipse Temurin 17 JDK and {page-component-title} Core
. Configure {page-component-title} Core to access the local PostgreSQL database and initialize the database scheme
. Sign in to the web UI and change the `admin` account's default password

NOTE: The default configuration is not optimized to run in a production environment or monitor large networks.

ifeval::["{page-component-title}" == "Horizon"]
TIP: If you want to evaluate or test OpenNMS {page-component-title} in a non-productive environment, you can check out our https://github.com/opennms-forge/opennms-install[quick installation scripts].
This convenient script installs Horizon on Debian or Red Hat compatible systems on a single node.
You can use it as a starting point to evaluate and explore how to configure Horizon before moving to more complex distributed environments.
endif::[]


[[setup-postgresql]]
== Step 1: Installing PostgreSQL

include::postgresql.adoc[]

== Step 2: Installing Java

include::../java/temurin.adoc[]

[[install-core-instance]]
== Step 3: Set up {page-component-title} Core

ifeval::["{page-component-title}" == "Horizon"]
include::../repos/horizon.adoc[]

[{tabs}]
====
CentOS/RHEL::
+
--
.Install OpenNMS {page-component-title} Core packages
[source,console]
[source, console, subs="attributes"]
----
sudo dnf -y install {package-prefix}
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
After upgrading, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
We recommend that you exclude the {page-component-title} packages from updates except when you plan to perform an upgrade.

.Disable auto updates for OpenNMS {page-component-title}
[source, console]
----
sudo dnf config-manager --disable opennms-repo-stable-*
----
--

Debian/Ubuntu::
+
--
.Install OpenNMS {page-component-title} Core packages
[source, console]
----
sudo apt -y install opennms
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
After upgrading, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
We recommend that you exclude the {page-component-title} packages from updates except when you plan to perform an upgrade.

[source,console]
----
sudo apt-mark hold libopennms-java \
  libopennmsdeps-java \
  opennms-common \
  opennms-db \
  opennms-server \
  opennms-source \
  opennms-webapp-jetty
----
--
====
endif::[]

ifeval::["{page-component-title}" == "Meridian"]
include::../repos/meridian.adoc

.Install {page-component-title} Core packages
[source,console]
[source, console, subs="attributes"]
----
sudo dnf -y install {package-prefix}
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
After upgrading, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
We recommend that you exclude the {page-component-title} packages from updates except when you plan to perform an upgrade.

.Disable auto updates for OpenNMS {page-component-title}
[source, console]
----
sudo dnf config-manager --disable meridian
----
endif::[]

.Set credentials for the PostgreSQL database connections:
[source, console]
----
sudo -u opennms /opt/opennms/bin/scvcli set postgres opennms <YOUR SECRET PASSWORD> <1>
sudo -u opennms /opt/opennms/bin/scvcli set postgres-admin postgres <YOUR SECRET PASSWORD>
----
<1> Replace both `<YOUR SECRET PASSWORD>` instances with the actual passwords for your `opennms` and `postgres` database accounts.

.Detect Java environment and persist in `/opt/opennms/etc/java.conf`
[source, console]
----
sudo /opt/opennms/bin/runjava -s
----

.Initialize the database and detect system libraries persisted in `/opt/opennms/etc/libraries.properties`
[source, console]
----
sudo /opt/opennms/bin/install -dis
----

.Define any necessary xref:operation:deep-dive/admin/configuration/startup.adoc[startup configuration], such as open file descriptors or maximum Java heap
[source, console]
----
echo "JAVA_HEAP_SIZE=12G" | sudo tee /opt/opennms/etc/opennms.conf
echo "MAXIMUM_FILE_DESCRIPTORS=512000" | sudo tee -a /opt/opennms/etc/opennms.conf
----
NOTE: These values are provided as examples; ideal values will vary based on your environment and workload.
It is recommended to not use more than **75% of RAM** for maximum Java heap size.
Java requires additional space for threads, metaspace, socket buffers, etc.

.Enable {page-component-title} core instance on system boot and start immediately
[source, console]
----
sudo systemctl enable --now opennms
----


[[configure-firewall]]
=== Configure firewall rules

include::firewall.adoc[]

[[first-sign-in]]
== Step 4: First-time Sign In

After you start the {page-component-title} core services, you can access the web application at `\http://core-instance-ip:8980/opennms`.
The default user credentials are as follows:

* *Username:* `admin`
* *Password:* `admin`

When you try to sign in with these credentials, {page-component-title} prompts you to change your password.
Although you can also skip this action and sign in with default the credentials, we strongly recommend that you change the `admin` account's password to a secure one.

. Type your current password.
. Type your new password and confirm it.
. Click *Change Password*.

=== Change Admin Password

To change your account's password after the first time you sign in, follow these steps:

. On the top menu bar, click menu:Admin[Change Password].
. Type your current password and new password in the appropriate fields.
. Confirm your new password and click *Submit*.

The password is updated.

We encourage you to use {page-component-title} with individual user accounts instead of using only the `admin` account.
If all users have individual accounts, you can see who is completing tasks, (for example, clearing or acknowledging alarms).
For information on how to create personalized user accounts, see xref:operation:quick-start/users.adoc#create-user[Create a new user] in the Quick Start guide.

[[usage-statistics]]
=== Usage Statistics

The first time you sign in, {page-component-title} notifies you that it collects anonymized usage statistics and publishes them to https://stats.opennms.com.
Consent to share collected usage statistics is assumed by default.

The OpenNMS Group uses this information to help determine product use and to improve the {page-component-title} software.
We do not share it with third parties, and we will not use it for sales purposes.

Click *Learn More* to view the xref:operation:deep-dive/admin/configuration/usage-statistics.adoc[information that we collect and share].
This also hides the notification.

Click *Dismiss* to simply hide the notification.
You can view the usage statistics at any time on the admin page.

NOTE: Admin users can xref:operation:deep-dive/admin/configuration/usage-statistics.adoc#disable-data-collection[opt out of sharing the statistics] at any time.

=== First Monitored Node

The default configuration will discover a single node with an interface `127.0.0.1` and detect services exposed on the loopback interface, including the `OpenNMS-JVM` service.
Nodes with this service have JMX-based data collection performed on Java JVM statistics such as heap memory and open file handles.

== Related Topics

* xref:operation:deep-dive/admin/configuration/startup.adoc[]
* xref:reference:configuration/selinux.adoc[]
* xref:reference:configuration/receive-snmp-traps.adoc[]
* xref:core/installing-jdbc-driver.adoc[]

== Next Steps

See the xref:operation:quick-start/introduction.adoc[Quick Start guide] for more information on setting up and configuring your {page-component-title} instance.
