
[[requirements-core]]
= Requirements
:description: OpenNMS system requirements, supported operating systems, version compatibility with Grafana, Cassandra, Elasticsearch, JDK, Kafka, PostgreSQL.

[[system-requirements-core]]
== System requirements

Your system must meet the following minimum specifications to run {page-component-title}:

[options="autowidth"]
|===
|   | Just Testing ^1^   | Minimum Server Specification ^2^

s| CPU
| 2GHz dual core x86_64
| 3GHz quad core x86_64 and above

s| RAM
| 4GB (physical)
| 16GB (physical) and above

s| Storage (disk space)
| 50-GB HDD, SSD
| 1TB with SSD and above
|===

. You can install the packages, and the {page-component-title} services start.
. Your intended workload (network size, number of monitored metrics, flows, events, and data retention requirements) affects these requirements.

[[operating-systems-core]]
== Operating systems

OpenNMS {page-component-title} requires one of the following operating systems:

[options="autowidth"]
|===
| Operating System  | Compatible Versions (64-bit)

| RHEL
| {compatible-rhel}

| CentOS Stream
| {compatible-centos}

ifeval::["{page-component-title}" == "Horizon"]
| Debian
| {compatible-debian}

| Ubuntu
| {compatible-ubuntu}
endif::[]
|===

See the xref:releasenotes:whatsnew.adoc[release notes] for information about platform support changes, including deprecated platforms.

[[compatibility-core]]
== Compatibility

{page-component-title} is compatible with the following components.
Components marked with an asterisk are required:

[options="autowidth"]
|===
| Component | Version Compatibility

| OpenNMS plugin for Grafana
| {compatible-opennms-plugin}

| OpenNMS Plugin API
| {compatible-oia}

| Cassandra
| {compatible-cassandra}

| Elasticsearch
| {compatible-elasticsearch}

| Java Development Kit *
| {compatible-javajdk}

| Kafka
| {compatible-kafka}

| PostgreSQL *
| {compatible-postgresql}

| RRDTool *
| {compatible-rrdtool}

| Browser *
| Latest https://www.mozilla.org[Mozilla Firefox] or https://www.google.com/intl/en_us/chrome/[Google Chrome]
|===

== Before You Begin

The following components and settings are required to set up a new {page-component-title} Core instance:

ifeval::["{page-component-title}" == "Meridian"]
* Credentials to access the Meridian repositories.
endif::[]
* A Linux physical server, or a virtual machine running a <<./requirements.adoc#operating-systems-core,supported Linux operating system>>.
* Internet access to download the installation packages.
* A working DNS server, and ensure `localhost` and the server name resolves properly.
* A system user with administrative permissions (`sudo`) to perform installation.
ifeval::["{page-component-title}" == "Horizon"]
* To run services in Docker, you need https://docs.docker.com/compose/install[Docker Compose] for the service stacks from our examples.
* On Debian, you must install and configure `sudo` yourself.
See the https://wiki.debian.org/sudo/[Debian Wiki] for more information.
endif::[]
* If you use SELinux, you need a policy that permits binding to the ICMP service, see xref:reference:configuration/selinux.adoc[SELinux and ICMP permissions].

IMPORTANT: OpenNMS {page-component-title} is designed to run within an organization's protected intranet.
Do not expose the web console or sign-in pages directly to the Internet without appropriate isolation controls, (for example, a VPN with multifactor authentication).

.System preparation
[{tabs}]
====
CentOS/RHEL::
+
--
.Ensure you have the English language pack installed
[source, console]
----
sudo dnf install langpacks-en glibc-all-langpacks -y
----

.It is recommended to set your system locale to en_US.UTF-8
[source, console]
----
sudo localectl set-locale LANG=en_US.UTF-8
sudo localectl
----

.If you want faster package search, download package metadata
[source, console]
----
sudo dnf makecache
----

.Get your system up to date
[source, console]
----
sudo dnf update -y
----
--

Debian/Ubuntu::
+
--
.It is recommended to set your system locale to en_US.UTF-8
[source,console]
----
sudo locale-gen en_US.UTF-8 en_GB.UTF-8
sudo update-locale LANG=en_US.UTF-8
----

.Get your system up to date
[source, console]
----
sudo apt update
sudo apt upgrade
----
--
====

include::../time-sync.adoc[]

== DNS Considerations

If you are planning a large deployment, you may need to review your DNS configuration to ensure name lookups can be processed quickly.
DNS lookups may be performed by different processes:

* provisioning new nodes
* receiving syslog messages
* Network flow processing

Slow DNS lookups can introduce latency and degraded performance.
A common way to mitigate high DNS latency is to set up your {page-component-title} Core instance as a caching DNS server.
