[[setup-message-broker]]
= Setting up Message Broker

Distributing {page-component-title} components like Minions and Sentinel require a messaging infrastructure.
This section describes how to setup your {page-component-title} Core instance to use an existing messaging infrasturce based on ActiveMQ or Apache Kafka.
If you want to learn how it works, {page-component-title} Core comes with an embedded ActiveMQ system which is by default not reachable from external network.
To get you started quickly, we describe here as well how you can enable and configure the embedded ActiveMQ instance.

CAUTION: We recommend to use Apache Kafka in production and can be scaled to process high workloads.
         The embedded ActiveMQ instance is for convinience to get you started quickly in a testing environment.
         It is not suited for production workloads.

== Objectives

* Configure {page-component-title} Core instance to use a message broker for communication
* Create a Minion user which is used to authenticate the communication channels

== Requirements

Configuring a Minion requires the following information::

* Web UI URL for your OpenNMS {page-component-title} Core instance
* SSH access to the Karaf Shell
* ActiveMQ or Apache Kafka server IP addresses or FQDNs to configure the broker URL endpoints
* Credentials for message broker if you use your existing environment

== Create a minion user

The communication between {page-component-title} Core instance and the componetnsMinion is secured with credentials.
We use here as example the user _my-minion-user_ with password _my-minion-password_.

. Log in to the web UI as an administrative user
. Click on the gears icon and choose btn:[Configure Users, Groups and On-Call Roles] -> btn:[Configure Users]
. Add a new user with login name _my-minion-user_ and password _my-minion-password_ and click btn:[OK]
. In the *Security Roles* area, assign the _ROLE_MINION_ security role
.. Optional: fill in a comment for the Minion user's location and purpose
. Click btn:[Finish]

The new created Minion user should now be listed in the user List.

IMPORTANT: Replace at least _my-minion-password_ with a secure password.

== Configure Message Broker

NOTE: Configurations has to be made in the {page-component-title} etc directory.
      We reference `etc` relative to the OpenNMS {page-component-title} Core home directory.
      Depending on your operating system the home directory is `/usr/share/opennms` for Debian/Ubuntu or `/opt/opennms` for CentOS/RHEL.

[{tabs}]
====
Kafka::
+
--
include::message-broker/kafka.adoc[]
--

ActiveMQ::
+
--
include::message-broker/activemq.adoc[]
--

embedded ActiveMQ::
+
--
include::message-broker/embedded-activemq.adoc[]
--

gRPC::
+
--
include::message-broker/grpc.adoc[]
--

AWS SQS::
+
--
include::message-broker/aws-sqs.adoc[]
--
====
