[[asset-layers]]
= Asset Layers

The entries for `assetLayers` can be any node or asset entry from the following list (defined in class NodeParamLabels).
Keys beginning with `node-` come from the node table.
Keys beginning with `parent-` come from the node table entry of the designated parent node (if defined).
Keys beginning with `asset-`  come from the corresponding asset table entry for the given node (if defined).

[options="autowidth"]
|===
5+| *Node fields*
| node-nodelabel | node-nodeid | node-foreignsource | node-foreignid | node-nodesysname
| node-nodesyslocation | node-operatingsystem | node-categories| |
5+| *Parent node fields*
| parent-nodelabel | parent-nodeid | parent-foreignsource | parent-foreignid |
5+| *Node asset fields*
| asset-address1 | asset-address2| asset-city | asset-zip| asset-state
| asset-latitude | asset-longitude| asset-region | asset-division| asset-department
| asset-building | asset-floor| asset-room | asset-rack | asset-slot
| asset-port | asset-circuitid | asset-category | asset-displaycategory | asset-notifycategory
| asset-pollercategory | asset-thresholdcategory | asset-managedobjecttype | asset-managedobjectinstance | asset-manufacturer
| asset-vendor | asset-modelnumber | asset-description | asset-operatingsystem | asset-country
|===

This lets you generate arbitrary topologies, including physical fields (room, rack) and logical fields (asset node categories).
You should not put any spaces in the comma-separated `assetLayers` list.
If the `assetLayers` property is defined as empty, then a single graph layer is generated containing all OpenNMS nodes.
