
[[housekeeping]]
= Housekeeping Tasks

There are a number of housekeeping tasks you may want to do regularly to ensure optimum system performance.
We also recommend you complete these housekeeping tasks before upgrading {page-component-title}.

[[prune-events]]
== Prune unneeded events
It's a good idea to use vacuumd or cron to regularly prune unneeded events.
This helps to clean up your events table, and reduces the amount of data in your backups.
We also recommend doing this before you begin the {page-component-title} upgrade process.

For example, run the following to delete events older than six weeks that have no associated outages:

##do we have a better example?##

[source, console]
----
--# this deletes any events that are not associated with outages
DELETE FROM events WHERE NOT EXISTS
(SELECT svclosteventid FROM outages WHERE svclosteventid = events.eventid
UNION
SELECT svcregainedeventid FROM outages WHERE svcregainedeventid = events.eventid
UNION
SELECT eventid FROM notifications WHERE eventid
----





[[non-root-permissions]]
== Update permissions (if upgrading from pre-29 versions)
Since version 29, {page-component-title} runs as the opennms user rather than root by default.
If you are upgrading from a version of {page-component-title} older than 29, you must fix the ownership of your files before upgrading.

For information on how to do this, see https://docs.opennms.com/horizon/29/releasenotes/whatsnew.html?q=non-root#running-as-non-root[Running as non-root].

[[delete-old-events]]
== Delete older events

[[event-table-size]]
== Assess event table size

[[delete-cache-folder]]
== Delete cache folder
Run the Fix Karaf script to delete cached items so that your system is cleaned up.
We recommend doing this after an upgrade. 
