
=== Encrypting SNMP Credentials

SNMP credentials like readCommunity/WriteCommunity, authPassPhrase/privPassPhrase can be saved on the file system in encrypted format.

==== Encryption methodology

A random password is generated (once) for `snmp-config` alias and it is stored in java keystore file at `$OPENNMS_HOME/etc/scv.jce`.
This password is used to encrypt/decrypt SNMP credentials.

==== Enabling encrypting on SNMP Config

Enable encryption on SNMP config by setting following system property.
[source, sh]
----
echo 'org.opennms.snmp.encryption.enabled=true' >> "$OPENNMS_HOME/etc/opennms.properties.d/snmp-encryption.properties"
----

SNMP config that is modified from User Interface will be encrypted directly on file system.
Config that is updated on the file system needs to be saved with karaf command `opennms-snmp:save-config` to get encrypted.

NOTE:  Currently, SNMP config encryption is not supported on the snmp profiles.

NOTE:  Encryption Utils needs https://www.oracle.com/java/technologies/javase-jce-all-downloads.html[JCE] (Java Cryptography Extension) enabled on the JDK.