= Time Series Storage
 
{page-component-title} stores performance data in a time series storage which is by default link:https://wiki.opennms.org/wiki/JRobin[JRobin].
For different scenarios it is useful to switch to a different time series storage.
The following implementations are installed by default:

.Supported Time Series Databasees
[width="100%", cols="1,4"]
|===
| JRobin      | JRobin is a clone of RRDTool written in Java, it does not fully cover the latest feature set of RRDTool and is the default when you install {page-component-title}.
                Data is stored on the local file system of the {page-component-title} node.
                Depending on I/O capabilities it works good for small to medium sized installations.
| RRDTool     | RRDTool is active maintained and the de-facto standard dealing with time series data.
                Data is stored on the local file system of the {page-component-title} node.
                Depending on I/O capabilities it works good for small to medium sized installations.
| Newts       | link:http://opennms.github.io/newts/[Newts] is a database schema for link:http://cassandra.apache.org[Cassandra].
                The time series is stored on a dedicated Cassandra cluster, which gives growth flexibility and lets time series data persist in a large scale.
|===

You can use time series storage integrations with plugins that were based on our OpenNMS Integration API (OIA).
The following plugins can be used as a replacement for the ones shipped with OpenNMS {page-component-title}:

* https://github.com/OpenNMS/opennms-cortex-tss-plugin
* https://github.com/opennms-forge/timeseries-integration-influxdb
* https://github.com/opennms-forge/timeseries-integration-timescale

This section describes how to configure {page-component-title} to use RRDTool and Newts.

CAUTION: The way how data is stored in the different time series databases makes it extremely hard to migrate from one technology to another.
         Data loss can't be prevented when you switch from one to another.
