
[[ref-daemon-config-files-bsmd]]
= Bsmd
:description: Learn about the OpenNMS {page-component-title} business services monitoring daemon (bsmd), which tracks the operational status of all business services.

Handles calculation of the operational status of the defined xref:operation:deep-dive/bsm/introduction.adoc[business services].
The daemon tracks the operational status of all business services and sends events when there are operational status changes.

Every time you change the configuration of a business service, you must reload the daemon's configuration.
This includes changes like the name of the business service or its attributes, as well as changes regarding the reduction keys, contained business services, or IP services.
Reload the BSMD configuration with any of the following mechanisms:

* Click the `Reload Daemon` button in the Business Service Editor.
* Send the `reloadDaemonConfig` event using `send-event.pl` or use the "Manually Send an Event"  UI with parameter `daemonName bsmd`.
* Use the REST API to perform a `POST` request to `/opennms/api/v2/business-services/daemon/reload`.

.Bsmd log file overview
[options="header"]
[cols="2,3"]
|===
| File
| Description

| bsmd.log
| Logs relating to bsmd server events.
|===
