
[[ref-daemon-config-files-rtcd]]
= Rtcd
:description: Learn about rtcd, which calculates the availability percentages displayed on the OpenNMS {page-component-title} home page.

Calculates the availability percentages displayed on the {page-component-title} home page.
This daemon checks the database and updates availability data by sending REST calls to the server.

IMPORTANT: {page-component-title} comes with a local `rtc` user account.
This account is used by rtcd to send updates, and is granted access rights only for updating RTC data.
Any modifications to this account can impact the server's ability to update availability data.

.Rtcd configuration file overview
[options="header"]
[cols="2,3,1,1"]
|===
| File
| Description
| Reload Event
| Restart Required

| categories.xml
| Defines categories for grouping availability data and which nodes apply to the categories.
These are independent of node tags, and can use node tags to define the filter rules.
| no
| yes

| rtc-configuration.xml
| Defines properties of the RTC polling intervals.
| no
| yes

| viewdisplay.xml
| Defines which categories from `categories.xml` the home page displays.
| no
| yes
|===

.Rtcd log file overview
[options="header"]
[cols="2,3"]
|===
| File
| Description

| rtcd.log
| Logs relating to rtcd server events.
|===