
[[ref-daemon-config-files-trapd]]
= Trapd
:description: Learn about trapd in OpenNMS {page-component-title}, which processes SNMP traps into events.

Handles processing of xref:operation:deep-dive/events/sources/snmp-traps.adoc[SNMP traps] into events.
Based around traditional UDP-based SNMP traps, it receives traps that remote devices create.
It enables OpenNMS to receive SNMP traps and convert them into events and, if configured accordingly, convert those events into alarms and notifications.
Its functionality is similar to how xref:reference:daemons/daemon-config-files/syslogd.adoc[syslogd] handles syslog entries.

Trapd supports V1 traps, V2 traps and notifications, and V3 traps and notifications.
It also accepts traps with any community name (V1, V2c).
You can use that community name in event definitions as part of a mask.

== How it works

When an SNMP trap arrives, trapd parses the message, comparing the sender to known nodes.
If the sender is not a monitored node and the `new-suspect-on-trap` parameter is set to `true`, {page-component-title} sends an event to xref:operation:deep-dive/provisioning/auto-discovery.adoc[discover] the node.
Otherwise, {page-component-title} tags the trap to the monitored node, broadcasts it to eventd, and the trap becomes a {page-component-title} event.

.Trapd configuration file overview
[options="header"]
[cols="2,3,1,1"]
|===
| File
| Description
| Reload Event
| Restart Required

| trapd-configuration.xml
| Configure generic behavior of trapd (for example, port numbers with IP addresses to listen for traps).
| yes
| no

| events/*.xml
| Defines mapping between OIDs and UEIs.
Files in this folder must be specified as an include directive in `eventconf.xml`.
| yes
| no
|===

.Trapd log file overview
[options="header"]
[cols="2,3"]
|===
| File
| Description

| trapd.log
| Logs relating to trapd server events.
|===

== Additional information

For information on how to automate alarms and reduce the number of messages, see https://opennms.discourse.group/t/syslogd-automations/1454[Syslogd Automations] on Discourse.

You can configure the eventd subsystem to discard unwanted SNMP traps.
To do so, use the `discardtraps` logmsg.
See xref:operation:deep-dive/events/event-definition.adoc#ga-events-anatomy-of-an-event[Anatomy of an event] in the Event Daemon Configuration section for more information.

Note that for V3, you must specify the SNMPv3 credentials used to authenticate and decode V3 traps in `trapd-configuration.xml`, as in the following example:

[source, xml]
----
<trapd-configuration snmp-trap-port="162" new-suspect-on-trap="true">
  <snmpv3-user security-name="opennms" auth-passphrase="0p3nNMSv3" auth-protocol="MD5"
      privacy-passphrase="0p3nNMSv3" privacy-protocol="DES"/>
  <snmpv3-user security-name="sample-name" auth-passphrase="secret" auth-protocol="MD5"
      privacy-passphrase="super-secret" privacy-protocol="DES"/>
</trapd-configuration>
----
For `privacy-protocol`, the available options are `DES`, `AES`, `AES192`, and `AES256`
For `auth-protocol`, the available options are  `MD5`, `SHA`, `SHA-224`, `SHA-256`, and `SHA-512`

NOTE: Metadata expressions can also be used in attributes of the `trapd-configuration.xml` configuration file.
This lets the user to also reference credentials stored in the secure credentials.
