
[[install-minion]]
= Native Installation
:description: How to install OpenNMS Minion on CentOS/RHEL, Debian/Ubuntu, and configure with message brokers: Kafka, ActiveMQ, Embedded ActiveMQ, gRPC.

This section explains how to install and configure a new OpenNMS {page-component-title} Minion for distributed network monitoring:

* Install a {page-component-title} Minion on one of the supported <<./requirements.adoc#operating-systems-minion,operating systems>>.
* Secure access to the xref:reference:karaf-shell/karaf-shell.adoc[Karaf shell] with encrypted passwords.
* Configure connection to message broker for communication with the {page-component-title} core instance.
* Verify the setup.

include::../time-sync.adoc[]

== Step 1: Installing Java

include::../java/temurin.adoc[]

== Step 2: Set up {page-component-title} Minion

ifeval::["{page-component-title}" == "Horizon"]
include::../repos/horizon.adoc[]

[{tabs}]
====
CentOS/RHEL::
+
--
.Install the {page-component-title} Minion package
[source, console]
----
sudo dnf -y install opennms-minion
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
After upgrade, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
For this reason, we recommend that you exclude the {page-component-title} packages from update except when you plan to perform an upgrade.

.Disable auto updates for {page-component-title} Minion
[source, console]
----
sudo dnf config-manager --disable opennms-repo-stable-*
----

.Enable {page-component-title} Minion on system boot and start immediately
[source, console]
----
sudo systemctl enable --now minion
----
--

Debian/Ubuntu::
+
--
.Install the {page-component-title} Minion package
[source, console]
----
sudo apt -y install opennms-minion
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
After upgrade, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
For this reason, we recommend that you exclude the {page-component-title} packages from update except when you plan to perform an upgrade.

.Disable auto updates for {page-component-title} Minion
[source, console]
----
sudo apt-mark hold opennms-minion
----

.Enable {page-component-title} Minion on system boot and start immediately
[source, console]
----
sudo systemctl enable --now minion
----

--
====
endif::[]

ifeval::["{page-component-title}" == "Meridian"]
include::../repos/meridian.adoc[]

[{tabs}]
====
CentOS/RHEL::
+
--
.Install the {page-component-title} Minion package
[source, console]
----
sudo dnf -y install meridian-minion
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
After upgrade, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
For this reason, we recommend that you exclude the {page-component-title} packages from update except when you plan to perform an upgrade.

.Disable auto updates for {page-component-title} Minion
[source, console]
----
sudo dnf config-manager --disable meridian
----

.Enable {page-component-title} Minion on system boot and start immediately
[source, console]
----
sudo systemctl enable --now minion
----
--
====
endif::[]

TIP: If you use SELinux you can use the policy to allow ICMP from a non-root application described in xref:reference:configuration/selinux.adoc[].

[[secure-karaf-shell]]
== Step 3: Secure access to Karaf shell

Change the default username and password (_admin/admin_) for the Karaf shell and encrypt it.

.Log in to the Karaf shell
[source, console]
----
ssh -p 8201 admin@localhost
----

.Enable password encryption using SHA-512
[source, karaf]
----
config:edit org.apache.karaf.jaas
config:property-set encryption.enabled true
config:property-set encryption.algorithm SHA-512
config:property-set encryption.name jasypt
config:update
----

WARNING: If you set the `encryption.name` option, you will need to reset any existing passwords that were created while `encryption.enabled` was set to `true`.

.Set a new secure admin password
[source, karaf]
----
jaas:realm-manage --index 1 --realm karaf
jaas:user-add admin my-secure-password<1>
jaas:update
----
<1> Replace `my-secure-password` with a strong password.

Log out and log back in to verify that your new password is set.

Changes to the password and encryption algorithm are applied immediately.
You do not need to restart the Minion.

TIP: By default, the Karaf Shell is restricted to `127.0.0.1`.
To enable remote access, set `sshHost=0.0.0.0` in `org.apache.karaf.shell.cfg`.
The change is applied immediately, and you do not need to restart the Minion.
If you have a firewall running on your host, allow `8201/tcp` to grant access to the Karaf shell.

== Step 4: Configure connectivity to the Core instance

Set configuration settings in the Minion `/opt/minion/etc` directory.

NOTE: If you are deploying in a container, this step should have been completed as part of the container definition.

[{tabs}]
====
Kafka::
+
--
include::message-broker/kafka.adoc[]
--

ActiveMQ::
+
--
include::message-broker/activemq.adoc[]
--

gRPC::
+
--
include::message-broker/grpc.adoc[]
--
====

== Step 5: Receive Trap/Syslog Messages

By default, the Minion service only listens for traps and syslog messages on the localhost interface.
If you would like to receive messages on the Minion, the interfaces and ports need to be configured.

=== Syslog messages

.`/opt/minion/etc/org.opennms.netmgt.syslog.cfg`
[source, properties]
----
syslog.listen.interface=0.0.0.0
syslog.listen.port=514
----

=== SNMP traps

.`/opt/minion/etc/org.opennms.netmgt.trapd.cfg`
[source, properties]
----
trapd.listen.interface=0.0.0.0
trapd.listen.port=162
----

== Step 6: Check Minion in the core web user interface

. Log in to the web UI as an administrative user.
. Click menu:Administration[Configure OpenNMS] in the side menu, then click menu:Distributed Monitoring[Manage Minions].

After a few minutes your Minion should be provisioned automatically and the status should be "up".

== Related Topics

* xref:reference:configuration/selinux.adoc[]
* xref:minion/installing-jdbc-driver.adoc[]
