[[install-minion]]
= Installing Minion

[[objectives]]
== Objectives

* Installing a {page-component-title} Minion on one of the following <<minion/system-requirements.adoc#operating-systems-Core, Operating Systems>>
* Secure access with encrypted passwords to the Karaf shell
* Configure connection to message broker for communication with the {page-component-title} Core instance
* Veryfing the setup

== Requirements

* The {page-component-title} Core instance is running and configured with a <<core/setup-message-broker.adoc#setup-message-broker,message broker>>
* Linux physical server or a virtual machine running a supported Linux operating system
* Internet access to download the installation packages
* Ensure DNS is configured, localhost and your servers host name is resolved properly
* {page-component-title} Core instance runs on latest stable release
* The Minion server can access the {page-component-title} Core instance via REST (8980/tcp) and desired message broker nodes (e.g. ActiveMQ 61616/tcp, Apache Kafke 9092/tcp)
* System user with administrative permissions (sudo) to perform the installation tasks

ifeval::["{page-component-title}" == "Horizon"]
CAUTION: If you run Debian, you have to install and configure `sudo` yourself.
         A guide can be found in the link:https://wiki.debian.org/sudo/[Debian Wiki].
endif::[]

== Installing the Minion package

[{tabs}]
====
CentOS/RHEL 8::
+
--
include::centos-rhel8/step-2-install-minion.adoc[]
--

CentOS/RHEL 7::
+
--
include::centos-rhel7/step-2-install-minion.adoc[]
--

ifeval::["{page-component-title}" == "Horizon"]
Ubuntu::
+
--
include::ubuntu/step-2-install-minion.adoc[]
--

Debian::
+
--
include::debian/step-2-install-minion.adoc[]
--
endif::[]
====

== Secure Access to Karaf Shell

IMPORTANT: Change the default user/password _admin/admin_ for the Karaf shell and encrypt it.

[{tabs}]
====
CentOS/RHEL 7/8::
+
--
include::centos-rhel/step-4-secure-karaf.adoc[]
--

ifeval::["{page-component-title}" == "Horizon"]
Debian/Ubuntu::
+
--
include::debian-ubuntu/step-4-secure-karaf.adoc[]
--
endif::[]
====

TIP: Changing the password or encryption algorithm get applied immediately.
     It is not required to restart the Minion

TIP: By default the Karaf Shell is restricted to 127.0.0.1.
     If you want enable remote access, set `sshHost=0.0.0.0` in `org.apache.karaf.shell.cfg`.
     The change is applied immediately and a Minion restart is not required.
     If you have firewall running on your host, allow `8201/tcp` to grant access to the Karaf Shell.

== Configure Connectivity to the Core instance

NOTE: Configurations has to be made in the {page-component-title} etc directory.
      We reference `etc` relative to the OpenNMS {page-component-title} Core home directory.
      Depending on your operating system the home directory is `/usr/share/opennms` for Debian/Ubuntu or `/opt/opennms` for CentOS/RHEL.

[{tabs}]
====
Kafka::
+
--
include::message-broker/kafka.adoc[]
--

ActiveMQ::
+
--
include::message-broker/activemq.adoc[]
--
====

== Check Minion in the Core web UI

. Log in to the web UI as an administrative user
. Click on the gears icon and choose btn:[Manage Minions]

After a few minutes your Minion should be provisioned automatically and the status should be _up_.
