
[[system-requirements-minion]]
= Minimum System Requirements
:description: Minimum requirements for OpenNMS Minion, including operating systems.

The following hardware specs are the minimum required to run a Minion:

[options="autowidth"]
|===
|   | Just Testing^1^   | Minimum Server Specification^2^

s| CPU
| 2GHz dual core x86_64
| 3GHz quad core x86_64 and above

s| RAM
| 4GB (physical)
| 8GB (physical) and above

s| Storage (disk space)
| 20-GB HDD, SSD
| 100GB with SSD and above
|===

. You can install the packages, and the Minion services start. +
. Your intended workload (network size, number of monitored metrics, flows, events, and data retention requirements) affects these requirements.

[[operating-systems-minion]]
== Operating systems

OpenNMS {page-component-title} runs on the following operating systems:

[options="autowidth"]
|===
| Operating System  | Supported Versions (64-bit)

| CentOS
| {compatible-centos-stream}

ifeval::["{page-component-title}" == "Horizon"]
| Debian
| {compatible-debian}

| Ubuntu
| {compatible-ubuntu}
endif::[]
|===

NOTE: See the xref:releasenotes:whatsnew.adoc[release notes] for information about platform support changes, including deprecated platforms.
