
[[system-requirements-minion]]
= Minimum System Requirements

The following hardware specs are the minimum required to run a Minion:

[options="autowidth"]
|===
|   | Just Testing^1^   | Minimum Server Specification^2^

| *CPU*
| 2GHz dual core x86_64
| 3GHz quad core x86_64 and above

| *RAM*
| 4GB (physical)
| 8GB (physical) and above

| *Storage (Disk Space)*
| 20-GB HDD, SSD
| 100GB with SSD and above
|===

^1^ You can install the packages, and the Minion services start. +
^2^ Your intended workload (network size, number of monitored metrics, flows, events, and data retention requirements) affects these requirements.

[[operating-systems-minion]]
== Operating systems

OpenNMS {page-component-title} runs on the following operating systems:

[options="autowidth"]
|===
| Operating System  | Supported Versions (64-bit)

| RHEL
| {compatible-rhel7} +
{compatible-rhel8}

| CentOS
| {compatible-centos7} +
{compatible-centos-stream}

ifeval::["{page-component-title}" == "Horizon"]
| Debian
| {compatible-debian}

| Ubuntu
| {compatible-ubuntu}
endif::[]
|===

NOTE: See the xref:releasenotes:whatsnew.adoc[release notes] for information about platform support changes, including deprecated platforms.
