/*******************************************************************************
 * This file is part of OpenNMS(R).
 *
 * Copyright (C) 2019 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2019 The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is a registered trademark of The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OpenNMS(R) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with OpenNMS(R).  If not, see:
 *      http://www.gnu.org/licenses/
 *
 * For more information contact:
 *     OpenNMS(R) Licensing <license@opennms.org>
 *     http://www.opennms.org/
 *     http://www.opennms.com/
 *******************************************************************************/

package org.opennms.netmgt.alarmd.usecases;

import java.util.Date;
import java.util.LinkedList;
import org.kie.api.time.SessionClock;
import org.opennms.netmgt.model.OnmsAlarm;
import org.opennms.netmgt.model.OnmsCategory;
import org.opennms.netmgt.model.OnmsSeverity;

global org.opennms.netmgt.alarmd.drools.AlarmService alarmService;

/**
Miscellaneous rules that can be used as a basis and example to build your own rulesets.
*/

declare org.opennms.netmgt.model.OnmsAlarm
    @role(event)
    @timestamp(lastUpdateTime)
end


rule "escalate alarms for node in category"
  when
    $alarm : OnmsAlarm(alarmType == OnmsAlarm.PROBLEM_TYPE,
                       lastEvent != null,
                       lastEvent.eventUei in ( "uei.opennms.org/nodes/nodeDown", "uei.opennms.org/nodes/interfaceDown" ),
                       severity.isGreaterThan(OnmsSeverity.NORMAL),
                       severity.isLessThan(OnmsSeverity.CRITICAL),
                       node != null)
    LinkedList( isEmpty == false ) from collect( OnmsCategory( name == "EMERGENCY_F0" ) from $alarm.node.categories )
  then
    Date now = new Date(drools.getWorkingMemory().getSessionClock().getCurrentTime());
    alarmService.escalateAlarm($alarm, now);
end
