
[[releasenotes-29]]

= What's New in OpenNMS Horizon 29

== System Requirements

* *Java 11*: OpenNMS Horizon 29 runs on JDK 11.
* *PostgreSQL 10 or higher*: Horizon 29 requires any supported version of PostgreSQL from 10 up to (and including) 13.

== Breaking Changes

=== OpenNMS Runs As Non-Root By Default

By default, OpenNMS runs as the `opennms` user rather than `root`.

WARNING: If you are upgrading from a version of OpenNMS Horizon older than 29, you will have to fix the ownership of your files.

Since many OpenNMS instances are very large with thousands or even millions of RRD and similar data files in `$OPENNMS_HOME/share`,
we decided _not_ to change ownership automatically upon package upgrade.

The OpenNMS installer will detect if you need to fix the ownership of your files and warn you to run the script to fix permissions
(`$OPENNMS_HOME/bin/fix-permissions`) in this case.

=== Timeseries Integration Layer
* Time series plugins need to be compatible with OIA 0.6.x.
* Resource level string attributes are now also stored via the plugin in the respective time series database.
  The so far used database tables in PostgreSQL have been removed.
  There is no migration support.

=== Your Change Here

== New Features and Improvements

=== Your Feature Here

== Important Internal Changes

* Dependency Change Here
