[[releasenotes-32]]

= What's New in OpenNMS Horizon 33

== System requirements

* *Java 11 and 17*: OpenNMS Horizon 33 runs on JDKs 11 and 17.
* *PostgreSQL 10 or higher*: Horizon 33 requires any supported version of PostgreSQL from 10 up to (and including) 16.

== New features and important changes

=== Asynchronous Polling Enabled By Default

The new asynchronous polling scheduler introduced in Horizon 32 is now on by default, allowing OpenNMS to use fewer Pollerd threads to handle the same amount of load.

If you wish to disable it and revert to the old scheduler, see xref:operation:deep-dive/service-assurance/configuration.adoc#ga-pollerd-configuration-async[the operation manual].

=== OpenNMS Plugin API

The OpenNMS Plugin API has been updated to version 1.6.0, which includes some new APIs ported over from the Horizon codebase to simplify plugin development, as well as cleanups to dependencies.
It also includes some fixes to the protocol list used by Enlinkd.

=== Expanded Metadata Support

It is now possible to use the metadata DSL in nearly all configuration files.
For details on all of the subsystems that support the metadata DSL, see xref:operation:deep-dive/meta-data.adoc[the operation manual].

== Breaking changes

=== Asynchronous Polling

Please note that if you rely on the node-outage critical service functionality, you may need to disable asynchronous polling, since the optimizations to thread-handling means the functionality can no longer be guaranteed.
For details, see xref:operation:deep-dive/service-assurance/critical-service.adoc[the operation manual].

=== Important internal updates

* Our embedded Karaf container and Karaf APIs have been updated to 4.3.10
* The OpenNMS Plugin API has been updated to 1.6.0
* Zookeeper APIs have been updated to 3.7.x
