
// Allow GitHub image rendering
:imagesdir: ../../images

=== Using Kafka

By default, _{opennms-product-name}_ uses the embedded _ActiveMQ_ broker to communicate with _Minions_.
This broker is used for both issuing remote procedure calls (RPCs, ie. ping this host) and for transporting unsolicited messages such as SNMP traps and syslog messages.

_Apache Kafka_ can be used as an alternative to _ActiveMQ_ for transporting the unsolicited messages.

WARNING: _Kafka_ cannot currently be used for handling RPC messages.
This means that _ActiveMQ_ is still required even when _Kafka_ support is enabled.

_Kafka_ must be enabled on both _{opennms-product-name}_ and _Minion_ to function.

The _Kafka_ server must be compatible with _Kafka_ client version `1.0.1`.

==== Consumer Configuration

Enable and configure the _Kafka_ consumer on _{opennms-product-name}_ by using the following commands. The `initialSleepTime` property will ensure that messages are not consumed from _Kafka_ until the _{opennms-product-name}_ system has fully initialized.

[source, sh]
----
echo 'org.opennms.core.ipc.sink.initialSleepTime=60000' > "$OPENNMS_HOME/etc/opennms.properties.d/sink-initial-sleep-time.properties"
echo 'org.opennms.core.ipc.sink.strategy=kafka
org.opennms.core.ipc.sink.kafka.bootstrap.servers=127.0.0.1:9092' > "$OPENNMS_HOME/etc/opennms.properties.d/kafka.properties"
----

Restart _{opennms-product-name}_ to apply the changes.

Additional _Kafka_ consumer options can be set by defining additional system properties prefixed with `org.opennms.core.ipc.sink.kafka`.
For example, you can customize the group ID using `org.opennms.core.ipc.sink.kafka.group.id=MyOpenNMS`.

A list of all the available options can be found here in link:https://kafka.apache.org/10/documentation.html#newconsumerconfigs[New Consumer Configs].

==== Producer Configuration

Enable the _Kafka_ producer on _Minion_ using:

[source, sh]
----
echo '!opennms-core-ipc-sink-camel
opennms-core-ipc-sink-kafka' > "$MINION_HOME/etc/featuresBoot.d/kafka.boot"
----

NOTE: The snippet above prevents the `opennms-core-ipc-sink-camel` feature from starting when _Minion_ is started, and loads the `opennms-core-ipc-sink-kafka` feature instead.

Next, configure the _Kafka_ producer on _Minion_ using:

[source, sh]
----
echo 'bootstrap.servers=127.0.0.1:9092
acks=1' > "$MINION_HOME/etc/org.opennms.core.ipc.sink.kafka.cfg"
----

Restart _Minion_ to apply the changes.

Additional _Kafka_ producer options can be set directly in the `org.opennms.core.ipc.sink.kafka.cfg` file reference above.
A list of all the available options can be found here in link:https://kafka.apache.org/10/documentation.html#producerconfigs[Producer Configs].
