// Allow GitHub image rendering
:imagesdir: ../../images

=== Using Off-heap Storage for Sink Messages

If a _Minion_ loses connectivity with the broker (i.e. _Kafka_ or _ActiveMQ_), then any received messages (i.e. syslog, flows, SNMP traps) are queued until connectivity is restored.
This queue is limited by a fixed (and configurable) number of messages queued in the JVM heap and can optionally queue
additional messages by persisting directly to the filesystem avoiding heap memory usage.
Once the queue is full, additional messages will be dropped.

The off-heap storage feature allows us to extend the storage capacity by queuing messages outside of the JVM heap.

==== Configuring Off-heap Storage

Configure storage limits:

[source, sh]
----
echo 'offHeapSize = 1GB
entriesAllowedOnHeap = 100000
offHeapFilePath =' > "$MINION_HOME/etc/org.opennms.core.ipc.sink.offheap.cfg"
----

A file will be created for each module and the configuration will be applied to each module individually. Therefore
setting a size of 1GB for example means that the maximum size for each module's file is 1GB not that the total for all
modules is 1GB.

The number of entries allowed to be queued on the heap can be controlled by setting the entriesAllowedOnHeap value.

Specify offHeapSize in KB, MB or GB. For ex: 1, 128MB, 65536KB. The size specified must be a power of 2. For example
128MB is a valid value but 140MB is not.

The offHeapSize can also be left empty or set to 0 to disable queueing off heap. In this case only heap memory will be
used for queueing.

The offHeapFilePath should be set to the path where the queue files should be stored and defaults to the Karaf data
directory if left empty.