// Allow GitHub image rendering
:imagesdir: ../../images

[[ga-minion-ttl]]

=== Time to Live (TTL) for RPCs

Remote procedure calls (RPCs) between _{opennms-product-name}_ and _Minion_ have certain time limit after which the requests are discarded.
We call this limit the time-to-live or TTL.
We make an effort to use logical values where possible and provide means to configure the TTLs for circumstances where the default values are not suitable.

In the context of pollerd, or collectd the RPCs for the respective service monitors and service collectors default to the `interval` at which these are scheduled.
This can be overwritten by adding a parameter named `ttl` to the corresponding service definitions.
The link:#ga-meta-data[meta-data] feature can be leverage to customize these values on a per node/interface/service basis.

For SNMP communication (i.e. provisiond) the TTL can also be specified in the SNMP agent configuration (snmp-config.xml).
The SNMP agent configuration will overrride any other TTL specified through parameters.
For example, if the SNMP collector is configured to use a TTL of 5 minutes, but the agent being queried has a TTL of 10 minutes, then the later will win.

If no TTL is found in any of the ways specified above, a default TTL of `20000` msec (20 sec) will be used.
The default TTL can also be configured.
When using the JMS-based RPC implementation, set value of the `org.opennms.jms.timeout` system property to the desired number of milliseconds.
When using the Kafka-based RPC implementation, set the value of the `org.opennms.core.ipc.rpc.kafka.ttl` system property to the desired number of milliseconds.

