org.opennms.netmgt.notifd.slack.webhookURL=${env:OPENNMS_NOTIFD_SLACK_WEBHOOKURL|Webhook URL}
org.opennms.netmgt.notifd.slack.channel=${env:OPENNMS_NOTIFD_SLACK_CHANNEL|Webhook}
org.opennms.netmgt.notifd.slack.username=${env:OPENNMS_NOTIFD_SLACK_USERNAME|none}
org.opennms.netmgt.notifd.slack.iconEmoji=${env:OPENNMS_NOTIFD_SLACK_ICONEMOJI|}
org.opennms.netmgt.notifd.slack.iconURL=${env:OPENNMS_NOTIFD_SLACK_ICONURL|}
org.opennms.netmgt.notifd.slack.useSystemProxy=${env:OPENNMS_NOTIFD_SLACK_USESYSTEMPROXY|true}
