org.opennms.newts.config.hostname=${env:CASSANDRA_HOSTNAME|hostname}
org.opennms.newts.config.keyspace=${env:CASSANDRA_KEYSPACE|newts}
org.opennms.newts.config.port=${env:CASSANDRA_PORT|9042}
org.opennms.newts.config.username=${env:CASSANDRA_USERNAME|cassandra}
org.opennms.newts.config.password=${env:CASSANDRA_PASSWORD|cassandra}
org.opennms.newts.config.datacenter=${env:CASSANDRA_DATACENTER|datacenter1}
