org.opennms.netmgt.notifd.mattermost.webhookURL=${env:OPENNMS_NOTIFD_MATTERMOST_WEBHOOKURL:-Webhook URL}
org.opennms.netmgt.notifd.mattermost.channel=${env:OPENNMS_NOTIFD_MATTERMOST_CHANNEL:-Webhook}
org.opennms.netmgt.notifd.mattermost.username=${env:OPENNMS_NOTIFD_MATTERMOST_USERNAME:-none}
org.opennms.netmgt.notifd.mattermost.iconEmoji=${env:OPENNMS_NOTIFD_MATTERMOST_ICONEMOJI:-}
org.opennms.netmgt.notifd.mattermost.iconURL=${env:OPENNMS_NOTIFD_MATTERMOST_ICONURL:-}
org.opennms.netmgt.notifd.mattermost.useSystemProxy=${env:OPENNMS_NOTIFD_MATTERMOST_USESYSTEMPROXY:-true}
