org.opennms.newts.config.hostname=${env:OPENNMS_CASSANDRA_HOSTNAME|hostname}
org.opennms.newts.config.keyspace=${env:OPENNMS_CASSANDRA_KEYSPACE|newts}
org.opennms.newts.config.port=${env:OPENNMS_CASSANDRA_PORT|9042}
org.opennms.newts.config.username=${env:OPENNMS_CASSANDRA_USERNAME|cassandra}
org.opennms.newts.config.password=${env:OPENNMS_CASSANDRA_PASSWORD|cassandra}
org.opennms.newts.config.datacenter=${env:OPENNMS_CASSANDRA_DATACENTER|datacenter1}
