org.opennms.rrd.storeByForeignSource=${env:OPENNMS_RRD_STORE_BY_FOREIGN_SOURCE|true}
org.opennms.timeseries.strategy=${env:OPENNMS_TIMESERIES_STRATEGY|rrd}
org.opennms.rrd.interfaceJar=${env:OPENNMS_RRD_INTERFACE_JAR|/usr/share/java/jrrd2.jar}
org.opennms.rrd.strategyClass=${env:OPENNMS_RRD_STRATEGY_CLASS|org.opennms.netmgt.rrd.rrdtool.MultithreadedJniRrdStrategy}
opennms.library.jrrd2=${env:OPENNMS_LIBRARY_JRRD2|/usr/lib/jni/libjrrd2.so}
