
= JDBCDetector

The JDBCDetector connects to a JDBC-enabled database and tries to fetch its catalog.
If the fetch is successful, it returns a `detected` value.
If it is not successful, it returns a `not detected` value.

== Detector facts

[options="autowidth"]
|===
| Implementation | `org.opennms.netmgt.provision.detector.jdbc.JdbcDetector`
|===

== Configuration and use

.Parameters for the JDBC detector
[options="header, autowidth"]
[cols="1,4,1"]
|===
| Parameter
| Description
| Default value

3+| *Required*

| dbDriver
| Database driver class name.
| org.postgresql.Driver

| password
| JDBC password.
| Empty String object.

| url
| JDBC URL to query.
Note: this URL can differ based on JDBC drivers, databases, and so on.
| `jdbc:postgresql://localhost/opennms`

| user
| JDBC username.
| postgres

3+| *Optional*

| ipMatch
| IP address to match.
|

| port
| Port to query.
| 3306

| retries
| Number of times detector should try to connect to database.
|

| serviceName
| Description
|

| timeout
| Time limit for trying to connect to database.
|
|===

== Database driver
The JDBCDetector is based on JDBC and requires a JDBC driver to communicate with any database.
Since {page-component-title} uses a PostgreSQL database, the PostgreSQL JDBC driver is available out of the box.
For all other database systems, you must provide a compatible JDBC driver as a JAR file.
To provide a JDBC driver, place the driver-jar in your `$\{OPENNMS_HOME}/lib` folder.

== Examples

[source,xml]
----
<detector name="MySQL-JDBC" class="org.opennms.netmgt.provision.detector.jdbc.JdbcDetector">
    <parameter key="password" value="borkborkbork"/>
    <parameter key="user" value="opennms"/>
    <parameter key="dbDriver" value="com.mysql.jdbc.Driver"/>
    <parameter key="url" value="jdbc:mysql://OPENNMS_JDBC_HOSTNAME:3306/test"/>
    <parameter key="timeout" value="5000"/>
</detector>
----

This example assumes you have loaded the MySQL driver file.