
[[housekeeping]]
= Housekeeping Tasks

There are a number of housekeeping tasks you may want to do regularly to ensure optimum system performance.
We also recommend you complete some of these housekeeping tasks before upgrading {page-component-title}.

== Prior to upgrading

[[prune-events]]
=== Prune unneeded events
Use vacuumd or cron to regularly prune unneeded events.
This helps to clean up your events table, and reduces the amount of data in your backups.
We also recommend doing this before you begin the {page-component-title} upgrade process.

For example, run the following to delete events older than six weeks that have no associated outages:

[source, sql]
----
--# this deletes any events that are not associated with outages
DELETE FROM events WHERE NOT EXISTS
(SELECT svclosteventid FROM outages WHERE svclosteventid = events.eventid
UNION
SELECT svcregainedeventid FROM outages WHERE svcregainedeventid = events.eventid
UNION
SELECT eventid FROM notifications WHERE eventid = events.eventid)
AND eventtime < now() - interval '6 weeks';
----

== After Upgrading

[[delete-cache-folder]]
=== Delete cache folder
Run the Fix Karaf script to delete cached items so that your system is cleaned up.
We recommend doing this after an upgrade.
This script tries to fix Karaf configuration problems by pruning `opt/opennms/data` and restoring all Karaf-related configuration files to a pristine state.

NOTE: Back up `/opt/opennms/etc` before running the script.

[source, console]
----
/opt/opennms/bin/fix-karaf-setup.sh
----

[[ga-data-collection]]
== Data collection

When enabled, the `Data Choices` module collects anonymous use statistics.
It publishes them on system startup and every 24 hours after.
Usage statistics include the following data points:

* System ID (a randomly generated, universally unique identifier (UUID))
* {page-component-title} release
* {page-component-title} version
* OS architecture
* OS name
* OS version
* Number of available processors (CPU)
* Amount of free physical memory
* Amount of total physical memory
* Number of alarms in the `alarms` table
* Number of situations in the `alarms` table
* Number of events in the `events` table
* Number of IP interfaces in the `ipinterface` table
* Number of nodes in the `node` table
* Number of nodes, grouped by System OID
* Number of locations
* Number of Minions
* Number of provisiond requisitions by scheme
* Provisiond thread pool sizes
* List of enabled/disabled services
* List of installed features in Karaf
* Global notification enablement status
* Destination path count
* On-call role count
* Relational Database Management System (RDBMS) name
* RDBMS version
* Pollerd tasks completed
* Event logs processed count
* Core Flows persisted count
* Core Newts samples inserted count
* Core Queued updates completed
* Number of Virtual Appliance, Appliance Mini, and Appliance 1U connected to the system

[[disable-data-collection]]
=== Enable or disable usage statistics collection

Admin users can enable or disable usage statistics collection at any time by logging into the UI, clicking the menu:gear icon[Additional Tools, Data Choices] and selecting *Opt-in* or *Opt-out*.

