
= Beyond the Quick Start Guide

After you have finished following the steps in the Quick Start guide, your {page-component-title} instance should be set up and monitoring your network.
You should now be able to do the following:

* Create and configure new user accounts.
* Provision your network inventory.
* Customize performance data collection settings.
* Create and manage thresholds.
* Explore service availability stats.
* Configure and manage notifications.
* Visualize your data.

Of course, there is still much more that you can do to customize {page-component-title} to suit your needs.
You can explore the Deep Dive section to learn more.

The following sections include suggested topics that supplement the Quick Start guide.

== User management

* <<deep-dive/user-management/user-config.adoc, Create users>> and <<deep-dive/user-management/security-roles.adoc, assign permissions>>.
* <<deep-dive/user-management/user-groups.adoc, Create and maintain user groups>>.
* <<deep-dive/user-management/user-oncall.adoc, Define on-call roles and schedules>>.

== Provision inventory

We covered initial inventory provisioning in <<quick-start/inventory.adoc, Step 3: Provision Inventory>>.
As your monitored network grows, you may need to provision new nodes and iterate on the work done in the Quick Start guide.
These topics serve as starting points for more information:

* <<deep-dive/provisioning/auto-discovery.adoc, Set up auto discovery>>.
* <<deep-dive/provisioning/directed-discovery.adoc, Set up directed discovery>>.
* <<deep-dive/provisioning/foreign-source.adoc, Define a foreign source>>.

== Customize {page-component-title} home page

We covered visualizations in <<quick-start/visualize-data.adoc, Step 9: Visualize Data>>, but you can do much more to display your data--including customizing your {page-component-title} home page.
For more information, see <<deep-dive/grafana-dashboard-box.adoc, Grafana Dashboard Box>> in the Deep Dive section.

== Explore the Deep Dive section

To learn more about any of the topics covered in the Quick Start guide, you can explore their corresponding docs in the Deep Dive section.
Deep Dive topics are referenced in each of the Quick Start pages; they can provide a starting point.
