
= Quick Start

This Quick Start guide assumes that you have already completed the xref:deployment:core/introduction.adoc[deployment steps], have xref:deployment:core/getting-started.adoc[installed a {page-component-title} instance], and that you are able to connect to the web UI at `\http://<ip-or-fqdn-of-your-server>:8980/opennms`.

== Introduction

Now that you have installed and started {page-component-title}, you should consider your monitoring goals.
Knowing what kind of information you want to collect will help focus your setup process.

{page-component-title} provides robust functionality out of the box, including (but not limited to) the following:

* Self-monitoring via JMX data collection.
* Detection and monitoring of more than twelve services, including DNS, HTTP/S, and more.
* Reception and recognition of SNMP traps from over 200 MIBs.
* Collection of SNMP performance data from over 200 families of SNMP-capable devices.
* Collection of standard MIB-2 stats from any SNMP-capable device.

== Quick Start contents

This guide covers the following tasks:

* xref:operation:quick-start/users.adoc#ga-data-choices[First-time login and usage data permissions].
* xref:operation:quick-start/users.adoc#ga-admin-user-setup[Set up admin user].
* xref:operation:quick-start/users.adoc#create-user[Create a new user].
* xref:operation:quick-start/notifications.adoc[Turn on default notifications].
* xref:operation:quick-start/inventory.adoc[Provision inventory].
* xref:operation:quick-start/performance-data.adoc[Set up performance data collection].
* xref:operation:quick-start/thresholding.adoc[Set up a threshold].
* xref:operation:quick-start/baseline.adoc[Establish a baseline].
* xref:operation:quick-start/service-assurance.adoc[Determine service availability].
* xref:operation:quick-start/notification-config.adoc[Configure notifications].
* Visualize your data.

NOTE: Unless otherwise stated, the procedures in this guide require you to be logged in to the OpenNMS web UI as a user with admin privileges.
