
= Step 8: Configure Notifications

This section describes how to configure and customize your {page-component-title} notifications.

NOTE: This step is separate from xref:operation:quick-start/notifications.adoc[setting up default notifications].
We assume that you have followed the previous steps and are ready to proceed to more in-depth work with notifications.

== Configuration and customization

Now that you have xref:operation:quick-start/baseline.adoc[established your environment's baseline], it's time to take your notes and configure your custom notifications.
Establishing notifications that are tailored for your environment and monitoring requirements lets the right people see and respond to the right issues in a timely manner.

Here, we will describe how to configure event notifications and path outages.
Event notifications can be configured to provide coverage of specific unique event identifiers (UEIs), allowing for granular control of incoming information.
Path outages prevent the generation of excess notifications by identifying network paths where failures may cause multiple nodes to appear offline.

You can define multiple notifications for the same UEI to use different destination paths.
By default, {page-component-title} uses the destination path of all notifications matching the event's UEI.
You can configure notifd to process only the destination path of the first matching notification by editing `$\{OPENNMS_HOME}/etc/notifd-configuration.xml` and setting `match-all="false"` in the top-level `notifd-configuration` element.

NOTE: Changes to `$\{OPENNMS_HOME}/etc/destinationPaths.xml` happen immediately, with no need to restart {page-component-title}.

== Configure event notifications

An event notification defines a destination path and message template for a specific unique event identifier (UEI).
It is possible to define multiple notifications for the same UEI to use different filters, destination paths, and message templates.
Follow these steps to configure event notifications:

. Click the *Gear* symbol in the top-right of the screen.
. Under Event Management, click menu:Configure Notifications[Configure Event Notifications].
A list of events that are configured for notifications is displayed.
. Click *Add New Event Notification*, choose the UEI that will trigger a notification, and click *Next*.
. (Optional) Build a rule to match a subset of IP addresses or services, and click menu:Validate Rule Results[Next] or *Skip Results Validation*.
If you do not build a rule, notifications will be generated for all monitored IP addresses.
. In the *Choose Path* screen, specify information to include in the notification, including the destination path, subject (for email messages), body text, and so on.
. Click *Finish*.

NOTE: Event notification configuration is stored in `$\{OPENNMS_HOME}/etc/notifications.xml`.
Changes to this file happen immediately, with no need to restart {page-component-title}.

=== Filter rules

A filter rule lets you define which notifications to send or save.
Strict rules are always evaluated, and if there is no node or interface associated with the event, the notification will not be saved.
Filter rules work alongside your event notification configuration to enable better, more fine-tuned control over the notifications that you receive.

By default, the filter rule configured in `$\{OPENNMS_HOME}/etc/notifications.xml` (for example, `<rule>IPADDR != '0.0.0.0'</rule>`) does not have the `strict` flag enabled.
That means if there is an event that is not associated with a node or interface (and therefore no `IPADDR` value), it will bypass validation and the notification would be processed.

A strict rule (for example, `<rule strict="true">IPADDR != '0.0.0.0'</rule>`) will always be evaluated, and if there is no node or interface associated with the event, the notification will not be saved.

== Configure path outages

Configuring a path outage lets you suppress notifications for nodes that appear to be down due to a failure in the network path between the nodes and {page-component-title}.
For example, if a WAN link fails, all nodes at the remote site served by the WAN link will appear to be down.
Because you get a notification that the router on the far end of the WAN link is not responding, you don't need notifications for all devices that sit behind that router.

You can configure a path outage for an individual node by setting a parent on the node in a requisition:

. Click the *Gear* symbol in the top-right of the screen.
. Under Event Management, click menu:Configure Notifications[Configure Path Outages].
. Enter the critical path IP address, select a critical path service, and click *Validate Rule Results*.
. Click *Next* to save the configuration.

== Beyond Quick Start

For more information on notifications, refer to xref:operation:deep-dive/notifications/introduction.adoc[Notifications] in the Deep Dive section.
Topics include:

* xref:operation:deep-dive/notifications/concepts.adoc[Concepts (events, UEIs, on-call roles, and so on)]
* xref:operation:deep-dive/notifications/commands.adoc[Notification commands]


For example, defining a five minute delay will mean that, when a notification is generated, the first member of the group will be notified immediately.
Subsequent members will then be notified in five-minute increments, from the top of the list of group members to the bottom.