
= Step 8: Configure Notifications

This section describes how to configure and customize your {page-component-title} notifications.

NOTE: This step is separate from xref:operation:quick-start/notifications.adoc[setting up default notifications].
We assume that you have followed the previous steps and are ready to proceed to more in-depth work with notifications.

== Configuration and customization

Beyond setting up default notifications in {page-component-title}, establishing notifications that are tailored for your environment will help maintain it.

You can configure event notifications to provide UEI-specific coverage.
You can also configure path outages for instances where a network path failure may occur.
By default, this would trigger as many notifications as nodes served by that network path; path outages prevent this by generating only one notification.

== Examples

=== Configure event notifications

An event notification defines a destination path and message template for a specific event UEI.
It is possible to define multiple notifications for the same UEI to utilize different filters, destination paths, and message templates.
Configure event notifications by following these steps:

. Click the *Gear* symbol in the top-right of the screen.
. Under Event Management, click menu:Configure Notifications[Configure Event Notifications].
A list of events that are configured for notifications is displayed.
. Click *Add New Event Notification*, choose the UEI that will trigger a notification, and click *Next*.
** (Optional) Build a rule to match a subset of IP addresses or services, and click menu:Validate Rule Results[Next] or *Skip Results Validation*.
. In the *Choose Path* screen, specify information to be included in the notification, including the destination path, subject (for email messages), body text, and so on.
. Click *Finish*.

NOTE: Event notification configuration is stored in `$\{OPENNMS_HOME}/etc/notifications.xml`.
Changes to this file happen immediately, with no need to restart {page-component-title}.

==== Filter rules

The filter rule configured in `$\{OPENNMS_HOME}/etc/notifications.xml` (for example, `<rule>IPADDR != '0.0.0.0'</rule>`) is not strict by default.
That means if there is an event that is not associated with a node or interface, it will not validate the rule and, by default, the notification would be saved.

A strict rule (for example, `<rule strict="true">IPADDR != '0.0.0.0'</rule>`) will always be evaluated, and if there is no node or interface associated with the event, the notification will not be saved.

=== Configure path outages

Configuring a path outage lets you suppress notifications for nodes that appear to be down due to a failure in the network path between the nodes and {page-component-title}.
For example, if a WAN link fails, all nodes at the remote site served by the WAN link will appear to be down.
Because you get a notification that the router on the far end of the WAN link is not responding, you don't need notifications for all devices that sit behind that router.

You can configure a path outage for an individual node, or create a rule-based configuration for a group of nodes:

. Click the *Gear* symbol in the top-right of the screen.
. Under Event Management, click menu:Configure Notifications[Configure Path Outages].
. Enter the critical path IP address, select a critical path service, and click *Validate Rule Results*.
. Click *Next* to save the configuration.

== Beyond Quick Start

For more information on notifications, refer to xref:operation:deep-dive/notifications/introduction.adoc[Notifications] in the Deep Dive section.
Topics include:

* xref:operation:deep-dive/notifications/concepts.adoc[Concepts (events, UEIs, on-call roles, and so on)]
* xref:operation:deep-dive/notifications/commands.adoc[Notification commands]
