
= Step 4: Set Up Performance Data Collection
:description: Step 4 of {page-component-title} setup: set up performance data collection and SNMP collectors and data collection groups.

This section describes performance data collection in {page-component-title}.

{page-component-title} collects performance data using xref:reference:daemons/daemon-config-files/collectd.adoc[collectd], which is enabled by default.
Collectd schedules data collection processes on network entities using management agents and protocol-specific collectors.

NOTE: In this documentation, any reference to collectd refers to the {page-component-title} collect daemon, not the independent open source project of the same name.

Data collection for SNMP and OpenNMS-JVM is enabled by default, allowing {page-component-title} to monitor itself through JMX.

For additional information, including collector configuration, see xref:deep-dive/performance-data-collection/introduction.adoc[Performance Management] in the Deep Dive section.

== Before you begin

{page-component-title} data collection for SNMP works out of the box, provided your SNMP credentials are configured correctly.

The default value for the community string is `public`.
We recommend that you do not use the default community string in production.
See <<quick-start/inventory.adoc#provision-snmp-configuration, Configure SNMP for provisioning>> for steps to change the community string.

Performance data collection on other protocols (HTTPS, JMX, and so on) requires additional configuration.
You may also want to change how collectd works--when, how, and what data it collects.
For more information, see xref:reference:performance-data-collection/introduction.adoc[Collectors] in the Reference section.

== Default performance data collection

By default, {page-component-title} collects a variety of information from monitored nodes that support SNMP.
This information includes widely implemented metrics that are standard for MIB-2 sources (for example, TCP group data and network interface counters).
SNMP data collection definitions are also included for devices from a range of popular vendors (for example, if you add a Cisco router to your instance, {page-component-title} will automatically collect Cisco-specific metrics).
The metrics included in these collections vary by vendor.

== SNMP collections and data collection groups

Data collection groups collect sets of performance data measurements for persisting, indexing, and visualizing the data in the UI.
Individual data collection groups are stored in unique `.xml` files, which define associated resource types, MIB groups, and system definitions.
System definitions bring together MIB groups with full or partial SNMP `sysObjectID` values, enabling automatic collection of appropriate metrics from devices for which they exist.
