
= Step 5: Set up a Threshold

A threshold lets you define limits against network performance metrics (CPU load, bandwidth, disk space, and so on) of a managed entity to trigger an event when a data source value goes above or below the specified limit:

* High - equals or exceeds the threshold value, and re-arms when it equals or drops below the re-arm value (for example, bandwidth use exceeds the specified amount).
* Low - equals or drops below the threshold value and re-arms when it equals or comes back up above the re-arm value (for example, available disk space falls under the specified value).
* Absolute change - changes by the specified amount (for example, on a fiber-optic link, a change in loss of anything greater than 3 dB is a problem regardless of what the original or final value is).
* Relative change - changes by percent (for example, available disk space changes more than 5% from the last poll).

These thresholds can be *basic* (tested against a single value) or an *expression* (evaluated against multiple values in an expression).

== Create a basic threshold

This Quick Start describes how to create a basic threshold for a single, system-wide variable: the number of logged-in users.
Our threshold tells {page-component-title} to create an event when the number of logged-in users on the device exceeds two, and re-arm when it falls below two.

Before creating a threshold, you need to make sure you are collecting the metric against which you want to threshold.

[[metric-collect]]
=== Determine that you are collecting the metric
In this case, we have chosen a metric (number of logged-in users) that is collected by default.
We are also using data collected via SNMP. (For information on other collectors, see <<deep-dive/performance-data-collection/collectors.adoc#collectors-overview,Collectors>>.)

. In the {page-component-title} UI, choose *Reports>Resource Graphs*.
. Select one of the listed resources.
. Under *SNMP Node Data*, select *Node-level Performance Data* and choose *Graph Selection*.
. Scroll to find the *Number of Users* graph.
.. You can click the binoculars icon to display only this graph.

[[threshold-create]]
=== Create threshold

. Click the gear icon in the top-right.
. Under *Performance Measurement*, choose *Configure Thresholds*.
.. A screen with a list of preconfigured threshold groups appears.
We will work with *netsnmp*.
For information on how to create a threshold group, see xref:deep-dive/thresholds/thresh-group.adoc#threshold-group[Create a Threshold Group].
. Click *Edit* beside the *netsnmp* group.
. Click *Create New Threshold* at the bottom of the *Basic Thresholds* area of the screen.
. Set the following information and click *Save*:

[options="header"]
[cols="1,3,2"]
|===

| Field
| Description
| Input value

| Type
| Triggers an event when the data source value equals or exceeds the threshold value, and re-arms when it equals or drops below the re-arm value.
| high

| Datasource
| Name of the data source you want to threshold against.
For this tutorial, we have provided the data source for logged-in users.
For information on how to determine a metric's data source, see xref:operation:deep-dive/thresholds/datasource.adoc#datasource-determine[Determine the data source].
| hrSystemNumUsers


| Datasource label
| Optional text label.
Not required for this tutorial.
| leave blank

| Value
| The value above which we want to trigger an event.
In this case, we want to trigger an event when the number of logged-in users exceeds two.
| 2

| Re-arm
| The value below which we want the system to re-arm.
In this case, once the number of logged-in users falls below two.
| 2

| Trigger| The number of consecutive times the threshold value can occur before the system triggers an event.
Since our default polling period is 5 minutes, a value of 3 means {page-component-title} would create a threshold event if there are more than 2 users for 15 minutes.
| 3

| Description
| Optional text to describe your threshold.
| leave blank

| Triggered UEI
| A custom unique event identifier (UEI) sent into the events system when the threshold is triggered.
A custom UEI for each threshold makes it easier to xref:deep-dive/notifications/introduction.adoc#ga-notifications-introduction[create notifications].
If left blank, it defaults to the standard thresholds UEIs.
| leave blank

| Re-armed UEI
| A custom unique event identifier (UEI) sent into the events system when the threshold is re-armed.
| leave blank

|===

[[threshold-test]]
=== Test the threshold

To test the threshold we just created, log a second person into the node you are monitoring.
Navigate to the *Events* page.
You should see an event that indicates your threshold triggered when more than one user logged in.

Log out the second user.
The *Events* page should indicate that the system has re-armed.

[[thresh-cpu]]
== Create an expression-based threshold

This procedure describes how to create an expression-based threshold for CPU use.
It will create an event when the five-minute CPU load average metric reaches or goes above 70% for two consecutive measurement intervals.
Expression-based thresholds are useful when you need to threshold on a percentage, not the actual value of the data collected.

NOTE: Expression-based thresholds work only if the data sources in question are in the same directory.

. Click the gear icon in the top-right.
. Under *Performance Measurement*, choose *Configure Thresholds*.
. Click *Edit* beside the *netsnmp* group.
. Click *Create New Expression-based Threshold*.
. Fill in the following information:

+

[options="header"]
[cols="1,3,3"]
|===

| Field
| Description
| Default

| Type
| Triggers an event when the data source value equals or exceeds the threshold value, and re-arms when it equals or drops below the re-arm value.
| high

| Expression
| Divides the five-minute CPU load average by 100 (to obtain the effective load average\*), which is then divided by the number of CPUs.
This value is then multiplied by 100 to provide a percentage.

(* SNMP does not report in decimals, which is why the expression divides the loadavg5 by 100.)
| ((loadavg5 / 100) / CpuNumCpus) * 100

| Datasource type
| The type of data source from which you are collecting data.
| node

| Datasource label
| Optional text label.
Not required for this tutorial.
| leave blank

| Value
| Trigger an event when the five-minute CPU load average goes above 70%.
| 70

| Re-arm
| Re-arm the system when the five-minute CPU load average drops below 50%.
| 50

| Trigger
| The number of consecutive times the threshold value can occur before the system triggers an event.
In this case, when the five-minute CPU load average goes above 70% for two consecutive polling periods.
| 2

| Description
| Optional text to describe your threshold.
| Trigger an alert when the five-minute CPU load average metric reaches or goes above 70% for two consecutive measurement intervals.

| Triggered UEI
| A custom unique event identifier (UEI) sent into the events system when the threshold is triggered.
A custom UEI for each threshold makes it easier to xref:deep-dive/notifications/introduction.adoc#ga-notifications-introduction[create notifications].
If left blank, it defaults to the standard thresholds UEIs.
| leave blank

| Re-armed UEI
| A custom unique event identifier (UEI) sent into the events system when the threshold is re-armed.
| leave blank

|===

. Click *Save*.

== Beyond Quick Start

Refer to <<deep-dive/thresholds/thresholding.adoc, Thresholding>> in the Deep Dive section for more information on thresholding, including the following:

* <<deep-dive/thresholds/metadata.adoc, Using metadata in a threshold>>.
* <<deep-dive/thresholds/thresh-group.adoc, Creating a threshold group>>.
* <<deep-dive/thresholds/troubleshoot.adocTroubleshooting and managing thresholds>>.



