.Install gnupg and add OpenNMS repository GPG key
[source, console]
----
sudo apt -y install gnupg
sudo apt-key adv --fetch-keys https://debian.opennms.org/OPENNMS-GPG-KEY
----

.Add apt repository
[source, console]
----
sudo apt -y install software-properties-common
sudo add-apt-repository -s 'deb https://debian.opennms.org stable main'
sudo apt update
----

NOTE: You can safely ignore the message with conflicting distributions stable but got opennms-xx.

.Install OpenNMS {page-component-title} with built-in dependencies (optional)
[source, console]
----
sudo apt -y install opennms
----

TIP: This is optional. If you want time series trending and forecast functions you must install the link:https://www.r-project.org/[R project] packages.
     The additional download size for packages is ~134 MB.

.Install R package for trending and forcasting
[source, console]
----
sudo apt -y install r-recommended
----

TIP: We recommend that you disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades while it is running.
     {page-component-title} requires some manual steps upon upgrade configuration files or migrate database schemas to a new version.
     For this reason, we recommend that you exclude the {page-component-title} packages from update except when you plan perform an upgrade.

[source, console]
----
sudo apt-mark hold libopennms-java \
              libopennmsdeps-java \
              opennms-common \
              opennms-db
----

.Verify directory structure with the tree command
[source, console]
----
sudo apt -y install tree
tree /usr/share/opennms -L 1
----

.Directory structure after successful installation
[source, output]
----
/usr/share/opennms
├── bin
├── data
├── deploy
├── etc -> /etc/opennms
├── jetty-webapps
├── lib -> ../java/opennms
├── logs -> /var/log/opennms
├── share -> /var/lib/opennms
└── system
----
