[[adapter-ddns]]
= Dynamic DNS
:description: Learn how the DDNS adapter uses the dynamic DNS protocol to send updated DNS records to your DNS system when OpenNMS {page-component-title} provisions nodes.

The DDNS adapter uses the dynamic DNS protocol to send updated A/AAAA DNS records to your DNS system as nodes are provisioned into {page-component-title}.

For every IP address found, a corresponding forward DNS zone must exist on your DNS server.

== Installation

To use this feature you have to install the DNS provisioning plugin from the repository.

* For RPM-based distributions:
** `yum install {package-prefix}-plugin-provisioning-dns`
* For Debian-based distributions:
** `apt-get install {package-prefix}-plugin-provisioning-dns`

== Configuration

To configure this adapter, create a .properties file in  the `$\{OPENNMS_HOME}/etc/opennms.properties.d/` folder and set the `importer.adapter.dns.server property`:

[source, properties]
----
importer.adapter.dns.server=192.168.1.1 <1>
----
<1> Replace with the IP address of your DNS server to receive dynamic DNS updates.

NOTE: This DNS server setting may be shared with the xref:provisioning/adapters/rdns.adoc[reverse DNS adapter] if you have them both installed.
