/*******************************************************************************
 * This file is part of OpenNMS(R).
 * 
 * Copyright (C) 2017-2017 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2017 The OpenNMS Group, Inc.
 * 
 * OpenNMS(R) is a registered trademark of The OpenNMS Group, Inc.
 * 
 * OpenNMS(R) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 * 
 * OpenNMS(R) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with OpenNMS(R).  If not, see:
 *     http://www.gnu.org/licenses/
 * 
 * For more information contact:
 *     OpenNMS(R) Licensing <license@opennms.org>
 *     http://www.opennms.org/
 *     http://www.opennms.com/
 *******************************************************************************/

package org.opennms.netmgt.config.snmpinterfacepoller;


import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Critical service. Defining a critical service greatly
 *  reduces the traffic generated by the snmp poller when a service is DOWN.
 *  The snmp poller stop polling if one of the critical service is down on the 
 *  SNMP primary node interface.
 * 
 * @version $Revision$ $Date$
 */
@XmlRootElement(name = "critical-service")
@XmlAccessorType(XmlAccessType.FIELD)

@SuppressWarnings("all") public class CriticalService implements java.io.Serializable {


    /**
     * Name of the critical service (typically,
     *  "SNMP")
     */
    @XmlAttribute(name = "name", required = true)
    private String name;

    public CriticalService() {
    }

    /**
     * Overrides the Object.equals method.
     * 
     * @param obj
     * @return true if the objects are equal.
     */
    @Override
    public boolean equals(final Object obj) {
        if ( this == obj ) {
            return true;
        }
        
        if (obj instanceof CriticalService) {
            CriticalService temp = (CriticalService)obj;
            boolean equals = Objects.equals(temp.name, name);
            return equals;
        }
        return false;
    }

    /**
     * Returns the value of field 'name'. The field 'name' has the following
     * description: Name of the critical service (typically,
     *  "SNMP")
     * 
     * @return the value of field 'Name'.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Method hashCode.
     * 
     * @return a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int hash = Objects.hash(
            name);
        return hash;
    }

    /**
     * Sets the value of field 'name'. The field 'name' has the following
     * description: Name of the critical service (typically,
     *  "SNMP")
     * 
     * @param name the value of field 'name'.
     */
    public void setName(final String name) {
        this.name = name;
    }

}
