
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-oracle-java-rhel]]
==== Oracle Java SE Development Kit 8

Installing the _Oracle Java SE Development Kit 8_ (_JDK8_) requires installation packages provided by _Oracle_.
The following tools should be installed to follow this installation manual:

* Download files and tools with `wget` and `curl`
* Extract archives with `tar`
* Text manipulation with `sed`
* Editing text, e.g. `vi`, `nano` or `joe`
* Internet access

WARNING: By downloading the _Oracle Java SE Development Kit 8_ RPM installer, you will accept the license agreement
from _Oracle_ which can be found on the link:https://www.java.com/en/download/faq/distribution.xml[Java distribution] web site.

WARNING: Installing the _Java Runtime Environment (JRE)_ is not sufficient.
         The development kit is often named _openjdk-devel_ or _openjdk-jdk_.
         With a _JRE_ installed, _{opennms-product-name}_ will not start and throws a `java.lang.ClassNotFoundException: com.sun.tools.attach.AttachNotSupportedException`.
         For more details see link:https://issues.opennms.org/browse/NMS-9327[NMS-9327].// include::text/java/rhel.adoc

This section describes how to install _Oracle Java SE Development Kit 8_ on a _RPM-based_ system like _Red Hat Enterprise Linux 7_ or _CentOS 7.1_.

.Download Oracle JDK RPM
[source, bash]
----
wget --no-cookies \
     --no-check-certificate \
     --header \
              "Cookie: oraclelicense=accept-securebackup-cookie" \
              "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.rpm" \
     -O /tmp/jdk-8-linux-x64.rpm
----

.Install Oracle JDK RPM file
[source, bash]
----
yum install /tmp/jdk-8-linux-x64.rpm
----
