mvn:org.apache.zookeeper/zookeeper/${zookeeperVersion}
mvn:org.ops4j.pax.logging/pax-logging-api/${paxLoggingVersion};range=[1.0,2.0)
mvn:org.ops4j.pax.logging/pax-logging-log4j2/${paxLoggingVersion};range=[1.0,2.0)
mvn:org.ops4j.pax.logging/pax-logging-logback/${paxLoggingVersion};range=[1.0,2.0)
mvn:org.apache.commons/commons-collections4/${commonsCollections4Version}

mvn:io.netty/netty-resolver/${netty4Version}
mvn:io.netty/netty-common/${netty4Version}
mvn:io.netty/netty-buffer/${netty4Version}
mvn:io.netty/netty-transport/${netty4Version}
mvn:io.netty/netty-handler/${netty4Version}
mvn:io.netty/netty-transport-classes-epoll/${netty4Version}
mvn:io.netty/netty-transport-native-epoll/${netty4Version}
mvn:io.netty/netty-transport-native-kqueue/${netty4Version}
mvn:io.netty/netty-transport-native-unix-common/${netty4Version}
mvn:io.netty/netty-codec/${netty4Version}
mvn:io.netty/netty-codec-http/${netty4Version}