
[[threshold-group]]
= Create a Threshold Group
:description: How to create a threshold group in {page-component-title} to associate a set of thresholds to a service. Includes list of default threshold groups.

A threshold group associates a set of thresholds to a service (for example, thresholds that apply to all Cisco devices).
{page-component-title} includes the following preconfigured, editable threshold groups:

* mib2
* cisco
* hrstorage
* netsnmp
* juniper-srx
* netsnmp-memory-linux
* netsnmp-memory-nonlinux
* opennms-jvm-jvx

Threshold groups are stored in the database and are created and edited through the web UI.
Editing `$\{OPENNMS_HOME}/etc/thresholds.xml` has no effect: the file's contents are migrated into the database during the upgrade and the file is no longer read.
You can also manage groups over the xref:development:rest/thresholds-rest-api.adoc[Thresholds REST API].

This procedure creates a threshold group called "demo_group":

. Log in to the web UI.
. Click menu:Administration[Configure Thresholds] in the side menu.
. Or, click menu:Administration[Configure OpenNMS] in the side menu, then click menu:Performance Measurement[Configure Thresholds].
. On the *Groups* tab, click *New group*.
. Enter `demo_group` as the name and `/opt/opennms/share/rrd/snmp/` as the RRD repository, then click *Save*.
+
The group opens, ready for you to add thresholds.

A group with an expression threshold corresponds to the following configuration:

[source, xml]
-----
<group name="demo_group" rrdRepository="/opt/opennms/share/rrd/snmp/"> <1>
  <expression type="high" ds-type="hrStorageIndex" value="90.0"
    rearm="75.0" trigger="2" ds-label="hrStorageDescr"
    filterOperator="or" expression="hrStorageUsed / hrStorageSize * 100.0">
    <resource-filter field="hrStorageType">^\.1\.3\.6\.1\.2\.1\.25\.2\.1\.4$</resource-filter> <2>
  </expression>
</group>
-----
<1> The name of the group and the directory of the stored data.
<2> The details of the threshold, including type, data source type, threshold value, re-arm value, and so on.
