reports=onms.linkd.threadpool, \
onms.linkd.completedRatio, \
onms.linkd.taskqueue


###
## OpenNMS EnhancedLinkd
###

report.onms.linkd.threadpool.name=OpenNMS EnhancedLinkd ThreadPool
report.onms.linkd.threadpool.columns=ONMSELDThrdAct,ONMSELDPoolThrd,ONMSELDPoolCore
report.onms.linkd.threadpool.type=interfacesSnmp
report.onms.linkd.threadpool.command=--title="OpenNMS EnhancedLinkd ThreadPool" \
 --vertical-label="Threads" \
 DEF:active={rrd1}:ONMSELDThrdAct:AVERAGE \
 DEF:currentPool={rrd2}:ONMSELDPoolThrd:AVERAGE \
 DEF:corePool={rrd3}:ONMSELDPoolCore:AVERAGE \
 AREA:currentPool#A6CEE3 \
 LINE2:currentPool#89B2C6:"Current Pool     " \
 GPRINT:currentPool:AVERAGE:"Avg\\: %5.0lf\" \
 GPRINT:currentPool:MIN:"Min\\: %5.0lf" \
 GPRINT:currentPool:MAX:"Max\\: %5.0lf\\n" \
 LINE2:corePool#1F78B4:"Core Pool Size   " \
 GPRINT:corePool:AVERAGE:"Avg\\: %5.0lf\" \
 GPRINT:corePool:MIN:"Min\\: %5.0lf" \
 GPRINT:corePool:MAX:"Max\\: %5.0lf\\n" \
 AREA:active#B2DF8A \
 LINE2:active#8CB569:"Active Threads  " \
 GPRINT:active:AVERAGE:" Avg\\: %5.0lf" \
 GPRINT:active:MIN:"Min\\: %5.0lf" \
 GPRINT:active:MAX:"Max\\: %5.0lf\\n"

report.onms.linkd.completedRatio.name=OpenNMS EnhancedLinkd Task Completion Ratio
report.onms.linkd.completedRatio.columns=ONMSELDTasksTot,ONMSELDTasksCpt
report.onms.linkd.completedRatio.type=interfaceSnmp
report.onms.linkd.completedRatio.command=--title="OpenNMS EnhancedLinkd Task Completion" \
 --vertical-label="Percent" \
 --lower-limit=0 --upper-limit=100 --units-exponent=0 \
 DEF:total={rrd1}:ONMSELDTasksTot:AVERAGE \
 DEF:completed={rrd2}:ONMSELDTasksCpt:AVERAGE \
 CDEF:percent=completed,total,/,100,* \
 AREA:percent#F5CD9A \
 LINE2:percent#F19A2A:"Completion Ratio" \
 GPRINT:percent:AVERAGE:" Avg  \\: %8.2lf %s" \
 GPRINT:percent:MIN:"Min  \\: %8.2lf %s" \
 GPRINT:percent:MAX:"Max  \\: %8.2lf %s\\n"

report.onms.linkd.taskqueue.name=OpenNMS EnhancedLinkd Task Queue
report.onms.linkd.taskqueue.columns=ONMSELDTskQPCnt
report.onms.linkd.taskqueue.type=interfaceSnmp
report.onms.linkd.taskqueue.command=--title="OpenNMS EnhancedLinkd Task Queue" \
 --vertical-label="Tasks" \
 DEF:active={rrd1}:ONMSELDTskQPCnt:AVERAGE \
 LINE1:active#0000ff:"Pending Tasks" \
 GPRINT:active:AVERAGE:" Avg  \\: %8.2lf %s" \
 GPRINT:active:MIN:"Min  \\: %8.2lf %s" \
 GPRINT:active:MAX:"Max  \\: %8.2lf %s\\n"
