#
# PostgreSQL Backend Activity Reports
#

reports=pgsql.backendstates, pgsql.autovacuum

report.pgsql.backendstates.name=PostgreSQL Backend States
report.pgsql.backendstates.type=nodeSnmp
report.pgsql.backendstates.columns=pg_sa_active,pg_sa_idle,pg_sa_idle_txn,pg_sa_idle_txn_abrt,pg_sa_fastpath,pg_sa_disabled,pg_sa_starting,pg_sa_masked
report.pgsql.backendstates.command=--title="PostgreSQL Backend States" \
 --vertical-label="backends" \
 DEF:active={rrd1}:pg_sa_active:AVERAGE \
 DEF:idle={rrd2}:pg_sa_idle:AVERAGE \
 DEF:idletxn={rrd3}:pg_sa_idle_txn:AVERAGE \
 DEF:idletxnabrt={rrd4}:pg_sa_idle_txn_abrt:AVERAGE \
 DEF:fastpath={rrd5}:pg_sa_fastpath:AVERAGE \
 DEF:disabled={rrd6}:pg_sa_disabled:AVERAGE \
 DEF:starting={rrd7}:pg_sa_starting:AVERAGE \
 DEF:masked={rrd8}:pg_sa_masked:AVERAGE \
 AREA:active#7EE600:"Active                 " \
 GPRINT:active:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:active:MIN:"Min\\: %8.2lf %s" \
 GPRINT:active:MAX:"Max\\: %8.2lf %s\\n" \
 STACK:idle#00A0C1:"Idle                   " \
 GPRINT:idle:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:idle:MIN:"Min\\: %8.2lf %s" \
 GPRINT:idle:MAX:"Max\\: %8.2lf %s\\n" \
 STACK:idletxn#FFCC00:"Idle in Txn            " \
 GPRINT:idletxn:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:idletxn:MIN:"Min\\: %8.2lf %s" \
 GPRINT:idletxn:MAX:"Max\\: %8.2lf %s\\n" \
 STACK:idletxnabrt#FF0000:"Idle in Txn (aborted)  " \
 GPRINT:idletxnabrt:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:idletxnabrt:MIN:"Min\\: %8.2lf %s" \
 GPRINT:idletxnabrt:MAX:"Max\\: %8.2lf %s\\n" \
 STACK:fastpath#B575E5:"Fastpath Function Call " \
 GPRINT:fastpath:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:fastpath:MIN:"Min\\: %8.2lf %s" \
 GPRINT:fastpath:MAX:"Max\\: %8.2lf %s\\n" \
 STACK:disabled#888888:"Disabled               " \
 GPRINT:disabled:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:disabled:MIN:"Min\\: %8.2lf %s" \
 GPRINT:disabled:MAX:"Max\\: %8.2lf %s\\n" \
 STACK:starting#F5B26B:"Starting               " \
 GPRINT:starting:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:starting:MIN:"Min\\: %8.2lf %s" \
 GPRINT:starting:MAX:"Max\\: %8.2lf %s\\n" \
 STACK:masked#000000:"Masked (no pg_monitor) " \
 GPRINT:masked:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:masked:MIN:"Min\\: %8.2lf %s" \
 GPRINT:masked:MAX:"Max\\: %8.2lf %s\\n"

report.pgsql.autovacuum.name=PostgreSQL Autovacuum Workers
report.pgsql.autovacuum.type=nodeSnmp
report.pgsql.autovacuum.columns=pg_av_workers,pg_av_max_workers
report.pgsql.autovacuum.command=--title="PostgreSQL Autovacuum Workers" \
 --vertical-label="workers" \
 DEF:workers={rrd1}:pg_av_workers:AVERAGE \
 DEF:maxworkers={rrd2}:pg_av_max_workers:AVERAGE \
 AREA:workers#7EE600:"Active Workers" \
 GPRINT:workers:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:workers:MIN:"Min\\: %8.2lf %s" \
 GPRINT:workers:MAX:"Max\\: %8.2lf %s\\n" \
 LINE2:maxworkers#FF0000:"Max Workers   " \
 GPRINT:maxworkers:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:maxworkers:MIN:"Min\\: %8.2lf %s" \
 GPRINT:maxworkers:MAX:"Max\\: %8.2lf %s\\n"
