#
# PostgreSQL Dead Tuples Reports
#

reports=pgsql.deadtuples

report.pgsql.deadtuples.name=PostgreSQL Dead Tuples
report.pgsql.deadtuples.type=nodeSnmp
report.pgsql.deadtuples.columns=pg_n_dead_tup
report.pgsql.deadtuples.command=--title="PostgreSQL Dead Tuples" \
 --vertical-label="dead tuples" \
 DEF:dead={rrd1}:pg_n_dead_tup:AVERAGE \
 AREA:dead#7EE600:"Dead Tuples" \
 GPRINT:dead:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:dead:MIN:"Min\\: %8.2lf %s" \
 GPRINT:dead:MAX:"Max\\: %8.2lf %s\\n"
