#
# PostgreSQL XID Horizon Reports
#

reports=pgsql.xidhorizon, pgsql.xidholders

report.pgsql.xidhorizon.name=PostgreSQL XID Horizon Age
report.pgsql.xidhorizon.type=nodeSnmp
report.pgsql.xidhorizon.columns=pg_data_horizon_age,pg_cat_horizon_age
report.pgsql.xidhorizon.command=--title="PostgreSQL XID Horizon Age" \
 --vertical-label="transactions" \
 DEF:datahorizon={rrd1}:pg_data_horizon_age:AVERAGE \
 DEF:cathorizon={rrd2}:pg_cat_horizon_age:AVERAGE \
 LINE2:datahorizon#FF0000:"Data Horizon   " \
 GPRINT:datahorizon:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:datahorizon:MIN:"Min\\: %8.2lf %s" \
 GPRINT:datahorizon:MAX:"Max\\: %8.2lf %s\\n" \
 LINE2:cathorizon#B575E5:"Catalog Horizon" \
 GPRINT:cathorizon:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:cathorizon:MIN:"Min\\: %8.2lf %s" \
 GPRINT:cathorizon:MAX:"Max\\: %8.2lf %s\\n"

report.pgsql.xidholders.name=PostgreSQL XID Horizon Holders
report.pgsql.xidholders.type=nodeSnmp
report.pgsql.xidholders.columns=pg_backend_xmin_age,pg_slot_xmin_age,pg_slot_catalog_age,pg_standby_xmin_age,pg_prepared_age
report.pgsql.xidholders.command=--title="PostgreSQL XID Horizon Holders" \
 --vertical-label="transactions" \
 DEF:backends={rrd1}:pg_backend_xmin_age:AVERAGE \
 DEF:slotxmin={rrd2}:pg_slot_xmin_age:AVERAGE \
 DEF:slotcat={rrd3}:pg_slot_catalog_age:AVERAGE \
 DEF:standby={rrd4}:pg_standby_xmin_age:AVERAGE \
 DEF:prepared={rrd5}:pg_prepared_age:AVERAGE \
 LINE2:backends#7EE600:"Backend Snapshots   " \
 GPRINT:backends:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:backends:MIN:"Min\\: %8.2lf %s" \
 GPRINT:backends:MAX:"Max\\: %8.2lf %s\\n" \
 LINE2:slotxmin#00A0C1:"Slot xmin           " \
 GPRINT:slotxmin:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:slotxmin:MIN:"Min\\: %8.2lf %s" \
 GPRINT:slotxmin:MAX:"Max\\: %8.2lf %s\\n" \
 LINE2:slotcat#B575E5:"Slot catalog_xmin   " \
 GPRINT:slotcat:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:slotcat:MIN:"Min\\: %8.2lf %s" \
 GPRINT:slotcat:MAX:"Max\\: %8.2lf %s\\n" \
 LINE2:standby#FFCC00:"Standby Feedback    " \
 GPRINT:standby:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:standby:MIN:"Min\\: %8.2lf %s" \
 GPRINT:standby:MAX:"Max\\: %8.2lf %s\\n" \
 LINE2:prepared#FF0000:"Prepared Xacts      " \
 GPRINT:prepared:AVERAGE:" Avg\\: %8.2lf %s" \
 GPRINT:prepared:MIN:"Min\\: %8.2lf %s" \
 GPRINT:prepared:MAX:"Max\\: %8.2lf %s\\n"
