
[[getting-started-core]]
= {page-component-title} other errors

This section explains some other errors when {page-component-title} won't start properly.

[[xml-errors]]
== XML configuration errors preventing Startup

Changes were made to an XML file in `$OPENNMS_HOME/etc/events/` and a value wasn't set properly in a XML configuration file and when startiong {page-component-title}, there is an error.

A snippet of the output from `systemctl status opennms`
[source,shell]
Mar 20 14:41:53 rhel9h.totusmel.com opennms[130123]: Starting OpenNMS:
Mar 20 14:41:53 rhel9h.totusmel.com opennms[130823]: ERROR: XML validation failed: /opt/opennms/etc/events/VMWare.events.xml
Mar 20 14:41:53 rhel9h.totusmel.com opennms[130823]:            run '/usr/bin/xmllint /opt/opennms/etc/events/VMWare.events.xml' for details
Mar 20 14:41:53 rhel9h.totusmel.com opennms[130123]: Validation failed on 1 XML files.  Exiting.
Mar 20 14:41:53 rhel9h.totusmel.com opennms[130123]: failed

Running the diagnotic tool `confi-tester -a`, an error is produce right after the config for `Drools Northbounder` is loaded.

Below is a snippet of the error:

[source,shell]
11:05:42.570 [Main] INFO  org.opennms.core.xml.AbstractJaxbConfigDao - Loaded Config for Drools Northbounder in 6 ms
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.opennms.bootstrap.Bootstrap$4.run(Bootstrap.java:531)
    at java.base/java.lang.Thread.run(Thread.java:829)

Running the `xmllint` tool to validate the XML files in `$OPENNMS_HOME/etc/events` will help identify the error:
[source,shell]
[root@rhel9h ~]# xmllint --schema /var/opennms/xsds/eventconf.xsd /opt/opennms/etc/events/VMWare.events.xml --noout
/opt/opennms/etc/events/VMWare.events.xml:275: parser error : Opening and ending tag mismatch: logmsg line 273 and event
   </event>
           ^
/opt/opennms/etc/events/VMWare.events.xml:276: parser error : Opening and ending tag mismatch: logmsg line 265 and events
</events>
         ^
/opt/opennms/etc/events/VMWare.events.xml:277: parser error : Premature end of data in tag event line 223
^

There is a unmatched tag in `/opt/opennms/etc/events/VMWare.events.xml` that is causing the problem.

The problem (line numbers added for visibility of where the error is):
[source,xml]
   265      <logmsg dest="logndisplay">&lt;p>
   266            vpxdTrap trap received
   267            vpxdTrapType=%parm[#1]%
   268            vpxdHostName=%parm[#2]%
   269            vpxdVMName=%parm[#3]%
   270            vpxdNewStatus=%parm[#4]%
   271            vpxdOldStatus=%parm[#5]%
   272            vpxdObjValue=%parm[#6]%&lt;/p>
   273      <logmsg>

Once this is fixed by changing line `273` from `<logmsg>` to `</logmsg>` and running `xmllint` again, the file now validates and {page-component-title} will start properly.
[source]
[root@rhel9h ~]# xmllint --schema /var/opennms/xsds/eventconf.xsd /opt/opennms/etc/events/VMWare.events.xml --noout
/opt/opennms/etc/events/VMWare.events.xml validates

TIP: To quickly run `xmllint` through all of the files in `$OPENNMS_HOME/etc/events` run:
[source,shell]
for x in $OPENNMS_HOME/etc/events/*;do xmllint --schema $OPENNMS_HOME/share/xsds/eventconf.xsd $x --noout;done