
==== IPFIX

The _IP Flow Information Export (IPFIX)_ protocol is a vendor-neutral standard for transmitting traffic flow information.
See <<ga-flow-support, Flow Support>> for details on flow support in _{opennms-product-name}_.

[[telemetryd-ipfix-parser-udp]]
===== IPFIX UDP Parser

The IPFIX UDP Parser accepts packets received by a <<telemetryd-listener-udp, UDP Listener>> and must forward them to an <<telemetryd-ipfix-adapter, IPFIX Adapter>>.

The IPFIX UDP Parser supports protocol detection.

====== Facts

[options="autowidth"]
|===
| Class Name          | `org.opennms.netmgt.telemetry.protocols.netflow.parser.IpfixUdpParser`
|===

====== Parameters

.Parameters for the IPFIX UDP Parser
[options="header, autowidth"]
|===
| Parameter             | Description                                                                    | Required | Default value
| `templateTimeout`     | Templates must be redeclared in the given duration or they will be dropped.    | no       | 30 minutes
| `maxClockSkew`        | The maximum delta in seconds between exporter and Minion timestamps.       | no       | 0
| `clockSkewEventRate`  | Used to rate-limit clock skew events in seconds.                           | no       | 3600
| `dnsLookupsEnabled`      | Used to enable or disable DNS resolution for flows.                        | no       | true
|===


[[telemetryd-ipfix-parser-tcp]]
===== IPFIX TCP Parser

The IPFIX TCP Parser accepts packets received by a <<telemetryd-listener-tcp, TCP Listener>> and must forward them to a <<telemetryd-ipfix-adapter, IPFIX Adapter>>.

====== Facts

[options="autowidth"]
|===
| Class Name          | `org.opennms.netmgt.telemetry.protocols.netflow.parser.IpfixTcpParser`
|===

====== Parameters

This parser does not currently have any configurable parameters.

===== Configure IPFIX Listener on a Minion

To enable and configure a _TCP Listener_ for IPFIX on Minion, connect to the _Karaf Console_ and set the following properties:

[source]
----
$ ssh -p 8201 admin@localhost
...
admin@minion()> config:edit --alias tcp-50000 --factory org.opennms.features.telemetry.listeners
admin@minion()> config:property-set name IPFIX
admin@minion()> config:property-set class-name org.opennms.netmgt.telemetry.listeners.TcpListener
admin@minion()> config:property-set parameters.port 50000
admin@minion()> config:property-set parsers.0.name IPFIX 
admin@minion()> config:property-set parsers.0.class-name org.opennms.netmgt.telemetry.protocols.netflow.parser.IpfixParser
admin@minion()> config:update
----

NOTE: The protocol must also be enabled on _{opennms-product-name}_ for the messages to be processed.
If you do not specify the queue name, the fallback is the name of the parser. 

[[telemetryd-ipfix-adapter]]
===== IPFIX Adapter

The IPFIX Adapter handles _IPFIX_ telemetry data received and parsed by either of the <<telemetryd-ipfix-parser-udp, IPFIX UDP Parser>> or <<telemetryd-ipfix-parser-tcp, IPFIX TCP Parser>>.
Received flows are decoded from the messages into the canonical flow format and published to the _flow repository_.

====== Facts

[options="autowidth"]
|===
| Class Name          | `org.opennms.netmgt.telemetry.protocols.netflow.adapter.ipfix.IpfixAdapter`
|===

====== Parameters

.Parameters for the IPFIX TCP Parser
[options="header, autowidth"]
|===
| Parameter             | Description                                                                    | Required | Default value
| `templateTimeout`     | Templates must be redeclared in the given duration or they will be dropped.    | no       | 30 minutes
| `maxClockSkew`        | The maximum delta in seconds between exporter and Minion time stamps.       | no       | 0
| `clockSkewEventRate`  | Used to rate-limit clock skew events in seconds.                           | no       | 3600
| `dnsLookupsEnabled`      | Used to enable or disable DNS resolution for flows.                        | no       | true
|===

TIP: The parameter `maxClockSkew` in your parser definition enables clock skew detection for exporters. 
It specifies the maximum delta in seconds between exporter and Minion timestamps. 
If exceeded, an alarm will be generated for the exporting device. 
The default value is 0, so clock skew detection is disabled. 
Furthermore, a parameter `clockSkewEventRate` can be used to rate-limit clock skew events.
The default is `3600` seconds, so every hour an event will be sent.
