
==== Tuning Apache Kafka

The configuration is shipped with sane defaults, but depending on the size and network topology it can be required to tune the _Apache Kafka_ environment to meet certain needs.
_Apache Kafka_ options can be set directly in the `org.opennms.core.ipc.rpc.kafka.cfg` and `org.opennms.core.ipc.sink.kafka.cfg` file.

Alternatively: _Kafka_ producer/consumer options can be set by defining additional system properties prefixed with `org.opennms.core.ipc.rpc.kafka` and `org.opennms.core.ipc.sink.kafka`.

You can find available configuration parameters for _Kafka_ here:

* link:https://kafka.apache.org/10/documentation.html#producerconfigs[Producer Configs] for RPC communication
* link:https://kafka.apache.org/10/documentation.html#newconsumerconfigs[New Consumer Configs] for Sink communication

===== Multiple {opennms-product-name} instances

Topics will be automatically created and are prefixed by default with `OpenNMS`. 
If you want to use an _Apache Kafka_ cluster with multiple _{opennms-product-name}_ instances, the topic prefix can be customized by setting `org.opennms.core.ipc.rpc.kafka.group.id` and `org.opennms.core.ipc.sink.kafka.group.id` to a string value which identifies your instance.

===== Tips for Kafka

TIP: For Kafka RPC, the number of partitions should always be greater than the number of minions at a location.
     When there are multiple locations, partitions >= max number of minions at a location.

TIP: By default, Kafka RPC supports buffers greater than >1MB by splitting large buffer into chunks of 900KB(912600).
     Max buffer size (900KB, by default) can be configured by setting org.opennms.core.ipc.rpc.kafka.max.buffer.size ( in bytes).

TIP: Default time to live (time at which request will expire) is 20000 msec (20sec).
     It can be changed by configuring system property `org.opennms.core.ipc.rpc.kafka.ttl` in msec.
