
// Allow GitHub image rendering
:imagesdir: ../../../images

[[ga-events-sources-snmp-traps]]
==== SNMP Traps

If SNMP-capable devices in the network are configured to send *traps* to {opennms-product-name}, these traps are transformed into events according to pre-configured rules.
The `Trapd` service daemon, which enables {opennms-product-name} to receive SNMP traps, is enabled by default.

IMPORTANT: Disabling the `Trapd` service daemon will render {opennms-product-name} *incapable* of receiving SNMP traps.

Event definitions are included with {opennms-product-name} for traps from many vendors' equipment.

[[ga-events-sources-snmp-traps-minion]]
===== Receiving SNMP Traps from Minion

If you have _Minions_ deployed in your network it is possible to enable them as a _SNMP Trap_ receiver.
The _Minion_ will forward the _SNMP Traps_ to the _{opennms-product-name}_ instance where they gets processed and persisted.
_SNMP Trap_ reception on the _Minion_ can be configured through the Karaf Shell_.



*Step 1: Create a Trapd configuration for the Minion*

[source]
----
vi ${MINION_HOME/etc/org.opennms.netmgt.trapd.cfg

trapd.listen.port = 162 <1>
trapd.listen.interface = 0.0.0.0 <2>
----
<1> The _UDP_ port number where _Minion_ will listen for incoming _SNMP Traps_.
<2> IP address to bind the UDP listener on an interface, `0.0.0.0` receives on all IP interfaces.

*Step 2: Restart the Minion to apply changes*

[source]
----
systemctl restart minion
----
