#! /bin/sh
#
# Get JAVA_HOME
#

if [ -z "$JAVA_HOME" ]; then
	for dir in /usr/java/jdk1.4* /usr/java/j2sdk1.4* /usr/lib/j2sdk1.4* /usr/lib/j2sdk-1.4* /opt/IBMJava2-13 /usr/java/jdk1.3* /usr/java/j2sdk1.3* /usr/lib/j2sdk1.3*; do
		if [ -d "$dir" -a -f "$dir/lib/tools.jar" ]; then
			JAVA_HOME="$dir"
			break
		fi
	done

	if [ -z "$JAVA_HOME" ]; then
		echo "You need to set a valid JAVA_HOME in /etc/default/$NAME" >&2
		exit 1
	fi
fi
export JAVA_HOME
echo $JAVA_HOME

