#! /bin/sh

# $Id$

if [ -z "$JAVA_HOME" ]; then
    for dir in /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-1.5.0-sun
    do
        if [ -d "$dir" -a -f "$dir/lib/tools.jar" ]; then
            JAVA_HOME="$dir"
            break
        fi
    done

    if [ -z "$JAVA_HOME" ]; then
        echo "Could not find the jvm, please set JAVA_HOME" >&2
        exit 1
    fi
fi

echo "$JAVA_HOME"
