#! /bin/sh

if [ -z "$JAVA_HOME" ]; then
    for version in 7 8; do
        for postfix in oracle sun openjdk; do
            dir="/usr/lib/jvm/java-$version-$postfix"
            if [ -d "$dir" -a -f "$dir/lib/tools.jar" ]; then
                JAVA_HOME="$dir"
                break
            fi
        done
    done

    if [ -z "$JAVA_HOME" ]; then
        echo "Could not find the jvm, please set JAVA_HOME" >&2
        exit 1
    fi
fi

echo "$JAVA_HOME"
