.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.\" Copyright (C) 1996 Erick Branderhorst <branderh@debian.org>
.\"
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2, or (at your option) any later
.\" version.
.\" 
.\" This is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\" You should have received a copy of the GNU General Public License with
.\" your Debian GNU/Linux system, in /usr/share/common-licenses/GPL, or with
.\" the dpkg source package as the file COPYING.  If not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" This manpage is created thanks to:
.\" Kai Henningsen <kai@khms.westfalen.de>,
.\" Ian Jackson <iwj10@cus.cam.ac.uk>,
.\" David H. Silber <dhs@firefly.com>,
.\" Carl Streeter <streeter@cae.wisc.edu>,
.\" Martin Michlmayr <tbm@cyrius.com>.
.\"
.TH OPENNMS 1 "February 11th, 2003" "Debian/GNU Linux" "Linux Programmer's Manual"
.SH NAME
OpenNMS \- No manpage for this program, utility or function.
.SH DESCRIPTION
This
.B program, utility
or 
.B function 
does not have a useful manpage.  Before opening a bug to report this,
please check with the Debian Bug Tracking System (BTS) at
.RI < http://bugs.debian.org/ >
if a bug has already been reported.  If not, you can submit a wishlist bug
if you want.

If you are a competent and accurate writer and are willing to spend
the time reading the source code and writing good manpages please
write a better man page than this one.  Please 
.B contact 
the 
.B package maintainer 
in order to avoid several people working on the same manpage.

Try the following options if you want more information.

foo \-\-help, foo \-h, foo \-?
.PP 
info foo
.PP 
whatis foo, apropos foo
.PP 
check directories /usr/share/doc/foo, /usr/lib/foo
.PP 
dpkg \-\-listfiles foo, dpkg \-\-search foo
.PP
locate '*foo*'
.PP
find / \-name '*foo*'
.PP
The documentation might be in a package starting with the same
name as the package the software belongs to, but ending with -doc or -docs.
.PP
If you still didn't find the information you are looking for you might
consider posting a call for help to
.IR debian-user@lists.debian.org .
.SH SEE ALSO
.BR info (1),
.BR whatis (1),
.BR apropos (1),
.BR dpkg (1),
.BR locate (1),
.BR find (1),
.BR updatedb (1),
.BR undocumented (2),
.BR missing (7).
