//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 08:33:26 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.opennms.org/xsd/config/wsman-datacollection", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opennms.netmgt.config.wsman;
