
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-opennms-debian]]
=== Install on Debian-based systems

IMPORTANT: This guide does not apply to OpenNMS Meridian, which can be installed only on Red Hat Enterprise Linux or CentOS systems.

This section describes how to install the _OpenNMS_ platform on _Ubuntu 14.04 LTS_.
The setup process is described in the following steps:

. Install _OpenNMS_ apt repository server with GPG key to verify packages
. Installation of the _opennms_ meta package which handles all dependencies
. Initialize _PostgreSQL_ database and configure access
. Initialize _OpenNMS_ and first start of the application

[[gi-install-opennms-deb-repo]]
==== Setup OpenNMS Debian repository

_OpenNMS_ can be installed with Installation of stable repository and GPG key

.Installation of _OpenNMS Debian_ repository
[source, shell]
----
deb http://debian.opennms.org stable main
deb-src http://debian.opennms.org stable main
----

.Installation of repository GPG key
[source, shell]
----
wget -O - http://debian.opennms.org/OPENNMS-GPG-KEY | apt-key add -
----

.Update apt repository cache
[source, shell]
----
apt-get update
----

[[gi-install-opennms-deb-package]]
==== Install OpenNMS package

.Installation of the full application with all dependencies like PostgreSQL and Java
[source, shell]
----
apt-get install -y opennms
----

The following packages will be automatically installed:

* _opennms_: The platform meta package which handles all dependencies from _OpenNMS_ repository.
* _jicmp6_ and _jicmp_: _Java_ bridge to allow sending _ICMP messages_ from _OpenNMS_ repository.
* _opennms-core_: _OpenNMS_ core services, e.g. _Provisiond_, _Pollerd_ and _Collectd_ from _OpenNMS_ repository.
* _opennms-webapp-jetty_: _OpenNMS_ web application from _OpenNMS_ repository
* _jdk1.8_: _Oracle Java 8_ environment from _OpenNMS_ respository
* _postgresql_: _PostgreSQL_ database server from distribution repository
* _postgresql-libs_: _PostgreSQL_ database from distribution repository

With the successful installed packages the _OpenNMS_ platform is installed in the following directory structure:

[source, shell]
----
[root@localhost /usr/share/opennms]# tree -L 2
.
└── opennms
   ├── bin
   ├── data
   ├── deploy
   ├── etc -> /etc/opennms
   ├── instances
   ├── jetty-webapps
   ├── lib -> ../java/opennms
   ├── logs -> /var/log/opennms
   ├── share -> /var/lib/opennms
   └── system
----

[[gi-install-opennms-deb-prepare-pg]]
==== Prepare PostgreSQL

The _Debian_ package installs also _PostgreSQL_ database and is already initialized and added in the runlevel configuration.
It is only necessary to start the _PostgreSQL_ database without a restart.

.Startup PostgreSQL database
[source, shell]
----
service postgresql start
----

The next step is creating an _opennms_ database user with password and configure the authentication method.

.Accounting and database management for _OpenNMS_
[source, shell]
----
su - postgres
createuser -P opennms
createdb -O opennms opennms
exit
----

NOTE: It is not necessary to change the authentication method in `pg_hba.conf`, it is by default set to `md5` for localhost connections.

.Set password for Postgres super user
[source, shell]
----
su - postgres
psql -c "ALTER USER postgres WITH PASSWORD 'YOUR-POSTGRES-PASSWORD';"
exit
----

NOTE: The super user is required to be able to initialize and change the database schema for installation and updates.

[source, shell]
----
vi ${OPENNMS_HOME}/etc/opennms-datasources.xml
----

.Configuration for database authentication in _OpenNMS_
[source, xml]
----
<jdbc-data-source name="opennms"
                    database-name="opennms"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/opennms"
                    user-name="** YOUR-OPENNMS-USERNAME **"<1>
                    password="** YOUR-OPENNMS-PASSWORD **" /><2>

<jdbc-data-source name="opennms-admin"
                    database-name="template1"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/template1"
                    user-name="postgres"<3>
                    password="** YOUR-POSTGRES-PASSWORD **" /><4>
----

<1> Set the user name to access the _OpenNMS_ database table
<2> Set the password to access the _OpenNMS_ database table
<3> Set the _postgres_ user for administrative access to PostgreSQL
<4> Set the password for administrative access to PostgreSQL

[[gi-install-opennms-deb-init]]
==== Initialize OpenNMS

_OpenNMS_ is now configured to access the database.
It is required to set the _Java_ environment running _OpenNMS_ and initialize the database schema.

.Configuration of _Java_ environment for _OpenNMS_
[source, shell]
----
${OPENNMS_HOME}/bin/runjava -s
----

.Initialization of database and system libraries
[source, shell]
----
${OPENNMS_HOME}/bin/install -dis
----

NOTE: It is not necessary to add _OpenNMS_ to the run level manually, it is automatically added after setup.

.Startup _OpenNMS_
[source, shell]
----
service opennms start
----

After starting OpenNMS, the web application can be accessed on http://<ip-or-fqdn-of-your-server>:8980/opennms.
The default login user is _admin_ and the password is initialized to _admin_.

IMPORTANT: Change the default admin password to a secure password immediately.
