
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-basic-install-opennms]]
== Installation Overview

The _OpenNMS_ platform can be installed in several ways.
This guide describes the installation of the platform on _Red Hat Enterprise Linux (RHEL)_-based, _Debian_-based and _Microsoft Windows_
operating systems. The following abbreviations will be used to refer to the following operating systems:

* _RHEL_: Red Hat Enterprise Linux 6 or higher, CentOS 6 or higher, Fedora 20 or higher
* _Debian_: Debian 7 or higher, Ubuntu 14.04 or higher
* _Microsoft Windows_: Windows 8.1, Windows Server 2012, Windows 10

Installable, precompiled software packages are provided through _RHEL Yum_ and _Debian APT_ repository servers and from the
link:https://sourceforge.net/projects/opennms/files/OpenNMS/[OpenNMS Sourceforge project page].
Installing _OpenNMS_ requires the following prerequisites:

* A configured <<gi-install-opennms-repo-releases, Yum or APT Package Repository>> for your platform (Linux only)
* Internet access to download and verify _OpenNMS_ packages from the Yum or APT package repositories
* <<gi-install-oracle-java, Oracle Java SE Development Kit 8>> environment
* PostgreSQL database version 9.1 or higher, it has only been tested with PostgreSQL 9.1 through 9.6
* A time-series database engine to persist long-term performance data:
** JRobin: The default choice. JRobin is included inside OpenNMS and doesn't require additional software to be installed.
** <<gi-rrdtool-time-series-database, RRDtool>>: A higher performance, file-based database.
** <<gi-install-ts-newts, Newts>>: The highest performance solution. Newts uses an Apache Cassandra database for clustered scalability.

CAUTION: Please make sure your DNS settings for the OpenNMS server are correct.
         In case there is an incorrect or missing _A Resource Record_ for the server, OpenNMS might not start correctly.
         The reason is that the Java security manager cannot be initialized and an _RMI class loader disabled_ exception will be shown.

NOTE: _OpenJDK 8_ can be used, but for production and critical environments _Oracle Java SE Development Kit 8_ is recommended.

[NOTE]
====
`${OPENNMS_HOME}` will be used to refer to the path where _OpenNMS_ is installed. It is different
depending on your platform:

* _RHEL_: `/opt/opennms`
* _Debian_: `/usr/share/opennms`
* _Microsoft Windows_: `C:\Program Files\opennms`
====

With the _opennms_ meta package all dependencies needed for the components mentioned above are maintained.
The following sections describe how to install _OpenNMS_ on a single system.
Dependencies for _Java_ and the _PostgreSQL_ database are maintained with the _opennms_ meta installation package.
