
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-basic-install-opennms]]
== Basic Installation of OpenNMS

The _OpenNMS_ platform can be installed in several ways.
This guide describes the installation of the platform on _RHEL-_, _Debian-_ and _Microsoft Windows_ based operation systems.
Installable pre-compiled software packages are provided through _RPM_ and _Debian_ repository servers.
Running _OpenNMS_ requires the following components:

* Internet access to download and verify installation packages from public repository server
* Installed <<gi-install-oracle-java, Oracle Java 8>> environment
* PostgreSQL 9.1+ data base
* Set link to section which describes to install with RRDTool.
  Optional link:http://oss.oetiker.ch/rrdtool/[RRDtool] to persist long term performance data

NOTE: _OpenJDK 8_ can be used, but for production and critical environment _Oracle Java 8_ is recommended.

NOTE: `${OPENNMS_HOME}` is referred to the path _OpenNMS_ is installed to.
      On _RHEL-based_ systems it is `/opt/opennms` on _Debian-based_ systems it is `/usr/share/opennms`.
      The environment in _Microsoft Windows_ can refer to `C:\Program Files\opennms`

With an _opennms_ meta package all dependencies for the components mentioned above are maintained.
The following sections describe to install _OpenNMS_ on a single system.
Dependencies for _Java_ and the _PostgreSQL_ data base are maintained with the _opennms_ meta installation package.

[[gi-install-opennms-repo-releases]]
=== Repositories for Releases

Installation packages are available for different releases of _OpenNMS_.
The configuration of the repository decides which _OpenNMS_ release will be installed.

The following release are available to be installed

.Names used in repositories to install different _OpenNMS_ releases.
[options="header, autowidth"]
|===
| Release    | Description
| `stable`   | Latest stable release
| `testing`  | Release candidate for next stable
| `snapshot` | Latest successful develop build
| `branches/${BRANCH-NAME}` | Install from a specific branch name, e.g. `branches/features-newts` installs the repository for the _Newts_ development branch.
                              Branches can be found in http://yum.opennms.org/branches/ or http://debian.opennms.org/dists/branches/
| `branches/${RELEASE}`     | Install a specific release, e.g. `branches/release-14.0.3`.
                              This release branches are also found in http://yum.opennms.org/branches/ or http://debian.opennms.org/dists/branches/
|===

To install a different release the repository files have to be installed and manually modified.

==== Specific Release on RHEL-based system

.Change the directory in the base URL to select a release to install
[source, shell]
----
[opennms-stable-common]
name=RPMs Common to All OpenNMS Architectures (snapshot)<1>
baseurl=http://yum.opennms.org/snapshot/common<2>
failovermethod=roundrobin
gpgcheck=1
gpgkey=file:///etc/yum.repos.d/OPENNMS-GPG-KEY

[opennms-stable-rhel7]
name=RedHat Enterprise Linux 7.x and CentOS 7.x (snapshot)<1>
baseurl=http://yum.opennms.org/snapshot/rhel7<2>
failovermethod=roundrobin
gpgcheck=1
gpgkey=file:///etc/yum.repos.d/OPENNMS-GPG-KEY
----

<1> Change description in this example from `stable` to `snapshot`
<2> Change the _URL_ to use _RPM_ packages in subdirectory `snapshot` instead of `stable`

Install _OpenNMS_ with _YUM_ following the normal installation procedure.

==== Specific Release on Debian-based system

.Change the _Debian_ repository file
[source, shell]
----
vi /etc/apt/sources.list.d/opennms.list
----

[source, shell]
----
deb http://debian.opennms.eu snapshot main <1>
deb-src http://debian.opennms.eu snapshot main <1>
----

<1> Change repository path in this example from `stable` to `snapshot`

Run `apt-get update`and install _OpenNMS_ with _apt_ following the normal installation procedure.
