
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-opennms-rhel]]
=== Installing on RHEL-based system

This section describes how to install the _OpenNMS_ platform on _CentOS 7.1_.
The setup process is described in the following steps:

. Install _OpenNMS_ _YUM_ repository server with GPG key to verify packages
. Installation of the _opennms_ meta package which handles all dependencies
. Initialize _PostgreSQL_ database and configure access
. Initialize _OpenNMS_ and first start of the application

[[gi-install-opennms-yum-repo]]
==== Setup OpenNMS YUM repository

.Installation of stable repository and GPG key
[source, shell]
----
rpm -Uvh http://yum.opennms.org/repofiles/opennms-repo-stable-rhel7.noarch.rpm
rpm --import http://yum.opennms.org/OPENNMS-GPG-KEY
----

[[gi-install-opennms-rhel-package]]
==== Install OpenNMS package

.Installation of the full application with all dependencies like PostgreSQL and Java
[source, shell]
----
yum -y install opennms
----

The following packages will be automatically installed:

* _opennms_: The platform meta package which handles all dependencies from _OpenNMS_ repository.
* _jicmp6_ and _jicmp_: _Java_ bridge to allow sending _ICMP messages_ from _OpenNMS_ repository.
* _opennms-core_: _OpenNMS_ core services, e.g. _Provisiond_, _Pollerd_ and _Collectd_ from _OpenNMS_ repository.
* _opennms-webapp-jetty_: _OpenNMS_ web application from _OpenNMS_ repository
* _jdk1.8_: _Oracle Java 8_ environment from _OpenNMS_ respository
* _postgresql_: _PostgreSQL_ database server from distribution repository
* _postgresql-libs_: _PostgreSQL_ database from distribution repository

With the successful installed packages the _OpenNMS_ platform is installed in the following directory structure:

[source, shell]
----
[root@localhost /opt/opennms]# tree -L 2
.
└── opennms
   ├── bin
   ├── contrib
   ├── data
   ├── deploy
   ├── etc
   ├── jetty-webapps
   ├── lib
   ├── logs -> /var/log/opennms
   ├── share -> /var/opennms
   └── system
----

[[gi-install-opennms-rhel-prepare-pg]]
==== Prepare PostgreSQL

The _CentOS_ package installs but doesn't initialize the _PostgreSQL_ database directory.
Additionally _OpenNMS_ requires authentication to access the database and are described in this section.
Initialize the database directory with

.Initialization of the _PostgreSQL_ database
[source, shell]
----
postgresql-setup initdb
----

.System startup configuration for PostgreSQL
[source, shell]
----
systemctl enable postgresql
----

.Startup PostgreSQL database
[source, shell]
----
systemctl start postgresql
----

The next step is creating an _opennms_ database user with password and configure the authentication method.

.Accounting and database management for _OpenNMS_
[source, shell]
----
su - postgres
createuser -P opennms
createdb -O opennms opennms
exit
----

To allow _OpenNMS_ access to the database over the local network _PostgreSQL_ has to be configured.

[source, shell]
----
vi /var/lib/pgsql/data/pg_hba.conf
----

.Configuration of network access for _PostgreSQL_
[source, shell]
----
host    all             all             127.0.0.1/32            md5<1>
host    all             all             ::1/128                 md5<1>
----

<1> Change method from `ident` to `md5` for _IPv4_ and _IPv6_ on localhost.

.Apply configuration changes for _PostgreSQL_
[source, shell]
----
systemctl reload postgresql
----

In the next step configure the _OpenNMS_ database configuration.

[source, shell]
----
vi ${OPENNMS_HOME}/etc/opennms-datasources.xml
----

.Configuration for database authentication in _OpenNMS_
[source, xml]
----
<jdbc-data-source name="opennms"
                    database-name="opennms"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/opennms"
                    user-name="** YOUR-OPENNMS-USERNAME **"<1> 
                    password="** YOUR-OPENNMS-PASSWORD **" /><2>

<jdbc-data-source name="opennms-admin"
                    database-name="template1"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/template1"
                    user-name="** YOUR-OPENNMS-USERNAME **"<3>
                    password="** YOUR-OPENNMS-PASSWORD **" /><4>
----

<1> Set the user name to access the _OpenNMS_ database table
<2> Set the password to access the _OpenNMS_ database table
<3> Set the user name for administrative changes of the _OpenNMS_ database table
<4> Set the password for administrative changes of the _OpenNMS_ database table

[[gi-install-opennms-rhel-init]]
==== Initialize OpenNMS

_OpenNMS_ is now configured to access the database.
It is required to set the _Java_ environment running _OpenNMS_ and initialize the database schema.

.Configuration of _Java_ environment for _OpenNMS_ 
[source, shell]
----
${OPENNMS_HOME}/bin/runjava -s
----

.Initialization of database and system libraries
[source, shell]
----
${OPENNMS_HOME}/bin/install -dis
----

.System startup configuration for _OpenNMS_
[source, shell]
----
systemctl enable opennms
----

.Startup _OpenNMS_
[source, shell]
----
systemctl start opennms
----

After starting _OpenNMS_ the web application can be accessed on http://<ip-or-fqdn-of-your-server>:8980/opennms.
The default login user is _admin_ and the password is initialized to _admin_.

IMPORTANT: Change the default admin password to a secure password immediately.
