
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-opennms-rhel]]
=== Installing on RHEL-based system

This section describes how to install the _OpenNMS_ platform on _CentOS 7.1_.
The setup process is described in the following steps:

. Install OpenNMS YUM repository server with GPG key to verify packages
. Installation of the _opennms_ meta package which handles all dependencies
. Initialize _PostgreSQL_ database and configure access
. Initialize _OpenNMS_ and first start of the application

[[gi-install-opennms-yum-repo]]
==== Setup OpenNMS YUM repository

.Install stable repository and GPG key
[source, shell]
----
rpm -Uvh http://yum.opennms.org/repofiles/opennms-repo-stable-rhel7.noarch.rpm
rpm --import http://yum.opennms.org/OPENNMS-GPG-KEY
----

[[gi-install-opennms-rhel-package]]
==== Install OpenNMS package

.Installation of the full application including all dependencies like PostgreSQL or Java
[source, shell]
----
yum -y install opennms
----

The following packages will be automatically installed:

* _opennms_: The platform meta package which handles all dependencies from _OpenNMS_ repository.
* _jicmp6_ and _jicmp_: _Java_ bridge to allow sending _ICMP messages_ from _OpenNMS_ repository.
* _opennms-core_: _OpenNMS_ core services, e.g. _Provisiond_, _Pollerd_ and _Collectd_ from _OpenNMS_ repository.
* _opennms-webapp-jetty_: _OpenNMS_ web application from _OpenNMS_ repository
* _jdk1.8_: _Oracle Java 8_ environment from _OpenNMS_ respository
* _postgresql_: _PostgreSQL_ database server from distribution repository
* _postgresql-libs_: _PostgreSQL_ database from distribution repository

With the successful installed packages the _OpenNMS_ platform is installed in the following directory structure:

[source, shell]
----
[root@localhost /opt/opennms]# tree -L 2
.
└── opennms
   ├── bin
   ├── contrib
   ├── data
   ├── deploy
   ├── etc
   ├── jetty-webapps
   ├── lib
   ├── logs -> /var/log/opennms
   ├── share -> /var/opennms
   └── system
----

[[gi-install-opennms-rhel-prepare-pg]]
==== Prepare PostgreSQL

The _CentOS_ package installs but doesn't initialize the _PostgreSQL_ database directory.
Additionally _OpenNMS_ requires authentication to access the database and are described in this section.
Initialize the database directory with

.Initialize the database directory
[source, shell]
----
postgresql-setup initdb
----

.Start PostgreSQL service on system boot
[source, shell]
----
systemctl enable postgresql
----

.Start PostgreSQL database without rebooting the system
[source, shell]
----
systemctl start postgresql
----

The next step is creating an _opennms_ database user with password and configure the authentication method.

.Create database user _opennms_ and a database _opennms_ with the owner of the created user.
[source, shell]
----
su - postgres
createuser -P opennms
createdb -O opennms opennms
----

.Edit pg_hba.conf for authentication methods
[source, shell]
----
vi /var/lib/pgsql/data/pg_hba.conf
----

.Change the authentication method for _IPv4/IPv6_ localhost connection from `ident` to `md5`.
[source, shell]
----
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
----

.Restart the database to apply your changes
[source, shell]
----
systemctl reload postgresql
----

.Configure the authentication credentials in the _OpenNMS_ data configuration.
[source, shell]
----
vi ${OPENNMS_HOME}/etc/opennms-datasource.xml
----

.Add the username and password in *both* sections
[source, xml]
----
<jdbc-data-source name="opennms"
                    database-name="opennms"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/opennms"
                    user-name="** YOUR-OPENNMS-USERNAME **"
                    password="** YOUR-OPENNMS-PASSWORD **" />

<jdbc-data-source name="opennms-admin"
                    database-name="template1"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/template1"
                    user-name="** YOUR-OPENNMS-USERNAME **"
                    password="** YOUR-OPENNMS-PASSWORD **" />
----

[[gi-install-opennms-rhel-init]]
==== Initialize OpenNMS

_OpenNMS_ is now configured to access the database.
It is required to set the _Java_ environment running _OpenNMS_ and initialize the database schema.

.Set _Java_ environment
[source, shell]
----
${OPENNMS_HOME}/bin/runjava -s
----

.Initialize database and detect path to libraries
[source, shell]
----
${OPENNMS_HOME}/bin/install -dis
----

.Start _OpenNMS_ on system boot
[source, shell]
----
systemctl enable opennms
----

.Start _OpenNMS_ without restarting the system
[source, shell]
----
systemctl start opennms
----

You can now access the web application on http://<ip-or-fqdn-of-your-server>:8980/opennms.
The default login user is _admin_ and the password is initialized to _admin_.

IMPORTANT: Change the default admin password to a secure password immediately.
