[[avail-summary-report]]
= Availability Summary Report (Default Configuration for Past 7 Days)

This report provides a summary of availability across one or more node tags.

Each node tag includes a table of average, minimum, and maximum values for the following availability data for the specified node tag over the specified date range:

* Number of outages.
* Mean Time To Repair ("MTTR") (in hours).
* Length of time for each outage (in hours).
* Percent outage (per unit in category).
* Percent availability (per unit in category).

This report has a pie chart showing percent available time to outage time.
It then provides a stacked bar chart showing the available time and the outage time for each day in the specified date range.
The report then lists the top 25 nodes based on downtime and their respective and downtime percentages.

You can customize the report with a company logo (approximately 195px by 50px) in the header and footer.

== Parameters

[options="header, autowidth"]
[cols="1,2,3"]

|===
| Field
| Description
| Default

| Surveillance Category
| Identify one or more node tags to include in the report.
To select multiple tags use wildcards as described below.
If no tags match the entered string, the report will have no data.
| %

| Time Range in Days
| The range in days from the report start date.
| 7

| Start Date
| The starting date for the data contained in this report.
| 7 days before today

|===

include::standard-text-fields.adoc[]