[[classic-report]]
= Default Classic Report


== Report Contents
This report is generated directly from the {page-component-title} Java code and has no optional parameters for selecting a subset of the network devices.

The period is the current month to the last full day before the day the report was generated (i.e., yesterday).
All the data is presented in tables.

The first table contains a table of the monthly availability percentage for all services monitored by {page-component-title} for the past year.
It also lists the number of nodes that had outages, the number of interfaces and the number of services.
// QUESTION: Not sure if this last set of information show the maximum or current number of interfaces and services.

The next two tables list the daily average of services monitored  and availability of services divided by the total number of minutes for the last full month before the current month.
The first of these tables covers the last full month and the current month to date.

// QUESTION: The report says that the denominator is the "total svc minutes" but it is unclear whether it is using the total number of minutes in the period or the total number of minutes that the service was being monitored.  I dropped the "services" from the phrase.  I believe this is probably done taking the daily number of minutes that s service was available by the daily number of minutes that service was being monitored, and then averaging those percentagesI mention this because there are other ways that this can be calculated (e.g., Using the total number of minutes in a day as the denominator).  This should probably be checked.

The next table lists the devices with the worst availability over the past month.

// COMMENT: The text in the report says "worst available devices in the category" but I believe that is incorrect as there is no search parameter for category.  Also, the table lists 6 devices with the last having 99.99881% availability, so I am thinking the table is supposed to show the top 10 or top 25.  That should probably be fixed.

The next table lists the last 30 days of daily availability, dividing the average availability of every monitored service (on each device) by the total number of minutes.  The average of these 30 data points appears in the next table.

// COMMENT: I think the denominator here is the number of minutes that each service was monitored.  It could be total number of minutes.  This should be checked.

The next two tables show the average availability for every monitored service (on each device) for previous full month and the same average availability for the beginning of the current month to the last full day.

The remaining eight tables show the top service outages for each service for the last full month.  Each entry includes the device, duration of outage and the date/time when the outage occurred.

// QUESTION: I am not sure if this is correct.  In the sample report I reviewed, the names of the services were: Velocloud-Blork, Velocloud-Blurf, HTTPS, and OpenNMS-JVM.  The first four of these tables has no entries.  The last column on this one row table is "Service Lost Time" and I believe they meant date/time that the longest outage for this service began.  That should be confirmed.  I would also recommend changing the column heading as "Service Lost Time" sounds like a synonym for the second column heading, "Duration of Outage".

// COMMENT: There is no obvious way to change the company logo.  It also has the old OpenNMS logo.











