[[event-report]]
= Event Analysis Report


This report provides an analysis of all events over the past 30 days.
This report contains the following sections:

* All events by source
* Top 25 events by unique event identifier (UEI) and event source
* Top 25 event hours
* Top 25 events by node
* Top 25 events by node and UEI
* Top 25 nodes with generic enterprise default traps

The first section includes a pie showing all events by source, along with a table with the data for the pie chart.
This section also includes two line charts showing the total average processed events per hour and the events per day.
Finally, it contains a table with information about the database providing the above information.

The next four sections each contain a table and a line chart showing a breakdown of the top 25 events over the last 30 days broken down by event source, hours, node, and node and UEI.
The last section shows the top 25 nodes with the most common traps, assuming that SNMP traps are being received.

You can customize this report with a company logo (approximately 195px by 50px) in the header.

== Parameters

[options="header, autowidth"]
[cols="1,2,3"]

|===
| Field
| Description
| Default

| URL for embedded links
| This URL base for {page-component-title} embedded links will be used for all links to data in this report.
| \http://hostname:8980/opennms

|===
