[[morning-report]]
= Early Morning Report

== Report Contents

This report provides a global overview of outages, notifications, and events in the last 24 hours.

In the Outage Overview section, there are two pie charts, one that shows the current outages and one that shows the outages resolved in the last 24 hours. The slices of each pie represent the percent of the four types of outages: nodes, interfaces, services, and management.

The next section provides outage details in two tables, the first shows the current outages by nodes and the second table shows the resolved outages by node.

The third section is a stacked bar chart that shows the current outages stacked on the resolved outages over the last 24 hours.

The fourth section provides an overview of notifications over the past 24 hours.
It includes a pie chart and table showing the number of notifications by the media type.

// QUESTION: I still don't know what the slices are, there was nothing in this section of the sample report.

// QUESTION: I am not sure what "media type"

The fifth section provides and overview of events over the last 24 hours.
The first stacked bar chart shows, for each of the last 24 hours, the number of each of the 7 types of events: indeterminate, cleared, normal, warning, minor, major, and critical.
The second stacked bar chart shoes the top 20 nodes with each type of event per node.

This report has no parameters, but it can be customized with a company logo in the page header that is approximately 195px by 50 px.


include::standard.adoc[]