[[response-time-summary-report]]
= Response Time Summary Report

== Report Content
This report has a table for each matching surveillance category that contains the devices and a row for  each IP interface the minimum, average, and maximum ICMP latency of the period of the report. For each device in the tables, there is a stacked bar chart that shows the availability and outage time in seconds for that device.

This report can be customized with a company logo in the header and footer that is approximately 195px by 50px.

== Parameters

[options="header, autowidth"]
[cols="1,2,3"]

|===
| Field
| Description
| Default


| Surveillance Category
| Identify one or more surveillance categories to filter nodes to be included in the report.
To select multiple categories use wildcards as described below.
If no categories match the entered string, the report will have no data.
| %
// COMMENT: The default should probably be set to "Routers" like the Availability Summary.

| Report Time Range
| The range in days from the report start date. Must be an integer.
| 7

| Start Date
| The starting date for the data contained in this report.
| 7 days before today


|===

include::standard-text-fields.adoc[]
include::standard.adoc[]