[[response-time-report]]
= Response Time by Node Report

This report lists the response times by nodes across specified surveillance categories.

This report has a table for each matching surveillance category that contains the devices and a row for each IP interface with the minimum, average, and maximum ICMP latency of the period of the report.

You can customize this report with a company logo (approximately 195px by 50px) in the header and footer.

== Parameters

[options="header, autowidth"]
[cols="1,2,3"]

|===
| Field
| Description
| Default

| Surveillance Category
| Identify one or more surveillance categories to filter nodes to be included in the report.
To select multiple categories use wildcards as described below.
If no categories match the entered string, the report will have no data.
| %

// COMMENT: The default should probably be set to "Routers" like the Availability Summary.

| Start Date
| The starting date for the data contained in this report.
| 7 days before today

| End Date
| The end date for the data contained in this report.
If the end date is later than the start date, the report will have no data.
| Today

|===

include::standard-text-fields.adoc[]
include::standard.adoc[]