
= Report Templates

The last two parameters for most reports are checkboxes for delivery and scheduling of the report.
Checking the "Deliver this report" checkbox will provide the delivery options described below.
Checking the "Schedule this report" checkbox will open up the scheduling editor, which is described in the Schedule Editor section below.

=== Report Delivery Options

Specify the following report delivery options:

* Unique name (must be unique among all scheduled reports)
* Format (PDF, CSV)
* Delivery options
** Save a copy of the report (view in the *Persisted Reports* tab)
// where is it saved?
** Email report (use a comma to separate multiple email addresses)
** Webhook (posts generated report to specified http endpoint)

=== Schedule Editor

Specify the following types of schedule:
* Daily
* Days per week (specific day(s) of the week)
* Days per month (specific day(s) of the month, for example, third Sunday of the month)
* Cron expression

Each schedule has additional fields associated with it, such as days of the week, interval, and specific time.

Once you set that information, click *Deliver Report* to generate the report and save, email, or webhook the report as specified in the *Report Delivery Options* section of the screen.

Note that a list of scheduled reports appears in the *Report Schedules* tab.