[[total-bytes-report]]
= Total Bytes Transferred by Interface Report
Total bytes transferred by interface.

== Report Content

This report provides the total number of bytes transferred by each interface whose category matches the specified category during the specified time period.  For each interface, the report provides:

* Bytes Received
* Bytes Transmitted
* Total Bytes in and Out

This report can be customized with a company logo in the header and footer that is approximately 195px by 50px.

== Parameters

[options="header, autowidth"]
[cols="1,2,3"]

|===
| Field
| Description
| Default

| Surveillance Category
| Identify one or more surveillance categories to filter nodes to be included in the report.
To select multiple categories use wildcards as described below.
If no categories match the entered string, the report will have no data.
| Routers

| Start Date
| The starting date for the data contained in this report.
| 7 days before today

| End Date
| The end date for the data contained in this report. If the End Date is later than the Start Date, the report will fail.
| Today
|===

include::standard-text-fields.adoc[]
include::standard.adoc[]