
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-set-up-opennms]]
== Setting up a basic {opennms-product-name}

The _{opennms-product-name}_ platform can be installed on multiple OS families.
ifdef::opennms-prime[]
This guide provides instructions for installing the platform on _Red Hat Enterprise Linux (RHEL)_-based operating systems.
endif::opennms-prime[]
ifndef::opennms-prime[]
This guide provides instructions for installing the platform on _Red Hat Enterprise Linux (RHEL)_-based and _Debian_-based operating systems.
endif::opennms-prime[]

=== Objectives

* Installing _{opennms-product-name}_ components on a single node using the built-in _JRobin_ as time series storage
* Setup _{opennms-product-name}_ on recommended operating systems
* Login the Web User Interface and change the default admin password

=== Before you begin

The following abbreviations will be used to refer to their respective entry through this documentation.

.Operating Systems
[width="100%", cols="1,4"]
|===
| _RHEL_                       | Red Hat Enterprise Linux 7 or higher, CentOS 8^*^ or higher
ifndef::opennms-prime[]
| _Debian_                     | Debian 9 or higher, Ubuntu 16.04 LTS or higher
endif::opennms-prime[]
| _OpenJDK 11 Development Kit_ | Installed OpenJDK 11 Development Kit
|===

+*+ Technically, users can install OpenNMS on CentOS 7, but our convenient `opennms` meta RPM package, which resolves external things like PostgreSQL, will not work. 
You need to install Postgres10 by yourself.

==== What If I'm Running CentOS 7?

OpenNMS requires PostgreSQL as the database before installation. 
With `yum install opennms`, the package `opennms` is like a convenience package and depends on the PostgreSQL package coming with the CentOS Linux distribution.
CentOS 7 comes only with PostgreSQL 9. 
Horizon 25+ and Meridian 2019+ require PostgreSQL 10+. 

If you want to install Horizon 25+ or Meridian 2019+ on versions older than CentOS 8, the convenience package with `yum install opennms` will not work. 
Instead, you must first install PostgreSQL 10 manually, and then install OpenNMS with `yum install opennms-core opennms-webapp-jetty`.

We recommend you meet the following requirements:

.Installation Requirements
[width="100%", cols="1,4"]
|===
| _Minimal Hardware_ | 2 CPU, 2 GB RAM, 20 GB disk
ifndef::opennms-prime[]
| _Operating System_ | _RHEL_ or _Debian_ in a current version is recommended.
                       Please be aware _{opennms-product-name}_ is developed and mostly operated on Linux systems.
| _Internet_         | Access to _{yum,debian}.opennms.org_ via _https_.
endif::opennms-prime[]
ifdef::opennms-prime[]
| _Operating System_ | The latest version of _RHEL_ is recommended.
                       Please be aware _{opennms-product-name}_ is developed and mostly operated on Linux systems.
endif::opennms-prime[]
| _DNS Setup_        | Please make sure your DNS settings for the OpenNMS server are correct and the localhost name can be resolved.
                       If there is an incorrect or missing _A Resource Record_ for the server hostname, OpenNMS might not start correctly.
                       The Java security manager might not initialize and an _RMI class loader disabled_ exception will be shown.
|===

Depending on the installed operating system, the path for _{opennms-product-name}_ is different.
If the instruction refers to `${OPENNMS_HOME}`, the path is resolved to the following directories:

.Directory Structure
[width="100%", cols="1,4"]
|===
| _RHEL_              | `/opt/opennms`
ifndef::opennms-prime[]
| _Debian_            | `/usr/share/opennms`
endif::opennms-prime[]
|===
