package org.opennms.netmgt.correlation.drools;
import org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine;
import org.opennms.netmgt.xml.event.Event;
import org.opennms.netmgt.xml.event.Parm;
import org.opennms.netmgt.xml.event.Parms;
import org.opennms.netmgt.xml.event.Value;
import org.opennms.netmgt.model.events.EventBuilder;
import org.opennms.netmgt.model.events.EventUtils;
import org.opennms.netmgt.events.api.EventConstants;
import org.drools.core.spi.KnowledgeHelper;

global DroolsCorrelationEngine engine;

declare Event
    @role(event)
    @timestamp(creationTime)
end

declare Thing
    @role( event )
end

rule "test-got-something"
        salience 300
when
        $e : Event(uei matches "uei.opennms.org/nodes/nodeLostService")
then
        System.err.println("9247 got one: " + $e);
        EventBuilder eventBuilder = new EventBuilder("uei.opennms.org/nodes/nodeUp", "Component Correlator");
        eventBuilder.setNodeid($e.getNodeid());
        insert(eventBuilder.getEvent());
        insert(new Thing());
        insert(new Thing());
        engine.sendEvent(eventBuilder.getEvent());
end

rule "test-two-things-in-a-hmmm-wtf"
        salience 100
when
        accumulate( Thing() over window:length(2);
            $cnt: count(1); $cnt == 2)
then
        System.err.println("9247 got two things in time: " + $cnt);
        insert(new String("Test"));
end


// this rule causes a clastcast exception that is deep in the drools framework
// https://issues.jboss.org/browse/JBRULES-2735
// https://issues.jboss.org/browse/JBRULES-2423
//rule "test-two-things-in-time"
//      salience 100
//when
//      accumulate( Event( uei matches ".*reportRunFailed") over window:time(20s);
//              $cnt: count(1); $cnt == 2)
//then
//      System.err.println("9247 got two things in time: " + $cnt);
//end
