package org.opennms.netmgt.correlation.drools;
import org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine;
import org.opennms.netmgt.xml.event.Event;
import org.opennms.netmgt.xml.event.Parm;
import org.opennms.netmgt.xml.event.Parms;
import org.opennms.netmgt.xml.event.Value;
import org.opennms.netmgt.model.events.EventBuilder;
import org.opennms.netmgt.events.api.EventConstants;
import org.opennms.netmgt.capsd.EventUtils;
import org.drools.core.spi.KnowledgeHelper;

global org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine engine;

declare org.opennms.netmgt.xml.event.Event
        @role( event )
end

rule "test-got-something"
        salience 300
when
        $e : Event( uei matches ".*" )
then
        System.err.println("9247 got one: " + $e);
        EventBuilder eventBuilder = new EventBuilder("uei.opennms.org/nodes/nodeDown", "Component Correlator");
        eventBuilder.addParam("nodeid", $e.getNodeid().toString());
        engine.sendEvent(eventBuilder.getEvent());
end

rule "test-got-reportRunFailed"
        salience 200
when
        $e : Event( uei matches ".*reportRunFailed" )
then
        System.err.println("9247 got ReportRunFailed: " + $e);
        EventBuilder eventBuilder = new EventBuilder("uei.opennms.org/nodes/nodeDown", "Component Correlator");
        eventBuilder.addParam("nodeid", $e.getNodeid().toString());
        engine.sendEvent(eventBuilder.getEvent());
end


//rule "test-two-things-in-a-hmmm-wtf"
//        salience 100
//when
//        accumulate( Event( uei matches ".*reportRunFailed") over window:length(2);
//                $cnt: count(1); $cnt == 2)
//then
//        System.err.println("9247 got two things in time: " + $cnt);
//end


// this rule causes a clastcast exception that is deep in the drools framework
// https://issues.jboss.org/browse/JBRULES-2735
// https://issues.jboss.org/browse/JBRULES-2423
//rule "test-two-things-in-time"
//      salience 100
//when
//      accumulate( Event( uei matches ".*reportRunFailed") over window:time(20s);
//              $cnt: count(1); $cnt == 2)
//then
//      System.err.println("9247 got two things in time: " + $cnt);
//end