
= Instrumentation Log Reader
:description: Learn how to use the instrumentation log reader to view how long data collection takes for each node in {page-component-title}.

The instrumentation log reader provides information on how long data collection takes for each node in the system, and which nodes are taking the most time.
You can view this information in the Instrumentation Log Statistics UI:

. Click the *gear* symbol at the top-right of the page.
. Under Additional Tools, select *Instrumentation Log Reader*.

The reader parses the `instrumentation.log` file generated by collectd and analyzes each line to determine the time at which events took place during data collection.
It uses that information to compute the following statistics:

* Average time per collection of a service.
* Average time to persist data for a service.
* Average time between collections for a service.
* Number of times data is collected for a service.
* Total time collecting data for a service.
* Total time persisting data.

You can use the filtering field to filter the displayed services.
