
==== Step 1: Install {opennms-product-name}

.Add apt repository in /etc/apt/sources.list.d/opennms.list and add GPG key
[source, shell]
----
cat << EOF | sudo tee /etc/apt/sources.list.d/opennms.list
deb https://debian.opennms.org stable main
deb-src https://debian.opennms.org stable main
EOF
wget -O - https://debian.opennms.org/OPENNMS-GPG-KEY | apt-key add -
apt update
----

.Installation of {opennms-product-name} with all built-in dependencies
[source, shell]
----
apt -y install opennms
----

The following packages depend on the `opennms` package and will be automatically installed:

* _jicmp6_ and _jicmp_: _Java_ bridge to allow sending _ICMP messages_ from _OpenNMS_ repository.
* _opennms-core_: _OpenNMS_ core services, e.g. _Provisiond_, _Pollerd_ and _Collectd_ from _OpenNMS_ repository.
* _opennms-webapp-jetty_: _OpenNMS_ web application from _OpenNMS_ repository
* _jdk1.8_: _Oracle Java 8_ environment from _OpenNMS_ respository
* _postgresql_: _PostgreSQL_ database server from distribution repository
* _postgresql-libs_: _PostgreSQL_ database from distribution repository

With the successful installed packages the _{opennms-product-name}_ is installed in the following directory structure:

[source, shell]
----
[root@localhost /usr/share/opennms]# tree -L 1
.
└── opennms
   ├── bin
   ├── data
   ├── deploy
   ├── etc -> /etc/opennms
   ├── instances
   ├── jetty-webapps
   ├── lib -> ../java/opennms
   ├── logs -> /var/log/opennms
   ├── share -> /var/lib/opennms
   └── system
----

TIP: We recommend disabling the {opennms-product-name} apt repository after installation to prevent upgrades while it is running.
     _{opennms-product-name}_ requires some manual steps upon upgrade to make sure the database and configuration are consistent in the new version, and on systems with many nodes or lots of events, this can take hours.
     For this reason, it is recommended to exclude the {opennms-product-name} packages from update except when you are planning on performing an upgrade.

[source, shell]
----
apt-mark hold libopennms-java \
              libopennmsdeps-java \
              opennms-common \
              opennms-db
----
