
ifeval::["{page-component-title}" == "Horizon"]
include::../../repos/rpm-horizon.adoc[]
endif::[]

ifeval::["{page-component-title}" == "Meridian"]
include::../../repos/rpm-meridian.adoc[]
endif::[]

.Install {page-component-title} with all built-in dependencies
[source, console, subs="attributes"]
----
sudo dnf -y install opennms
----

TIP: Disable the OpenNMS {page-component-title} repository after installation to prevent unwanted upgrades when upgrading other packages on the server.
After upgrading, {page-component-title} requires manual steps to upgrade configuration files or migrate database schemas to a new version.
We recommend that you exclude the {page-component-title} packages from updates except when you plan to perform an upgrade.

.Disable auto updates for OpenNMS {page-component-title} Core
[source, console]
----
ifeval::["{page-component-title}" == "Horizon"]
sudo dnf config-manager --disable opennms-stable*
endif::[]
ifeval::["{page-component-title}" == "Meridian"]
sudo dnf config-manager --disable meridian
endif::[]
----

.Verify directory structure with the tree command
[source, console]
----
sudo dnf -y install tree
tree /opt/opennms -L 1
----

.Directory structure after successful installation
[source, output]
----
/opt/opennms
├── bin
├── contrib
├── data
├── deploy
├── etc
├── jetty-webapps
├── lib
├── logs -> /var/log/opennms
├── share -> /var/opennms
└── system
----
