NOTE: The installation procedure for PostgreSQL database is taken from the link:https://www.postgresql.org/download/linux/[official PostgreSQL] project website.

.Import the repository signing key
[source, console]
[subs="verbatim,attributes"]
----
sudo dnf -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
sudo dnf -y install postgresql{postgresql-version}-server
----

.Initialize the PostgreSQL database
[source, console]
[subs="verbatim,attributes"]
----
sudo /usr/pgsql-{postgresql-version}/bin/postgresql-{postgresql-version}-setup initdb
----

.Enable PostgreSQL on system boot and start immediately
[source, console]
[subs="verbatim,attributes"]
----
sudo systemctl enable --now postgresql-{postgresql-version}
----

.Create an opennms database user and password
[source, console]
sudo -i -u postgres createuser -P opennms

IMPORTANT: Set a secure password for the `opennms` database user account.

.Create an empty database and set the owner to the opennms user
[source, console]
sudo -i -u postgres createdb -O opennms opennms

.Set a password for PostgreSQL superuser
[source, console]
sudo -i -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'CHANGE_ME';"

IMPORTANT: Set a secure password for your PostgreSQL superuser.
           The superuser is required to initialize and change the database schema for installation and updates.

TIP: If you use PostgreSQL 13 you need to change the authentication method from `ident` to `md5` in the `pg_hba.conf`. In PostgreSQL 14 onwards the default is `scram-sha-256` which you can just use out of the box.
