= HostResourceSWRun Detector

This detector tests the running state of one or more processes.
It does this via SNMP by inspecting the http://www.ietf.org/rfc/rfc2790[HOST-RESOURCES-MIB] hrSwRunTable.
The test matches a given process as hrSwRunName to determine if it exists on the node.

This detector uses SNMP to accomplish its work.
Therefore, systems against which you use it must have an SNMP agent supporting the HOST-RESOURCES-MIB installed and configured.
Most modern SNMP agents, including most distributions of the Net-SNMP agent and the SNMP service that ship with Microsoft Windows, support this MIB.
Out-of-the-box support for HOST-RESOURCES-MIB among commercial Unix operating systems may be somewhat spotty.

NOTE: This detector implements the configuration parameters inherited from the <<provisioning/detectors/SnmpDetector.adoc, SNMP Detector>>.

== Detector facts

[options="autowidth"]
|===
| Implementation | `org.opennms.netmgt.provision.detector.snmp.HostResourceSWRunDetector`
|===

== Configuration and use

.Required parameters for the HostResourceSwRun service detector
[options="header, autowidth"]
|===
| Parameter       | Default | Description
| serviceToDetect | none    | Process name that should be detected
|===

== Examples

[source,xml]
----
<detector name="Process-dhcpd" class="org.opennms.netmgt.provision.detector.snmp.HostResourceSWRunDetector">
    <parameter key="serviceToDetect" value="dhcpd"/>
</detector>
----
