
= SNMP Detector

Use this detector to find and assigns services based on SNMP.
The detector binds a service with a given service name when a particular SNMP OID as scalar or table matches a given criteria.

== Detector facts

[options="autowidth"]
|===
| Implementation | `org.opennms.netmgt.provision.detector.snmp.SnmpDetector`
|===

== Configuration and use

.Parameters for the SNMP service detector
[options="header, autowidth"]
[cols="1,1,4"]
|===
| Parameter        | Default            | Description
3+| *Required*
| oid              | .1.3.6.1.2.1.1.2.0 | SNMP OID for scalar or table to detect the service.
3+| *Optional*
| retry            | agent config       | Number of retries to detect the service.
| timeout          | agent config       | Timeout in milliseconds to wait for a response from the SNMP agent.
| vbvalue          | none               | Expected return value to detect the service. +
                                          If not specified, the service is detected if the SNMP OID returned any kind of valid value. +
                                          Evaluated as a link:https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html[Java Regular Expression].
| hex               | false             | Set `true` if the data is from type HEX-String.
| isTable           | false             | Set `true` if detector should evaluate SNMP tables.
| matchType         | exist             | Set match type to evaluate the expected value in the SNMP table. +
                                          *exist*: the expected #`vbalue`# is ignored and the service is detected if the given table under OID exists. +
                                          *all*: all values in the table must match against expected `vbalue` to detect the service. +
                                          *any*: at least one value in the table must match against expected `vbalue` to detect the service. +
                                          *none*: none of the values should match against expected value to detect service.
| useSnmpProfiles   | false             | Set `true` if detector should use SNMP profiles to detect SNMP service.
| ttl               | 20000             | Time to live, in milliseconds, to wait for a response from a Minion.
|===

== Example for SNMP scalar value

Assume you have a Dell server farm and you want to monitor the global server status provided by the OpenManage Server Administrator.
Global status is provided by a scalar OID `.1.3.6.1.4.1.674.10892.1.200.10.1.2.1`.
The service should be detected automatically if the server supports this OID.

For provisioning, we have a requisition named `Server` that contains all servers in our data center.
We create a detector with the name `Dell-OMSA-Global-State` for this requisition with the following parameters:

.Parameters for the SNMP detector
[options="header, autowidth"]
|===
| Parameter | Value
| name      | Dell-OMSA-Global-State
| oid       | .1.3.6.1.4.1.674.10892.1.200.10.1.2.1
|===

When the requisition Server synchronizes with the service, `Dell-OMSA-Global-State` will be detected if it supports the given SNMP OID.

== Example using SNMP tables

Assume you have a HP server farm and want to monitor the status of logical drives over SNMP provided from the HP Insight Manager.
The status for logical drives is provided in a SNMP Table under `.1.3.6.1.4.1.232.3.2.3.1.1.4`.
The service should be automatically assigned to all servers exposing the given SNMP OID.

For provisioning, we have a requisition named `Server` that contains all server of our data center.
A detector with the name `HP-Insight-Drive-Logical` for this requisition is created with the following parameter:

.Parameters for the SNMP detector
[options="header, autowidth"]
|===
| Parameter | Value
| name      | HP-Insight-Drive-Logical
| oid       | .1.3.6.1.4.1.232.3.2.3.1.1.4
| isTable   | true
|===

When the requisition `Server` is synchronized, the service `HP-Insight-Drive-Logical` will be detected in case they support the given SNMP OID table.
