= Web Detector

Use this detector to find and assign services based on HTTP.

== Detector facts

[options="autowidth"]
|===
| Implementation | `org.opennms.netmgt.provision.detector.web.WebDetector`
|===

== Configuration and use

.Optional parameters for the Web service detector
[options="header, autowidth"]
[cols="1,1,3"]
|===
| Parameter       | Default            | Description
| authEnable      | false              | Whether to enable basic authentication.
| authPassword    | admin              | Password that is required for authentication.
| authPreemtive   | true               | Whether to send basic authentication even if the site did not ask for it.
| authUser        | admin              | Username that is required for authentication.
| headers         | none               | Optional headers to pass in the HTTP request.
| ipMatch         | none               | Matches against specific IP addresses or patterns.
                                         Use filters here to match single addresses or ranges. +
                                         Substring match by default (see note below regarding regular expressions).
| path            | /                  | The relative URL to call in the request.
| port            | 80                 | Port of the web server detector is connecting to.
| queryString     | none               | The query string to add to the URL after a ? (e.g., foo=bar&baz=zot).
| responseRange   | 100-399            | Range for allowed HTTP error codes from the response.
| responseText    | none               | Text to look for in the response body.
                                         This will be matched against every line, and it will be considered a success at the first match. +
                                         Substring match by default (see note below regarding regular expressions).
| retries         | none               | Number of attempts to test a service's up/down status.
| schema          | http               | Protocol/scheme to use.
| serviceName     | WEB                | A custom service name to identify this service.
| timeout         | 2000               | Timeout in milliseconds to wait for a response.
| useHttpV1       | false              | True/false whether to use HTTP 1.0 or 1.1.
| useSSLFilter    | false              | If true, certificate verification is skipped.
| useSystemProxy  | false              | Should the system-wide proxy settings be used? Configure system proxy settings via system properties.
| userAgent       | OpenNMS WebMonitor | Set the user agent field in HTTP header to identify the OpenNMS monitor.
| virtualHost     | none               | Set the virtual host field in HTTP header. +
                                         In case of an HTTPS request, this is also the virtual domain to send as part of the TLS negotiation.
|===

NOTE: If there is a `~` at the beginning of the parameter, the rest of the string will be used as a regular expression pattern match, otherwise the match will be a substring one.
The regular expression match is anchored at the beginning and end of the line, so you will likely need to put a `.*` on both sides of your pattern unless you are going to match on the entire line.

== Example configuration

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<foreign-source date-stamp="2010-06-29T13:15:30.494+02:00" name="test" xmlns="http://xmlns.opennms.org/xsd/config/foreign-source">
  <scan-interval>1d</scan-interval>
      <detector name="ServiceName" class="org.opennms.netmgt.provision.detector.web.WebDetector">
         <parameter key="useSSLFilter" value="true"/>
         <parameter key="port" value="443"/>
         <parameter key="schema" value="https"/>
         <parameter key="timeout" value="5000"/>
         <parameter key="responseText" value="~^.*WoooRegEx.*$"/>
         <parameter key="path" value="/login.jsp"/>
      </detector>
  <policies/>
</foreign-source>
----
