
Your {page-component-title} repository is defined in a file in `/etc/apt/sources.list`.

ifeval::["{page-component-title}" == "Horizon"]
It may be named `opennms-repo-stable-<OSversion>.repo but is not guaranteed to be.
endif::[]

ifeval::["{page-component-title}" == "Meridian"]
It may be named {page-component-title}.repo but is not guaranteed to be.
endif::[]

. Become root.
. Use the text editor of your choice to edit your {page-component-title} repository config to change the `baseurl` of the repository from the old release family to the new release family.
. Enable auto updates:
+
[source, console]
----
sudo apt-mark unhold libopennms-java \
              libopennmsdeps-java \
              opennms-common \
              opennms-db
----

. Purge any cached a data:
+
[source, console]
----
apt-get clean
----

. Make a backup copy of your OpenNMS config:
+
[source, console]
----
rsync -Ppav /opt/opennms/etc /tmp/etc.orig
rsync -Ppav /opt/opennms/jetty-webapps/opennms/WEB-INF /tmp/opennms-web-inf
----

. Upgrade the {page-component-title} packages to the new version:
+
[source, console]
----
apt-get upgrade opennms
----
+
You will see a lot of rpmnew files; `rpm -q {page-component-title}-core` reports the new version is installed.

. Upgrade Java 11 to the latest release:
+
[source, console]
----
apt-get install java-11-openjdk java-11-openjdk-devel
----

. Execute runjava:
+
[source, console]
----
$OPENNMS_HOME/bin/runjava -s
----

. Check for configuration file changes, and update accordingly, using the files you backed up in xref:deployment:upgrade/diff.adoc#run_diff[Idenfity Changed Configuration Files].
+
NOTE: If you upgrade in place, OpenNMS renames any shipped config that conflicts with an existing user-modified config to `.rpmnew`.
Inspect these files manually and reconcile the differences.
Use `diff -Bbw` and `diff -y`.

. Run the opennms installer:
+
[source, console]
----
$OPENNMS_HOME/bin/install -dis
----
+
The upgrade may take some time.
Eventually the following message appears: `Upgrade completed successfully!`

. Clear the Karaf cache:
+
[source, console]
----
yes | $OPENNMS_HOME/bin/fix-karaf-setup.sh
----
. Start OpenNMS {page-component-title}:
+
[source, console]
----
systemctl start opennms.service
----
+
NOTE: `tail -F /var/log/opennms/manager.log` can illustrate at what point in the startup process {page-component-title} is currently.

. Upgrade is complete and operation is resumed.