commands:
  trivy-analyze:
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: what is in workspace
          command: |
            echo "Workspace contents:"
            ls -la ~/project/
      - run:
          name: What is under artifacts
          command: |
            echo "Artifacts contents:"
            ls -la ~/project/artifacts/
      - run:
          name: Combine Trivy Reports
          command: |
            python3 ~/project/.circleci/pyscripts/combine_trivy_reports.py
      
      - store_artifacts:
          path: ~/project/artifacts/filtered_vulnerabilities.txt
          destination: filtered_vulnerabilities.txt

      # - persist_to_workspace:
      #     root: ~/project
      #     paths:
      #       artifacts/filtered_vulnerabilities.txt
        
