
= NetFlow v5

See <<flows/introduction.adoc#ga-flow-support-introduction, Flow Support>> for details on flow support in {page-component-title}.


[[telemetryd-netflow5-parser-udp]]
== Netflow v5 UDP Parser

The Netflow v5 UDP parser accepts packets received by a <<telemetryd/listener/udp.adoc#telemetryd-listener-udp, UDP listener>> and must forward them to a <<telemetryd-netflow5-adapter, Netflow v5 Adapter>>.

The Netflow v5 UDP parser supports protocol detection.

=== Facts

[options="autowidth"]
|===
| Class Name          | `org.opennms.netmgt.telemetry.protocols.netflow.parser.Netflow5UdpParser`
|===

=== Parameters

.Parameters for the Netflow v5 UDP Parser
[options="header, %autowidth"]
|===
| Parameter             | Description                                                                | Required | Default value
| `maxClockSkew`        | The maximum delta in seconds between exporter and Minion timestamps.       | no       | 0
| `clockSkewEventRate`  | Rate limit clock skew events, in seconds.                           | no       | 3600
| `dnsLookupsEnabled`      | Enable or disable DNS resolution for flows.                        | no       | true
|===

[[telemetryd-netflow5-adapter]]
== Netflow v5 Adapter

The Netflow v5 adapter handles Netflow v5 payloads received and parsed by by the <<telemetryd-netflow5-parser-udp, Netflow v5 UDP Parser>>.
Flows are decoded from the messages into the canonical flow format and published to the flow repository.

=== Facts

[options="autowidth"]
|===
| Class Name          | `org.opennms.netmgt.telemetry.protocols.netflow.adapter.netflow5.Netflow5Adapter`
|===

=== Parameters

This adapter does not currently have any configurable parameters.
