
//ui-provd: the contextual help from the external requisition screen links to this help, using the URL https://docs.opennms.com/horizon/latest/reference/provisioning/handlers/introduction.html. Ensure link in UI does not break if changing this section of docs.

[[file-handler]]
= File Handler

The file handler imports a properly-formatted requisition definition from an XML file stored locally on the server.

== Configure file requisition

ifeval::["{page-component-title}" == "Horizon"]
Prior to {page-component-title} 30, you set external requisitions in the `provisiond-configuration.xml` file.
This file is no longer available.
You must use the UI or the xref:development:rest/config_management.adoc#config-rest-api[config management REST API] to configure an external requisition.
endif::[]

To configure a file requisition, follow the steps in xref:reference:provisioning/handlers/introduction.adoc#create-req-def[Create an external requisition], but specify File as the type, and set the path, schedule, and rescan behavior.

== Examples

=== Simple

[source]
----
file:///path/to/my/requisition.xml
----

=== Using the generic handler

[source]
----
requisition://file?path=/path/to/my/requisition.xml;location=MINION
----
