
//ui-provd: the contextual help from the external requisition screen links to this help, using the URL https://docs.opennms.com/horizon/latest/reference/provisioning/handlers/introduction.html. Ensure link in UI does not break if changing this section of docs.

[[requisition-plugin]]
= Requisition Plugins

{page-component-title} provides some experimental plugins that can provision nodes from additional platforms, including software-defined networking, hypervisor, and configuration management database (CMDB) platforms.

* https://github.com/OpenNMS/opennms-opendaylight-plugin[OpenDaylight plugin]
* https://github.com/OpenNMS/opennms-aci-plugin[ACI plugin]
* https://github.com/OpenNMS/pris-plugin[PRIS (Provisioning Integration Server) plugin]
** https://docs.opennms.com/pris/1.3.2/index.html[PRIS documentation]

Each of these plugins has a handler that invokes the plugin with default settings.
Some plugins accept options in the form of query parameters, which shape the requisitions generated by that plugin and imported by Provisiond.

IMPORTANT: These plugins are experimental, with minimal documentation in their associated GitHub repository.