
== Installing a Minion

A Minion is a remote data collector that monitors devices and services in locations that {opennms-product-name} cannot reach. 
Minions communicate with these remote devices while OpenNMS performs coordination and task delegation.

=== Requirements

* Identical version numbers for {opennms-product-name} instance and Minion package
* {opennms-product-name} installed and communication to the REST (8980/tcp) and ActiveMQ (616161/tcp) endpoints is possible (see <<gi-minion-setup-communication, Set Up {opennms-product-name} to allow Minion communication>>)
ifdef::opennms-prime[]

Packages are available as RPMs for RHEL-based systems alongside OpenNMS in the yum repository
endif::opennms-prime[]
ifndef::opennms-prime[]

Packages are available as RPMs for RHEL-based systems and DEBs for Debian-based systems
endif::opennms-prime[]

If the instruction refers to `${MINION_HOME}`, the path for Minion resolves to the following directory, depending on the operating system:

.Directory Structure
[width="100%", cols="1,4"]
|===
| RHEL              | `/opt/minion`
ifndef::opennms-prime[]
| Debian            | `/usr/share/minion`
endif::opennms-prime[]
|===
