
==== Cisco NX-OS Telemetry

The _Cisco NX-OS Telemetry_ allows to push operational statistics asynchronously to _{opennms-product-name}_.
_{opennms-product-name}_ sends a request to stream periodic updates once to the device.
Data is generated as Google protocol buffers (gpb) structured messages over _UDP_.
Detailed information about _NX-OS_ can be found in link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/programmability/guide/b_Cisco_Nexus_9000_Series_NX-OS_Programmability_Guide_7x/b_Cisco_Nexus_9000_Series_NX-OS_Programmability_Guide_7x_chapter_011000.html[NXOS Documentation].

To enable support for NX-OS Telemetry, edit `${OPENNMS_HOME}/etc/telemetryd-configuration.xml` set `enabled=true` for `NXOS` protocol.

.Enable NX-OS protocol in telemetryd-configuration.xml
[source, xml]
----
<protocol name="NXOS" description="Cisco NX-OS Telemetry" enabled="true">
----

Apply the changes without restarting by sending a `reloadDaemonConfig` event in the CLI or the WebUI:

.Send a reloadDaemonConfig event through CLI
[source]
----
${OPENNMS_HOME}bin/send-event.pl -p 'daemonName Telemetryd' uei.opennms.org/internal/reloadDaemonConfig
----

By default, this will open a UDP socket bound to `0.0.0.0:50001` to which _NXOS_ messages can be forwarded.

===== Configure NX-OS Listener on a Minion

To enable and configure an _UDP Listener_ for NX-OS on Minion, connect to the _Karaf Console_ and set the following properties:

[source]
----
$ ssh -p 8201 admin@localhost
...
admin@minion()> config:edit org.opennms.features.telemetry.listeners-udp-50000
admin@minion()> config:property-set name NXOS
admin@minion()> config:property-set class-name org.opennms.netmgt.telemetry.listeners.udp.UdpListener
admin@minion()> config:property-set listener.port 50001
admin@minion()> config:update
----

NOTE: The protocol must also be enabled on _{opennms-product-name}_ for the messages to be processed.
