
Your {page-component-title} repository is defined in a file in `/etc/apt/sources.list`.

ifeval::["{page-component-title}" == "Horizon"]
It may be named `opennms-repo-stable-<OSversion>.repo but is not guaranteed to be.
endif::[]

. Become root.
. Enable auto updates:
+
[source, console]
----
sudo apt-mark unhold libopennms-java \
              libopennmsdeps-java \
              opennms-common \
              opennms-db
----

. Purge any cached data:
+
[source, console]
----
apt-get clean
----

. Make a backup copy of your OpenNMS config:
+
[source, console]
----
rsync -Ppav ${OPENNMS_HOME}/etc /tmp/etc.orig
rsync -Ppav ${OPENNMS_HOME}/jetty-webapps/opennms/WEB-INF /tmp/opennms-web-inf
----

. Upgrade the {page-component-title} packages to the new version:
+
[source, console]
----
apt-get upgrade opennms
----

. Disable auto updates:
+
[source, console]
----
sudo apt-mark hold libopennms-java \
              libopennmsdeps-java \
              opennms-common \
              opennms-db
----

. Upgrade Java 11 to the latest release:
+
[source, console]
----
apt-get install java-11-openjdk java-11-openjdk-devel
----

. Execute `runjava` to update which JVM {page-component-title} will use:
+
[source, console]
----
${OPENNMS_HOME}/bin/runjava -s
----

. Check for configuration file changes, and update accordingly, using the files you backed up in xref:deployment:upgrade/diff.adoc#run_diff[Idenfity Changed Configuration Files].
+
NOTE: Debian prompts you to keep or overwrite your files during the `apt upgrade` process.
Inspect these files manually and reconcile the differences.
Use `diff -Bbw` and `diff -y`.

. Run the {page-component-title} installer:
+
[source, console]
----
${OPENNMS_HOME}/bin/install -dis
----
+
The upgrade may take some time.
Eventually the following message appears: `Upgrade completed successfully!`

. Clear the Karaf cache:
+
[source, console]
----
yes | ${OPENNMS_HOME}/bin/fix-karaf-setup.sh
----
. Start OpenNMS {page-component-title}:
+
[source, console]
----
systemctl start opennms.service
----
+
NOTE: `tail -F ${OPENNMS_HOME}/logs/manager.log` can illustrate the current point in the startup process {page-component-title} is.

. Upgrade is complete and operation is resumed.