
= Daemon Configuration Files

Configuration changes can require a restart of OpenNMS and some daemons are able to reload configuration changes by a running CLI command or by sending a daemon reload event.
This section gives an overview about all daemons and the related configuration files and which can be reloaded without restarting OpenNMS.

== Reload daemons by CLI

To use the reload commands in the CLI, log into the Karaf Shell on your system using:

[source]
----
ssh -p 8101 admin@localhost
----

To reload a daemon use the `reload-daemon` command:
[source]
----
admin@opennms()> reload-daemon NAME
----

A list of reloadable daemons can be obtained by pressing `tabulator` after the command.

== Reload daemons by reload event


.Running reload command in a shell
[source, shell]
----
cd $\{OPENNMS_HOME}/bin
./send-event.pl uei.opennms.org/internal/reloadDaemonConfig --parm 'daemonName NAME'
----

.Running the reload command in Docker
[source, shell]
----
docker exec -it horizon /opt/opennms/bin/send-event.pl  uei.opennms.org/internal/reloadDaemonConfig --parm 'daemonName NAME'
----

== List of daemon configuration files

See Reference section.