
= Develop Documentation

There are different ways to contribute documentation, each suitable for different use cases:

* Publish tutorials and "how to"s in our https://opennms.discourse.group/c/knowledgebase[Discourse knowledge base].
For example, you may want to describe how to use the Net-SNMP agent and the OpenNMS SNMP monitor to solve a special use case.
This is a great way to help other OpenNMS users who might have similar questions, because we sometimes cross-reference these articles in official documentation.
* Contribute formal technical documentation related to the source code on https://github.com/OpenNMS/opennms[GitHub].
* Pick up `quickwin-docs` issues from our https://issues.opennms.org/secure/RapidBoard.jspa?rapidView=34&projectKey=NMS&view=planning&selectedIssue=NMS-13800&issueLimit=100[Jira Documentation backlog].
These are issues that should require only a short amount of time to address.
* Review, suggest improvements for, and provide comments on existing documentation.
* Report bugs, errors, or areas for improvement.

All formal technical documentation should follow a basic structure:

* A descriptive title (for example, "Create a Minion" or "SnmpCollector").
* A brief description of the subject being documented.
* Procedure steps and technical content such as parameters, configuration, and examples, as appropriate.

Minimize the use of screenshots; they should be included only to illustrate a concept that may be difficult to understand, or something that is not easy to locate in the UI.
// See the Images section for more information.

== `opennms` documentation file structure

All OpenNMS projects that have documentation include it in the `docs` directory.
Within this directory, you will find the `./modules` directory, which contains all technical documentation associated with the source code in the repository.
The `./modules` directory may have more nested directories to create a hierarchy for the content (for example, components and subcomponents).

You will find `.adoc` filds in the `./pages` directory or one of its subdirectories, and image files in the `./images` directory or one of its subdirectories.
The following table describes the documentation modules for the Horizon project:

[options="header", cols="1,3"]
|===
| Directory
| Contents

| `docs/modules/operation`
| Documentation for administrators to configure, optimize, and run Horizon.

| `docs/modules/development`
| Documentation for those who want to develop Horizon.

| `docs/modules/deployment`
| Documentation on how to install and configure Horizon on different operating systems.

| `docs/modules/reference`
| Glossary and miscellaneous configuration topics.

| `docs/modules/releasenotes`
| Changelog and release notes.

| `docs/modules/write-the-docs`
| Documentation on how to write docs for the Horizon project.
|===

NOTE: Documentation for other OpenNMS projects (for example, `opennms-helm`) follows a similar hierarchy, as appropriate for the project.

Every new directory or `.adoc` file must be included in the general structure of the documentation, defined by the `nav.adoc` files:

. Create a new doc (in this example, `dosc/modules/operation/pages/meta-data.adoc`)
. Open the directory's `nav.adoc` file (in this example, `docs/modules/operation/nav.adoc`).
. Add a new bullet list entry linking to the new page.
+
In this example, `meta-data.adoc` is located in the main `/operation/pages` directory, so it should be added as a level-one list item.
If the document is located in a sub-directory (for example, `/operation/pages/admin`), it should be added as a level-two list item, and so on.
To add a new level-one list item, use the following syntax:

.Example: Level-one `nav.adoc` list item with defined hyperlink text
[source adoc]
----
* xref:meta-data.adoc[Meta Data]
----

If you choose not to define the hyperlink text within the square brackets, the link will use the top-level heading in the specified file.

. Save your changes and commit them to your active repository branch.

// To test your changes locally, Build the docs.

== Write the docs

When writing documentation, place a single sentence on each line.
This makes it easy to move content around, and to spot long or fragmented sentences.
This will also allow us to assign comments on a single sentence in GitHub for easier review and merging.

Sentences should be concise, easy to read, and written in the present tense.
Refer to the reader in the second-person ("you"); this gives our docs a personable tone.

Avoid the use of abbreviations, especially those derived from Latin (for example, "e.g.," "i.e.," and "etc.").
You should also avoid certain terms because of their cultural history (for example, "abort," "hang," "master," and "slave").
For more information, see the Linguistic Society of America's https://www.linguisticsociety.org/resource/guidelines-inclusive-language[Guidelines for Inclusive Language].

Make sure that there are no trailing spaces at the end of each line.
A single space will automatically be added between each sentence when the docs are built; including trailing spaces affects this spacing.

Use commas to separate words and clauses in a simple series of three or more items (for example, "the mouse, the desktop, and the computer").
Always include a comma before the conjunction.

=== Text formatting conventions

The OpenNMS documentation uses the following conventions:

* File names and paths are written as \`poller-configuration.xml` (rendered as `poller-configuration.xml`).
* Bold field names, button and icon names, and words that require strong emphasis using the \*Bold* syntax (rendered as *Bold*).
* Italicize words that require emphasis using the \_Italics_ syntax (rendered as _Italics_).
* command line commands and configuration file lines are written as \`command` (rendered as `command`).
Note that the contents will not be parsed.
* You can force line breaks by including `+` at the end of a line, followed by a line break.
+
.Example: Forced line break
[source adoc]
----
This is the first line +
and this is a forced second line.
----

Always leave a blank line at the beginning and end of a new `.adoc` file.
Start the content on line 2, setting a relative path to the images directory (if applicable) to allow image rendering on GitHub:

.Example: Set relative path to images directory
[source adoc]
----
:imagesdir: relative/path/to/images/dir
----

Because curly braces (`{}`) are used for AsciiDoc attributes, everything inside the braces will be treated as an attribute.
To include braces without setting attributes, you must escape the opening brace by typing `\{`.
If you do not escape the opening brace, the braces and the text inside them will not be rendered in the final documentation build.

=== Headings and document structure

Each document begins with headings from level one (the document title) and an assigned ID.

.Example: Assigned ID and document title
[source adoc]
----
[[unique-id-verbose-is-ok]]
= The Document Title
----

When writing a document's title, capitalize the following:

* The initial letter of the first word in the title.
* The initial letter in all principal words——that is, words that are not articles ("the," "an," "a"), conjunctions ("and," "but," "or"), or prepositions.
* All prepositions with five or more letters.
* Any preposition that is part of a compound verb (for example, "Backing Up Files").
* Both words in a hyphenated compound (for example, "Year-End Processing"); exceptions are short articles, such as "of-the" in "Run-of-the-Mill."

Subsequent headings should use the following syntax:

.Example: Create subheadings
[source adoc]
----
== Subheading one

... content here ...

=== Sub-subheading one

... content here ...
----

Make sure that headings are brief, specific, and descriptive (for example, "Install server software").
Headings should be capitalized as follows:

* The initial letter of the first word in the heading.
* The initial letter in all proper nouns.

In some cases, sections in the document also need to have assigned IDs; this depends on where they fit in the overall structure.
If you want to have a link to specific content, that content _must_ have an ID.
A missing ID in a mandatory place causes the docs build to fail.

=== IDs and links

Use the target's assigned ID to link to other parts of the documentation.
To refer to a target's assigned ID, use the following syntax:

.Example: Reference assigned ID
[source adoc]
----
<<doc-guidelines-links>>
----

To use your target's assigned ID in a document, simply write the ID in your text.
For example, `see <<target-id>>`.

If you need to link to another document and want to modify the link text, use the following syntax:

.Example: Reference assigned ID with defined link text
[source adoc]
----
<<target-it, link text that fits the context>>
----

To include an external link, use the following syntax:

.Example: Include external link with defined hyperlink text
[source adoc]
----
http://www.opennnms.com[Link text here]
----

Links should have descriptive hyperlink text associated, and should avoid generic phrases (for example, "Click here").
This helps with search engine optimization.

=== Lists

Vertical lists provide clarity, emphasis, and order in documents, and can improve the visual impact when properly formatted.
List items can be sentences, phrases, or single words.
Sequential lists are numbered, and non-sequential lists are not.

When writing a list, follow these guidelines:

* Introduce the list using a complete sentence, followed by a colon (`:`).
Do not treat the list as an extension of this sentence; that is, do not use semicolons or commas to end items, and don't insert "and" or "or" before the last item.
* Capitalize the initial letter of the first word of each item in the list.
* End all items with a period if one or more of the items contains a verb.
* Use parallel structure for all items in a list.

=== Tables

Tables present structured information, and can improve the visual impact of a document when formatted properly.

When creating a table, follow these guidelines:

* Capitalize the initial letter of all principal words in column headings——that is, words that are not articles ("the," "an," "a"), conjunctions ("and," "but," "or"), or prepositions.
* In most cases, do not use end punctuation for column headings, with the exception of ellipses (`...`) when the items in the column complete the phrase begun in the heading.
* For items within a column (with the exception of the heading), use periods for whole sentences only (strings of words that include at least one verb).

In most cases, the "Description" column should appear immediately following the item being described.

Construct tables using the following syntax:

.Example: Construct table with three columns
[source adoc]
----
[options="header", cols="1,3,1"]
|===
| Parameter
| Description
| Default

| myFirstParam
| My first long description.
| myDefault

| mySecondParam
| My second long description.
| myDefault
|===
----

This is rendered as follows:

[options="header", cols="1,3,1"]
|===
| Parameter
| Description
| Default

| myFirstParam
| My first long description.
| myDefault

| mySecondParam
| My second long description.
| myDefault
|===

For tables that are made up of more than two columns, use a separate line for each cell's content and include a blank line to separate rows, as in the code sample above.

For content that has required and optional elements, use the following syntax:

.Example: Construct table with required and optional elements
[source adoc]
----
[options="header", cols="1,3,1"]
|===
| Parameter
| Description
| Default

3+|*Required*

| myFirstParam
| My first long description.
| myDefault

| mySecondParam
| My second long description.
| myDefault

3+|*Optional*

| myThirdParam
| My third long description.
| myDefault
|===
----

Tables should have alt text associated with them; this allows screen readers to provide users with more context for the information being presented.
Alt text should succinctly convey the table's content and function, and should not be redundant.
If it would be redundant, omit it.

=== Code snippets

You can include code snippets, configuration settings, or source code files in documentation.
To enable syntax highlighting, provide the appropriate language parameter; this works for source code and configuration settings.

WARNING: Use explicitly-defined code snippets as sparsely as possible.
Code becomes obsolete very quickly, and directing to archaic practices is detrimental for users.

To include code snippets, use the following syntax:

.Example: Include code snippet
[source adoc]
----
[source]
\----
example code here
\----
----