
= Write the Docs
:description: Read the OpenNMS {page-component-title} technical writing style guide for the standards and best practices for writing content for us. All contributions welcome!

The OpenNMS Group Technical Writing Style Guide is the set of standards for writing our content, to make it consistent and intuitive.
The OpenNMS software is free and open source, and we welcome any kind of contribution.
If you didn't find something in the docs, or you noticed a page that can be expanded upon, feel free to contribute.

Please observe the rules and guidelines outlined here to maintain consistency across the projects.

We use Antora and the AsciiDoc file format (`.adoc`) to create our documentation.
For information on syntax, see Antora's https://docs.antora.org/antora/2.3/asciidoc/asciidoc/[AsciiDoc Primer] guide.

== External style guides

We follow the guidelines established in the https://docs.microsoft.com/en-us/style-guide/welcome/[Microsoft Writing Style Guide].

[[ga-opennms-docs-dictionaries]]
== Dictionaries

We use American English spelling and grammar standards as outlined in the dictionaries below, in order of precedence:

. http://www.merriam-webster.com/[Merriam-Webster Online]
. http://www.dictionary.com/[Dictionary.com]
