
==== Junos Telemetry Interface

The _Junos Telemetry Interface (JTI)_ allows to push operational statistics asynchronously to _{opennms-product-name}_.
_{opennms-product-name}_ sends a request to stream periodic updates once to the device.
Data is generated as Google protocol buffers (gpb) structured messages over _UDP_.
Detailed information about _JTI_ can be found in link:https://www.juniper.net/documentation/en_US/junos/topics/concept/junos-telemetry-interface-oveview.html[Juniper Documentation].

To enable support for Junos Telemetry Interface (JTI), edit `${OPENNMS_HOME}/etc/telemetryd-configuration.xml` set `enabled=true` for `JTI` protocol.

.Enable JTI protocol in telemetryd-configuration.xml
[source, xml]
----
<protocol name="JTI" description="Junos Telemetry Interface (JTI)" enabled="true">
----

Apply the changes without restarting by sending a `reloadDaemonConfig` event in the CLI or the WebUI:

.Send a reloadDaemonConfig event through CLI
[source]
----
${OPENNMS_HOME}bin/send-event.pl -p 'daemonName Telemetryd' uei.opennms.org/internal/reloadDaemonConfig
----

By default, this will open a UDP socket bound to `0.0.0.0:50000` to which _JTI_ messages can be forwarded.

===== Configure JTI Listener on a Minion

To enable and configure an _UDP Listener_ for JTI on Minion, connect to the _Karaf Console_ and set the following properties:

[source]
----
$ ssh -p 8201 admin@localhost
...
admin@minion()> config:edit org.opennms.features.telemetry.listeners-udp-50000
admin@minion()> config:property-set name JTI
admin@minion()> config:property-set class-name org.opennms.netmgt.telemetry.listeners.udp.UdpListener
admin@minion()> config:property-set listener.port 50000
admin@minion()> config:update
----

NOTE: The protocol must also be enabled on _{opennms-product-name}_ for the messages to be processed.
