= Value Mapping Property extender
The Value Mapping property extender provides a mechanism that works like a lookup table for values of a local MIB table column.

== When to use the Value Mapping Property extender
Use the Value Mapping property extender to map an enumerated set of values (e.g. strings) to a corresponding set of values.
This allows to persist changes of string enumeration values as integers over time as time-series.

== Configure the Value Mapping Property Extender
The Value Mapping property extender expects zero or more parameters.
There are currently three parameters with a fixed name:

.Value Mapping Property Extender Parameters
[options="header", cols="1,3,2"]
|===
| Name
| Description
| Default value

3+| *Required*

| source-attribute
| The alias name of the property used for the value lookup.
| n/a

| target-type
| The target data-type, e.g. gauge.
| string

3+| *Optional*

| default-value
| The value for entries that cannot be matched.
| n/a
|===

The remaining parameters are named for the input values, and their values represent the output values.

