[[ga-enlinkd]]
= Enhanced Linkd

Enhanced Linkd (Enlinkd) discovers connections between nodes using data generated by various link discovery protocols and accessible via SNMP.
Enlinkd gathers this data regularly and creates a snapshot of a device's neighbors from its perspective by SNMP data collectors.
Enlinkd consolidates the collected Data by Bridge Domain Discovery and Topologies Updater.

Enlinkd-Bridge Domain Discovery use the data gathered by Bridge and IpNetToMedia collectors to provide Bridge Broadcast Domain layout.
The Bridge Forwarding Table provided by the single nodes displays information about the MAC address learned on which bridge port, this is what the Bridge considers a connection: this is not very useful, so Bridge Discovery performs domain calculations to assign to every MAC address the port where the device that holds it is effectively connected (or the known nearest bridge port).

Enlinkd-Updaters, for every supported discovery protocol, use the provided Topologies Update API to provide connections information to other OpenNMS service and daemon via OnmsTopologyDao.
The provided topologies are used in topology-map and for sending TopologyMessage via Kafka Producer.

The connections discovered by Enlinkd collectors and by Bridge Domain Discovery are called links.
The term link, within the context of Enlinkd, is not synonymous with the term "link" when used with respect to the network OSI Layer 2 domain, whereby a link only indicates a Layer 2 connection.
A link in context of Enlinkd is a more abstract concept and describes any connection between two {page-component-title} nodes.
These links are discovered based on information provided by an agent's understanding of connections at the OSI Layer 2, Layer 3, or other OSI layers.

The topologies that Enlinkd-Updaters discover are made of vertices and edges.

The following sections describe the Enlinkd daemon and its configuration.
Additionally, the supported link discovery implementations are described as well as a list of the SNMP MIBs that the SNMP agents must expose for EnLinkd to gather links between nodes.
You can view detailed information about a node's connections (discovered links) and supporting link data on the node detail page within the {page-component-title} Web UI.

[[ga-enlinkd-daemon]]
== Enlinkd daemon

More information on the enlinkd daemon can be found in our xref:reference:daemons/daemon-config-files/enlinkd.adoc[reference section].
