
[[ga-enlinkd]]
= Enhanced Link Daemon

The enhanced link daemon (enlinkd) discovers connections between nodes using data generated by various link discovery protocols, and that are accessible via SNMP.
Enlinkd gathers this data regularly and uses it to generate a snapshot of a device's neighbors from its perspective, as defined by SNMP data collectors.

The bridge domain discovery process uses the data gathered by the Bridge and IpNetToMedia collectors to generate a bridge broadcast domain layout.
The bridge forwarding tables (BFTs) that are provided by individual nodes display information about the MAC addresses discovered on bridge ports.
This is what the bridge domain discovery process considers a connection; it is not very useful on its own, however, so the process also performs domain calculations to assign each MAC address to the port where the device that holds it is effectively connected (the nearest known bridge port).

Connections that are discovered by the collectors and the bridge domain discovery process are called "links."
These links are discovered based on information that is provided by an agent's understanding of connections at the OSI Layer 2, Layer 3, or other OSI layers.

NOTE: In this context, a "link" does not refer only to the network OSI Layer 2 connection.

The updaters use the topologies update API provided by each supported discovery protocol to provide connections information to other OpenNMS services and daemons via the OnmsTopologyDao.
The topologies are made of verticies and edges, and are used to generate a topology map.
They also allow the Kafka Producer to send TopologyMessage data.

The following pages describe enlinkd and how it can be configured, the supported discovery protocols, and the SNMP MIBs that must be exposed so links between nodes can be gathered.
You can view detailed information about a node's connections and supporting link data on the node detail page in the {page-component-title} web UI.

[[ga-enlinkd-daemon]]
For more information, see xref:reference:daemons/daemon-config-files/enlinkd.adoc[Enlinkd] in the Reference section.
