
// Allow GitHub image rendering
:imagesdir: ../../images

===== Table of Index Mapping

The following table describes the mapping of simple
_{opennms-product-name}_ events to the Raw Events Index and the mapping of Alarm
Change Events to the Alarm Change Events index and  to the Alarms index

[cols="16l,16l,16l,16l,16l,20l",]
|=======================================================================
2+|ALARM INDEX FIELDS 2+|EVENT INDEX FIELDS (ALARM CHANGE and RAW EVENTS) 2+|DESCRIPTION

|EXAMPLE ALARM JSON |ALARM FIELD |EVENT FIELD |EXAMPLE EVENT JSON |type|

| \{ |\{ |\{ | \{ | |

| | | | | |All attributes beginning _ are internal to Elastic Search

| "_index": "opennms-alarms-2017.03", |"_index": |"_index": | "_index":
"opennms-events-alarmchange-2017.03", | |_index is the index in which
this alarm or event exists

| "_type": "alarmdata", |"_type": |"_type": | "_type": "eventdata", |
|_type either alarmdata or eventdata

| "_id": "31", |"_id": |"_id": | "_id": "1110", | |_id field matches the
event or alarm id

| "_score": 1, |"_score": |"_score": | "_score": 1, | |_score is an
internal ES ranking of the search result

| "_source": \{ |"_source": |"_source": | "_source": \{ | |_source
contains the data of the index entry

| | | | | |

| "@timestamp": "2017-03-03T12:44:21.210Z", |"@timestamp":
|"@timestamp": | "@timestamp": "2017-03-02T15:20:56.861Z", |date a| 
For Alarms @timestamp is Alarm creation time (from first event time)
For Events @timestamp is event time from event.getTime()
| "dom": "3", |"dom": |"dom": | "dom": "2", |long |Day of month from
@timestamp

| "dow": "6", |"dow": |"dow": | "dow": "5", |long |Day of week from
@timestamp

| "hour": "12", |"hour": |"hour": | "hour": "15", |long |Hour from
@timestamp

| | |"eventdescr": | "eventdescr": "<p>Alarm <a
href=\"/opennms/alarm/detail.htm?id=30\">30</a> Cleared<p>...", |string
|Description from raw event or alarm change event

| | |"eventseverity": | "eventseverity": "3", |long a|
Severity from raw event or alarm change event

(Note all alarm change events have severity normal)

| | |"eventseverity_text": | "eventseverity_text": "Normal", |string
|Text representation of severity value

| | |"eventsource": | "eventsource": "AlarmChangeNotifier", |string a|
OpenNMS event source

Alarm Change Events come from AlarmChangeNotifier

| | |"eventuei": | "eventuei":
"uei.opennms.org/plugin/AlarmChangeNotificationEvent/AlarmCleared",
|string |OpenNMS uei of event

| | |"id": | "id": "1110", |string |id of the Raw event or Alarm Change
Event

| | |"interface": | "interface": "127.0.0.1", |string a|
Interface of the Raw event or

Alarm Change Event takes interface from the Alarm interface field

| | |"ipaddr": | "ipaddr": "/127.0.0.1", |string a|
IP address of the Raw event or

Alarm Change Event takes IP address from the Alarm interface field

| | |"logmsg": | "logmsg": "<p>Alarm <a
href=\"/opennms/alarm/detail.htm?id=30\">30</a> Cleared<p>", |string a|
Log message of the Raw Event or

Alarm Change Event log message contains link to alarm

| | |"logmsgdest": | "logmsgdest": "logndisplay", |string |Log
Destination of Event

| | |"p_newalarmvalues": a|
 "p_newalarmvalues": "\{ + 
 \"suppressedtime\":\"2017-03-02T14:24:59.282Z\",+ 
 \"systemid\":\"00000000-0000-0000-0000-000000000000\",+ 
 \"suppresseduntil\":\"2017-03-02T14:24:59.282Z\",+ 
 \"description\":\"<p>SNMP data collection on interface 127.0.0.1\\n + 
failed.<\\/p>\", + 
 \"mouseovertext\":null, + 
 \"x733probablecause\":0, + 
 \"lasteventid\":1072, + 
 \"lasteventtime\":\"2017-03-02T14:24:59.282Z\", + 
 \"managedobjectinstance\":null, + 
 \"alarmacktime\":null, + 
 \"qosalarmstate\":null, + 
 \"ipaddr\":\"127.0.0.1\", + 
 \"alarmackuser\":null, + 
 \"nodeid\":88, + 
 \"firsteventtime\":\"2017-03-02T14:24:59.282Z\", + 
 \"severity\":2, + 
 \"ifindex\":null, + 
 \"alarmtype\":1, + 
 \"x733alarmtype\":null, + 
 \"logmsg\":\"SNMP data collection on interface 127.0.0.1 failed with Unexpected exception when collecting SNMP data for interface 127.0.0.1 at location Default.'.\",  + 
 \"tticketid\":null, + 
 \"firstautomationtime\":null, + 
 \"clearkey\":null, + 
 \"managedobjecttype\":null, + 
 \"eventuei\":\"uei.opennms.org\\/nodes\\/dataCollectionFailed\", + 
 \"counter\":1, + 
 \"applicationdn\":null, + 
 \"operinstruct\":null, + 
 \"ossprimarykey\":null, + 
 \"stickymemo\":null, + 
 \"tticketstate\":null, + 
 \"alarmid\":30, + 
 \"serviceid\":5, + 
\"reductionkey\":\"uei.opennms.org\\/nodes\\/dataCollectionFailed::88\", + 
 \"suppresseduser\":null, + 
 \"lastautomationtime\":null, + 
 \"eventparms\":\"reason=Unexpected exception when collecting SNMP data for interface 127.0.0.1 at location Default.(string,text)\"}", + 
 
 |string a|
Alarm and event parameters are name value pairs which can be associated
with alarms or events. All parameters in Alarms or Events are stored in
elastic search in separate index fields with names beginning with p_

Alarm Change Event parameters p_oldalarmvalues and p_newalarmvalue
contain a json string representing the alarm fields before and after the
Alarm change respectively.

The p_newalarmvalue values are copied into the alarm index of the
corresponding alarm (given by alarmid in p_newalarmvalue and by
p_alarmid)

| | |"p_oldalarmvalues": | "p_oldalarmvalues": "\{ .... }", |string |see
p_newalarmvalues

| | |"p_oldseverity": | "p_oldseverity": "5", | |Alarm Change Event
Parameter old severity of the alarm before this alarm change event

| "alarmackduration": "2132249", |"alarmackduration": | | |long |Time in
ms from first event which created the alarm to the latest alarm
acknowledgement

| "alarmacktime": "2017-03-03T13:19:53.351Z", |"alarmacktime":
|"p_alarmacktime": | "p_alarmacktime": "2017-03-03T13:19:53.351Z", | a|
AlarmChangeNotificationEvent/AlarmAcknowledged Event

p_alarmacktime time of acknowledgement

| "alarmackuser": "admin", |"alarmackuser": |"p_alarmackuser" |
"p_alarmackuser": "admin", | a|
AlarmChangeNotificationEvent/AlarmAcknowledged Event

p_alarmackuser name of user who acknowledged the alarm

| "alarmclearduration": "2175014" |"alarmclearduration": | | |long |Time
in ms from first event which created the alarm to the latest alarm clear

| "alarmcleartime": "2017-03-03T13:20:36.224Z", |"alarmcleartime":
|"p_alarmcleartime": | "p_alarmcleartime": "2017-03-03T13:20:36.224Z", |
a|
AlarmChangeNotificationEvent/AlarmClear Event

p_alarmcleartime time of clear

| "alarmid": "31", |"alarmid": |"p_alarmid": | "p_alarmid": "30",
|string |Alarm Change Event Parameter p_alarmid corresponds to the
alarmid of the alarm being changed

| "alarmtype": "1", |"alarmtype": |"p_alarmtype": | "p_alarmtype": "1",
|string |Alarm Change Event Parameter p_alarmtype corresponds to the
p_alarmtype of the alarm being changed

| "applicationdn": null, |"applicationdn": | | |string |

| "asset-category": "Power", |"asset-category": |"asset-category": |
"asset-category": "Power", |string |all asset_ entries correspond to
fields in the Asset Table of the node referenced in the event. These
fields are only present if populated in the asset table

| "asset-building": "55", |"asset-building": |"asset-building": |
"asset-building": "55", |string |

| "asset-room": "F201", |"asset-room": |"asset-room": | "asset-room":
"F201", |string |

| "asset-floor": "Gnd", |"asset-floor": |"asset-floor": | "asset-floor":
"Gnd", |string |

| "asset-rack": "2101", |"asset-rack": |"asset-rack": | "asset-rack":
"2101", |string |

| "categories": "", |"categories": |"categories": | "categories": "",
|string |categories corresponds to node categories table. This is a
comma separated list of categories associated with this nodeid. This
field is indexed so separate values can be searched

| "clearkey": null, |"clearkey": | | |string |

| "counter": "1", |"counter": | | |string |

| "description": "<p>SNMP data collection on interface 127.0.0.1\n
failed.</p>", |"description": | | |string |

| "eventuei": "uei.opennms.org/nodes/dataCollectionFailed", |"eventuei":
|"p_eventuei": | "p_eventuei":
"uei.opennms.org/nodes/dataCollectionFailed", |string |Alarm Change
Event Parameter p_eventuei corresponds to the p_eventuei of the alarm
being changed

| "firstautomationtime": null, |"firstautomationtime": | | |date |

| "firsteventtime": "2017-03-03T12:44:21.210Z", |"firsteventtime": | |
|date |

| "foreignid": "1488375237814", |"foreignid": |"foreignid": |
"foreignid": "1488375237814", |string |foreignid of node associated with
alarm or event

| "foreignsource": "LocalTest", |"foreignsource": |"foreignsource": |
"foreignsource": "LocalTest", |string |foreignsource of node associated
with alarm or event

| "ifindex": null, |"ifindex": | | |string |

| "ipaddr": "127.0.0.1", |"ipaddr": | | |string |

| "lastautomationtime": null, |"lastautomationtime": | | | |

| "lasteventid": "1112", |"lasteventid": | | |string |

| "lasteventtime": "2017-03-03T12:44:21.210Z", |"lasteventtime": | | | |

| "logmsg": "SNMP data collection on interface 127.0.0.1 failed with
'Unexpected exception when collecting SNMP data for interface 127.0.0.1
at location Default.'.", |"logmsg": |"p_logmsg": | "p_logmsg": "SNMP
data collection on interface 127.0.0.1 failed with 'Unexpected exception
when collecting SNMP data for interface 127.0.0.1 at location
Default.'.", |string |

| "managedobjectinstance": null, |"managedobjectinstance": | | |string |

| "managedobjecttype": null, |"managedobjecttype": | | |string |

| "mouseovertext": null, |"mouseovertext": | | |string |

| "nodeid": "88", |"nodeid": |"nodeid": | "nodeid": "88", |string
|nodeid of node associated with alarm or event

| "nodelabel": "localhost", |"nodelabel": |"nodelabel": | "nodelabel":
"localhost", |string |nodelabel of node associated with alarm or event

| "nodesyslocation": "Unknown (edit /etc/snmp/snmpd.conf)",
|"nodesyslocation": |"nodesyslocation": | "nodesyslocation": "Unknown
(edit /etc/snmp/snmpd.conf)", |string |nodesyslocation of node
associated with alarm or event

| "nodesysname": "localhost.localdomain", |"nodesysname":
|"nodesysname": | "nodesysname": "localhost.localdomain", |string
|nodesysname of node associated with alarm or event

| "operatingsystem": null, |"operatingsystem": | | |string |

| "operinstruct": null, |"operinstruct": | | |string |

| "ossprimarykey": null, |"ossprimarykey": | | |string |

| "p_alarmid": "31", |"p_alarmid": | | |string |The Elastic Search
alarms index has a field p_alarmid which corresponds to the alarmid of
thed alarm and also the p_alarmid field in Alarm Change Evens. This
allows Alarm and Alarm Change Event indexes to be easily searched
together for all Alarm Change Events corresponding to an alarm

| "p_reason": "Unexpected exception when collecting SNMP data for
interface 127.0.0.1 at location Default.", |"p_reason": | | |string a|
All parameters in Alarms or Events are stored in elastic search in
separate index fields with names beginning with p_

p_reason is an example parameter injected by the
uei.opennms.org/nodes/dataCollectionFailed event in OpenNMS

| "qosalarmstate": null, |"qosalarmstate": | | |string |

| "reductionkey": "uei.opennms.org/nodes/dataCollectionFailed::88",
|"reductionkey": |"p_reductionkey": | "p_reductionkey":
"uei.opennms.org/nodes/dataCollectionFailed::88", |string |Alarm Change
Event p_reductionkey corresponds to alarm reductionkey

| "serviceid": "5", |"serviceid": |"p_serviceid": | "p_serviceid": "5"
|string |Alarm Change Event p_serviceid corresponds to alarm serviceid

| "severity": "2", |"severity": |"p_severity": | "p_severity": "2",
|string |Alarm Change Event p_severity corresponds to alarm severity

| "severity_text": "Cleared", |"severity_text": | | |string |

| "stickymemo": null, |"stickymemo": |"p_stickymemo" | "p_stickymemo":
null, |string a|
AlarmChangeNotificationEvent/StickyMemoAdded

p_stickymemo content of current sticky memo corresponds to alarm
stickymemo

AlarmChangeNotificationEvent/StickyMemoUpdate

also has parameters

p_author author of stickymemo

p_ body content of sticky memo

AlarmChangeNotificationEvent/JournalMemoUpdate

also has parameters

p_author user who authored the memo

p_body content of the memo

p_reductionkey reduction key associated with memo (corresponds to alarm
reduction key

Note that journal memos do not have an entry in the alarm index but are
only referenced by reduction key

| "suppressedtime": "2017-03-03T12:44:21.210Z", |"suppressedtime":
|"p_suppressedtime": | "p_suppressedtime": "2017-03-02T14:24:59.282Z",
|date |AlarmChangeNotificationEvent/AlarmSuppressed Event
p_suppressedtime corresponds to alarm suppressedtime

| "suppresseduntil": "2017-03-03T12:44:21.210Z", |"suppresseduntil":
|"p_suppresseduntil": | "p_suppresseduntil": "2017-03-02T14:24:59.282Z",
|date |AlarmChangeNotificationEvent/AlarmSuppressed Event
p_suppresseduntil corresponds to alarm suppresseduntil

| "suppresseduser": null, |"suppresseduser": |"p_suppresseduser": |
"p_suppresseduser": null, |string
|AlarmChangeNotificationEvent/AlarmSuppressed Event p_suppresseduser
corresponds to alarm suppressedunti

| "systemid": "00000000-0000-0000-0000-000000000000", |"systemid":
|"p_systemid": | "p_systemid": "00000000-0000-0000-0000-000000000000",
|string |Alarm Change Event p_systemid corresponds to alarm systemid

| "tticketid": null, |"p_tticketid": | | "p_tticketid": null, |string a|
AlarmChangeNotificationEvent/TroubleTicketStateChange

p_tticketid corresponds to alarm tticketid

| "tticketstate": null, |"p_tticketstate": | | "p_tticketstate": null,
|string a|
AlarmChangeNotificationEvent/TroubleTicketStateChange

p_tticketstate corresponds to alarm p_tticketstate

| "x733alarmtype": null, |"x733alarmtype": | | |string |

| "x733probablecause": "0", |"x733probablecause": | | |string |

| } | } | } | } | |

| } |} | } |} | |
|=======================================================================
