[[ref-ssl-selfsigned]]
= Self-Signed Certificate

If you are content with a self-signed certificate, the certificate just needs to be loaded into a keystore and added to the Jetty configuration.


. Add the certificate to a keystore.
+
[source, console]
----
keytool -selfcert -validity 721 -keystore /tmp/propercert/proper.keystore -alias opennms-jetty
Enter keystore password:  aGoodStrongKeystorePassword
Enter key password for <mykey>:  anotherGoodStrongPassword
----

. Copy the keystore into place where {page-component-title} can find it.
In the real world, you might want to place the keystore in a different location, perhaps one that is not included in your nightly backups.
For the purposes of this exercise, we will assume that you copied the keystore to `$\{OPENNMS_HOME}/etc/opennms.keystore`.

. Configure the Jetty HTTPS parameters in OpenNMS.
Create or edit the file `$\{OPENNMS_HOME}/etc/opennms.properties.d/jetty.properties` and set the following properties.
+
[source, properties]
----
org.opennms.netmgt.jetty.https-keystore = ${OPENNMS_HOME}/etc/opennms.keystore <1>
org.opennms.netmgt.jetty.https-keystorepassword = aGoodStrongKeystorePassword <2>
org.opennms.netmgt.jetty.https-keypassword = anotherGoodStrongPassword
org.opennms.netmgt.jetty.https-port = 8443 <3>
org.opennms.netmgt.jetty.https-cert-alias = myOpennmsCertificate <4>
----

<1> Location of the keystore file you created.
<2> Set the password for the keystore and the key as you created them in the first step.
<3> Set the port for Jetty to listen for HTTPS connections.
<4> If you have multiple certificates in the keystore and wish to force Jetty to use a particular certificate, specify the alias of the certificate that you would like to use.
If this option is not present, Jetty will use the first certificate that it finds in the keystore.
