
// Allow GitHub image rendering
:imagesdir: ../../images

[[auto-discovery]]
=== Auto Discovery

Auto discovery is the process of automatically adding nodes to {opennms-product-name}.
You do this through discovery, either periodically on schedule or through single, unscheduled times. 

Make sure you complete the tasks in the xref:getting-started.adoc[Getting Started] section before adding nodes. 

[[discovery-configure]]
==== Configure Discovery

Configuring discovery specifies the parameters {opennms-product-name} uses when scanning for nodes.

. Click the gear icon and in the *Provisioning* area choose *Configure Discovery*.
+
NOTE: To configure a discovery scan to run once, select *Run Single Discovery Scan*. 

. In the *General Settings* area, accept the default scheduling options (sleeptime, retries,timeout, etc.), or set your own.
. From the *Foreign Source* drop-down, select the requisition to which you want to add the discovered nodes.  
. If you have installed Minions, select one from the *Location* drop-down. 
. Click *Add New* to add the following:

+
* specific address (IP addresses to add)
* URLs
* IP address ranges to include
* IP address ranges to exclude 

. Click *Save and Restart Discovery*. 
+
NOTE: For single discovery scan, click *Start Discovery Scan*. 

. When the discovery is finished, navigate to the requisition (*Manage Provisioning Requisitions*) you specified to view the nodes discovered. 
. If desired, edit the nodes or delete them from the requisition, then click *Synchronize* to add them to the {opennms-product-name} database. 
. Repeat this process for each requisition you want to provision. 

