
// Allow GitHub image rendering
:imagesdir: ../../../images

=== Directed Discovery

It is important to understand that the nodes requisitioned from each foreign source are managed as a complete set.
Nodes defined in a requisition from the foreign source _CRM_ and _CMDB_, for example, will be managed separately from each other even if they should contain exactly the same node definitions.
To {opennms-product-name}, these are individual entities and they are managed as a set.

Requisitions are referenced via a URL.
Currently, the URL can be specified as one of the following protocols: FILE, HTTP, HTTPS, and DNS.
Each protocol has a protocol handler that is used to stream the XML from a _foreign source_, i.e. http://inv.corp.org/import.cgi?customer=acme or `file:/opt/opennms/etc/imports/acme.xml`.
The DNS protocol is a special handler developed for Provisioning sets of nodes as a _foreign-source_ from a corporate DNS server.
See DNS Protocol Handler for details.

This determination is made by comparing the set foreign IDs of each node in the requisition set with the set of foreign IDs of currently managed entities in {opennms-product-name}.

When nodes are provisioned using the Provisioning Groups Web-UI, the requisitions are stored on the local file system and the file protocol handler is used to reference the requisition.
Each Provisioning Group is a separate foreign source and unique foreign IDs are generated by the Web-UI.
An MSP might use Provisioning Groups to define the set of nodes to be managed by customer name where each customer’s set of nodes are maintained in a separate Provisioning Group.