
// Allow GitHub image rendering
:imagesdir: ../../images

[[ga-provisioning-introduction]]
=== Introduction

Provisioning is a mechanism to import node and service definitions either from an external source such as DNS or HTTP or via the {opennms-product-name} web UI.
The _Provisiond_ daemon maintains your managed entity inventory through policy-based provisioning. 

Provisiond comes with a RESTFul Web Service API for easy integration with external systems such as CRM or external inventory systems.
It also includes an adapter API for interfacing with other management systems such as configuration management.

For more details on how provisioning works in {opennms-product-name}, see the provisioning white paper on the https://www.opennms.com/[Opennms website]. 

==== How It Works

Provisiond receives requests to add managed entities via two basic mechanisms: the {opennms-product-name} traditional "New Suspect" event, typically via the Discovery daemon, and the import requisition, typically via the Provisioning UI.

IMPORTANT: An import requisition is an XML definition of node entities to be provisioned from a foreign source into {opennms-product-name}.
See the http://xmlns.opennms.org/xsd/config/model-import[requisition schema] (XSD) for more information. 




