/*******************************************************************************
 * This file is part of OpenNMS(R).
 *
 * Copyright (C) 2017 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2017 The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is a registered trademark of The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OpenNMS(R) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with OpenNMS(R).  If not, see:
 *      http://www.gnu.org/licenses/
 *
 * For more information contact:
 *     OpenNMS(R) Licensing <license@opennms.org>
 *     http://www.opennms.org/
 *     http://www.opennms.com/
 *******************************************************************************/

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flows.proto

package org.opennms.netmgt.telemetry.listeners.flow.dto;

public final class Flows {
  private Flows() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Entry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required .Entry.Type type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .Entry.Type type = 2;</code>
     */
    org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type getType();

    /**
     * <code>optional bool bool = 100;</code>
     */
    boolean hasBool();
    /**
     * <code>optional bool bool = 100;</code>
     */
    boolean getBool();

    /**
     * <code>optional fixed64 timestamp = 101;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional fixed64 timestamp = 101;</code>
     */
    long getTimestamp();

    /**
     * <code>optional double float = 102;</code>
     */
    boolean hasFloat();
    /**
     * <code>optional double float = 102;</code>
     */
    double getFloat();

    /**
     * <code>optional bytes ipv4_address = 103;</code>
     */
    boolean hasIpv4Address();
    /**
     * <code>optional bytes ipv4_address = 103;</code>
     */
    com.google.protobuf.ByteString getIpv4Address();

    /**
     * <code>optional bytes ipv6_address = 104;</code>
     */
    boolean hasIpv6Address();
    /**
     * <code>optional bytes ipv6_address = 104;</code>
     */
    com.google.protobuf.ByteString getIpv6Address();

    /**
     * <code>optional bytes mac_address = 105;</code>
     */
    boolean hasMacAddress();
    /**
     * <code>optional bytes mac_address = 105;</code>
     */
    com.google.protobuf.ByteString getMacAddress();

    /**
     * <code>optional bytes bytes = 106;</code>
     */
    boolean hasBytes();
    /**
     * <code>optional bytes bytes = 106;</code>
     */
    com.google.protobuf.ByteString getBytes();

    /**
     * <code>optional sfixed64 signed = 107;</code>
     */
    boolean hasSigned();
    /**
     * <code>optional sfixed64 signed = 107;</code>
     */
    long getSigned();

    /**
     * <code>optional fixed64 unsigned = 108;</code>
     */
    boolean hasUnsigned();
    /**
     * <code>optional fixed64 unsigned = 108;</code>
     */
    long getUnsigned();

    /**
     * <code>optional string string = 109;</code>
     */
    boolean hasString();
    /**
     * <code>optional string string = 109;</code>
     */
    java.lang.String getString();
    /**
     * <code>optional string string = 109;</code>
     */
    com.google.protobuf.ByteString
        getStringBytes();
  }
  /**
   * Protobuf type {@code Entry}
   */
  public static final class Entry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Entry)
      EntryOrBuilder {
    // Use Entry.newBuilder() to construct.
    private Entry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Entry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Entry defaultInstance;
    public static Entry getDefaultInstance() {
      return defaultInstance;
    }

    public Entry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Entry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type value = org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 800: {
              valueCase_ = 100;
              value_ = input.readBool();
              break;
            }
            case 809: {
              valueCase_ = 101;
              value_ = input.readFixed64();
              break;
            }
            case 817: {
              valueCase_ = 102;
              value_ = input.readDouble();
              break;
            }
            case 826: {
              valueCase_ = 103;
              value_ = input.readBytes();
              break;
            }
            case 834: {
              valueCase_ = 104;
              value_ = input.readBytes();
              break;
            }
            case 842: {
              valueCase_ = 105;
              value_ = input.readBytes();
              break;
            }
            case 850: {
              valueCase_ = 106;
              value_ = input.readBytes();
              break;
            }
            case 857: {
              valueCase_ = 107;
              value_ = input.readSFixed64();
              break;
            }
            case 865: {
              valueCase_ = 108;
              value_ = input.readFixed64();
              break;
            }
            case 874: {
              com.google.protobuf.ByteString bs = input.readBytes();
              valueCase_ = 109;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Entry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.class, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder.class);
    }

    public static com.google.protobuf.Parser<Entry> PARSER =
        new com.google.protobuf.AbstractParser<Entry>() {
      public Entry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Entry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Entry> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Entry.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SCOPE = 0;</code>
       */
      SCOPE(0, 0),
      /**
       * <code>DATA = 1;</code>
       */
      DATA(1, 1),
      ;

      /**
       * <code>SCOPE = 0;</code>
       */
      public static final int SCOPE_VALUE = 0;
      /**
       * <code>DATA = 1;</code>
       */
      public static final int DATA_VALUE = 1;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return SCOPE;
          case 1: return DATA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Entry.Type)
    }

    private int bitField0_;
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite {
      BOOL(100),
      TIMESTAMP(101),
      FLOAT(102),
      IPV4_ADDRESS(103),
      IPV6_ADDRESS(104),
      MAC_ADDRESS(105),
      BYTES(106),
      SIGNED(107),
      UNSIGNED(108),
      STRING(109),
      VALUE_NOT_SET(0);
      private int value = 0;
      private ValueCase(int value) {
        this.value = value;
      }
      public static ValueCase valueOf(int value) {
        switch (value) {
          case 100: return BOOL;
          case 101: return TIMESTAMP;
          case 102: return FLOAT;
          case 103: return IPV4_ADDRESS;
          case 104: return IPV6_ADDRESS;
          case 105: return MAC_ADDRESS;
          case 106: return BYTES;
          case 107: return SIGNED;
          case 108: return UNSIGNED;
          case 109: return STRING;
          case 0: return VALUE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.valueOf(
          valueCase_);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type type_;
    /**
     * <code>required .Entry.Type type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Entry.Type type = 2;</code>
     */
    public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type getType() {
      return type_;
    }

    public static final int BOOL_FIELD_NUMBER = 100;
    /**
     * <code>optional bool bool = 100;</code>
     */
    public boolean hasBool() {
      return valueCase_ == 100;
    }
    /**
     * <code>optional bool bool = 100;</code>
     */
    public boolean getBool() {
      if (valueCase_ == 100) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 101;
    /**
     * <code>optional fixed64 timestamp = 101;</code>
     */
    public boolean hasTimestamp() {
      return valueCase_ == 101;
    }
    /**
     * <code>optional fixed64 timestamp = 101;</code>
     */
    public long getTimestamp() {
      if (valueCase_ == 101) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }

    public static final int FLOAT_FIELD_NUMBER = 102;
    /**
     * <code>optional double float = 102;</code>
     */
    public boolean hasFloat() {
      return valueCase_ == 102;
    }
    /**
     * <code>optional double float = 102;</code>
     */
    public double getFloat() {
      if (valueCase_ == 102) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }

    public static final int IPV4_ADDRESS_FIELD_NUMBER = 103;
    /**
     * <code>optional bytes ipv4_address = 103;</code>
     */
    public boolean hasIpv4Address() {
      return valueCase_ == 103;
    }
    /**
     * <code>optional bytes ipv4_address = 103;</code>
     */
    public com.google.protobuf.ByteString getIpv4Address() {
      if (valueCase_ == 103) {
        return (com.google.protobuf.ByteString) value_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int IPV6_ADDRESS_FIELD_NUMBER = 104;
    /**
     * <code>optional bytes ipv6_address = 104;</code>
     */
    public boolean hasIpv6Address() {
      return valueCase_ == 104;
    }
    /**
     * <code>optional bytes ipv6_address = 104;</code>
     */
    public com.google.protobuf.ByteString getIpv6Address() {
      if (valueCase_ == 104) {
        return (com.google.protobuf.ByteString) value_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int MAC_ADDRESS_FIELD_NUMBER = 105;
    /**
     * <code>optional bytes mac_address = 105;</code>
     */
    public boolean hasMacAddress() {
      return valueCase_ == 105;
    }
    /**
     * <code>optional bytes mac_address = 105;</code>
     */
    public com.google.protobuf.ByteString getMacAddress() {
      if (valueCase_ == 105) {
        return (com.google.protobuf.ByteString) value_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int BYTES_FIELD_NUMBER = 106;
    /**
     * <code>optional bytes bytes = 106;</code>
     */
    public boolean hasBytes() {
      return valueCase_ == 106;
    }
    /**
     * <code>optional bytes bytes = 106;</code>
     */
    public com.google.protobuf.ByteString getBytes() {
      if (valueCase_ == 106) {
        return (com.google.protobuf.ByteString) value_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int SIGNED_FIELD_NUMBER = 107;
    /**
     * <code>optional sfixed64 signed = 107;</code>
     */
    public boolean hasSigned() {
      return valueCase_ == 107;
    }
    /**
     * <code>optional sfixed64 signed = 107;</code>
     */
    public long getSigned() {
      if (valueCase_ == 107) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }

    public static final int UNSIGNED_FIELD_NUMBER = 108;
    /**
     * <code>optional fixed64 unsigned = 108;</code>
     */
    public boolean hasUnsigned() {
      return valueCase_ == 108;
    }
    /**
     * <code>optional fixed64 unsigned = 108;</code>
     */
    public long getUnsigned() {
      if (valueCase_ == 108) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }

    public static final int STRING_FIELD_NUMBER = 109;
    /**
     * <code>optional string string = 109;</code>
     */
    public boolean hasString() {
      return valueCase_ == 109;
    }
    /**
     * <code>optional string string = 109;</code>
     */
    public java.lang.String getString() {
      java.lang.Object ref = "";
      if (valueCase_ == 109) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8() && (valueCase_ == 109)) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string string = 109;</code>
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 109) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 109) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      type_ = org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type.SCOPE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (valueCase_ == 100) {
        output.writeBool(
            100, (boolean)((java.lang.Boolean) value_));
      }
      if (valueCase_ == 101) {
        output.writeFixed64(
            101, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 102) {
        output.writeDouble(
            102, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 103) {
        output.writeBytes(
            103, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
      }
      if (valueCase_ == 104) {
        output.writeBytes(
            104, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
      }
      if (valueCase_ == 105) {
        output.writeBytes(
            105, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
      }
      if (valueCase_ == 106) {
        output.writeBytes(
            106, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
      }
      if (valueCase_ == 107) {
        output.writeSFixed64(
            107, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 108) {
        output.writeFixed64(
            108, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 109) {
        output.writeBytes(109, getStringBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (valueCase_ == 100) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              100, (boolean)((java.lang.Boolean) value_));
      }
      if (valueCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(
              101, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 102) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              102, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 103) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              103, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
      }
      if (valueCase_ == 104) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              104, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
      }
      if (valueCase_ == 105) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              105, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
      }
      if (valueCase_ == 106) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              106, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
      }
      if (valueCase_ == 107) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(
              107, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 108) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(
              108, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 109) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(109, getStringBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Entry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Entry)
        org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Entry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.class, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder.class);
      }

      // Construct using org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type.SCOPE;
        bitField0_ = (bitField0_ & ~0x00000002);
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Entry_descriptor;
      }

      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry getDefaultInstanceForType() {
        return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.getDefaultInstance();
      }

      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry build() {
        org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry buildPartial() {
        org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry result = new org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (valueCase_ == 100) {
          result.value_ = value_;
        }
        if (valueCase_ == 101) {
          result.value_ = value_;
        }
        if (valueCase_ == 102) {
          result.value_ = value_;
        }
        if (valueCase_ == 103) {
          result.value_ = value_;
        }
        if (valueCase_ == 104) {
          result.value_ = value_;
        }
        if (valueCase_ == 105) {
          result.value_ = value_;
        }
        if (valueCase_ == 106) {
          result.value_ = value_;
        }
        if (valueCase_ == 107) {
          result.value_ = value_;
        }
        if (valueCase_ == 108) {
          result.value_ = value_;
        }
        if (valueCase_ == 109) {
          result.value_ = value_;
        }
        result.bitField0_ = to_bitField0_;
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry) {
          return mergeFrom((org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry other) {
        if (other == org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        switch (other.getValueCase()) {
          case BOOL: {
            setBool(other.getBool());
            break;
          }
          case TIMESTAMP: {
            setTimestamp(other.getTimestamp());
            break;
          }
          case FLOAT: {
            setFloat(other.getFloat());
            break;
          }
          case IPV4_ADDRESS: {
            setIpv4Address(other.getIpv4Address());
            break;
          }
          case IPV6_ADDRESS: {
            setIpv6Address(other.getIpv6Address());
            break;
          }
          case MAC_ADDRESS: {
            setMacAddress(other.getMacAddress());
            break;
          }
          case BYTES: {
            setBytes(other.getBytes());
            break;
          }
          case SIGNED: {
            setSigned(other.getSigned());
            break;
          }
          case UNSIGNED: {
            setUnsigned(other.getUnsigned());
            break;
          }
          case STRING: {
            valueCase_ = 109;
            value_ = other.value_;
            onChanged();
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.valueOf(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type type_ = org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type.SCOPE;
      /**
       * <code>required .Entry.Type type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Entry.Type type = 2;</code>
       */
      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type getType() {
        return type_;
      }
      /**
       * <code>required .Entry.Type type = 2;</code>
       */
      public Builder setType(org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Entry.Type type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Type.SCOPE;
        onChanged();
        return this;
      }

      /**
       * <code>optional bool bool = 100;</code>
       */
      public boolean hasBool() {
        return valueCase_ == 100;
      }
      /**
       * <code>optional bool bool = 100;</code>
       */
      public boolean getBool() {
        if (valueCase_ == 100) {
          return (java.lang.Boolean) value_;
        }
        return false;
      }
      /**
       * <code>optional bool bool = 100;</code>
       */
      public Builder setBool(boolean value) {
        valueCase_ = 100;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool bool = 100;</code>
       */
      public Builder clearBool() {
        if (valueCase_ == 100) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional fixed64 timestamp = 101;</code>
       */
      public boolean hasTimestamp() {
        return valueCase_ == 101;
      }
      /**
       * <code>optional fixed64 timestamp = 101;</code>
       */
      public long getTimestamp() {
        if (valueCase_ == 101) {
          return (java.lang.Long) value_;
        }
        return 0L;
      }
      /**
       * <code>optional fixed64 timestamp = 101;</code>
       */
      public Builder setTimestamp(long value) {
        valueCase_ = 101;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 timestamp = 101;</code>
       */
      public Builder clearTimestamp() {
        if (valueCase_ == 101) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional double float = 102;</code>
       */
      public boolean hasFloat() {
        return valueCase_ == 102;
      }
      /**
       * <code>optional double float = 102;</code>
       */
      public double getFloat() {
        if (valueCase_ == 102) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }
      /**
       * <code>optional double float = 102;</code>
       */
      public Builder setFloat(double value) {
        valueCase_ = 102;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double float = 102;</code>
       */
      public Builder clearFloat() {
        if (valueCase_ == 102) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional bytes ipv4_address = 103;</code>
       */
      public boolean hasIpv4Address() {
        return valueCase_ == 103;
      }
      /**
       * <code>optional bytes ipv4_address = 103;</code>
       */
      public com.google.protobuf.ByteString getIpv4Address() {
        if (valueCase_ == 103) {
          return (com.google.protobuf.ByteString) value_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>optional bytes ipv4_address = 103;</code>
       */
      public Builder setIpv4Address(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 103;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes ipv4_address = 103;</code>
       */
      public Builder clearIpv4Address() {
        if (valueCase_ == 103) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional bytes ipv6_address = 104;</code>
       */
      public boolean hasIpv6Address() {
        return valueCase_ == 104;
      }
      /**
       * <code>optional bytes ipv6_address = 104;</code>
       */
      public com.google.protobuf.ByteString getIpv6Address() {
        if (valueCase_ == 104) {
          return (com.google.protobuf.ByteString) value_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>optional bytes ipv6_address = 104;</code>
       */
      public Builder setIpv6Address(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 104;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes ipv6_address = 104;</code>
       */
      public Builder clearIpv6Address() {
        if (valueCase_ == 104) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional bytes mac_address = 105;</code>
       */
      public boolean hasMacAddress() {
        return valueCase_ == 105;
      }
      /**
       * <code>optional bytes mac_address = 105;</code>
       */
      public com.google.protobuf.ByteString getMacAddress() {
        if (valueCase_ == 105) {
          return (com.google.protobuf.ByteString) value_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>optional bytes mac_address = 105;</code>
       */
      public Builder setMacAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 105;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes mac_address = 105;</code>
       */
      public Builder clearMacAddress() {
        if (valueCase_ == 105) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional bytes bytes = 106;</code>
       */
      public boolean hasBytes() {
        return valueCase_ == 106;
      }
      /**
       * <code>optional bytes bytes = 106;</code>
       */
      public com.google.protobuf.ByteString getBytes() {
        if (valueCase_ == 106) {
          return (com.google.protobuf.ByteString) value_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>optional bytes bytes = 106;</code>
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 106;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes bytes = 106;</code>
       */
      public Builder clearBytes() {
        if (valueCase_ == 106) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional sfixed64 signed = 107;</code>
       */
      public boolean hasSigned() {
        return valueCase_ == 107;
      }
      /**
       * <code>optional sfixed64 signed = 107;</code>
       */
      public long getSigned() {
        if (valueCase_ == 107) {
          return (java.lang.Long) value_;
        }
        return 0L;
      }
      /**
       * <code>optional sfixed64 signed = 107;</code>
       */
      public Builder setSigned(long value) {
        valueCase_ = 107;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sfixed64 signed = 107;</code>
       */
      public Builder clearSigned() {
        if (valueCase_ == 107) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional fixed64 unsigned = 108;</code>
       */
      public boolean hasUnsigned() {
        return valueCase_ == 108;
      }
      /**
       * <code>optional fixed64 unsigned = 108;</code>
       */
      public long getUnsigned() {
        if (valueCase_ == 108) {
          return (java.lang.Long) value_;
        }
        return 0L;
      }
      /**
       * <code>optional fixed64 unsigned = 108;</code>
       */
      public Builder setUnsigned(long value) {
        valueCase_ = 108;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 unsigned = 108;</code>
       */
      public Builder clearUnsigned() {
        if (valueCase_ == 108) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional string string = 109;</code>
       */
      public boolean hasString() {
        return valueCase_ == 109;
      }
      /**
       * <code>optional string string = 109;</code>
       */
      public java.lang.String getString() {
        java.lang.Object ref = "";
        if (valueCase_ == 109) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 109) {
            if (bs.isValidUtf8()) {
              value_ = s;
            }
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string string = 109;</code>
       */
      public com.google.protobuf.ByteString
          getStringBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 109) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 109) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string string = 109;</code>
       */
      public Builder setString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 109;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string string = 109;</code>
       */
      public Builder clearString() {
        if (valueCase_ == 109) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string string = 109;</code>
       */
      public Builder setStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 109;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Entry)
    }

    static {
      defaultInstance = new Entry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Entry)
  }

  public interface FlowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Flow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required fixed64 sourceId = 1;</code>
     *
     * <pre>
     *    required fixed64 timestamp = 2;
     * </pre>
     */
    boolean hasSourceId();
    /**
     * <code>required fixed64 sourceId = 1;</code>
     *
     * <pre>
     *    required fixed64 timestamp = 2;
     * </pre>
     */
    long getSourceId();

    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    java.util.List<org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry> 
        getEntriesList();
    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry getEntries(int index);
    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    int getEntriesCount();
    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    java.util.List<? extends org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder> 
        getEntriesOrBuilderList();
    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder getEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Flow}
   */
  public static final class Flow extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Flow)
      FlowOrBuilder {
    // Use Flow.newBuilder() to construct.
    private Flow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Flow(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Flow defaultInstance;
    public static Flow getDefaultInstance() {
      return defaultInstance;
    }

    public Flow getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Flow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              sourceId_ = input.readFixed64();
              break;
            }
            case 794: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                entries_ = new java.util.ArrayList<org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry>();
                mutable_bitField0_ |= 0x00000002;
              }
              entries_.add(input.readMessage(org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Flow_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Flow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow.class, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow.Builder.class);
    }

    public static com.google.protobuf.Parser<Flow> PARSER =
        new com.google.protobuf.AbstractParser<Flow>() {
      public Flow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Flow(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Flow> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SOURCEID_FIELD_NUMBER = 1;
    private long sourceId_;
    /**
     * <code>required fixed64 sourceId = 1;</code>
     *
     * <pre>
     *    required fixed64 timestamp = 2;
     * </pre>
     */
    public boolean hasSourceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed64 sourceId = 1;</code>
     *
     * <pre>
     *    required fixed64 timestamp = 2;
     * </pre>
     */
    public long getSourceId() {
      return sourceId_;
    }

    public static final int ENTRIES_FIELD_NUMBER = 99;
    private java.util.List<org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry> entries_;
    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    public java.util.List<org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry> getEntriesList() {
      return entries_;
    }
    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    public java.util.List<? extends org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder> 
        getEntriesOrBuilderList() {
      return entries_;
    }
    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <code>repeated .Entry entries = 99;</code>
     */
    public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder getEntriesOrBuilder(
        int index) {
      return entries_.get(index);
    }

    private void initFields() {
      sourceId_ = 0L;
      entries_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSourceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getEntriesCount(); i++) {
        if (!getEntries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, sourceId_);
      }
      for (int i = 0; i < entries_.size(); i++) {
        output.writeMessage(99, entries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, sourceId_);
      }
      for (int i = 0; i < entries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(99, entries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Flow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Flow)
        org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.FlowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Flow_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Flow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow.class, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow.Builder.class);
      }

      // Construct using org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntriesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sourceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.internal_static_Flow_descriptor;
      }

      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow getDefaultInstanceForType() {
        return org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow.getDefaultInstance();
      }

      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow build() {
        org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow buildPartial() {
        org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow result = new org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sourceId_ = sourceId_;
        if (entriesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            entries_ = java.util.Collections.unmodifiableList(entries_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.entries_ = entries_;
        } else {
          result.entries_ = entriesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow) {
          return mergeFrom((org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow other) {
        if (other == org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow.getDefaultInstance()) return this;
        if (other.hasSourceId()) {
          setSourceId(other.getSourceId());
        }
        if (entriesBuilder_ == null) {
          if (!other.entries_.isEmpty()) {
            if (entries_.isEmpty()) {
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEntriesIsMutable();
              entries_.addAll(other.entries_);
            }
            onChanged();
          }
        } else {
          if (!other.entries_.isEmpty()) {
            if (entriesBuilder_.isEmpty()) {
              entriesBuilder_.dispose();
              entriesBuilder_ = null;
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000002);
              entriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntriesFieldBuilder() : null;
            } else {
              entriesBuilder_.addAllMessages(other.entries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSourceId()) {
          
          return false;
        }
        for (int i = 0; i < getEntriesCount(); i++) {
          if (!getEntries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Flow) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long sourceId_ ;
      /**
       * <code>required fixed64 sourceId = 1;</code>
       *
       * <pre>
       *    required fixed64 timestamp = 2;
       * </pre>
       */
      public boolean hasSourceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed64 sourceId = 1;</code>
       *
       * <pre>
       *    required fixed64 timestamp = 2;
       * </pre>
       */
      public long getSourceId() {
        return sourceId_;
      }
      /**
       * <code>required fixed64 sourceId = 1;</code>
       *
       * <pre>
       *    required fixed64 timestamp = 2;
       * </pre>
       */
      public Builder setSourceId(long value) {
        bitField0_ |= 0x00000001;
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 sourceId = 1;</code>
       *
       * <pre>
       *    required fixed64 timestamp = 2;
       * </pre>
       */
      public Builder clearSourceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry> entries_ =
        java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          entries_ = new java.util.ArrayList<org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry>(entries_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder> entriesBuilder_;

      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public java.util.List<org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry> getEntriesList() {
        if (entriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entries_);
        } else {
          return entriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public int getEntriesCount() {
        if (entriesBuilder_ == null) {
          return entries_.size();
        } else {
          return entriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry getEntries(int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);
        } else {
          return entriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public Builder setEntries(
          int index, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.set(index, value);
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public Builder setEntries(
          int index, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.set(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public Builder addEntries(org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public Builder addEntries(
          int index, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(index, value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public Builder addEntries(
          org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public Builder addEntries(
          int index, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public Builder addAllEntries(
          java.lang.Iterable<? extends org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry> values) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entries_);
          onChanged();
        } else {
          entriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public Builder clearEntries() {
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public Builder removeEntries(int index) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.remove(index);
          onChanged();
        } else {
          entriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder getEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder getEntriesOrBuilder(
          int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);  } else {
          return entriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public java.util.List<? extends org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder> 
           getEntriesOrBuilderList() {
        if (entriesBuilder_ != null) {
          return entriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entries_);
        }
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder addEntriesBuilder() {
        return getEntriesFieldBuilder().addBuilder(
            org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder addEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().addBuilder(
            index, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .Entry entries = 99;</code>
       */
      public java.util.List<org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder> 
           getEntriesBuilderList() {
        return getEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder> 
          getEntriesFieldBuilder() {
        if (entriesBuilder_ == null) {
          entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.Entry.Builder, org.opennms.netmgt.telemetry.listeners.flow.dto.Flows.EntryOrBuilder>(
                  entries_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          entries_ = null;
        }
        return entriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Flow)
    }

    static {
      defaultInstance = new Flow(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Flow)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Entry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Entry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Flow_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Flow_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013flows.proto\"\233\002\n\005Entry\022\013\n\003key\030\001 \002(\t\022\031\n\004" +
      "type\030\002 \002(\0162\013.Entry.Type\022\016\n\004bool\030d \001(\010H\000\022" +
      "\023\n\ttimestamp\030e \001(\006H\000\022\017\n\005float\030f \001(\001H\000\022\026\n" +
      "\014ipv4_address\030g \001(\014H\000\022\026\n\014ipv6_address\030h " +
      "\001(\014H\000\022\025\n\013mac_address\030i \001(\014H\000\022\017\n\005bytes\030j " +
      "\001(\014H\000\022\020\n\006signed\030k \001(\020H\000\022\022\n\010unsigned\030l \001(" +
      "\006H\000\022\020\n\006string\030m \001(\tH\000\"\033\n\004Type\022\t\n\005SCOPE\020\000" +
      "\022\010\n\004DATA\020\001B\007\n\005value\"1\n\004Flow\022\020\n\010sourceId\030" +
      "\001 \002(\006\022\027\n\007entries\030c \003(\0132\006.EntryB1\n/org.op" +
      "ennms.netmgt.telemetry.listeners.flow.dt",
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Entry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Entry_descriptor,
        new java.lang.String[] { "Key", "Type", "Bool", "Timestamp", "Float", "Ipv4Address", "Ipv6Address", "MacAddress", "Bytes", "Signed", "Unsigned", "String", "Value", });
    internal_static_Flow_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Flow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Flow_descriptor,
        new java.lang.String[] { "SourceId", "Entries", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
