.Configure PostgreSQL database access

You can store your PostgreSQL credentials in the secure credentials vault.
To do this, use the `scvcli` command line utility to add the credentials, and reference these credentials in `opennms-datasources.xml`:

. Create encrypted credentials for the PostgreSQL database connections:
+
[source, console]
----
sudo -u opennms ${OPENNMS_HOME}/bin/scvcli set postgres opennms password <1>
sudo -u opennms ${OPENNMS_HOME}/bin/scvcli set postgres-admin postgres password
----
<1> Replace both `password` instances with the actual passwords for your `opennms` and `postgres` database accounts.

. Edit `opennms-datasources.xml` with `vi`:
+
[source, console]
sudo -u opennms vi /opt/opennms/etc/opennms-datasources.xml

. Set encrypted credentials to access the PostgreSQL database:
+
[source, xml]
----
...
<jdbc-data-source name="opennms"
                    database-name="opennms" <1>
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/opennms" <2>
                    user-name="${scv:postgres:username}" <3>
                    password="${scv:postgres:password}" /> <4>

<jdbc-data-source name="opennms-admin"
                    database-name="template1"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/template1" <5>
                    user-name="${scv:postgres-admin:username}" <6>
                    password="${scv:postgres-admin:password}" /> <7>
...
<jdbc-data-source name="opennms-monitor"
                    database-name="postgres"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/postgres" <8>
                    user-name="${scv:postgres-admin:username}" <9>
                    password="${scv:postgres-admin:password}" /> <10>
...
----
<1> Set the database name that {page-component-title} should use.
<2> Set the JDBC connection string to your Postregres server for the instance database.
<3> Set the user name to access the opennms database table.
<4> Set the password to access the opennms database table.
<5> Set the JDBC connection string to your Postregres server for the schema database
<6> Set the postgres user for administrative access to PostgreSQL.
<7> Set the password for administrative access to PostgreSQL.
<8> Set the JDBC connection string to your Postregres server for the system database.
<9> Set the postgres user for administrative access to PostgreSQL.
<10> Set the password for administrative access to PostgreSQL.

.Detect and assign Java environment and persist in /opt/opennms/etc/java.conf
[source, console]
----
sudo /opt/opennms/bin/runjava -s
----

.Initialize the database and detect system libraries persisted in /opt/opennms/etc/libraries.properties
[source, console]
----
sudo /opt/opennms/bin/install -dis
----

[[initialize-core-cap]]
._Assign CAP_NET_RAW capabilities_
{page-component-title} runs as a non-root user, which requires having a Linux kernel greater than 3.10.
If you run on an older kernel and you cannot upgrade your OS, you need to assign `CAP_NET_RAW` capabilities:

. Run `systemctl edit opennms.service` and add the following code to the `[Service]` section:
+
[source, properties]
----
AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE
----

Reload the systemd unit with `systemctl daemon-reload` and restart the service with `systemctl restart opennms`.

(For more background on this issue, see https://opennms.discourse.group/t/h29-wont-start-with-permission-error-to-open-icmp-socket/2387[H29+ won't start with permission error to open ICMP socket] on Discourse.)

.Enable {page-component-title} core instance on system boot and start immediately
[source, console]
----
sudo systemctl enable --now opennms
----

[[initialize-core-firewall]]
.Allow connection to the web UI from your network
[source, console]
----
sudo firewall-cmd --permanent --add-port=8980/tcp
sudo systemctl reload firewalld
----
