.Configure PostgreSQL database access

You can store your PostgreSQL credentials in the secure credentials vault.
To do this, use the `scvcli` command line utility to add the credentials, and reference these credentials in `opennms-datasources.xml`:

. Create encrypted credentials for the PostgreSQL database connections:
+
[source, console]
----
sudo -u opennms ${OPENNMS_HOME}/bin/scvcli set postgres opennms password <1>
sudo -u opennms ${OPENNMS_HOME}/bin/scvcli set postgres-admin postgres password
----
<1> Replace both `password` instances with the actual passwords for your `opennms` and `postgres` database accounts.

. Edit `opennms-datasources.xml` with `vi`:
+
[source, console]
sudo -u opennms vi /opt/opennms/etc/opennms-datasources.xml

. Set encrypted credentials to access the PostgreSQL database:
+
[source, xml]
----
...
<jdbc-data-source name="opennms"
                    database-name="opennms" <1>
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/opennms" <2>
                    user-name="${scv:postgres:username}" <3>
                    password="${scv:postgres:password}" /> <4>

<jdbc-data-source name="opennms-admin"
                    database-name="template1"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/template1" <5>
                    user-name="${scv:postgres-admin:username}" <6>
                    password="${scv:postgres-admin:password}" /> <7>
...
<jdbc-data-source name="opennms-monitor"
                    database-name="postgres"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/postgres" <8>
                    user-name="${scv:postgres-admin:username}" <9>
                    password="${scv:postgres-admin:password}" /> <10>
...
----
<1> Set the database name that {page-component-title} should use.
<2> Set the JDBC connection string to your Postregres server for the instance database.
<3> Set the user name to access the opennms database table.
<4> Set the password to access the opennms database table.
<5> Set the JDBC connection string to your Postregres server for the schema database
<6> Set the postgres user for administrative access to PostgreSQL.
<7> Set the password for administrative access to PostgreSQL.
<8> Set the JDBC connection string to your Postregres server for the system database.
<9> Set the postgres user for administrative access to PostgreSQL.
<10> Set the password for administrative access to PostgreSQL.

.Detect and assign Java environment and persist in /opt/opennms/etc/java.conf
[source, console]
----
sudo /opt/opennms/bin/runjava -s
----

.Initialize the database and detect system libraries persisted in /opt/opennms/etc/libraries.properties
[source, console]
----
sudo /opt/opennms/bin/install -dis
----

.Define any necessary xref:operation:deep-dive/admin/configuration/startup.adoc[startup configuration], such as open file descriptors or maximum Java heap
[source, console]
----
echo "JAVA_HEAP_SIZE=16384" | sudo tee ${OPENNMS_HOME}/etc/opennms.conf
echo "MAXIMUM_FILE_DESCRIPTORS=512000" | sudo tee -a ${OPENNMS_HOME}/etc/opennms.conf
----
NOTE: These values are provided as examples; ideal values will vary based on your environment and workload

.Enable {page-component-title} core instance on system boot and start immediately
[source, console]
----
sudo systemctl enable --now opennms
----

[[initialize-core-firewall]]
.Allow connection to the web UI from your network
[source, console]
----
sudo firewall-cmd --permanent --add-port=8980/tcp
sudo systemctl reload firewalld
----
