.Configure PostgreSQL database access
[source, console]
----
sudo vi /opt/opennms/etc/opennms-datasources.xml
----

.Set credentials to access the PostgreSQL database
[source, xml]
----
<jdbc-data-source name="opennms"
                    database-name="opennms"<1>
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/opennms"
                    user-name="** YOUR-OPENNMS-USERNAME **"<2>
                    password="** YOUR-OPENNMS-PASSWORD **" /><3>

<jdbc-data-source name="opennms-admin"
                    database-name="template1"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/template1"
                    user-name="postgres"<4>
                    password="** YOUR-POSTGRES-PASSWORD **" /><5>
----

<1> Set the database name _{page-component-title}_ should use
<2> Set the user name to access the _opennms_ database table
<3> Set the password to access the _opennms_ database table
<4> Set the _postgres_ user for administrative access to PostgreSQL
<5> Set the password for administrative access to PostgreSQL

.Detect and assign _Java_ environment and persist in /opt/opennms/etc/java.conf
[source, console]
----
sudo /opt/opennms/bin/runjava -s
----

.Initialize the database and detect system libraries persisted in /opt/opennms/etc/libraries.properties
[source, console]
----
sudo /opt/opennms/bin/install -dis
----

.Enable {page-component-title} core server on system boot and start immediately
[source, console]
----
sudo systemctl enable --now opennms
----

.Allow connection to the Web UI from your network
[source, console]
----
sudo firewall-cmd --permanent --add-port=8980/tcp
sudo systemctl reload firewalld
----

TIP: If you want to receive SNMP Traps or Syslog messages you have to allow incoming traffic on your host firewall as well.
     By default OpenNMS {page-component-title} SNMP trap daemon is listening on 162/udp and Syslog daemon is listening on 10514/udp.
     The SNMP Trap daemon is enabled by default, the OpenNMS Syslog daemon is disabled.
