[[backup]]
= Back up OpenNMS {page-component-title}

OpenNMS {page-component-title} configurations and performance data storage methods can differ a lot depending on the customer needs.
This article describes the backup process of a default installation of OpenNMS {page-component-title}.
OpenNMS {page-component-title} binaries, logs, RRD archives, configurations and the database will be backed up.
NOTE: In this example the backup storage path is `/backup` for demonstration purposes.

[[backup-objectives]]
== Objectives

* Create backup of OpenNMS {page-component-title} components
* Create PostgreSQL database backup
* Being able to run a disaster recovery without having OpenNMS packages available

[[backup-requirements]]
== Requirements

* Linux physical server or a virtual machine running a supported xref:deployment:core/system-requirements.adoc#operating-systems-core[Linux operating system]
* System user with administrative permissions (sudo) to perform installation
* Database password for `opennms` and `postgres` user

== Create backups

[{tabs}]
====
ifeval::["{page-component-title}" == "Horizon"]
Debian/Ubuntu::
+
--
include::backup-debian-ubuntu.adoc[]
--
endif::[]
====

