package org.opennms.netmgt.correlation.drools;

import java.util.Date;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

import org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine;
import org.opennms.netmgt.xml.event.Event;

global org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine engine;

rule "create a file"
	when
		$e : Event(uei == "uei.opennms.org/junit/myTestEvent")
	then
		createFile($e); 
end

function void createFile(Event e) {
  try {
    Files.write(Paths.get("target/sample-file.txt"), e.toString().getBytes(), StandardOpenOption.CREATE_NEW);
  } catch (Exception e) {}
}

This should not exist