
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-rrdtool-time-series-database]]
== RRDtool

In most _Open Source_ applications, link:http://oss.oetiker.ch/rrdtool[RRDtool] is often used and is the de-facto open standard for _Time Series Data_.
The basic installation of _OpenNMS_ comes with _JRobin_ but it is simple to switch the system to use _RRDtool_ to persist _Time Series Data_.
This section describes how to install _RRDtool_, the _jrrd2_ _OpenNMS Java Interface_ and how to configure _OpenNMS_ to use it.
_RRDtool_ can be installed from the official package repositories provided by _RHEL_ and _Debian_ based _Linux_ distributions.


[[gi-rrdtool-install]]
=== RHEL

.Installation on RHEL/CentOS
[source, shell]
----
yum install rrdtool
----

[[gi-rrdtool-install-debian]]
=== Debian

.Installation of RRDtool on Debian/Ubuntu
[source, shell]
----
apt-get install rrdtool
----

[[gi-rrdtool-install-source]]
=== Source

If you want the latest version of RRDtool, you may want to compile it from source. Instructions for doing so are at 
link:https://oss.oetiker.ch/rrdtool/doc/rrdbuild.en.html[rrdbuild].

IMPORTANT: The latest version of RRDtool may not always be compatible with the version of _OpenNMS_ that you want to run.
           Please ask about RRDtool support on the discussion lists or chat rooms if you have any problems running a
           new version of RRDtool.

NOTE: If you want to install the latest _RRDtool_ from source, make sure the `rrdtool` binary is in search path.
      To make the setup easier, you can link the binary to `/usr/bin/rrdtool` which is the location where _OpenNMS_ will expect
      to find the executable binary.

[[gi-jrrd2-install]]
=== Install jrrd2 Interface

To get access from the _OpenNMS Java Virtual Machine_ you have to install _jrrd2_ as an interface.
You can install it from the _OpenNMS_ package repository with:

.Installation of _jrrd2_ on RHEL/CentOS
[source, shell]
----
yum install jrrd2
----

.Installation of _jrrd2_ on Debian/Ubuntu
[source, shell]
----
apt-get install jrrd2
----

NOTE: With OpenNMS 17.0.0 it is preferred to use _jrrd2_ instead of _jrrd_.
      The _jrrd2_ module is improved for performance by adding multithreading capabilities.

[[gi-rrdtool-configure-opennms]]
=== Configure {opennms-product-name}

To configure _OpenNMS_ to use _RRDtool_ instead of _JRobin_ configure the following properties in `rrd-configuration.properties`.

.Configuration of RRDtool in OpenNMS on RHEL/CentOS
[source]
----
org.opennms.rrd.strategyClass=org.opennms.netmgt.rrd.rrdtool.MultithreadedJniRrdStrategy
org.opennms.rrd.interfaceJar=/usr/share/java/jrrd2.jar
opennms.library.jrrd2=/usr/lib64/libjrrd2.so
----

.Configuration of RRDtool in OpenNMS on Debian/Ubuntu
[source]
----
org.opennms.rrd.strategyClass=org.opennms.netmgt.rrd.rrdtool.MultithreadedJniRrdStrategy
org.opennms.rrd.interfaceJar=/usr/share/java/jrrd2.jar
opennms.library.jrrd2=/usr/lib/jni/libjrrd2.so
----

TIP: _OpenNMS_ expects the _RRDtool_ binary in `/usr/bin/rrdtool`.

.References to the RRDtool binary
[options="header, autowidth"]
|===
| Configuration file                | Property
| `opennms.properties`              | `rrd.binary=/usr/bin/rrdtool`
| `response-adhoc-graph.properties` | `command.prefix=/usr/bin/rrdtool`
| `response-graph.properties`       | `command.prefix=/usr/bin/rrdtool` +
                                      `info.command=/usr/bin/rrdtool`
| `snmp-adhoc-graph.properties`     | `command.prefix=/usr/bin/rrdtool`
| `snmp-graph.properties`           | `command.prefix=/usr/bin/rrdtool` +
                                      `command=/usr/bin/rrdtool info`
|===
