[[setting-up-basic-sentinel]]
= Setting up a Sentinel Runtime

[[objectives]]
== Objectives

* Setting up a {page-component-title} Sentinel running on one of the following <<minion/system-requirements.adoc#operating-systems-Core, Operating Systems>>
* Sentinel can be configured with the Karaf Shell from the server via `ssh admin@localhost -p 8301`

== Requirements

* Linux physical server or a virtual machine running a supported Linux operating system
* Internet access to download the installation packages
* Ensure DNS is configured, localhost and your servers host name is resolved properly
* {page-component-title} Core instance runs on latest stable release
* System user with administrative permissions (sudo) to perform the installation tasks

ifeval::["{page-component-title}" == "Horizon"]
CAUTION: If you run Debian, you have to install and configure `sudo` yourself.
         A guide can be found in the link:https://wiki.debian.org/sudo/[Debian Wiki].
endif::[]

== Installing the Sentinel package

[{tabs}]
====
CentOS/RHEL 7::
+
--
include::centos-rhel7/step-1-install-sentinel.adoc[]
--

CentOS/RHEL 8::
+
--
include::centos-rhel8/step-1-install-sentinel.adoc[]
--

ifeval::["{page-component-title}" == "Horizon"]
Debian::
+
--
include::debian/step-1-install-sentinel.adoc[]
--

Ubuntu::
+
--
include::ubuntu/step-1-install-sentinel.adoc[]
--
endif::[]
====

== Secure Access to Karaf Shell

IMPORTANT: Change the default user/password _admin/admin_ for the Karaf shell and encrypt it.

[{tabs}]
====
CentOS/RHEL 7/8::
+
--
include::centos-rhel/step-2-secure-karaf.adoc[]
--

ifeval::["{page-component-title}" == "Horizon"]
Debian/Ubuntu::
+
--
include::debian-ubuntu/step-2-secure-karaf.adoc[]
--
endif::[]
====

TIP: Changing the password or encryption algorithm get applied immediately.
     It is not required to restart the Sentinel

TIP: By default the Karaf Shell is restricted to 127.0.0.1.
     If you want enable remote access, set `sshHost=0.0.0.0` in `org.apache.karaf.shell.cfg`.
     The change is applied immediately and a Sentinel restart is not required.
     If you have firewall running on your host, allow `8301/tcp` to grant access to the Karaf Shell.