
[[newts-configure]]
= Configure {page-component-title} Core to Use Newts

.Create a configuration file with the time series storage settings
[source, console]
----
sudo vi etc/opennms.properties.d/timeseries.properties
----

.Configure Newts as the time series strategy
[source, properties]
----
# Configure storage strategy
org.opennms.rrd.storeByForeignSource=true<1>
org.opennms.timeseries.strategy=newts<2>

# One year in seconds
org.opennms.newts.config.ttl=31540000<3>

# Seven days in seconds
org.opennms.newts.config.resource_shard=604800<4>

# Configure Newts time series storage connection
org.opennms.newts.config.driver_settings_file=/opt/opennms/etc/cassandra-driver.conf<5>
----

<1> Associate time series data by the foreign ID instead of the database-generated Node-ID.
<2> Set time series strategy to use `newts`.
<3> Retention rate for the time series data.
<4> Shard metrics every 7 days.
<5> The path to your driver configuration file

.Create a configuration file with the time series storage settings
[source, console]
----
sudo vi etc/cassandra-driver.conf
----

.Configure the Cassandra driver settings
[source, properties]
----
datastax-java-driver {
  basic.contact-points = [ "example-node1:9042", "example-node2:9042" ]<1>
  session-keyspace = "newts"<2>
  basic.load-balancing-policy {
    local-datacenter = datacenter1<3>
  }
  advanced.auth-provider {
    class = PlainTextAuthProvider <4>
    username = cassandra
    password = cassandra
  }
}
----

<1>	`Hostname:port` or `IP address:port` of one or more Cassandra cluster nodes.
<2> Name of the keyspace which is initialized and used.
<3> The local datacenter as defined by your Cassandra configuration
<4> The authentication provider to use with the supplied credentials

.Initialize the Newts schema in Cassandra
[source, console]
----
bin/newts init
----

.Connect to Cassandra with the CQL shell
[source, console]
----
cd ${CASSANDRA_HOME}/bin
./cqlsh
----

.Verify if the keyspace was properly initialized
[source, console]
----
use newts;
describe table terms;
describe table samples;
----

.Apply changes and verify your configuration
[source, console]
----
systemctl restart opennms
----

With this information set, upon restart, {page-component-title} will begin persisting metrics using the Newts engine.

Go to the Node detail page from a SNMP-managed device and verify that you see response time graphs for ICMP and node-level performance data.
Only metrics stored in Newts are displayed in graphs.
If you have data in RRD or JRB files, they will not be displayed unless they are xref:time-series-storage/newts/newts-repository-converter.adoc[migrated to Newts].
