
// Allow GitHub image rendering
:imagesdir: ../../images

=== Advanced Minion Configuration

This section provides information for advanced configuration topics, such as _Syslog_, _SNMP Trap_ receiving or running in non-root environments.

[[gi-install-minion-rhel-ping]]
==== Configure Linux to Allow Non-Root ICMP

By default, _Linux_ does not allow regular users to perform `ping` operations from arbitrary programs (including _Java_).
To enable the _Minion_ to ping properly, you must set a `sysctl` option.

.Enable User Ping (Running System)d
[source, shell]
----
# run this command as root to allow ping by any user (does not survive reboots)
sysctl net.ipv4.ping_group_range='0 429496729'
----

If you wish to restrict the range further, use the _GID_ for the user the _Minion_ will run as, rather than `429496729`.

To enable this permanently, create a file in `/etc/sysctl.d/` to set the range:

./etc/sysctl.d/99-zzz-non-root-icmp.conf
[source, shell]
----
# we start this filename with "99-zzz-" to make sure it's last, after anything else that might have set it
net.ipv4.ping_group_range=0 429496729
----

[[gi-install-minion-rhel-trapd]]
==== Configure Minion to Receive Traps

If you wish your Minion to listen to _SNMP Traps_, you will need to configure your firewall to port forward from the privileged trap port (162) to the Minion's default trap listener on port 1162.

.Forward 162 to 1162 with Firewalld
[source, shell]
----
# enable masquerade to allow port-forwards
firewall-cmd --add-masquerade
# forward port 162 TCP and UDP to port 1162 on localhost
firewall-cmd --add-forward-port=port=162:proto=udp:toport=1162:toaddr=127.0.0.1
firewall-cmd --add-forward-port=port=162:proto=tcp:toport=1162:toaddr=127.0.0.1
----

[[gi-install-minion-rhel-syslogd]]
==== Configure Minion to Receive Syslog Messages

If you wish your Minion to listen to syslog messages, you will need to configure your firewall to port forward from the privileged _Syslog_ port (514) to the Minion's default syslog listener on port 1514.

.Forward 514 to 1514 with Firewalld
[source, shell]
----
# enable masquerade to allow port-forwards
firewall-cmd --add-masquerade
# forward port 514 TCP and UDP to port 1514 on localhost
firewall-cmd --add-forward-port=port=514:proto=udp:toport=1514:toaddr=127.0.0.1
firewall-cmd --add-forward-port=port=514:proto=tcp:toport=1514:toaddr=127.0.0.1
----

[[gi-install-minion-config-file]]
==== Minion Configuration File

Beside manually configuring a _Minion_ instance via the _Karaf CLI_ it is possibleto modify and deploy its configuration file through configuration management tools.
The configuration file is located in `${MINION_HOME}/etc/org.opennms.minion.controller.cfg`.
All configurations set in _Karaf CLI_ will be persisted in this configuration file which can also be populated through configuration management tools.

.Configuration file for Minion
[source]
----
id = 00000000-0000-0000-0000-deadbeef0001
location = MINION
broker-url = tcp://myopennms.example.org:61616
http-url = http://myopennms.example.org:8980/opennms
----

The _Minion_ needs to be restarted when this configuration file is changed.

TIP: In case the credentials needs to be set through the _CLI_ with configuration management tools or scripts, the `/opt/minion/bin/client` command can be used which allows to execute _Karaf_ commands through the Linux shell.
