
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-minion-configure]]
=== Configuring Minion

This section describes how to configure _Minion_ once installed and started.

Once the _Minion_ service is started and the _Karaf_ shell is accessible, you can configure the _Minion_ to point to your _OpenNMS_ instance.

NOTE: By default the _Minion_ is configured to communicate with _OpenNMS_ via `localhost`.

.Configure the _Minion's_ location and URLs for communication with _OpenNMS_
[source]
----
admin@minion()> config:edit org.opennms.minion.controller
admin@minion()> config:property-set http-url http://opennms-fqdn:8980/opennms
admin@minion()> config:property-set broker-url tcp://opennms-fdqn:61616
admin@minion()> config:property-set location RDU
admin@minion()> config:update
----

.Configure the credentials to use when communicating with _OpenNMS_
[source]
----
admin@minion()> scv:set opennms.http admin admin
admin@minion()> scv:set opennms.broker admin admin
----

.Restart the Minion after updating the credentials
[source]
----
[root@localhost /root]# $ systemctl restart minion
----

NOTE: The credentials are configured separately since they are encrypted on disk.

[[gi-install-minion-configure-verify]]
==== Verifying Connectivity

Once the URLs and credentials for communicating with the _OpenNMS_ instance are configured, you can verify connectivity using:

.Verify connectivity with the _OpenNMS_ controller
[source]
----
admin@minion()> minion:ping
Connecting to ReST...
OK
Connecting to Broker...
OK
admin@minion()>
----
