
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-minion-configure-opennms]]
=== Configuring OpenNMS

Minions communicate with {opennms-product-name} via _ReST_, and over an _ActiveMQ_ broker.
Some configuration is required to setup and secure these communication channels.

==== Authentication and Authorization

The `minion` role includes the minimal amount of permissions required for a _Minion_ to operate.

This guide will assume you have created a user called `minion`, with a password of `minion` that has been associated to the `minion` role.

==== Configure ActiveMQ

_{opennms-product-name}_ embeds an _ActiveMQ_ broker which, by default, cannot be accessed remotely via the network.
In order to make the _ActiveMQ_ broker accessible remotely, you must edit `$OPENNMS_HOME/etc/opennms-activemq.xml` and
uncomment the `transportConnector` with the `tcp://0.0.0.0:61616` URI.

[source,xml]
----
<!-- Uncomment this line to allow external TCP connections -->
<!--
  WARNING: Access to port 61616 should be firewalled to prevent unauthorized injection
  of data into OpenNMS when this port is open.
-->
<transportConnector name="openwire" uri="tcp://0.0.0.0:61616?useJmx=false&amp;maximumConnections=1000&amp;wireformat.maxFrameSize=104857600"/>
----

If you wish to restrict _ActiveMQ_ connections to only one particular external IP address, you can change `0.0.0.0` to that
desired IP address.

[[gi-install-minion-configure]]
=== Configuring Minion

This section describes how to configure _Minion_ once it has been installed and started.

Once the _Minion_ service is started and the _Karaf_ shell is accessible, you can configure the _Minion_ to point it at your _{opennms-product-name}_ instance.

NOTE: By default the _Minion_ is configured to communicate with _{opennms-product-name}_ via `localhost`.

.Configure the _Minion's_ location and communication endpoints to _{opennms-product-name}_
[source]
----
[root@localhost /root]# $ ssh -p 8201 admin@localhost
...
admin@minion()> config:edit org.opennms.minion.controller
admin@minion()> config:property-set http-url http://opennms-fqdn:8980/opennms
admin@minion()> config:property-set broker-url tcp://opennms-fdqn:61616
admin@minion()> config:property-set location RDU
admin@minion()> config:update
----

.Configure the communication credentials for _{opennms-product-name}_
[source]
----
admin@minion()> scv:set opennms.http minion minion
admin@minion()> scv:set opennms.broker minion minion
----

.Restart the Minion after updating the credentials
[source]
----
[root@localhost /root]# $ systemctl restart minion
----

NOTE: The credentials are configured separately since they are encrypted on disk.

[[gi-install-minion-configure-verify]]
==== Verifying Connectivity

Once the URLs and credentials for communicating with the _{opennms-product-name}_ instance are configured, you can verify connectivity using:

.Verify connectivity with the _{opennms-product-name}_ controller
[source]
----
admin@minion()> minion:ping
Connecting to ReST...
OK
Connecting to Broker...
OK
admin@minion()>
----
