
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-minion-debian]]
==== Debian/Ubuntu

Start by <<gi-install-opennms-repo-releases,setting up the OpenNMS Apt repository>> and <<gi-install-oracle-java,installing Java>>.

Once the _Apt_ repository has been configured:

.Install the _Minion_ packages
[source, bash]
----
apt-get update
apt-get -y install opennms-minion
----

The following packages will be automatically installed:

* _opennms-minion_: The Minion meta package
* _opennms-minion-container_: The _Karaf_ OSGi container with _Minion_ branding and additional management extensions
* _opennms-minion-features-core_: Core utilities and services required by the _Minion_ features
* _opennms-minion-features-default_: Service-specific features

The _Minion_ packages setup the following directory structure:

[source, shell]
----
[root@localhost /usr/share/minion]# $ tree -L 1
.
├── bin
├── deploy
├── etc
├── lib
├── repositories
└── system
----

Additionally, symbolic links are set up pointing to `/etc/minion` and `/var/log/minion` to match Debian's expected filesystem layout.

===== Configuring Startup

The Minion's startup configuration can be changed by editing the `/etc/default/minion` file.  It allows you to override many of the defaults used at startup including the location of your JDK, how much memory to use, and what user to run as.

===== Starting the Minion

After successful installation a `minion` service can be started and enabled using standard Debian commands.

.System startup configuration for _Minion_
[source, shell]
----
update-rc.d minion enable
----

.Startup _Minion_
[source, shell]
----
service minion start
----

After starting _Minion_ the shell can be accessed locally on ssh://localhost:8201.
The default login user is _admin_ and the password is initialized to _admin_.

[source, shell]
----
[root@localhost /root]# $ ssh -p 8201 admin@localhost
----
