
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-minion]]
== Installing Minion

_Minion_ gives enterprises the ability to create a globally distributed, scalable monitoring fabric.

IMPORTANT: Support for _Minion_ is currently _experimental_ and packages are only available for RHEL based systems.

NOTE: Before attempting to setup _Minion_, you must have an instance of _OpenNMS_ set up using the same version of the packages.

_Minion_ can be installed on the same system as _OpenNMS_ or on other systems provided that it can communicate with:

. The OpenNMS REST interface
. The ActiveMQ broker used by OpenNMS

_OpenNMS_ embeds an _ActiveMQ_ broker which, by default, cannot be accessed remotely via the network.
In order to make the _ActiveMQ_ broker accessible remotely, you must edit `$OPENNMS_HOME/etc/opennms-activemq.xml` and 
uncomment the `transportConnector` with the `tcp://0.0.0.0:61616` URI.

[source,xml]
----
<!-- Uncomment this line to allow external TCP connections -->
<!-- 
  WARNING: Access to port 61616 should be firewalled to prevent unauthorized injection 
  of data into OpenNMS when this port is open.
-->
<transportConnector name="openwire" uri="tcp://0.0.0.0:61616?useJmx=false&amp;maximumConnections=1000&amp;wireformat.maxFrameSize=104857600"/>
----

If you wish to restrict ActiveMQ connections to only one particular external IP address, you can change `0.0.0.0` to that
desired IP address.