
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-minion]]
=== Installing Minion

This section describes how to install the _Minion_ and how to configure it to communicate with a central _{opennms-product-name}_ instance.

Installing a distributed _{opennms-product-name}_ requires:

* Instance of _{opennms-product-name}_ needs to be same version as _Minion_ Packages
* Packages are only available as _RPMs_ for _RHEL_-based systems
* _{opennms-product-name}_ needs to be installed and the communication to the _ReST_ and _ActiveMQ_ endpoints is possible

[[gi-install-minion-rhel]]
==== RHEL

NOTE: This description was built on _RHEL 7_ and _CentOS 7.1_.

Start by <<gi-install-rhel-repository,setting up the OpenNMS Yum repository>> and <<gi-install-oracle-java,installing Java>>.

Once the _Yum_ repository has been configured:

.Install the _Minion_ packages
[source, bash]
----
yum -y install opennms-minion
----

The following packages will be automatically installed:

* _opennms-minion_: The Minion meta package
* _opennms-minion-container_: The _Karaf_ OSGi container with _Minion_ branding and additional management extensions
* _opennms-minion-features-core_: Core utilities and services required by the _Minion_ features
* _opennms-minion-features-default_: Service-specific features

The _Minion_ packages setup the following directory structure:

[source, shell]
----
[root@localhost /opt/minion]# $ tree -L 1
.
├── bin
├── deploy
├── etc
├── lib
├── repositories
└── system
----

After successful installation a `minion` service can be started and enabled using _systemd_ commands.

.System startup configuration for _Minion_
[source, shell]
----
systemctl enable minion
----

.Startup _Minion_
[source, shell]
----
systemctl start minion
----

After starting _Minion_ the shell can be accessed locally on ssh://localhost:8201.
The default login user is _admin_ and the password is initialized to _admin_.

[source, shell]
----
[root@localhost /root]# $ ssh -p 8201 admin@localhost
----
