
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-minion-rhel]]
==== RHEL

NOTE: This description was built on _RHEL 7_ and _CentOS 7.1_.

Start by <<gi-install-opennms-repo-releases,setting up the OpenNMS Yum repository>> and <<gi-install-oracle-java,installing Java>>.

Once the _Yum_ repository has been configured:

.Install the _Minion_ packages
[source, bash]
----
yum -y install opennms-minion
----

The following packages will be automatically installed:

* _opennms-minion_: The Minion meta package
* _opennms-minion-container_: The _Karaf_ OSGi container with _Minion_ branding and additional management extensions
* _opennms-minion-features-core_: Core utilities and services required by the _Minion_ features
* _opennms-minion-features-default_: Service-specific features

The _Minion_ packages setup the following directory structure:

[source, shell]
----
[root@localhost /opt/minion]# $ tree -L 1
.
├── bin
├── deploy
├── etc
├── lib
├── repositories
└── system
----

===== Configuring Startup

The Minion's startup configuration can be changed by editing the `/etc/sysconfig/minion` file.  It allows you to override many of the defaults used at startup including the location of your JDK, how much memory to use, and what user to run as.

===== Starting the Minion

After successful installation a `minion` service can be started and enabled using _systemd_ commands.

.System startup configuration for _Minion_
[source, shell]
----
systemctl enable minion
----

.Startup _Minion_
[source, shell]
----
systemctl start minion
----

After starting _Minion_ the shell can be accessed locally on ssh://localhost:8201.
The default login user is _admin_ and the password is initialized to _admin_.

[source, shell]
----
[root@localhost /root]# $ ssh -p 8201 admin@localhost
----
