NOTE: The installation procedure for PostgreSQL database is taken from the link:https://www.postgresql.org/download/linux/[official PostgreSQL] project website.

.Import the repository signing key
[source, console]
----
sudo apt -y install curl ca-certificates
sudo install -d /usr/share/postgresql-common/pgdg
sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
----

.Install the official PostgreSQL repository
[source, console]
----
. /etc/os-release
sudo sh -c "echo 'deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $VERSION_CODENAME-pgdg main' > /etc/apt/sources.list.d/pgdg.list"
sudo apt update
----

.Install PostgreSQL client and server
[source, console]
[subs="verbatim,attributes"]
----
sudo apt -y install postgresql-{postgresql-version}
----
 
.Create an opennms database user and password
[source, console]
----
sudo -u postgres createuser -P opennms
----

IMPORTANT: Set a secure password for the `opennms` database user account.

.Create an empty database and set the owner to the opennms user
[source, console]
----
sudo -u postgres createdb -O opennms opennms
----

.Set a password for PostgreSQL superuser
[source, shell]
----
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'CHANGE_ME';"
----

IMPORTANT: Set a secure password for your PostgreSQL superuser.
           The superuser is required to initialize and change the database schema for installation and updates.

TIP: If you use PostgreSQL 13 you need to change the authentication method from `ident` to `md5` in the `pg_hba.conf`. In PostgreSQL 14 onwards the default is `scram-sha-256` which you can just use out of the box.

TIP: When you want to install the PostgreSQL server on a dedicated machine, configure the PostgreSQL listener so that it can be reached from the OpenNMS Horizon Core server and Sentinels.
     The listener configuration `listen_addresses` can be set in the `postgresql.conf` and the allowed IP ranges and authentication can be configured in the `pg_hba.conf`.