[release-notes-supported-systems]
== Supported Systems

[release-notes-supported-unix-like-oses]
=== Supported UNIX-like OSes

OpenNMS is written almost entirely in Java, and should be able to run on any system that supports the Sun Java Virtual Machine -- OpenNMS 1.13.x and higher requires Java 6 or higher.
There are requirements for other programs such as PostgreSQL and Perl, but the JDK is the key requirement as most of the other packages can be compiled from source.

The following are the systems that support or are known to run OpenNMS.

Windows 2000/XP/Vista are supported as of 1.3.8.

[supported-fullysupported]
=== Fully Supported

The following systems are supported out-of-the-box with native installation packages:

* RPM-based Distributions (Using Yum)
** Red hat Enterprise Linux 3 and higher
** CentOS 3 and higher
** Fedora Core 4 and higher (including 64-bit)
** SuSE Linux 9 and 10 (Using the Yum repository through YAST)
* Other RPM-based Distributions
** Mandriva Linux 2007 and higher (Using URPMI)
* Debian and Ubuntu Linux: Debian packages for Etch and later are available at the following
apt repository:
[source, bash]
----
deb http://debian.opennms.org/ unstable main
----
These same packages should work equally well with Ubuntu releases 6.10 (Edgy Eft) and higher.

* Solaris 10 (X86 and SPARC)
* MacOSX 10.4 and Higher.
On MacOSX, the Fink distribution http://pdb.finkproject.org/pdb/package.php/opennms[packages of OpenNMS]are supported.
See http://www.finkproject.org[the Fink web site] for more information on installing and using Fink.
Also note that on MacOSX, PostgreSQL must be configured in the same manner as above for Linux.
_However_, to do so you will need to update the `SHM` settings so that the OS allows enough resources for PostgreSQL to run with larger buffers.
There are details for configuring the shared memory segments on http://wiki.finkproject.org/index.php/Shared_Memory_Regions_on_Darwin[the Fink wiki].
* Windows Server and Desktop (Windows 2000+) Note that while it is technically possible to install on FAT32, NTFS is the only officially supported filesystem for Windows installs.
Additionally, while Windows is supported, OpenNMS is much more heavily tested (and easier to maintain) on UNIX, and it is recommended that unless you have a specific reason to go with Windows, that you use one of the supported UNIX-based operating systems.

[supported-unsupported]
=== Unsupported
OpenNMS 1.3.7 and up require Java 5 (a 1.5 JDK) and PostgreSQL 7.4 or higher.
In addition, for native RRD support (as opposed to the builtin Java-based JRobin round-robin database), RRDTool 1.2 is required.

Any operating system that can support these dependencies should be able to run OpenNMS.
However, since many older distributions do not support packages for these applications it will be much harder to get them installed, and so they are not officially supported.

A number of distributions that used to be supported are still able to run OpenNMS but are not officially supported:

* Gentoo: Ebuilds are available but are not officially supported, as we depend on Gentoo packager volunteers from the at-large user community to keep them up-to-date.
Information is available http://www.opennms.org/wiki/Other_Install_instructions#Gentoo_Installation[on the wiki].
* Red Hat Linux: While Red hat Linux 7, 8, and 9 (and potentially even others might still work, they have long gone untested and are not recommended for production use.
* SuSE 8 and earlier
* Solaris 9 and earlier
