[[releasenotes-21]]
== What's New in OpenNMS Horizon 21

=== System Requirements

* *Java 8*: OpenNMS Horizon 21 requires Java 8 as the runtime environment.
  To run Horizon 21, we recommend the most recent version of Oracle JDK 8 for your platform.
* *PostgreSQL 9.3 or higher*: Horizon 21 requires PostgreSQL 9.3 or higher. All older versions of PostgreSQL are past their end-of-life support date.

=== Important Upgrade Notes

* Event parameters have been moved to their own table, rather than being embedded (preformatted) in the `events` table.
If you have a large number of events and/or event parameters in your database, the conversion while running `install` may take as long as an hour or even more.
It is recommended that you archive and delete old events you do not need anymore before upgrading.

=== Breaking Changes

* Property format change of `opennms.alarmTroubleTicketLinkTemplate`:
Originally the `opennms.alarmTroubleTicketLinkTemplate` defined in `$OPENNMS_HOME/etc/opennms.properties` requires the full `<a href="...">${id}</a>` link to be configured.
This is changed to the ticketer system url, e.g. `https://issues.opennms.org/browse/${id}` instead of `<a href="https://issues.opennms.org/browse/${id}">${id}</a>`.
If the `opennms.alarmTroubleTicketEnabled` is `true` then the `opennms.alarmTroubleTicketLinkTemplate` must be updated as well in order to not break the link to an external ticketing system on the Alarm Details Page.
* XML configuration reformat:
Most XML configuration files in `$OPENNMS_HOME/etc` have been reformatted so they match the way they would be written out by our XML APIs.
This will likely cause additional `.rpmnew` or `.dpkg-*` files on upgrade.
* Event parameters:
There are a few side-effects of the event parameter changes.
  ** When you view or retrieve an alarm it will always have the parameters of the newest event associated with it.
  ** Vacuumd no longer honors the `add-all-parms` attribute on an `action-event`.
* Changes to `TCPAddress` and `UDPAddress` format in `eventd-configuration.xml`:
When Eventd was converted to use Camel under the covers, the format for listening on all interfaces changed from a wildcard (`*`) to `0.0.0.0`.
Note that despite looking like an IPv4 format, the JVM interprets `0.0.0.0` as listening on _all_ interfaces, IPv4 and IPv6.

=== New Features

* The experimental ReSTv2 API introduced in Horizon 20.1 has been improved to support new features made possible by moving event parameters to their own table.
* Improved Minions:
  ** Minions now automatically get JMX data collection, as well as RPC monitoring.
  ** The Minion now has support for remote-poller-like behavior.  You can now override the location at which monitors are executed.

=== Dependency Updates

* Camel has been upgraded to `2.19.1`
* ActiveMQ has been upgraded to `5.14.5`
* Karaf has been upgraded to `4.1.2`
