[[releasenotes-24]]
== What's New in OpenNMS Horizon 24

=== System Requirements

* *Java 8*: OpenNMS Horizon 24 requires Java 8 as the runtime environment.
  To run Horizon 24, we recommend the most recent version of Oracle JDK 8 for your platform.
* *PostgreSQL 9 or higher*: Horizon 24 requires Any supported version PostgreSQL 9 or higher.
  As of this writing, PostgreSQL 9.3 is the earliest version under active support, but OpenNMS is known to work with at least PostgreSQL 9.1 and up.

=== Breaking Changes

==== Reloadable Flag in service-configuration.xml

Starting with the newest OpenNMS release, there will be a reloadable Flag in the `service-configuration.xml`, which indicates whether a daemon is reloadable or not.
If the flag is not set, the property defaults to `false`.
This should help the manual work with the `Opennms-deamons`, and will also be used by the newly added Daemon-Configuration Page, which allows to reload (reloadable) Daemons via the GUI.

=== New Features

=== Other Improvements

* list of notable issues not covered elsewhere
