[[releasenotes-24]]
== What's New in OpenNMS Horizon 24

* Added support for browser notifications to notifd.
  The browser notification can be added to a notification path and desktop notifications will pop-up for currently logged in users if a notice is delivered.
* Added support for user defined links (UDLs) in the Enhanced Linkd topology.
  Users may now programitically (using the REST API) create "manual" links between node and have them appear in the topology UI.

=== System Requirements

* *Java 8 through 11*: OpenNMS Horizon 24 requires at least Java 8 as the runtime environment and now supports running on JDK 11 as well.
  To run Horizon 24, we recommend the most recent version of Oracle JDK 8 for your platform, or the latest OpenJDK 11.
* *PostgreSQL 9 or higher*: Horizon 24 requires Any supported version PostgreSQL 9 or higher.
  As of this writing, PostgreSQL 9.3 is the earliest version under active support, but OpenNMS is known to work with at least PostgreSQL 9.1 and up.

=== Breaking Changes

* Flows are grouped by conversations using applications instead of ports.
  This changes the way statistics about flows are presented and grouped.
  Therefore the elasticsearch storage has changed and old data must be converted to the new format.
  To adopt existing flows, the following command can be used (please be aware that this can take a long time and put your CPU and disk under high stress):
```
curl -v -X POST -H 'Content-Type: application/json' "http://${ES_HOST}:${ES_PORT}/netflow-*/_update_by_query?refresh=true" -d @- << EOF
{
  "script": {
    "lang": "painless",
    "source": "ctx._source['netflow.convo_key'] = '[\"' + ctx._source['location'] + '\",' + ctx._source['netflow.protocol'] + ',\"' + ((Objects.compare(ctx._source['netflow.src_addr'], ctx._source['netflow.src_addr'], String::compareTo) < 0) ? ctx._source['netflow.src_addr'] : ctx._source['netflow.dst_addr']) + '\",\"' + ((Objects.compare(ctx._source['netflow.src_addr'], ctx._source['netflow.src_addr'], String::compareTo) < 0) ? ctx._source['netflow.dst_addr'] : ctx._source['netflow.src_addr']) + '\",' + ((ctx._source['netflow.application'] != null) ? ('\"' + ctx._source['netflow.application'] + '\"') : 'null') + ']'"
  },
  "query": {
    "match_all": {}
  }
}
EOF
```
* *Dhcpd*: The *Dhcpd* plugin (and its configuration) was removed in favor of a Minion-capable implementation.
  The new *DhcpMonitor* options can be set in the `poller-configuration.xml` file.
* The default parser used for Syslog messages has been switched from the `CustomSyslogParser` to the `RadixTreeSyslogParser`.

=== New Features

=== Other Improvements

* list of notable issues not covered elsewhere
