[releasenotes-2016]
=== OpenNMS Meridian 2016

[releasenotes-whatsnew-2016]
==== What's New in Meridian 2016

Since Meridian 2015, a number of backend changes have been made, as well as a large amount of refactoring and many new features.

===== Java 8

Meridian 2015 dropped support for Java 6, and now in 2016 we are dropping support for Java 7, which has been EOL'd for some time now.
OpenNMS Meridian 2015 requires Java 8 to run, and we strongly recommend the latest version of Oracle JDK 8 for your platform.

===== PostgreSQL 9.1 or Higher

OpenNMS Meridian 2016 now requires PostgreSQL 9.1 or higher. All older versions of PostgreSQL are past their end-of-life support date.

===== Retired Features

* The legacy capability scanner, Capsd, has been removed from OpenNMS. It was deprecated in OpenNMS Horizon 1.12 and disabled by default
  in Horizon 14 and Meridian 2015 in favor of the provisioning systems of OpenNMS.
* The original link scanning daemon, Linkd, has been superseded by Enhanced Linkd since it was introduced in OpenNMS Horizon 15.
  Enhanced Linkd is a refactored replacement that is more efficient than the original Linkd code.
* *SVG Maps*: The SVG map feature relied on Linkd's code for drawing links between items on the map so it was also removed in OpenNMS 17.
* *Xmlrpcd*: Xmlrpcd was a daemon that relayed inventory and polling events to an external system over the XML-RPC protocol. Because you can
  accomplish almost all of its use cases by using the provisioning REST service, it has been removed.
* *MX4J*: The MX4J HTTP interface has been removed in favor of using more modern JMX access methods that have been added in recent versions
  of the JVM.

===== Important Upgrade Notes

* *Clean Up Events and Alarms*: Please clean up your event and alarm lists as much as possible before performing an upgrade to Meridian 2016.
  The upgrade process contains a large number of database schema migrations which will cause rewrites of all of the data in some tables.
  If you prune unused data from these tables beforehand, it will make the upgrade process much quicker.
* *Remote Poller API Change*: Due to internal API changes, the Remote Poller API has changed in Meridian 2016.
  If you upgrade to Meridian 2016, you will also need to upgrade all Remote Pollers attached to the system to 2016 as well.
* *RMI Security Updates*: The RMI registry has been changed to only listen on localhost by default.  It also now requires authentication
  using an OpenNMS administrator account.
* *JMX Updates*: JMX is no longer enabled by default on port 18980.
  If you have reason to access your OpenNMS instance remotely over JMX, you can reenable it by adding `-Dcom.sun.management.jmxremote.port=18980`
  and `-Dcom.sun.management.jmxremote.ssl=false` to `ADDITIONAL_MANAGER_OPTIONS` in `$OPENNMS_HOME/etc/opennms.conf`.  Complete documentation
  on enabling remote access and configuring authentication is available in the admin guide.
  Note that OpenNMS-JVM monitoring of the local instance (ie, localhost) will still work by using the JMX Access API, without needing to
  enable the TCP port.

===== API Changes

Several classes changed location in Meridian 2016 and these changes may require you to update configuration files or scripts with the new names.

* The *IndexStorageStrategy* and *PersistAllSelectorStrategy* classes moved into the *org.opennms.netmgt.collection.support* Java package. These classes
  are heavily referenced in data collection configuration files. There is an upgrade task that should update all data collection files when you
  run the *install* command after upgrading OpenNMS.
* All *EventUtils* class methods were consolidated inside the *org.opennms.netmgt.model.events.EventUtils* class.
* Monitoring locations for the Remote Poller are now viewed and configured in the UI under `/locations/index.jsp`.
  Monitoring locations were previously configured in the `etc/monitoring-locations.xml` file but are now stored in `monitoringlocations` database table.
* All data previously in the `location_monitors` table is now in the `monitoringsystems` table.
* The `ifIndex` column has been removed from the `ipInterface` table.
  To fetch the ifIndex, you need to join to the `snmpInterface` table by `nodeId`.
* The `nodeId` and `ipAddr` columns have been removed from the `ifServices` table.
  To fetch these columns, you need to join to the `ipInterface` table.
* The `nodeId`, `ipAddr` and `serviceId` columns have been removed from the `outages` table.
  To fetch these columns, you need to join to the `ifServices` table.

===== New Features

* There is a new REST service that can be used to export performance data. This service can be used to easily export OpenNMS metrics into external
  graphing engines such as Grafana. See the REST API documentation for details.
* *Newts Storage for Data Collection*: In addition to RRD and JRobin, OpenNMS 17 data collection now supports our [Newts](http://opennms.github.io/newts/) time-series data store that uses the highly-scalable Apache Cassandra database as the storage backend.
  This storage solution provides higher performance than the file-based RRD and JRobin databases and practically unlimited scalability when using a cluster of Cassandra nodes.
  You can drastically reduce CPU and storage load on your OpenNMS system and increase the number of metrics stored per second by using the Newts storage engine.
* *Measurements REST API Filtering*: The measurements REST API now supports the use of arithmetic filters on the returned datasets.
  This allows you to perform calculations or statistical operations on the data via server-side processing.
* *Grafana Panel*: An optional panel has been added to the UI to allow you to integrate links to Grafana graphs in the UI.
* *Streamlined UI Style*: The style of the UI has been refined to provide a clearer, more modern look-and-feel.
* *Alarm Heatmap*: A heatmap visualization has been added that lets you quickly visualize alarm status and outages within a category or on a node.
* *FreeIPA Kerberos Authentication*: We've added a sample configuration for FreeIPA Kerberos SSO to our `jetty-webapps/opennms/WEB-INF/spring-security.d` directory.
* *JMX Configuration UI and CLI*: The JMX Configuration web UI and CLI have been rewritten to make it easier to generate complex JMX data collection configurations.
* *JMS Alarm Northbounder*: The implementation of a JMS northbounder for sending OpenNMS Alarms to external JMS listeners has been completed. Thanks to David Schlenk (@dschlenk) for this contribution!
* *OTRS 3.1+ Ticketing Integration*: Our OTRS ticketing integration has been updated to work with the API in OTRS 3.1 and higher. Thanks to Jonathan Sartin (@blackpoplar) for this contribution!
* *Easier Remote Poller Configuration*: Monitoring locations can now be associated with multiple polling and collection packages. This can make some Remote Poller scenarios easier to configure.

===== Events

New or updated trap definitions have been added for the following classes of devices:

* A10 AX Load Balancer
* Avocent DSView
* Citrix NetScaler
* Dell Force 10
* Evertz 7800FR Multiframe
  * 7880-IP-ASI-IP
  * 7881-DEC-MP2
  * 7780-ASI-IP2
* Infoblox
* Mikrotik RouterOS
* ~50 new NetApp Events
* OpenSSH syslog events
* Postfix syslog events
* Procmail syslog events
* Raytheon NXU-2A
* Siemens HiPath
* Veeam Backup/Replication

===== Data Collection

* Fortinet Fortigate
* Sonicwall

===== Core Updates

As always, many updates and cleanups have been made to the OpenNMS core, through refactoring,
addition of unit tests, and other code modernization.

* A few subsystems have been updated to run properly under OSGi.
* A large number of places where we were still using JDBC calls have been converted to use our DAO infrastructure and Hibernate.
* The OpenNMS ReST APIs now support CORS properly to aid in writing web applications that consume or update OpenNMS data.
* The JMX detector, monitor, and collector were refactored for modularity.
* The Dashboard was rewritten using the Vaadin UI toolkit to improve and modernize its look-and-feel.
* Bean Scripting Framework (BSF) notifications and the BSFMonitor were optimized and are now much more efficient. (Thanks to David Schlenk for this contribution!)
* RTC, which calculates the availability percentages for the category panel on the main page, was rewritten using Spring for initialization and
  using database calls to perform availability calculations. This will improve its maintainability.
* The web controllers for provisioning, RANCID integration, reports, the node list, and Remote Poller administration were rewritten
  to modernize their code.
* The REST portion of the OpenNMS webapp was modularized into its own project.
* The REST interface has been refactored to be based on Apache CXF 3.1.4.
* The web UI service layer was separated from the main web UI to improve modularity.
* The Jasper and statsd reports have been changed so that they use a new unified interface for fetching data from either RRD, JRobin, or Newts.
* The Discovery engine has been refactored into its own project.
* The Dashboard has been rewritten using the Vaadin toolkit to modernize its look-and-feel.
* The `opennms-assemblies/jmx-config-generator-onejar` project has been moved to `features/jmx-config-generator`.

===== Dependency Updates

A number of internal libraries have been upgraded for bugfixes and new features. None of these updates should require configuration changes.

* Spring has been upgraded from 3.2.9 to 4.0.5.
* Spring Security has been upgraded from 3.1.7 to 3.2.7.
* Drools has been upgraded from 5.1.1 to 6.0.1.
* Apache Camel has been upgraded from 2.13.2 to 2.14.1.
* Smack (used for XMPP notifications) has been upgraded from 3.0.4 to 4.0.6.
* The webapp schemas have all been updated to the Servlet 3.0 specification.
* Jasper Reports has been upgraded from 5.6.1 to 6.1.1.

[releasenotes-changelog-2016.1.4]
==== Release 2016.1.4

Release 2016.1.4 is an update to 2016.1.4 that provides a number of bug fixes and a few enhancements.

The codename for 2016.1.4 is _Dymaxion_.

===== NOTE: Configuration Changes

While we strive to make no changes to `$OPENNMS_HOME/etc` in micro Meridian releases, we have a few changes that we deemed important or low-impact enough for this release:

* An entry was added to `log4j2.xml` for SNMP4J, avoiding large amounts of spurious SNMP logs.
* The Peak Traffic Jasper subreport was modified to report in octets.
* A number of graph definitions in `snmp-graph.properties.d` were fixed.

===== Bug

* If a target node is rebooted the RRD/JRB files contains spikes because the sysUpTime check is not working (Issue http://issues.opennms.org/browse/NMS-7106[NMS-7106])
* Opsboard change title color to something neutral than red (Issue http://issues.opennms.org/browse/NMS-7911[NMS-7911])
* ConstraintViolationException in Enlinkd for OSPF (Issue http://issues.opennms.org/browse/NMS-8067[NMS-8067])
* Enlinkd Topology: Cannot search for nodes without alarms (Issue http://issues.opennms.org/browse/NMS-8420[NMS-8420])
* Replace VDEF with {diffTime} on the resource templates to avoid conflicts with Backshift (Issue http://issues.opennms.org/browse/NMS-8490[NMS-8490])
* Inconsistencies with the Measurements API when using Newts (Issue http://issues.opennms.org/browse/NMS-8498[NMS-8498])
* Restarting OMNS results in numerous SNMP outage alarms and notifications (Issue http://issues.opennms.org/browse/NMS-8620[NMS-8620])
* Measurements API can fail with exception when operating in relaxed mode (Issue http://issues.opennms.org/browse/NMS-8665[NMS-8665])
* Newts: When Cassandra Cluster is unavailable, OpenNMS gives up on trying to contact it again (Issue http://issues.opennms.org/browse/NMS-8670[NMS-8670])
* Any SNMP error-status > 5 treated as unrecognized, aborts AggregateTracker (Issue http://issues.opennms.org/browse/NMS-8671[NMS-8671])
* Event advanced search does not work because of encoded &s (Issue http://issues.opennms.org/browse/NMS-8768[NMS-8768])
* The Alarms Details widget on the OpsBoard shows the text on green instead of black (Issue http://issues.opennms.org/browse/NMS-8771[NMS-8771])
* Installer script doesn't work with PostgreSQL 9.6 (Issue http://issues.opennms.org/browse/NMS-8779[NMS-8779])
* SNMP web configurator does not allow zero retries (Issue http://issues.opennms.org/browse/NMS-8789[NMS-8789])
* The search page for events is not working as expected (Issue http://issues.opennms.org/browse/NMS-8790[NMS-8790])
* InterruptedExceptions thrown when using SNMP (Issue http://issues.opennms.org/browse/NMS-8813[NMS-8813])
* Outage ReST service forNode use case calculates dates incorrectly (Issue http://issues.opennms.org/browse/NMS-8823[NMS-8823])
* Discovery duplicates nodes when foreign-source is set (Issue http://issues.opennms.org/browse/NMS-8835[NMS-8835])
* Several ICMPv6 tests fail with NoRouteToHostException (Issue http://issues.opennms.org/browse/NMS-8840[NMS-8840])
* user detection in `install` is busted on some Linux systems (Issue http://issues.opennms.org/browse/NMS-8843[NMS-8843])
* Backshift shows the name of the string variables when the value is not available (Issue http://issues.opennms.org/browse/NMS-8847[NMS-8847])
* Wallboard / Ops board renders product logo strangely (Issue http://issues.opennms.org/browse/NMS-8855[NMS-8855])
* NonUniqueResultException when retrieving CDP links (Issue http://issues.opennms.org/browse/NMS-8863[NMS-8863])
* The ipinterface.iphostname field is not updated after changing the FQDN associated with a given IP address (Issue http://issues.opennms.org/browse/NMS-8874[NMS-8874])
* The label of unreachable auto-discovered nodes is set to the IP after a rescan. (Issue http://issues.opennms.org/browse/NMS-8880[NMS-8880])
* Memory Leak in enlinkd? (Issue http://issues.opennms.org/browse/NMS-8896[NMS-8896])
* Spurious Trapd error logs: unknown SNMP protocol version 'v2' (Issue http://issues.opennms.org/browse/NMS-8900[NMS-8900])
* Can't save cached requisition associated with HTTP when scheduling the import through provisiond-configuration.xml (Issue http://issues.opennms.org/browse/NMS-8912[NMS-8912])
* ArrayIndexOutOfBoundsException while processing some trap varbinds (Issue http://issues.opennms.org/browse/NMS-8915[NMS-8915])
* WS-Man collection fail with unknown reason code 2 (Issue http://issues.opennms.org/browse/NMS-8923[NMS-8923])
* WS-Man collection with resource-type only store last resource (Issue http://issues.opennms.org/browse/NMS-8924[NMS-8924])
* Backshift failing with legend errors for NRTG + Forecasts (Issue http://issues.opennms.org/browse/NMS-8939[NMS-8939])
* wsdl2java in features/ticketing/remedy is causing build failures (Issue http://issues.opennms.org/browse/NMS-8940[NMS-8940])
* WS_Man datacollection using WQL fails with 'unsupported element' (Issue http://issues.opennms.org/browse/NMS-8955[NMS-8955])

===== Enhancement

* Replace the X with back button in the Angular provisioning WebUI  (Issue http://issues.opennms.org/browse/NMS-7908[NMS-7908])
* Missing image in provisioning doc (Issue http://issues.opennms.org/browse/NMS-8121[NMS-8121])
* Add ReST Elastic Search Alarms to Foundation2016 (Issue http://issues.opennms.org/browse/NMS-8693[NMS-8693])
* Create a more useful example content for opennms.conf (Issue http://issues.opennms.org/browse/NMS-8721[NMS-8721])
* Add documentation for Mattermost/Slack notifications (Issue http://issues.opennms.org/browse/NMS-8742[NMS-8742])
* Allow filtering by severity in alarm list (Issue http://issues.opennms.org/browse/NMS-8851[NMS-8851])
* Expose alarm-list "limit" parameter as a UI control (Issue http://issues.opennms.org/browse/NMS-8852[NMS-8852])
* Make the ILR put the node label alongside the package/IPADDR/Service tuple (Issue http://issues.opennms.org/browse/NMS-8858[NMS-8858])
* Better logging for SNMP traps with processing problems (Issue http://issues.opennms.org/browse/NMS-8903[NMS-8903])
* Make the RRAs tunable for the metrics:stress command when using for RRDtool. (Issue http://issues.opennms.org/browse/NMS-8972[NMS-8972])


[releasenotes-changelog-2016.1.3]
==== Release 2016.1.3

Release 2016.1.3 is an update to 2016.1.2 that provides a few bug fixes, including a fix to a XSS vulnerability in the web UI.

The codename for 2016.1.3 is _Hobo-Dyer_.

===== Bug

* Syslogd may not associate messages with new nodes without a restart (Issue http://issues.opennms.org/browse/NMS-7236[NMS-7236])
* No event for Informational syslog (Issue http://issues.opennms.org/browse/NMS-7934[NMS-7934])
* IE11 and Firefox Browsers Display Double Scroll Bars for the RTC: Service Monitoring Table in the Ops Panel (Issue http://issues.opennms.org/browse/NMS-8035[NMS-8035])
* Null Pointer Exception in bridge discovery (Issue http://issues.opennms.org/browse/NMS-8390[NMS-8390])
* upgrade error: too many open files (Issue http://issues.opennms.org/browse/NMS-8507[NMS-8507])
* Documentation for the Requisition ReST API is confusing (Issue http://issues.opennms.org/browse/NMS-8521[NMS-8521])
* Missing documentation for ifservices ReST end point. (Issue http://issues.opennms.org/browse/NMS-8604[NMS-8604])
* Lost Bridge Forwarding Table Links (Issue http://issues.opennms.org/browse/NMS-8619[NMS-8619])
* Missing documentation for categories ReST end point. (Issue http://issues.opennms.org/browse/NMS-8629[NMS-8629])
* The categories ReST end point returns HTTP 500 when querying it with a browser. (Issue http://issues.opennms.org/browse/NMS-8637[NMS-8637])
* Database Reports Are Emailed When "Email report" is Unchecked (Issue http://issues.opennms.org/browse/NMS-8654[NMS-8654])
* Custom Resource graphs draw magenta lines if "Blue" is selected (Issue http://issues.opennms.org/browse/NMS-8655[NMS-8655])
* The ReST end point /foreignSourcesConfig/assets contains invalid fields (Issue http://issues.opennms.org/browse/NMS-8690[NMS-8690])
* Site status view gives a 400 error for aggregate view for node downs (Issue http://issues.opennms.org/browse/NMS-8700[NMS-8700])
* View current Site outages does not filter for "building" (Issue http://issues.opennms.org/browse/NMS-8702[NMS-8702])
* The Vaddin version of the dashboard shows negative availability sometimes (Issue http://issues.opennms.org/browse/NMS-8705[NMS-8705])
* Scriptd is not working at all for events that have nodes associated. (Issue http://issues.opennms.org/browse/NMS-8716[NMS-8716])
* vmwarecimquery and vmwareconfigbuilder tools is not working (Issue http://issues.opennms.org/browse/NMS-8718[NMS-8718])
* XSS vulnerability in display of SNMP sysName and trap varbind values (Issue http://issues.opennms.org/browse/NMS-8722[NMS-8722])
* IllegalStateException when using the RrdSummaryController (Issue http://issues.opennms.org/browse/NMS-8743[NMS-8743])
* Trapd JMX trap counters don't count traps (Issue http://issues.opennms.org/browse/NMS-8744[NMS-8744])
* Blank content when clicking on "View Node Link Detailed Info" (Issue http://issues.opennms.org/browse/NMS-8808[NMS-8808])
* Search Events Error (Issue http://issues.opennms.org/browse/NMS-8970[NMS-8970])

===== Enhancement

* Add Mattermost and Slack notification strategies (Issue http://issues.opennms.org/browse/NMS-8346[NMS-8346])
* Outage REST service cannot filter on event fields (Issue http://issues.opennms.org/browse/NMS-8724[NMS-8724])


[releasenotes-changelog-2016.1.2]
==== Release 2016.1.2

Release 2016.1.2 is an update to 2016.1.1 that provides a number of bug fixes, including a fix for geographical maps that were using the (end-of-life'd) MapQuest OpenStreetMap tile server.

The codename for 2016.1.2 is _Loximuthal_.

===== Bug

* observations related to "ping".option in topology page (Issue http://issues.opennms.org/browse/NMS-6849[NMS-6849])
* Using ping in topology view cause strange behavior (Issue http://issues.opennms.org/browse/NMS-7204[NMS-7204])
* New Monitoring Locations Editor only allows integers in the latitude and longitude fields (Issue http://issues.opennms.org/browse/NMS-7869[NMS-7869])
* output.log fills up with GLib-GObject-CRITICAL messages (Issue http://issues.opennms.org/browse/NMS-8016[NMS-8016])
* Ping from topology view does not work (results in 404 Page not found) (Issue http://issues.opennms.org/browse/NMS-8043[NMS-8043])
* VMware-ManagedEntity does not work with VMware 6 (Issue http://issues.opennms.org/browse/NMS-8187[NMS-8187])
* Install -dis on "SocketException:Too many open files" on centos:latest docker  (Issue http://issues.opennms.org/browse/NMS-8200[NMS-8200])
* JdbcCollector does not close database connections correctly (Issue http://issues.opennms.org/browse/NMS-8488[NMS-8488])
* HW ENTITY_MIB plugin is not showing all information for certain devices (Issue http://issues.opennms.org/browse/NMS-8506[NMS-8506])
* OEM graph for Storage Utilization fails due to '::' (Issue http://issues.opennms.org/browse/NMS-8519[NMS-8519])
* Topology Map is very very slow (Issue http://issues.opennms.org/browse/NMS-8589[NMS-8589])
* Requisitioned IP interfaces never have ipHostName set (Issue http://issues.opennms.org/browse/NMS-8593[NMS-8593])
* Compiler warnings about MaxPermSize support is removed in 8.0 (Issue http://issues.opennms.org/browse/NMS-8594[NMS-8594])

===== Configuration

* Distributed/Geographical Maps do not show images anymore (Issue http://issues.opennms.org/browse/NMS-8597[NMS-8597])

===== Enhancement

* Improve built-in Newts graphs for easier diagnostics (Issue http://issues.opennms.org/browse/NMS-8495[NMS-8495])
* Alphabetize nodes in surveillance category listing (Issue http://issues.opennms.org/browse/NMS-8535[NMS-8535])
* Make custom event parameters expandable (Issue http://issues.opennms.org/browse/NMS-8590[NMS-8590])


[releasenotes-changelog-2016.1.1]
==== Release 2016.1.1

Release 2016.1.1 is an update to 2016.1.0 that provides a fix for upgrades.

The codename for 2016.1.1 is _Cassini_.


[releasenotes-changelog-2016.1.0]
==== Release 2016.1.0

Release 2016.1.0 is the first release of OpenNMS Meridian 2016.  It is based on OpenNMS Horizon 17.1.1, plus a number of smaller bug fixes.

The codename for 2016.1.0 is _Mercator_.
