[releasenotes-2019]

== OpenNMS Meridian 2019

=== System Requirements

* *Java 8 through 11*: OpenNMS Meridian 2019 runs on JDK 8 through 11.
  We recommend the most recent version of OpenJDK 11.
* *Default Heap Size*: The default heap size is now 2GB.
* *PostgreSQL 10 or higher*: Meridian 2019 requires any supported version of PostgreSQL 10 or higher.

[releasenotes-whatsnew-2019]

=== What's New in Meridian 2019

Since Meridian 2018, we have introduced a large number of features, most notably Telemetryd (for processing streaming telemetry like NetFlow and sFlow), the Sentinel (for horizontal scaling of telemetry and other processing), and ALEC (for alarm correlation).

On top of that, there have been many other improvements and bug fixes since Meridian 2018.

Meridian 2019 roughly matches the feature set available in Horizon 25.

==== Architecture for Learning Enabled Correlation

Horizon 23 introduced support for correlation of alarms into meta-alarms called "situations" using an engine called the link:https://github.com/OpenNMS/alec[Architecture for Learning Enabled Correlation].

Situations are OpenNMS alarms that contain one or more triggering alarms, which allows them to be browsed, acknowledged, and unacknowledged just like any other alarm.

A high-level overview of the goal and implementation of correlation can be seen link:https://alec.opennms.com[on the ALEC web site].

==== Changes to the Alarm Lifecycle

===== Alarm Clearing

Traditionally, OpenNMS has created and resolved alarms in pairs, with one alarm representing the triggering event (or events), and then a second alarm representing the resolution.
Horizon 23 changes this default behavior to use a single alarm to track the problem state, incrementing the alarm count when it occurs while in a problem state, or when moving from resolved _back_ into a problem state.
Additionally, you can configure OpenNMS to create a new alarm if a problem happens again.

These behaviors are controlled by the introduction of 2 new settings in the `opennms.properties` file:

`org.opennms.alarmd.legacyAlarmState`::
    This setting reverts to the old (pre-23) behavior of creating separate alarms for a problem and its resolution.
`org.opennms.alarmd.newIfClearedAlarmExists`::
    This setting forces Alarmd to create a new alarm if a problem reoccurs, rather than incrementing an existing alarm.
    (Note: this is ignored if `legacyAlarmState` is set to `true`.)

These improvements are covered in a link:https://www.youtube.com/watch?v=5jpHVb1Od-g[lunch and learn video] we published recently, if you would like to learn more.

===== Alarmd Architecture

To facilitate the implementation of ALEC, alarmd has been rearchitected to use Drools to manage the alarm lifecycle, rather than Vacuumd automations, triggers, and actions.

If are migrating changes to `vacuumd-configuration.xml` from an earlier Meridian release, it is strongly recommended you port them to the new Alarmd Drools context.
The Drools rules are in the `$OPENNMS_HOME/etc/alarmd/drools-rules.d/` directory.

Additionally, we no longer generate `alarmCreated`, `alarmEscalated`, `alarmCleared`, `alarmUncleared`, `alarmUpdatedWithReducedEvent`, and `alarmDeleted` events.
Instead, it is recommended that you add Drools rules to react to alarm changes.

For more complicated integrations, we also have a new API -- `AlarmLifecycleListener` -- for reacting to alarm changes.

==== Kafka Data Collection Sync

In addition to publishing events, alarms, and node inventory to Kafka, we now link:https://issues.opennms.org/browse/NMS-10215[publish collected time-series data to the Kafka bus] as well.

==== Sentinel

In addition to the Minion, we have added a new container-based subsystem called "Sentinel."
The Sentinel is a Karaf container that can be configured to run a subset of OpenNMS daemons as a standalone tool, to aid in horizontal scaling and/or high availability.

Sentinel is designed to run our Karaf/Camel/SQS-based messaging bus, syslog listener, telemetry receiver, and Newts and Elasticsearch persistence.

==== Node and Interface Metadata

There is now support for associating arbitrary metadata with nodes and interfaces, including configuring arbitrary metadata in the requisition UI.

For details on using the metadata APIs, see link:https://meridian.opennms.com/docs/2019/latest/guide-admin/guide-admin.html#ga-meta-data[the Admin Guide] and link:$$https://meridian.opennms.com/docs/2019/latest/guide-development/guide-development.html#_meta_data$$[the Developer Guide].

=== Breaking Changes

==== PostgreSQL 10

OpenNMS Meridian 2019 is supported on PostgreSQL 10 or later.

If you are upgrading from an OpenNMS using an older PostgreSQL version, you can use the `pg_upgrade` tool to migrate.
For details on the migration process, see link:https://www.postgresql.org/docs/10/pgupgrade.html[the PostgreSQL `pg_upgrade` documentation].

If you are running on a distribution that does not provide PostgreSQL 10 packages by default, you can link:https://www.postgresql.org/download/[download packages provided by PostgreSQL instead].

==== Minion Packages Combined

The Minion RPM and Debian/Ubuntu packages have been combined into a single package.
Previously it was possible to just install the core container and optionally a set of features on top, but in the real world no one used this, and it's still possible to choose what features are used with the configuration.

NOTE: If you were previously _only_ installing the sub-packages and not installing the wrapper `opennms-minion` RPM package, you may need to run this command to upgrade cleanly:

[source, shell]
----
$ yum swap 'opennms-minion*' -- install opennms-minion
----

==== Elasticsearch 7.x Support

===== Version Compatibility

All of the features that leverage integrations with Elasticsearch (i.e., event & alarm history, flows & situation feedback) have been updated to support Elasticsearch 7.x.
Elasticsearch versions before 7.x are no longer supported.

Given the pace of change and the number of breaking changes between major versions of Elasticsearch, we will focus on supporting a single major version of Elasticsearch per release moving forward.

===== ReST Plugin Configuration

The configuration of the _Elasticsearch ReST plugin_ has changed.

Some properties have new defaults and have been renamed.
It is now also possible to define index settings and provide a index strategy to have more control over the index creation.

Some properties of the plugin have changed.
The following table shows the old (no longer supported) and the new property name, as well as the new default, which is used if the configuration is not updated manually.
Please update the configuration file `etc/org.opennms.plugin.elasticsearch.rest.forwarder.cfg` accordingly.
For more details on how to configure the plugin to use Elasticsearch refer to link:../guide-admin/index.html#ga-elasticsearch-integration-configuration[Configure Elasticsearch].

[options="header, autowidth"]
|===
| Old parameter | New parameter | Default Value

| `elasticsearchUrl`
| `elasticUrl`
| `http://localhost:9200`

| `esusername`
| `globalElasticUser`
| `-`

| `espassword`
| `globalElasticPassword`
| `-`

| `timeout`
| `connTimeout`
| `5000`

| `socketTimeout`
| `readTimeout`
| `30000`

|===

Besides that the following default values have been changed:

[options="header, autowidth"]
|===
| Parameter | Old default | New default

| `batchSize`
| `1`
| `200`

| `batchInterval`
| `0`
| `500`

|`connTimeout`
| `3000`
| `5000`

| `readTimeout`
| `3000`
| `30000`

|===

===== Index Properties

It is now possible to define index-related properties, e.g. the number of shards and replicas.
It is also possible to define a property  `elasticIndexStrategy` to determine if a `hourly`, `daily`, `monthly` or `yearly` index should be created.
It defaults to `monthly`.

For more details please refer to link:../guide-admin/index.html#ga-elasticsearch-integration-configuration[Configure Elasticsearch].

==== Karaf Container

The embedded Karaf has been upgraded to 4.2.

This changes the default `users.properties` file.
Ensure that the `admingroup` in `${OPENNMS_HOME}/etc/users.properties` contains the role `ssh`.
You can use the link:https://github.com/OpenNMS/opennms/blob/c51bddef095a0ad23e31be13c241dc9d862950b7/container/karaf/src/main/filtered-resources/etc/users.properties[new default users.properties file] for comparison.

Other notable Karaf and OSGi-related changes include:

* We now support link:https://issues.opennms.org/browse/HZN-1436[adding OSGi-capable code at runtime] by putting a `.kar` file in the `deploy/` directory and adding relevant features to boot files in `etc/featuresBoot.d/`.
* The usage of `config:edit` has changed in some cases.
  This affects all configuration edits, where the configuration contains a `-`, e.g. `org.opennms.features.telemetry.listeners-udp-50003`.
  If you are using Minion, you may be affected (e.g. for Telemetry Listeners/Adapters).
+
For example, this set of configuration commands:
+
----
config:edit org.opennms.features.telemetry.listeners-udp-50003
config:property-set key value
config:update
----
+
...should now be written as:
+
----
config:edit --alias udp-50003 --factory org.opennms.features.telemetry.listeners
config:property-set key value
config:update
----

==== Polling, Collection, Plugins, Parsers, and Services

* *Cassandra JMX*: The `cassandra30x.xml` datacollection config for thread pool metrics has been modified to be of type `counter` rather than type `gauge`.  If you are using RRD or JRobin storage, you will need to delete any `.jrb` or `.rrd` files with both `path_request` and `CurrentlyBlockedTasks` in their filename (eg, `org_apache_cassandra_metrics_type_ThreadPools_path_request_scope_MutationStage_name_CurrentlyBlockedTasks.jrb`).
* *Pollerd and Collectd*: Additional attributes for thread pool graphs have been added to the Pollerd and Collectd mbeans.
  If you are using `storeByGroup=true` with RRD or JRobin, you will need to delete the `OpenNMS_Name_Pollerd` and `OpenNMS_Name_Collectd` `.jrb` or `.rrd` files and let them be reinitialized.
  Newts and `storeByGroup=false` should be unaffected.
* *Dhcpd*: The _Dhcpd_ plugin (and its configuration) was removed in favor of a Minion-capable implementation.
  The new _DhcpMonitor_ options can be set in the `poller-configuration.xml` file.
* *Syslog*: The default parser used for _Syslog_ messages has been switched from the `CustomSyslogParser` to the `RadixTreeSyslogParser`.
* *Plugins*: The _Plugin Manager_ is no longer distributed with OpenNMS.
  Features or bundles should be installed via the Karaf Shell.

IMPORTANT: If you have legacy SNMP agents which only support 32bit interface counters, the data collection for this interfaces will stop after you upgraded to 22.0.0.
  To get them enabled, you have to create a data collection package and add the `mib2-interfaces` data collection group manually for this devices with the example below.

.Example to collect 32bit MIB-2 Interface counter from nodes in a category configured in collectd-configuration.xml
[source, xml]
----
<package name="Legacy-MIB2-Interfaces" remote="false">
    <filter>categoryName == 'Legacy-MIB2-Interfaces'</filter>
    <include-range begin="1.1.1.1" end="254.254.254.254"/>
    <include-range begin="::1" end="ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"/>

    <service name="SNMP" interval="300000" user-defined="false" status="on">
        <parameter key="collection" value="legacy-32bit-mib2"/>
        <parameter key="thresholding-enabled" value="true"/>
    </service>
</package>
----

.Load the Legacy MIB-2 Interfaces metrics configured in the datacollection-config.xml
[source, xml]
----
<snmp-collection name="legacy-32bit-mib2" snmpStorageFlag="select">
    <rrd step="300">
        <rra>RRA:AVERAGE:0.5:1:2016</rra>
        <rra>RRA:AVERAGE:0.5:12:1488</rra>
        <rra>RRA:AVERAGE:0.5:288:366</rra>
        <rra>RRA:MAX:0.5:288:366</rra>
        <rra>RRA:MIN:0.5:288:366</rra>
    </rrd>
    <include-collection dataCollectionGroup="Legacy_MIB2-Interfaces"/>
    <include-collection dataCollectionGroup="REF_MIB2-Interfaces"/>
</snmp-collection>
----

==== Removed from Meridian 2019

* The Centric Trouble Ticketer plugin has been removed.
* The NCS-Alarm page and the NCS-Topology-Plugin have been removed. See issue link:https://issues.opennms.org/browse/HZN-1422[HZN-1422].
* The remote poller map has been removed.
* The Alarm Change Notifier plugin has been removed due to performance problems.  Use the Alarm History function instead.
* The `resourcecli` tool has been removed in favor of link:https://docs.opennms.org/opennms/releases/latest/guide-admin/guide-admin.html#ga-performance-mgmt-measurements-shell[Karaf shell commands] to perform the same operations.

==== Vacuumd Alarm Handling

In previous OpenNMS releases, a large portion of the alarm workflow was handled by Vacuumd automations, triggers, and actions.
As part of the work to implement alarm correlation, this logic has been moved to Drools, running inside Alarmd.

If you made any changes to `vacuumd-configuration.xml` related to alarms, it is strongly recommended you port them to the new Alarmd Drools context.
The Drools rules are in the `$OPENNMS_HOME/etc/alarmd/drools-rules.d/` directory.

Also, we no longer generate `alarmCreated`, `alarmEscalated`, `alarmCleared`, `alarmUncleared`, `alarmUpdatedWithReducedEvent`, and `alarmDeleted` events.
Instead, it is recommended that you add Drools rules to react to alarm changes.
For more complicated integrations, we also have a new API -- `AlarmLifecycleListener` -- for reacting to alarm changes.

==== Event (and Alarm) Date/Time Formats

Events and alarms previously used the current locale for formatting timestamps.
As of Meridian 2019, we now format dates as ISO-8601 date-time with offsets (eg, `2011-12-03T10:15:30+01:00`) _and_ we expect dates in incoming events to be the same.
This reduces the amount of code we run through trying to figure out date formats while parsing events, and simplifies things to work no matter what locale you are using.

==== Developer Considerations

* The `HttpService` can no longer be consumed.
  This will only affect custom implementations of HTTP Servlets and Resources, but only if they are exposed via `httpServices.register(...)`.
  If you need those, please expose the according services via the OSGi Service Registration.
  Refer to the link:https://osgi.org/specification/osgi.cmpn/7.0.0/service.http.whiteboard.html[OSGi Http Whiteboard Specification] for more details.

* Exposing Servlets now follow the OSGi Specification.
  Refer to the  link:https://osgi.org/specification/osgi.cmpn/7.0.0/service.http.whiteboard.html[OSGi Http Whiteboard Specification] for more details.

* Properties to expose Vaadin Applications have changed:
  ** `init.widgetset` becomes `servlet.init.widgetset`
  ** `alias` becomes `osgi.http.whiteboard.servlet.pattern`

==== Helm 4

Technically not a part of OpenNMS, but it's important to note that Helm 4 introduces a datasource that _replaces_ the "Faults" datasource.
Migration of existing dashboards requires a few manual steps; documentation on how to do so will be available in link:https://docs.opennms.org/helm/releases/latest/helm/latest/welcome/index.html[the latest Helm documentation] once Helm 4 goes live.

=== Other Improvements

Since Meridian 2019 is based on Horizon 25, it contains all the fixes and updates that have occurred since Meridian 2018 was created from the Horizon 21 codebase.

For a more complete list of changes included in this release, see the "What's New" documentation for the following Horizon releases:

* link:https://docs.opennms.org/opennms/releases/22.0.4/releasenotes/releasenotes.html[Horizon 22]
* link:https://docs.opennms.org/opennms/releases/23.0.4/releasenotes/releasenotes.html[Horizon 23]
* link:https://docs.opennms.org/opennms/releases/24.1.3/releasenotes/releasenotes.html[Horizon 24]
* link:https://docs.opennms.org/opennms/releases/25.1.0/releasenotes/releasenotes.html[Horizon 25]

[releasenotes-changelog-Meridian-2019.1.7]

==== Release Meridian-2019.1.7

Release 2019.1.7 is the eighth release in the Meridian 2019 series.

It contains a few bug fixes as well as a number of enhancements to the documentation.

The codename for 2019.1.7 is _link:$$https://en.wikipedia.org/wiki/Uranus$$[Uranus]_

===== Bug

* Prevent multiple node scans from being scheduled for a single node (Issue http://issues.opennms.org/browse/NMS-12504[NMS-12504])
* Add more context to Response Time resources (Kafka Producer) (Issue http://issues.opennms.org/browse/NMS-12661[NMS-12661])
* Reloading the Pollerd daemon causes multiple nodeDown messages (Issue http://issues.opennms.org/browse/NMS-12681[NMS-12681])
* Streaming Telemetry is broken when using OpenJDK 11 and minion (Issue http://issues.opennms.org/browse/NMS-12688[NMS-12688])

===== Enhancement

* Document JDBCQueryMonitor "compare_string" Action (Issue http://issues.opennms.org/browse/NMS-9581[NMS-9581])
* SystemExecuteMonitor fails with exit code 6 (Issue http://issues.opennms.org/browse/NMS-12564[NMS-12564])
* Add an example for SystemExecuteMonitor into the docs (Issue http://issues.opennms.org/browse/NMS-12568[NMS-12568])
* Provide written procedures on the proper way to restart  (Issue http://issues.opennms.org/browse/NMS-12650[NMS-12650])

[releasenotes-changelog-Meridian-2019.1.6]

==== Release Meridian-2019.1.6

Release 2019.1.6 is the seventh release in the Meridian 2019 series.

It is an off-schedule release to fix a vulnerability in ActiveMQ and the Minion.
Thanks to Florian Hauser of Code White for catching this one.

The codename for 2019.1.6 is _link:$$https://en.wikipedia.org/wiki/Europa$$[Europa]_

===== Bug

* Authenticated RCE vulnerability via ActiveMQ Minion payload deserialization (Issue http://issues.opennms.org/browse/NMS-12673[NMS-12673])

[releasenotes-changelog-Meridian-2019.1.5]

==== Release Meridian-2019.1.5

Release 2019.1.5 is the sixth release in the Meridian 2019 series.

It fixes a few more security issues, as well as a number of other bugs
and a couple of enhancements.
Hat tip to Johannes Moritz for the security report.

The codename for 2019.1.5 is _link:$$https://en.wikipedia.org/wiki/Saturn$$[Saturn]_

===== Bug

* SNMP Remove from definitions fails for definitions with profile label (Issue http://issues.opennms.org/browse/NMS-12413[NMS-12413])
* persisted defaultCalendarReport database reports are broken (Issue http://issues.opennms.org/browse/NMS-12438[NMS-12438])
* Security issue disclosures, 31 Jan 2020 (Issue http://issues.opennms.org/browse/NMS-12513[NMS-12513])
* Selecting an Icon on Topology Map breaks the map (Issue http://issues.opennms.org/browse/NMS-12532[NMS-12532])
* Description: Cannot create monitored-service with JSON via ReST (Issue http://issues.opennms.org/browse/NMS-12625[NMS-12625])
* Confd download fails silently on Docker install (Issue http://issues.opennms.org/browse/NMS-12642[NMS-12642])

===== Enhancement

* Event documentation is missing tokens (Issue http://issues.opennms.org/browse/NMS-12228[NMS-12228])
* Splitting Docker documentation in Horizon, Minion and Sentinel (Issue http://issues.opennms.org/browse/NMS-12529[NMS-12529])
* Improve OIA performance when mapping alarms (Issue http://issues.opennms.org/browse/NMS-12581[NMS-12581])
* Events not balanced across partitions when using opennms-kafka-producer (Issue http://issues.opennms.org/browse/NMS-12616[NMS-12616])

[releasenotes-changelog-Meridian-2019.1.4]

==== Release Meridian-2019.1.4

Release 2019.1.4 is the fifth release in the Meridian 2019 series.

It fixes an HQL injection bug, as well as a few other issues.
Hat tip to Johannes Moritz for the security report.

The codename for 2019.1.4 is _link:$$https://en.wikipedia.org/wiki/Jupiter$$[Jupiter]_

===== Bug

* Cannot process SNMPv3 Informs due to random Engine ID associated with users (Issue http://issues.opennms.org/browse/NMS-12473[NMS-12473])
* Downtime model change was not updated in the docs (Issue http://issues.opennms.org/browse/NMS-12520[NMS-12520])
* HQL Injection (Issue http://issues.opennms.org/browse/NMS-12572[NMS-12572])

===== Enhancement

* Support signing code in CircleCI (Issue http://issues.opennms.org/browse/NMS-12557[NMS-12557])

[releasenotes-changelog-Meridian-2019.1.3]

==== Release Meridian-2019.1.3

Release 2019.1.3 is the fourth release in the Meridian 2019 series.

It contains a few bug fixes, most notably a fix for some NPEs as well as a performance issue in topology processing.

The codename for 2019.1.3 is _link:$$https://en.wikipedia.org/wiki/Mars$$[Mars]_

===== Bug

* changing GUI date/timeformat breaks requisition update/import date/time display (Issue http://issues.opennms.org/browse/NMS-12428[NMS-12428])
* Inefficient locking in the TopologyUpdater class (Issue http://issues.opennms.org/browse/NMS-12443[NMS-12443])
* MIB Compiler fails with Null Pointer Exception (Issue http://issues.opennms.org/browse/NMS-12459[NMS-12459])
* The Karaf poller:test command is not location aware (Issue http://issues.opennms.org/browse/NMS-12460[NMS-12460])
* NPE while compiling a MIB (Issue http://issues.opennms.org/browse/NMS-12472[NMS-12472])

[releasenotes-changelog-Meridian-2019.1.2]

==== Release Meridian-2019.1.2

Release 2019.1.2 is the third release in the Meridian 2019 series.

It contains a number of alarm classification bug fixes and performance improvements, flow enhancements, and more.

The link:https://i.ytimg.com/vi/psiq5imRIj8/maxresdefault.jpg[c]odename for 2019.1.2 is _link:$$https://en.wikipedia.org/wiki/Earth$$[Earth]_

===== Bug

* possible issue in JCIFS Monitor - contiously increase of threads - finally heap dump (Issue http://issues.opennms.org/browse/NMS-12407[NMS-12407])
* Wrong links in the Help/Support page (Issue http://issues.opennms.org/browse/NMS-12418[NMS-12418])
* Classification Engine reload causes OOM when defining a bunch of rules (Issue http://issues.opennms.org/browse/NMS-12429[NMS-12429])
* Cannot define a specific layer in topology app URL (Issue http://issues.opennms.org/browse/NMS-12431[NMS-12431])
* Classification UI: Error responses are not shown properly (Issue http://issues.opennms.org/browse/NMS-12432[NMS-12432])
* Classification Engine: The end of the range is excluded, which is not intuitive (Issue http://issues.opennms.org/browse/NMS-12433[NMS-12433])
* Ticket-creating automations are incorrectly enabled by default (Issue http://issues.opennms.org/browse/NMS-12439[NMS-12439])
* Enable downtime model-based node deletion to happen when unmanaged interfaces exist (Issue http://issues.opennms.org/browse/NMS-12442[NMS-12442])
* Improve alarmd Drools engine performance by using STREAM mode (Issue http://issues.opennms.org/browse/NMS-12455[NMS-12455])

===== Enhancement

* Refactoring of the Cassandra installation instructions (Issue http://issues.opennms.org/browse/NMS-12397[NMS-12397])
* Allow telemetry flows to balance across Kafka partitions (Issue http://issues.opennms.org/browse/NMS-12427[NMS-12427])
* Add system test for IpfixTcpParser (Issue http://issues.opennms.org/browse/NMS-12434[NMS-12434])
* Associate exporter node using Observation Domain Id (Issue http://issues.opennms.org/browse/NMS-12435[NMS-12435])

[releasenotes-changelog-Meridian-2019.1.1]

==== Release Meridian-2019.1.1

Release 2019.1.1 is the second release in the Meridian 2019 series.

It contains a number of bug fixes mostly related to alarm and event processing and potential resource leaks, as well as provisioning enhancements to SNMP profiles.

The codename for 2019.1.1 is _link:$$https://en.wikipedia.org/wiki/Venus_(planet)$$[Venus]_

===== Bug

* Readiness probe with Minion in Kubernetes with health:check does not work (Issue http://issues.opennms.org/browse/NMS-12120[NMS-12120])
* Cannot use poller:poll karaf command with WsManMonitor through Minions (Issue http://issues.opennms.org/browse/NMS-12365[NMS-12365])
* Strange behavior on used threads and file descriptors on Minion (Issue http://issues.opennms.org/browse/NMS-12366[NMS-12366])
* Upstream Drools Bug: From with modify fires unexpected rule (Issue http://issues.opennms.org/browse/NMS-12367[NMS-12367])
* "Page Not Found" in alarm-list when choosing number of alarms in dropdown-list (Issue http://issues.opennms.org/browse/NMS-12379[NMS-12379])
* Build failure during release for 25.1.0 in CircleCI (Issue http://issues.opennms.org/browse/NMS-12380[NMS-12380])
* backport missing patches from 25.1.0 to foundation-2019 (Issue http://issues.opennms.org/browse/NMS-12384[NMS-12384])
* Discovery does not honor exclude-range inside a definition (Issue http://issues.opennms.org/browse/NMS-12385[NMS-12385])
* Discovery exclude-range is not location-aware (Issue http://issues.opennms.org/browse/NMS-12386[NMS-12386])
* Update OpenJDK 11.0.4 to 11.0.5 (Issue http://issues.opennms.org/browse/NMS-12387[NMS-12387])
* Elasticsearch event forwarder manipulates in-flight event (Issue http://issues.opennms.org/browse/NMS-12390[NMS-12390])
* send-event.pl is broken after OpenNMS 25.1.0 update (Issue http://issues.opennms.org/browse/NMS-12392[NMS-12392])
* SNMP profile fitting is not triggered in some cases when MINION is involved (Issue http://issues.opennms.org/browse/NMS-12399[NMS-12399])
* Alarmd fails intermittently and OOMs (Issue http://issues.opennms.org/browse/NMS-12412[NMS-12412])
* SNMP Remove from definitions fails for definitions with profile label (Issue http://issues.opennms.org/browse/NMS-12413[NMS-12413])

===== Enhancement

* Create a step-by-step guide how to setup Kafka for Minions (Issue http://issues.opennms.org/browse/NMS-12368[NMS-12368])
* Enhance new snmp profiles to allow fitting to nodes inside requisitions without SNMP service associated to any IPs configured (Issue http://issues.opennms.org/browse/NMS-12396[NMS-12396])

[releasenotes-changelog-Meridian-2019.1.0]

==== Release Meridian-2019.1.0

Release 2019.1.0 is the first release in the Meridian 2019 series.

The codename for 2019.1.0 is _link:$$https://en.wikipedia.org/wiki/Mercury_(planet)$$[Mercury]_

===== Bug

* removed service will break BSM web ui (Issue http://issues.opennms.org/browse/NMS-9322[NMS-9322])
* Event parameters no longer preserve ordering (Issue http://issues.opennms.org/browse/NMS-9827[NMS-9827])
* The JMX-Cassandra service goes down for all the cluster when a single instance is down. (Issue http://issues.opennms.org/browse/NMS-10027[NMS-10027])
* deleting a BSM monitor while an alarm is active doesn't clear the alarm (Issue http://issues.opennms.org/browse/NMS-10184[NMS-10184])
* default event description is incorrect (Issue http://issues.opennms.org/browse/NMS-10346[NMS-10346])
* Config tester doesn't detect missing xml datacollection file (Issue http://issues.opennms.org/browse/NMS-10396[NMS-10396])
* BSM alarm severity is not being updated (Issue http://issues.opennms.org/browse/NMS-10578[NMS-10578])
* snmp authentication error traps with Enhanced Linkd / bridge discovery (Issue http://issues.opennms.org/browse/NMS-10582[NMS-10582])
* Zooming with Backshift is broken (Issue http://issues.opennms.org/browse/NMS-10635[NMS-10635])
* Karaf shell history thrown out with bathwater on upgrade (Issue http://issues.opennms.org/browse/NMS-10664[NMS-10664])
* Node detail page renders with no content when invalid node ID specified (Issue http://issues.opennms.org/browse/NMS-10679[NMS-10679])
* Apparent memory leak in JMX collector, possibly restricted to "weird" JMX transports (Issue http://issues.opennms.org/browse/NMS-10684[NMS-10684])
* Elasticsearch forwarding fails to recover after outage (Issue http://issues.opennms.org/browse/NMS-10697[NMS-10697])
* Flow rest results for top N queries are not returned in the correct order (Issue http://issues.opennms.org/browse/NMS-12104[NMS-12104])
* karaf.log appears on the root file system when running Minion/Sentinel on Ubuntu/Debian. (Issue http://issues.opennms.org/browse/NMS-12125[NMS-12125])
* WS-MAN  doesn't work with JDK 11 (Issue http://issues.opennms.org/browse/NMS-12235[NMS-12235])
* ReST API for meta-data doesn't support JSON (Issue http://issues.opennms.org/browse/NMS-12272[NMS-12272])
* UI for meta-data is only present when using the horizontal layout (Issue http://issues.opennms.org/browse/NMS-12273[NMS-12273])
* Groups disappear in classification UI (Issue http://issues.opennms.org/browse/NMS-12291[NMS-12291])
* BSM simulation mode does not reset the last state (Issue http://issues.opennms.org/browse/NMS-12302[NMS-12302])
* Web Assets Dependency Rollup 2019-09-24 (Issue http://issues.opennms.org/browse/NMS-12320[NMS-12320])
* Memory leak in Drools engine for alarmd (Issue http://issues.opennms.org/browse/NMS-12322[NMS-12322])
* Threshold state keys do not incorporate the collected resource's instance label (Issue http://issues.opennms.org/browse/NMS-12329[NMS-12329])
* Reportd generated reports cause: "No bean named '' is defined" in Persisted Reports (Issue http://issues.opennms.org/browse/NMS-12337[NMS-12337])
* InterfaceNodeCache doesn't remove deleted nodes immediately (Issue http://issues.opennms.org/browse/NMS-12338[NMS-12338])
* Delivering a report with "-" in local part of email address is not working (Issue http://issues.opennms.org/browse/NMS-12342[NMS-12342])
* Install guide for R-core is broken for CentOS 8 (Issue http://issues.opennms.org/browse/NMS-12352[NMS-12352])
* Karaf feature install issue with opennms-core-tracing-jaeger (Issue http://issues.opennms.org/browse/NMS-12359[NMS-12359])
* Fix requisition cache when accessing the Requisitions UI via "Edit in Requisition" (Issue http://issues.opennms.org/browse/NMS-12360[NMS-12360])

===== Enhancement

* Refactor the compatibility matrix in the documentation (Issue http://issues.opennms.org/browse/NMS-9684[NMS-9684])
* Be able to change the number of rows for the pagination control on the Requisitions UI (Issue http://issues.opennms.org/browse/NMS-9793[NMS-9793])
* Documentation typo for /rest/ifservices on the developers guide (Issue http://issues.opennms.org/browse/NMS-9842[NMS-9842])
* Remove alarm-change-notifier plugin (Issue http://issues.opennms.org/browse/NMS-10658[NMS-10658])
* Add OpenTracing support for Camel (JMS) RPC (Issue http://issues.opennms.org/browse/NMS-10961[NMS-10961])
* Support large buffer sizes in Kafka Sink Layer (Issue http://issues.opennms.org/browse/NMS-11126[NMS-11126])
* Investigate OpenTracing for our RPC communications (Issue http://issues.opennms.org/browse/NMS-11177[NMS-11177])
* RPC Metrics (Issue http://issues.opennms.org/browse/NMS-11517[NMS-11517])
* Sink Metrics (Issue http://issues.opennms.org/browse/NMS-11540[NMS-11540])
* Add a command to show configuration diffs (Issue http://issues.opennms.org/browse/NMS-12129[NMS-12129])
* Add Web-Hook as delivery option (Issue http://issues.opennms.org/browse/NMS-12153[NMS-12153])
* Add reply-to field to notification emails (Issue http://issues.opennms.org/browse/NMS-12224[NMS-12224])
* Refactor Event Timestamps to ISO-8601 Format (Breaking Change) (Issue http://issues.opennms.org/browse/NMS-12263[NMS-12263])
* Improve robustness of CassandraBlobStore for async operations (Issue http://issues.opennms.org/browse/NMS-12274[NMS-12274])
* Clearing threshold states via shell should take effect immediately and not require restart (Issue http://issues.opennms.org/browse/NMS-12277[NMS-12277])
* BSM configuration breaks without being notifed (Issue http://issues.opennms.org/browse/NMS-12288[NMS-12288])
* List Kafka RPC/Sink topics, Expose Metrics on Karaf shell (Issue http://issues.opennms.org/browse/NMS-12294[NMS-12294])
* Create proper systemd files for OpenNMS, Minion and Sentinel (Issue http://issues.opennms.org/browse/NMS-12299[NMS-12299])
* Add ability to update definitions when SNMP profile changes (Issue http://issues.opennms.org/browse/NMS-12307[NMS-12307])
* Fix security vulnerability with jackson-databind (Issue http://issues.opennms.org/browse/NMS-12308[NMS-12308])
* Availability boxes on node pages including sub pages differ (Issue http://issues.opennms.org/browse/NMS-12321[NMS-12321])
* OpenNMS 25 Dependency Still Allows Old PostgreSQL Versions (Issue http://issues.opennms.org/browse/NMS-12341[NMS-12341])
* Update base container image to use CentOS 8 (Issue http://issues.opennms.org/browse/NMS-12353[NMS-12353])
* Remove floating OpenJDK dependencies in OCI build (Issue http://issues.opennms.org/browse/NMS-12354[NMS-12354])
* Detect and help resolve Karaf bootstrap issues (Issue http://issues.opennms.org/browse/NMS-12356[NMS-12356])
* Update CISCO-ENTITY-SENSOR-MIB threshold trap events to include alarm-data (Issue http://issues.opennms.org/browse/NMS-12362[NMS-12362])
* switch core/web-assets from yarn to npm (Issue http://issues.opennms.org/browse/NMS-12363[NMS-12363])
* Collect and display file descriptor statistics via JMX for OpenNMS and Minion (Issue http://issues.opennms.org/browse/NMS-12364[NMS-12364])
