[[poller-config]]
= Poller configuration

OpenNMS backs up device configuration through the xref:reference:service-assurance/monitors/DeviceConfigMonitor.adoc[Device Config Monitor].

You must configure the <<tftp-port-configure, TFTP port>> before OpenNMS can back up device configurations.

[[tftp-port-configure]]
== Configure TFTP Port

By default, the TFTP server uses non-privileged port 6969 on both Minion and {page-component-title}.

.Connect to Karaf shell on {page-component-title}
[source, console]
----
ssh -p 8101 admin@localhost
----

.Conect to Karaf shell on Minion
[source, console]
----
ssh -p 8201 admin@localhost
----

.Configure TFTP port (Minion/{page-component-title})
[source, karaf]
----
config:edit org.opennms.features.deviceconfig.tftp
config:property-set port 69
config:update
----

== (optional) Enable push-based configuration upload

Devices may also push configuration through TFTP manually whenever their configuration changes.
This is not enabled by default; you must enable the sink for device configuration.

.Configure device config sink feature via Karaf shell on {page-component-title}
[source, console]
----
ssh -p 8101 admin@localhost
----

.Configure device config sink feature via Karaf shell on Minion
[source, console]
----
ssh -p 8201 admin@localhost
----

.Configure opennms-deviceconfig-sink feature ({page-component-title}/Minion)
[source, karaf]
----
feature:install opennms-deviceconfig-sink
----

. To make the device config sink start automatically on future service starts, add the line `opennms-deviceconfig-sink` to the file `$\{OPENNMS/MINION_HOME}/etc/featuresBoot.d/device-config.boot`.
(Create the file if it does not exist.)
. To make the device config sink start now, log in to the Karaf shell and run the following command to load the feature: `feature:install opennms-deviceconfig-sink`

== Events associated with device config backup

Pollerd can generate the following events in {page-component-title} for device config backup.

[options="header, autowidth"]
[cols="1,2"]
|===
| Event name
| Description

| uei.opennms.org/deviceconfig/configRetrievalFailed
| Failed to retrieve config associated with a given service during the last poll on a given interface

| uei.opennms.org/deviceconfig/configRetrievalSucceeded
| Config retrieval succeeded on a given service during the last poll on a given interface.

|===

== Retrieve device configuration on demand

You can use the Rest API to trigger device configuration retrieval outside of a monitor schedule.
(See xref:development:rest/device_config.adoc[Device Config Rest API].)

== Trigger backup from Karaf shell

You can also use the Karaf shell to manually trigger and retrieve a device configuration backup.

[source, karaf]
----
ssh -p 8101 admin@localhost
----

Once in the shell, you can print show the commands help as follows:
[source, console]
----
admin@opennms()> opennms:device-config-get --help
DESCRIPTION
        opennms:device-config-get

	Get device config from a specific Interface

SYNTAX
        opennms:device-config-get [options] host

ARGUMENTS
        host
                Hostname or IP Address of the system to poll
                (required)

OPTIONS
        -l, --location
                Location
                (defaults to Default)
        -t, --timeout
                Timeout for device config retrieval in msec
                (defaults to 60000)
        -s, --service
                Device Config Service
                (defaults to DeviceConfig)
        --help
                Display this help message
        -n, --node-id
                Node Id for Service
        -e, --encoding
                Encoding format
                (defaults to UTF-8)
----