[[dcb-requisition]]
= Create Requisition for Device Configuration Backup

After you have xref:operation:device-config-backup/ssh.adoc#backup-script[created a backup script for each device type] and xref:operation:device-config-backup/configuration.adoc#poller-config[configured the TFTP port], you can create a requisition for each device whose configuration you want to back up.

To activate the device configuration backup, you must add metadata that defines the device configuration backup script you created for the node's device type, and the device's username and password.

We recommend you also add metadata to overwrite the default device configuration backup schedule.
By default, {page-component-title} fetches device configuration backups every 24 hours at 12:00 a.m. (see xref:reference:service-assurance/monitors/DeviceConfigMonitor.adoc[Device Config Monitor] for details).
Changing the default schedule spaces out the backup for each group of nodes, rather than them all running at the same time.

. Log in to OpenNMS and click the gears icon.
. Choose *Provisioning>Manage Provisioning Requisitions*.
. Click *Add Requisition* and enter a name for the requisition.
If you want to enable device config backup on existing nodes in a requisition, select the desired requisition and edit the node definition.
. Click on the edit icon and click *Add Node*.
. Set up your requisition as described in xref:operation:provisioning/getting-started.adoc#requisition-create[Create a requisition].
. Click *Add Meta-Data*, and define the following key-value pairs:
.. `username`: username for the device
.. `password`: password for the device
.. `script-file`: name of the device configuration script for this type of device
.. `schedule`: a cron expression to specify the time to fetch the device backup configuration (default is `0 0 0 * * ?`, every 24 hrs at 12:00 a.m.)
. Click *Save* to save the metadata and then *Save* to save the requisition.
. Click *Return* and click *Synchronize*.
. Choose a scan option and click *Synchronize*.