[[dcb-manage]]
= Manage Device Configuration Backups

Once you have set up device configuration backups, you can do the following in the UI:

* View configuration backups for specific devices and device configuration backup history
* Download and compare device configuration backups
* Manually perform a device configuration backup

To manage device configuration backups, follow these steps:

. Click the gear icon and choose *Configuration Management* to view a list of devices.
+
NOTE: If you do not see any devices, [xref] run one backup immediately. Additional backups will appear according to their schedule.

. Click the icon in the *Last Backup Data* field to view the device’s configuration backup.
.. In the case of backups that have failed or are in progress, no icon appears.
. To perform actions such as compare, download, and view history, place a check beside the device(s) and click the menu option.
. You can search and sort the list of backups by typing in the search bar and clicking on the headers in the table respectively.