= Device Configuration Backup

OpenNMS lets you back up the configuration of devices like routers, firewalls, and switches, for better disaster recovery in case of network failure.

Through the UI, users can:

* Back up network device configuration on demand at any time for a single device or group of devices.
* Create a user-defined schedule to automate configuration backups.
* Trigger backups to occur when a device’s configuration changes, to ensure you always have a copy of the active device configuration.
* View backup history, download configurations, search, and compare configurations for specific devices at different points in time.

Only users with the xref:operation:user-management/security-roles.adoc#ga-role-user-management-roles[ROLE_DEVICE_CONFIG_BACKUP role] can perform and monitor device configuration backups.

IMPORTANT: The devices whose configuration you want to back up must either be TFTP-enabled or support an SSH shell.

== Before You Begin

You must configure OpenNMS to perform configuration backups before you can xref:operation:device-config-backup/dcb.adoc#dcb-manage[view and manage] them in the {page-component-title} UI:

* xref:operation:device-config-backup/ssh.adoc#backup-script[Create a backup script for each device type]
* xref:operation:device-config-backup/configuration.adoc#tftp-port-configure[Configure TFTP port]
* xref:operation:device-config-backup/dcb-requisition.adoc#dcb-requisition[Create a requisition], specify its metadata, and schedule it for immediate backup

== How it works

OpenNMS collects database configuration backups through a TFTP server embedded in the OpenNMS and Minion services.
Devices send their configuration to that TFTP server with either a pull- or push-based backup.

* Pull-based backup: OpenNMS uses its poller infrastructure to schedule tasks that connect via SSH into devices and execute configurable scripts that do the TFTP uploads.
* Push-based backup: Devices may upload their configuration themselves.
This may happen either by administrator interaction or scheduled jobs running on the devices themselves.

OpenNMS stores device configuration backups for IP addresses in the default location or at remote locations.
It archives received backups and records when changes happened.
It also records if backups fail and raises corresponding alarms.