
= Alarm Correlation
:description: Learn how to configure {page-component-title} to provide real-time feedback on alarm correlation.

This section describes how to configure {page-component-title} to provide real-time feedback on alarm correlation.

[[ga-situation-feedback]]
== Situation feedback

Situation feedback lets operators provide real-time feedback on alarm correlation.
You must have Elasticsearch installed to persist the feedback records.

=== Install feature

Follow these steps to install the situation feedback feature:

. Install the package from the Karaf shell:
+
[source, shell]
feature:install opennms-situation-feedback

. Add `opennms-situation-feedback` to a `.boot` file in `featuresBoot.d` to configure the feature to remain installed after {page-component-title} restarts:
+
[source, console]
echo "opennms-situation-feedback" | sudo tee ${OPENNMS_HOME}/etc/featuresBoot.d/opennms-situation-feedback.boot

=== Configure Elasticsearch persistence

Configure the situation feedback feature to use your Elasticsearch cluster from a Karaf shell in your {page-component-title} instance:

[source, shell]
----
$ ssh -p 8101 admin@localhost
...
admin@opennms()> config:edit org.opennms.features.situationfeedback.persistence.elastic
admin@opennms()> config:property-set elasticUrl http://elastic:9200
admin@opennms()> config:update
----

NOTE: This configuration is stored in `$\{OPENNMS_HOME}/etc/org.opennms.features.situationfeedback.persistence.elastic.cfg`.
See xref:deep-dive/elasticsearch/introduction.adoc[] for more information.

Installing the situation feedback feature exposes a REST endpoint that the OpenNMS plugin for Grafana uses to display and submit feedback.
You can find more information on the REST API in the xref:development:rest/situation-feedback.adoc[developer guide].
