
// Allow GitHub image rendering
:imagesdir: ../../images

[[gi-install-cassandra-rhel]]
===== RHEL

This section describes how to install the _Cassandra 3.11.x_ release on a _RHEL_ based systems for _Newts_.
The first step is to add the _DataStax_ community repository and install the required _GPG Key_ to verify the integrity of the _RPM packages_.
After that install the package with _yum_ and the _Cassandra_ service is managed by _Systemd_.

NOTE: This description was built on _CentOS 8_.

NOTE: Cassandra 3.x requires Java 8.

.Add the Cassandra repository
[source, bash]
----
vi /etc/yum.repos.d/cassandra.repo
----

.Content of the cassandra.repo file
[source, bash]
----
[cassandra]
name=Apache Cassandra
baseurl=https://www.apache.org/dist/cassandra/redhat/311x/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://www.apache.org/dist/cassandra/KEYS
----

.Accept the GPG keys and install Cassandra
[source, bash]
----
dnf install -y cassandra
----

.Enable Cassandra to start on system boot
[source, bash]
----
chkconfig cassandra on
----

.Start cassandra service
[source, bash]
----
service cassandra start
----

TIP: Verify whether the _Cassandra_ service is automatically started after rebooting the server.

NOTE: There is a bug reported with _Cassandra_ running with Systemd documented in link:https://issues.apache.org/jira/browse/CASSANDRA-15273[CASSANDRA-15273].
