
[[ga-user-config]]
= User Creation and Configuration

Only a user with admin privileges can create users and assign security roles.
We recommend creating a new user with admin privileges instead of using the default `admin` user profile (see <<quick-start/users.adoc#ga-admin-user-setup, Admin user setup>>).

Ideally, each user account corresponds to a single person.
This helps track who performs tasks in your {page-component-title} system.
Assigning different <<deep-dive/user-management/security-roles.adoc#ga-role-user-management-roles, security roles>> to each user helps restrict what tasks the user can perform.

In addition to local users, you can configure external authentication services including link:https://opennms.discourse.group/t/spring-security-and-ldap/1425[LDAP/LDAPS], link:https://opennms.discourse.group/t/spring-security-and-radius/1424[RADIUS], and link:https://opennms.discourse.group/t/single-sign-on-sso-using-spring-security-and-kerberos/[Single Sign On (SSO)].
Configuration specifics for these services are outside the scope of this documentation.

WARNING: Do not delete the default `admin` and `rtc` user profiles.
The `rtc` user profile is used for the communication of the Real-Time Console on the start page to calculate the node and service availability.

[[ga-user-create]]
== Create a user

. Log in as a user with admin permissions.
. Click the gear icon at the top-right of the screen.
. Choose menu:Configure OpenNMS[Configure Users, Groups and On-Call Roles > Configure Users].
. Click *Add new user* and specify a user ID and password, confirm the password, and click *OK*.
+
WARNING: You cannot use angle brackets (<>), single (') and double quotation marks ("), or the ampersand symbol (&) in a user ID.

. (Optional) Add user information in the appropriate fields.
. (Optional) Assign <<deep-dive/user-management/security-roles.adoc#ga-role-user-management-roles, user permissions>>.
+
NOTE: By default, a new user has permissions to acknowledge and work with alarms and notifications.
They cannot access the *Configure OpenNMS* administration menu.
+
To create a user with administrative priviliges, add the `ROLE_ADMIN` role to their account. 

. (Optional) Specify where to send messages to the user in the notification information area.
. (Optional) <<ga-user-schedule, Set a schedule>> for when a user should receive notifications.
. Click *Finish* to save changes.

[[ga-user-schedule]]
== Create user duty schedule

A duty schedule specifies the days and times a user or group of users receives notifications, on a per-week basis.
This feature lets you customize a schedule based on your team's hours of operation.
Schedules are additive: a user could have a regular work schedule, and a second schedule for days or weeks when they are on-call.

If {page-component-title} needs to notify an individual user, but they are not on duty at the time the notification is generated, it never sends the notification to them.

Notifications sent to users in groups are different, depending on the scenario:

* For a group on duty at time of notification – all users also on duty receive the notification.
* For a group on duty with no members on duty – notification is queued and sent to the next user who comes on duty.
* For an off-duty group – notification is never sent.

To add a duty schedule for a user or group of users, follow these steps:

. Log in as a user with admin permissions.
. Click the gear icon at the top-right of the screen.
. Choose menu:Configure OpenNMS[Configure Users, Groups and On-Call Roles > Configure Users] or *Configure Groups*.
. Choose the user or group you want to modify.
. In the *Duty Schedule* area, choose the number of schedules you want to add from the list and click *Add Schedule*.
. Specify the days and times during which you want the user or group to receive notifications.
. Click *Finish*.

