
[[ga-user-groups]]
= Groups
:description: How to create user groups and add members to them in {page-component-title}.

Groups in {page-component-title} are collections of users.
They may be used to organize users, such as in the case of an instance with many users or permissions sets.

You can configure groups to receive notifications.
This is often a more convenient way to maintain notification schedules, rather than configuring them to be sent to individual users.
Sending notifications to groups lets you build more complex notification workflows, and makes it easier to manage recipients.

[[ga-user-group-create]]
== Create a group

To create a group of users, follow these steps:

. Log in as a user with admin permissions.
. Click menu:User Management[Manage Groups] in the side menu.
. Or, click menu:Administration[Configure OpenNMS] in the side menu, then under OpenNMS System, click menu:Configure Users, Groups and On-Call Roles[Configure Groups].
. Click *Add New Group* and specify the its name and description.
+
NOTE: You cannot use angle brackets (`<>`), single (`'`) and double (`"`) quotation marks, or the ampersand symbol (`&`) in a group name.

. Add a user to the group by selecting them from the Available Users list and clicking *>>* to move them to the Currently in Group list.
. (Optional) Assign responsibility categories (Routers, Switches, Servers, and so on).
. (Optional) Create a <<deep-dive/user-management/user-config.adoc#ga-user-schedule, duty schedule>>.
. Click *Finish* to apply the changes.

NOTE: The order of users in a group is important.
Notifications are sent to users in order from the top of the group membership list to the bottom.

=== Modify group membership

You may need to add or remove users from groups as team membership changes.
To modify the users in a group, follow these steps:

. Log in as a user with admin permissions.
. Click menu:User Management[Manage Groups] in the side menu.
. Or, click menu:Administration[Configure OpenNMS] in the side menu, then under OpenNMS System, click menu:Configure Users, Groups and On-Call Roles[Configure Groups].
. Find the group that you want to modify and click the *modify* symbol next to its name.
. Modify the group membership as appropriate.
** Add a user to the group by selecting them from the Available Users list and clicking *>>* to move them to the Currently in Group list.
** Remove a user from the group by selecting them from the Currently in Group list and clicking *<<* to move them to the Available Users list.
. Click *Finish* to apply the changes.

NOTE: The order of users in a group is important.
Notifications are sent to users in chronological order, from the top of the group membership list to the bottom.

=== Delete a group

To delete a group from your {page-component-title} instance, follow these steps:

. Log in as a user with admin permissions.
. Click menu:User Management[Manage Groups] in the side menu.
. Or, click menu:Administration[Configure OpenNMS] in the side menu, then under OpenNMS System, click menu:Configure Users, Groups and On-Call Roles[Configure Groups].
. Find the group that you want to delete and click the *delete* symbol next to its name.
. Click *OK* to confirm your decision.

IMPORTANT: If you delete a group, users do not receive a notification that it has been deleted.
If the group is associated with a schedule, that schedule will also be deleted, and users previously included in the group will no longer receive notifications as configured in that schedule.
