
[[ga-user-maintenance]]
= User Maintenance
User maintenance describes additional tasks and information related to users.

== Passwords

=== Set a new password for any user
. Log in as a user with admin permissions.
. Click the gear icon at the top-right of the screen.
. Choose menu:Configure OpenNMS[Configure Users, Groups and On-Call Roles > Configure Users].
. Click the *Modify* icon next to an existing user and select *Reset Password*.
. Type a new password, confirm the password, and click *OK*.
. Click *Finish*.

=== Change your password

. Log in with user name and current password.
. Choose *Change Password* from the list below your login name.
. Specify your current password, then set and confirm the new password.
. Click *Submit*.
. Log out and log in with your new password.

== Delete users and groups

. Log in as a user with admin permissions.
. Click the gear icon at the top-right of the screen.
. Choose menu:Configure OpenNMS[Configure Users, Groups and On-Call Roles > Configure Users]  or *Configure Groups*.
. Click the trash bin icon beside the user or group you want to delete.
. Click *OK* to confirm deletion.

IMPORTANT: When you delete a group no one receives a notification that the group has been deleted.
Be aware that deleting a group or user also removes any schedules associated with that group or user, meaning they will not receive notifications specified as part of a schedule.

== Advanced configuration

{page-component-title} persists the user, password, and other detail descriptions in the `users.xml` file.

