[[ga-logging-introduction]]
= Logging

{page-component-title} stores logs based on the name of the daemon that was acting on a process.
For example, logs for xref:operation:service-assurance/introduction.adoc#ga-service-assurance[service assurance checks] that are done by `pollerd` are stored in the `pollerd.log` file.

The log files can be found in `$/{OPENNMS_HOME}/logs`, which is a symlink to `/var/log/opennms`.


For information on the different log files, how they are named, and what they include, see xref:reference:logging/introduction.adoc[List of log files].

[[ga-change-logging]]
== Change logging

{page-component-title} uses the https://logging.apache.org/log4j/[Apache Log4j] framework to manage how the logs are written, structured, and rotated.

The log configuration file can be found in `$\{OPENNMS_HOME}/etc/opennms/log4j2.xml`.

Each daemon can have an individual logging level.

The corresponding configuration in this file can be found in the XML tree path: `configuration/loggers/root/DynamicThresholdFilter/KeyValuePair`.

The default logging level is `WARN`, and for troubleshooting, use `DEBUG`. 
See the table below for a description of the available log levels.
After saving the changes in this file, {page-component-title} needs a few seconds to apply the changes.

NOTE: Don't forget to set the logging level back to WARN after changing it to a higher severity.
Depending on the scale, {page-component-title} can generate a lot more logs, which requires more disk space.
