
[[ga-enlinkd]]
= Enhanced Link Daemon

The enhanced link daemon (enlinkd) discovers connections between nodes using data generated by various link discovery protocols, and that is accessible via SNMP.
Enlinkd gathers this data regularly and uses it to generate a snapshot of a device's neighbors from its perspective, as defined by SNMP data collectors.

The xref:operation:topology/enlinkd/layer-2/bridge-discovery.adoc[bridge domain discovery process] uses the data gathered by the Bridge and IpNetToMedia collectors to generate a bridge broadcast domain layout.
The bridge forwarding tables (BFTs) that are provided by individual nodes display information about the MAC addresses discovered on bridge ports.
This is what the bridge domain discovery process considers a connection; it is not very useful on its own, however, so the process also performs domain calculations to assign each MAC address to the port where the device that holds it is effectively connected (the nearest known bridge port).

Connections that are discovered by the collectors and the bridge domain discovery process are called "links."
These links are discovered based on information that is provided by an agent's understanding of connections at the OSI layer 2, layer 3, or other OSI layers.

NOTE: In this context, a "link" does not refer only to the network OSI layer 2 connection.

The updaters use the topologies update API provided by each supported discovery protocol to provide connections information to other OpenNMS services and daemons via the OnmsTopologyDao.
The topologies are made of vertices and edges, and are used to generate a topology map.
They also allow the Kafka Producer to send TopologyMessage data.

The following pages describe enlinkd and how it can be configured, the supported discovery protocols, and the SNMP MIBs that must be exposed so links between nodes can be gathered.
You can view detailed information about a node's connections and supporting link data on the node detail page in the {page-component-title} web UI.

[[ga-enlinkd-layers]]
== Topology Layers

The Enhanced Linkd topology map supports layered protocol maps.

Choose menu:Maps[Topology] to display the topology map, and click the Layers icon on the right panel of the map to access available layers:


All:: (default) Displays the topology Enhanced Linkd discovers, for all supported protocols (OSPF, ISIS, Bridge, LLDP and CDP).
It also includes xref:development:rest/user-defined-links.adoc[User-Defined] topology.

CDP:: Displays the Cisco Discovery Protocol (CDP) topology Enhanced Linkd discovers.

LLDP:: Displays the Link Layer Discovery Protocol (LLDP) topology Enhanced Linkd discovers.

Layer2:: Displays CDP and LLDP combined topology Enhanced Linkd discovers.

Bridge:: Shows only Bridge links.

OSPF:: Displays the Open Shortest Path First (OSPF) topology Enhanced Linkd discovers.

ISIS:: Displays the Intermediate System to Intermediate System (IS-IS) topology Enhanced Linkd discovers.

Layer3:: Displays OSPF and IS-IS combined topology Enhanced Linkd discovers.

UserDefined:: Displays xref:development:rest/user-defined-links.adoc[User-Defined] topology.

[[ga-enlinkd-daemon]]
For more information, see xref:reference:daemons/daemon-config-files/enlinkd.adoc[Enlinkd] in the Reference section.
