[[ga-enlinkd]]
= Enhanced Linkd

Enhanced Linkd (Enlinkd) discovers connections between nodes using data generated by various link discovery protocols and accessible via SNMP.
Enlinkd gathers this data regularly and creates a snapshot of a device's neighbors from its perspective by SNMP data collectors.
Enlinkd consolidates the collected Data by Bridge Domain Discovery and Topologies Updater.

Enlinkd-Bridge Domain Discovery use the data gathered by Bridge and IpNetToMedia collectors to provide Bridge Broadcast Domain layout.
The Bridge Forwarding Table provided by the single nodes displays information about the MAC address learned on which bridge port, this is what the Bridge considers a connection: this is not very useful, so Bridge Discovery performs domain calculations to assign to every MAC address the port where the device that holds it is effectively connected (or the known nearest bridge port).

Enlinkd-Updaters, for every supported discovery protocol, use the provided Topologies Update API to provide connections information to other OpenNMS service and daemon via OnmsTopologyDao.
The provided topologies are used in topology-map and for sending TopologyMessage via Kafka Producer.

The connections discovered by Enlinkd collectors and by Bridge Domain Discovery are called links.
The term link, within the context of Enlinkd, is not synonymous with the term "link" when used with respect to the network OSI Layer 2 domain, whereby a link only indicates a Layer 2 connection.
A link in context of Enlinkd is a more abstract concept and describes any connection between two {page-component-title} nodes.
These links are discovered based on information provided by an agent's understanding of connections at the OSI Layer 2, Layer 3, or other OSI layers.

The topologies that Enlinkd-Updaters discover are made of vertices and edges.

The following sections describe the Enlinkd daemon and its configuration.
Additionally, the supported link discovery implementations are described as well as a list of the SNMP MIBs that the SNMP agents must expose for EnLinkd to gather links between nodes.
You can view detailed information about a node's connections (discovered links) and supporting link data on the node detail page within the {page-component-title} Web UI.

[[ga-enlinkd-layers]]
== Topology Layers

The Enhanced Linkd topology map supports layered protocol maps.

Choose menu:Maps[Topology] to display the topology map, and click the Layers icon on the right panel of the map to access available layers:


* *All* (default) – displays the topology Enhanced Linkd discovers, for all supported protocols (OSPF, ISIS, Bridge, LLDP and CDP).
It also includes xref:development:rest/user-defined-links.adoc[User-Defined] topology.

* *Cdp* – displays the Cisco Discovery Protocol (CDP) topology Enhanced Linkd discovers.

* *Lldp* – displays the Link Layer Discovery Protocol (LLDP) topology Enhanced Linkd discovers.

* *Layer2* – displays CDP and LLDP combined topology Enhanced Linkd discovers.

* *Bridge* – shows only Bridge links.

* *Ospf* – displays the Open Shortest Path First (OSPF) topology Enhanced Linkd discovers.

* *Isis* – displays the Intermediate System to Intermediate System (IS-IS) topology Enhanced Linkd discovers.

* *Layer3* – displays OSPF and IS-IS combined topology Enhanced Linkd discovers.

* *UserDefined* – displays xref:development:rest/user-defined-links.adoc[User-Defined] topology.

[[ga-enlinkd-daemon]]
== Enlinkd daemon

Essentially, each Enlinkd-Collector asks each device the following question: "What is the network topology from your point of view?"
CDP, LLDP, OSPF and ISIS collectors provide the required information about links.
Bridge Collectors are able to collect Bridge Forwarding Table and IpNetToMedia Table on devices and to provide effective links a further step is required.
The Enlinkd-Bridge-Discovery process attempts to discover bridge domain links with the data coming from all collected Bridge Forwarding Tables.
The Topology-Updaters correlate all collected topology data to generate a global topology layout of your network.
For each supported protocol {page-component-title} creates a collection group with an assigned priority.
The collection group is scheduled according to the rescan interval defined for the related protocol.
The collection group run sends protocol-specific SNMP collection and storage to the Priority Executor.
Collection starts with data that has the lowest priority value.
Further, collection uses a priority map to assign a priority to a specific node.
Starting from the lowest IP subnetwork, the same nodeID priority is assigned to the nodes that belong to the same network.
The final node collection priority is the sum of node priority and protocol-related collection group priority.
By default, CDP data collection (priority 1000) is done before LLDP data collection (priority 2000), followed by OSPF, IS-IS, and Bridge data collection (priority 3000, 4000, and 10000 respectively).

For large environments, you can configure the behavior of Enlinkd.
During the EnLink discovery process, informational and error output is logged to a global log file.

.Global log and configuration files for Enlinkd
[options="header"]
[cols="1,3,1"]
|===
| File
| Description
| Location

| enlinkd-configuration.xml
| Global configuration for the daemon process
| $OPENNMS_HOME/etc

| enlinkd.log
| Global Enlinkd log file
| $OPENNMS_HOME/logs

| log4j2.xml
| Configuration file to set the log level for Enlinkd.
| $OPENNMS_HOME/etc
|===

.Configuration file for Enlinkd
[source, xml]
----
<?xml version="1.0" encoding="ISO-8859-1"?>
<enlinkd-configuration threads="5"
                     executor-queue-size="100"
                     executor-threads="5"
                     discovery-bridge-threads="1"
                     initial_sleep_time="60000"
                     bridge_topology_interval="300000"
                     topology_interval="30000"
                     cdp_rescan_interval="86400000"
                     lldp_rescan_interval="86400000"
                     bridge_rescan_interval="86400000"
                     ospf_rescan_interval="86400000"
                     isis_rescan_interval="86400000"
                     cdp-priority="1000"
                     lldp-priority="2000"
                     bridge-priority="10000"
                     ospf-priority="3000"
                     isis-priority="4000"
                     use-cdp-discovery="true"
                     use-bridge-discovery="true"
                     use-lldp-discovery="true"
                     use-ospf-discovery="true"
                     use-isis-discovery="true"
                     disable-bridge-vlan-discovery="false"
                     max_bft="100"
                     />
----

NOTE: If multiple protocols are enabled, the links will be discovered for each enabled discovery protocol.
      The topology Web UI visualizes links for each discovery protocol.
      For example, if you start CDP and LLDP discovery, the Web UI visualizes a CDP link and an LLDP link.

.Description for global configuration parameter
[options="header"]
[cols="1,3,1"]
|===
| Attribute
| Description
| Default

3+| *Integer*

| threads
| Number of parallel threads schedulable objects use: collector groups, updaters, and discovery.
| 3

| executor-queue-size
| The initial queue size of the Priority Executor.
| 100

| executor-threads
| Number of parallel threads the collector uses.
| 5

| discovery-bridge-threads
| The number of parallel threads used for bridge topology discovery.
| 1

| max_bft
| The maximum number of bridge forwarding tables (BFTs) stored in memory for bridge topology discovery.
| 100

| initial_sleep_time
| Time in milliseconds to wait to start collectors after {page-component-title} is started.
| 60000

| bridge_topology_interval
| Interval in milliseconds for executing bridge topology discovery.
| 300000

| topology_interval
| Interval in milliseconds for topology updater.
| 30000

| cdp_rescan_interval
| Interval in milliseconds for Cisco Discovery Protocol (CDP) links discovery.
| 86400000

| lldp_rescan_interval
| Interval in milliseconds for Link Layer Discovery Protocol (LLDP) links discovery.
| 86400000

| bridge_rescan_interval
| Interval in milliseconds for Bridge data discovery.
| 86400000

| ospf_rescan_interval
| Interval in milliseconds for Open Short Path First (OSPF) links discovery.
| 86400000

| isis_rescan_interval
| Interval in milliseconds for Intermediate System to Intermediate System (IS-IS) links discovery.
| 86400000

| cdp-priority
| The priority used for running CDP links discovery.
| 1000

| lldp-priority
| The priority used for running LLDP links discovery.
| 2000

| bridge-priority
| The priority used for running Bridge links discovery.
| 10000

| ospf-priority
| The priority used for running OSPF links discovery.
| 3000

| isis-priority
| The priority used for running IS-IS links discovery.
| 4000

3+| *Boolean*

| use-cdp-discovery
| Enable or disable discovery based on CDP information.
| true

| use-bridge-discovery
| Enable or disable discovery based on the bridge information.
| true

| use-lldp-discovery
| Enable or disable discovery based on LLDP information.
| true

| use-ospf-discovery
| Enable or disable discovery based on OSPF information.
| true

| use-isis-discovery
| Enable or disable discovery based on IS-IS information.
| true

| disable-bridge-vlan-discovery
| Set to true to skip VLAN enumeration and scanning during bridge discovery
| false
|===

The discovery for bridge first start is scheduled at `initial_sleep_time + bridge_topology_interval`.
The updaters' first start is scheduled at 0L.
Restart OpenNMS or just the Enlinkd daemon to apply configuration changes.

.Send configuration reload event via CLI

[source, console]
----
cd ${OPENNMS_HOME}/bin
./send-event.pl uei.opennms.org/internal/reloadDaemonConfig --parm 'daemonName Enlinkd'
----
