
[[ga-enlinkd]]
= Enhanced Link Daemon
:description: Learn how the Enhanced Link Daemon in {page-component-title} helps with network topology mapping, including a list of supported topology layers.

The enhanced link daemon (enlinkd) discovers connections between nodes using data generated by various link discovery protocols.
This data is collected from nodes via SNMP.
Enlinkd gathers this data regularly and uses it to generate a snapshot of a device's neighbors from its perspective, as defined by SNMP data collectors.

NOTE: In this context, a "link" refers to more than the network OSI Layer 2 connection.

The topologies are made of vertices and edges, and are used to generate a topology map.
They also allow the Kafka Producer to send TopologyMessage data.

The following pages describe enlinkd and how to configure it, the supported discovery protocols, and the SNMP MIBs that must be exposed to gather links between nodes.
You can view detailed information about a node's connections and supporting link data on the node detail page in the {page-component-title} web UI.

[[ga-enlinkd-collectors]]
== Enhanced linkd supported protocols

Enhanced Linkd collects topology data from CDP, LLDP, OSPF, IS-IS and Bridge MIBs.
For more information, see xref:deep-dive/topology/enlinkd/layer-2-discovery.adoc[Layer 2 Discovery] and xref:deep-dive/topology/enlinkd/layer-3-discovery.adoc[Layer 3 Discovery].

[[ga-enlinkd-layers]]
== Topology layers

The enlinkd topology map supports layered protocol maps.

Click *Topology Map* in the side menu to display the topology map, and click the *layers* symbol in the panel to the right of the map to view layers.
The following layers are available:

All (default):: Displays the topology that enlinkd discovers, for all supported protocols (OSPF, IS-IS, Bridge, LLDP, and CDP).
This layer also includes xref:development:rest/user-defined-links.adoc[user-defined topologies].

CDP:: Displays the Cisco Discovery Protocol (CDP) topology that enlinkd discovers.

LLDP:: Displays the Link Layer Discovery Protocol (LLDP) topology that enlinkd discovers.

Layer2:: Displays the combined CDP and LLDP topology that enlinkd discovers.

Bridge:: Displays only Bridge links.

OSPF:: Displays the Open Shortest Path First (OSPF) topology that enlinkd discovers.

OSPFAREA:: Displays the OSPF Area topology that enlinkd discovers.

ISIS:: Displays the Intermediate System to Intermediate System (IS-IS) topology that enlinkd discovers.

Layer3:: Displays the combined OSPF and IS-IS topology that enlinkd discovers.

NetworkRouter:: Displays the combined topology for subnetworks and routers.

UserDefined:: Displays xref:development:rest/user-defined-links.adoc[user-defined topologies].

[[ga-enlinkd-daemon]]
For more information, see xref:reference:daemons/daemon-config-files/enlinkd.adoc[Enlinkd] in the Reference section.
