
= FtpMonitor

The FtpMonitor validates FTP connection dial-up processes.
The monitor can test the FTP server on multiple ports with specific login data.

The service using the FtpMonitor is up if the FTP server responds with return codes between 200 and 299.
For special cases, the service is also marked as up for codes 425 and 530.

This monitor implements <<service-assurance/monitors/introduction.adoc#ga-service-assurance-monitors-placeholder-substitution-parameters, placeholder substitution in parameter values>>.

== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.FtpMonitor`
| Remote Enabled | `true`
|===

== Configuration and use

.Monitor specific parameters for the FtpMonitor.
[options="header, autowidth"]

All listed parameters are optional. 

|===
| Parameter              | Description                                                                                 |Default| Placeholder substitution
| retry                | Number of attempts to get a valid FTP response/response-text.                                | 0| No
| port                 | A list of TCP ports to which connection shall be tried.                                     | 20, 21 | No
| password             | Use this parameter with the `userid` parameter to perform
                           authentication. This parameter specifies the password to use.                           | empty string | Yes
| userid            | Use this parameter with the `password` parameter to perform
                           authentication. This parameter specifies the user ID to use.                            |n/a | Yes
|===

This monitor implements the <<service-assurance/monitors/introduction.adoc#<ga-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

== Examples

Example configuration on how to configure the monitor in poller-configuration.xml.
[source, xml]
----
<service name="FTP" interval="300000" user-defined="false" status="on">
 <parameter key="retry" value="1"/>
 <parameter key="timeout" value="3000"/>
 <parameter key="port" value="21"/>
 <parameter key="userid" value=""/>
 <parameter key="password" value=""/>
</service>

<service name="FTP-With-Auth-From-Asset" interval="300000" user-defined="false" status="on">
 <parameter key="retry" value="1"/>
 <parameter key="timeout" value="3000"/>
 <parameter key="port" value="21"/>
 <parameter key="userid" value="\{username\}"/>
 <parameter key="password" value="{password}"/>
</service>

<service name="FTP-Customer" interval="300000" user-defined="false" status="on">
 <parameter key="retry" value="1"/>
 <parameter key="timeout" value="3000"/>
 <parameter key="port" value="21"/>
 <parameter key="userid" value="Customer"/>
 <parameter key="password" value="MySecretPassword"/>
</service>

<monitor service="FTP" class-name="org.opennms.netmgt.poller.monitors.FtpMonitor"/>
<monitor service="FTP-With-Auth-From-Asset" class-name="org.opennms.netmgt.poller.monitors.FtpMonitor"/>
<monitor service="FTP-Customer" class-name="org.opennms.netmgt.poller.monitors.FtpMonitor"/>
----

== Hint

*Comment from FtpMonitor source*

Also want to accept the following ERROR message generated by some FTP servers following a QUIT command without a previous successful login:
"530 QUIT : User not logged in. Please login with USER and PASS first."

Also want to accept the following ERROR message generated by some FTP servers following a QUIT command without a previously successful login:
"425 Session is disconnected."

See also: http://tools.ietf.org/html/rfc959
