
= HostResourceSwRunMonitor

This monitor tests the running state of one or more processes.
It does this via SNMP by inspecting the _hrSWRunTable_ of the http://www.ietf.org/rfc/rfc2790[HOST-RESOURCES-MIB].
A given service name is matched to a _hrSWRunName_ value, then the monitor checks the run level of the matching _hrSWRunState_.

Your OpenNMS instance must be able to successfully collect SNMP metrics from your node(s) for this monitor to work.
Furthermore, the SNMP agent on the system must support the HOST-RESOURCES-MIB.
Most modern SNMP agents, including most distributions of the Net-SNMP agent and the SNMP service that ships with Microsoft Windows, support this MIB.
Out-of-box support for HOST-RESOURCES-MIB among commercial Unix operating systems may be somewhat spotty.

== Monitor Facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.HostResourceSwRunMonitor`
| Remote Enabled | false
|===

== Configuration and Use

.Monitor specific parameters for the HostResourceSwRunMonitor
[options="header, autowidth"]
|===
| Parameter            | Description                                                                                    | Required | Default value
| `service-name`       | The name of the process to be monitored. This parameter's value is case-sensitive and is
                         evaluated as an exact match.                                                                   | required | `-`
| `port`               | The port of the SNMP agent of the server to test.                                              | optional | `from snmp-config.xml`
| `match-all`          | If the process name appears multiple times in the _hrSWRunTable_, and this parameter is set to
                         `true`, then all instances of the named process must match the value specified for
                         `run-level`.                                                                                   | optional | `false`
| `run-level`          | The maximum allowable value of _hrSWRunStatus_ among +
                         _running(1)_, +
                         _runnable(2)_ = waiting for resource +
                         _notRunnable(3)_ = loaded but waiting for event +
                         _invalid(4)_ = not loaded                                                                      | optional | `2`
| `service-name-oid`   | The numeric object identifier (OID) from which process names are queried.
                         Defaults to _hrSWRunName_ and should not be changed under normal circumstances.
                         However, changing it to _hrSWRunParameters_ (`.1.3.6.1.2.1.25.4.2.1.5`) is helpful when dealing
                         with processes running in Java Virtual Machines which all have the same process name _java_.   | optional | `.1.3.6.1.2.1.25.4.2.1.2`
| `service-status-oid` | The numeric object identifier (OID) from which run status is queried.
                         Defaults to _hrSWRunStatus_ and should not be changed under normal circumstances.              | optional | `.1.3.6.1.2.1.25.4.2.1.7`

|===

This monitor implements the <<service-assurance/monitors/introduction.adoc#ga-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

== Examples

The following example shows how to monitor the process called _httpd_ running on a server using this monitor.
The configuration in `poller-configuration.xml` has to be defined as the following:
[source, xml]
----
<service name="Process-httpd" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="3"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="service-name" value="httpd"/><1>
    <parameter key="run-level" value="3"/><2>
    <parameter key="match-all" value="true"/><3>
</service>

<monitor service="Process-httpd" class-name="org.opennms.netmgt.poller.monitors.HostResourceSwRunMonitor"/>
----
<1> Name of the process on the system
<2> Test the state if the process is in a valid state, i.e. have a `run-level` no higher than _notRunnable(3)_
<3> If the _httpd_ process runs multiple times the test is done for each instance of the process.
