
= VmwareCimMonitor

This monitor is part of the VMware integration Provisiond provides.
The monitor is specialized to test the health status provided from all host system (host) sensor data.

This monitor runs only if the host is in power state "on".

This monitor requires hosts be imported with Provisiond and the VMware import.{page-component-title} requires network access to VMware vCenter and the hosts. It uses the credentials from vmware-config.xml for the responsible vCenter to get the sensor data. 
The following asset fields are filled from Provisiond and provided by the VMware import feature:

* VMware Management Server
* VMware Managed Entity Type
* foreignId (which contains an internal VMware vCenter Identifier)

The global health status is evaluated by testing all available host sensors and evaluating the state of each sensor.
A sensor state could be represented as the following:

* Unknown(0)
* OK(5)
* Degraded/Warning(10)
* Minor failure(15)
* Major failure(20)
* Critical failure(25)
* Non-recoverable error(30)

The service is up if all sensors have the status OK(5).
If any sensor gives another status than OK(5), the service is marked as down.
The monitor error reason contains a list of all sensors which do not return status OK(5).

When using link:https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/techpaper/Distributed-Power-Management-vSphere.pdf[Distributed Power Management] (automatic PDF download), the standBy state forces a service down. 
The health status is gathrered with a direct connection to the host and in standby this connection is unavailable and the service is down.

To deal with standby states, use the ignoreStandBy parameter.
In case of a standby state, the service is considered as up. See the ignoreStandBy parameter on how to change the state. 

== Monitor facts

[options="autowidth"]
|===
| Class Name     | `org.opennms.netmgt.poller.monitors.VmwareCimMonitor`
| Remote Enabled | false
|===

== Configuration and use

.Optional monitor-specific parameters for the VmwareCimMonitor
[options="header"]
[cols="1,3,2"]
|===
| Parameter       | Description                                                    |Default
| retry         | Number of retries before the service is marked as down.        | 0
| ignoreStandBy | Treat power state standBy as up.                           | false
|===

This monitor implements the <<service-assurance/monitors/introduction.adoc#ga-service-assurance-monitors-common-parameters, Common Configuration Parameters>>.

== Examples
Some example configuration on how to configure the monitor in poller-configuration.xml.

[source, xml]
----
<service name="VMwareCim-HostSystem" interval="300000" user-defined="false" status="on">
  <parameter key="retry" value="2"/>
  <parameter key="timeout" value="3000"/>
</service>

<monitor service="VMwareCim-HostSystem" class-name="org.opennms.netmgt.poller.monitors.VmwareCimMonitor"/>
----
