.Configure PostgreSQL database access
[source, shell]
----
sudo -u opennms vi /usr/share/opennms/etc/opennms-datasources.xml
----

.Set credentials to access the PostgreSQL database
[source, xml]
----
<jdbc-data-source name="opennms"
                    database-name="opennms"<1>
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/opennms"
                    user-name="** YOUR-OPENNMS-USERNAME **"<2>
                    password="** YOUR-OPENNMS-PASSWORD **" /><3>

<jdbc-data-source name="opennms-admin"
                    database-name="template1"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/template1"
                    user-name="postgres"<4>
                    password="** YOUR-POSTGRES-PASSWORD **" /><5>
----

<1> Set the database name {page-component-title} should use.
<2> Set the user name to access the opennms database table.
<3> Set the password to access the opennms database table.
<4> Set the postgres user for administrative access to PostgreSQL.
<5> Set the password for administrative access to PostgreSQL.

.Detect Java environment and persist in /usr/share/opennms/etc/java.conf
[source, console]
----
sudo /usr/share/opennms/bin/runjava -s
----

.Initialize the database and detect system libraries persisted in /opt/opennms/etc/libraries.properties
[source, console]
----
sudo /usr/share/opennms/bin/install -dis
----

._Binding to privileged ports_

The core service user must be able to send ICMP echo requests.
During setup, the permissions for `net.ipv4.ping_group_range` are set permanently on boot via `/etc/sysctl.d/99-opennms-non-root-icmp.conf`.
Some system kernels do not honor this setting, and in those cases, additional configuration is required to allow binding to privileged ports.
We recommend creating a systemd overlay to add the necessary settings to the service configuration.

Run `systemctl edit --full opennms.service` and add the following line to the `[Service]` section:

[source, properties]
----
AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE
----

Reload the systemd unit with `systemctl daemon-reload` and restart the service with `systemctl restart opennms`.

(For more background on this issue, see https://opennms.discourse.group/t/h29-wont-start-with-permission-error-to-open-icmp-socket/2387[H29+ won't start with permission error to open ICMP socket] on Discourse.)

.Allow connection to the web UI from your network

If you are using Uncomplicated Firewall (UFW) as your host firewall, you can allow access to the web user interface with the command:

[source, console]
----
sudo ufw allow 8980/tcp
----
