
[[telemetryd-netflow5-protocol]]
==== NetFlow Version 5

link:https://www.cisco.com/c/en/us/td/docs/net_mgmt/netflow_collection_engine/3-6/user/guide/format.html[NetFlow] is a protocol that provides the ability to collect IP network traffic from network devices and administrators can determine and analyze the network communication.
This protocol allows to process and persist NetFlow v5 packets with _{opennms-product-name}_.
Data is persisted in link:https://www.elastic.co/products/elasticsearch[ElasticSearch] and can be analyzed with link:https://www.elastic.co/products/kibana[Kibana].

IMPORTANT: The NetFlow v5 requires a running ElasticSearch 5.6+ to persist the NetFlow data.

To enable support for NetFlow v5, edit `${OPENNMS_HOME}/etc/telemetryd-configuration.xml` and add the following protocol configuration:

.Enable NetFlow v5 in telemetryd-configuration.xml
[source, xml]
----
<protocol name="Netflow-5" description="Listener for Netflow 5 UDP packets" enabled="true">
   <listener name="Netflow-5-UDP-8877" class-name="org.opennms.netmgt.telemetry.listeners.udp.UdpListener">
        <parameter key="port" value="8877"/>
    </listener>

    <adapter name="Netflow-5-Parser" class-name="org.opennms.netmgt.telemetry.adapters.netflow.Netflow5Adapter">
    </adapter>
 </protocol>
----

Apply the changes without restarting by sending a `reloadDaemonConfig` event in the CLI or the WebUI:

.Send a reloadDaemonConfig event through CLI
[source]
----
${OPENNMS_HOME}bin/send-event.pl -p 'daemonName Telemetryd' uei.opennms.org/internal/reloadDaemonConfig
----

By default, this will open a UDP socket bound to `0.0.0.0:8877` to which _NetFlow v5_ messages can be forwarded.

====== Configure Node Cache

By default each _Flow Document_ is - if known by _{opennms-product-name}_ - enriched with node information.
To reduce the number of queries to the database, the data is cached.
The following cache properties are available:

[options="header, autowidth"]
|===
| Property | Description | Required | default

| `nodeCache.maximumSize`
| The maximum size of the cache
| `false`
| `1000`

| `nodeCache.expireAfterWrite`
| Number of seconds until an entry in the node cache is evicted. Set to 0 to disable eviction.
| `false`
| `300`

| `nodeCache.recordStats`
| Defines if cache statistics are exposed via jmx. Set to `false` to disable statistic recording.
| `false`
| `true`

|===

===== Configure Deep Dive Tool URL

In order to access flow related graphs from _{opennms-product-name}_ web interface, a valid `flowGraphUrl` needs to be configured.
It needs to have $nodeId and $ifIndex as place holders which will be replaced by resulting values from graphs.

----
$ ssh -p 8101 admin@localhost
...
admin@opennms()> config:edit org.opennms.netmgt.flows.rest
admin@opennms()> config:property-set flowGraphUrl 'http://localhost:3000/dashboard/flows?node=$nodeId&interface=$ifIndex'
admin@opennms()> config:update
----

NOTE: Configure flowGraphUrl with a valid deep dive tool url with placeholders `$nodeId` and `$ifIndex`. It can also have optional variables $start, $end.

===== Configure NetFlow v5 Listener on a Minion

To enable and configure an _UDP Listener_ for NetFlow v5 on Minion, connect to the _Karaf Console_ and set the following properties:

[source]
----
$ ssh -p 8201 admin@localhost
...
admin@minion()> config:edit org.opennms.features.telemetry.listeners-udp-8877
admin@minion()> config:property-set name Netflow-5
admin@minion()> config:property-set class-name org.opennms.netmgt.telemetry.listeners.udp.UdpListener
admin@minion()> config:property-set listener.port 8877
admin@minion()> config:update
----

TIP: If a configuration management tool is used, the properties file can be created and is used as startup configuration in `${MINION_HOME}/etc/org.opennms.features.telemetry.listeners-udp-8877.cfg`.

[source]
----
name = Netflow-5
class-name = org.opennms.netmgt.telemetry.listeners.udp.UdpListener
listener.port = 8877
----

NOTE: The protocol must also be enabled on _{opennms-product-name}_ for the messages to be processed.
