
// Allow GitHub image rendering
:imagesdir: ../../images

[[ga-opennms-properties]]
=== OpenNMS Properties

The properties file allows you to set global properties for the _{opennms-product-title}_ application.
These properties will be set as system properties at the beginning of Java startup.
Any properties set on the Java command-line with `-Dproperty=value` will be overridden by these values.

[[ga-snmp-settings]]
==== SNMP

OpenNMS provides two different SNMP implementations.
JoeSNMP is the original OpenNMS SNMP Library and provides SNMP v1 and v2 support.
SNMP4J is a new 100% Java SNMP library that provides support for SNMP v1, v2 and v3.

To enable the JoeSnmp library uncomment the following line.
`org.opennms.snmp.strategyClass=org.opennms.netmgt.snmp.joesnmp.JoeSnmpStrategy`

The SNMP4J library is currently the default.
But can also be set with the following line.

`org.opennms.snmp.strategyClass=org.opennms.netmgt.snmp.snmp4j.Snmp4JStrategy`

===== SMI Syntaxes

The world is full of buggy SNMP agents.
We can work around many of their quirks by extending various SMI classes from SNMP4J.
The following property must be set in order for any of these workarounds to be enabled.

`org.snmp4j.smisyntaxes=opennms-snmp4j-smisyntaxes.properties`

=====  Forward Runtime exceptions

When debugging SNMP problems when using the SNMP4J library, it may be helpful to receive runtime exceptions from SNMP4J.
These exceptions almost always indicate a problem with an SNMP agent.
Any that we don't catch will end up in output.log, so they're disabled by default, but they may provide more information (albeit without timestamps) than the messages that SNMP4J logs (see snmp4j.LogFactory).

`org.opennms.snmp.snmp4j.forwardRuntimeExceptions=false`

===== Logging

By default, SNMP4J does not do any logging internally, but it's easy to enable.
See log4j.properties to adjust log levels for these messages.

`snmp4j.LogFactory=org.snmp4j.log.Log4jLogFactory`

===== Allow 64bit IP Addresses

Net-SNMP agents prior to release 5.4.1 on 64-bit platforms exhibit a bug that causes the discovery of a node's interfaces to fail.
A workaround has been made that helps SNMP4J cope with this bug.
If for some reason you need to disable this workaround, comment out the following line.

`org.opennms.snmp.workarounds.allow64BitIpAddress=true`

===== Allow Zero Length IP Addresses

DrayTek Corporation, Router Model: Vigor2820 Series devices with a sysObjectID of `.1.3.6.1.4.1.7367` sometimes present objects from the ipAddrTable with an instance ID of "0".
To substitute a valid (though still dodgy) value of `0.0.0.0` when we encounter one of these, set the following property to true.

`org.opennms.snmp.workarounds.allowZeroLengthIpAddress=true`

===== noGetBulk

Some SNMP agents claim to support SNMPv2c, but either completely fail to respond to GET-BULK requests or return bad responses to them under some conditions.
To disable the use of GET-BULK PDUs globally in the SNMP4J strategy, set this property to true.
This change will adversely affect the efficiency of SNMP data collection from agents that properly support GET-BULK.

`org.opennms.snmp.snmp4j.noGetBulk=false`

==== Allow v2 in v1

Some buggy SNMP agents fail to exclude Counter64 objects from view when responding to SNMPv1 requests (as mandated by RFC3584 ยง 4.2.2.1).
To relax handling of v1 responses to permit Counter64 varbinds rather than discarding them as ill-formed (per the same RFC), set this property to true.

`org.opennms.snmp.snmp4j.allowSNMPv2InV1=false`
