[[core-docker]]
= Core Docker
:description: Learn about startup arguments and environment variables for the Docker with the {page-component-title} core.

== Startup arguments

These startup arguments can be passed in the `command` definition of the Docker Compose file.

[options="header, %autowidth"]
|===
| Argument | Description

| `-h`
| Display help with available arguments.

| `-f`
| Start the process in the foreground and use existing data and configuration.

| `-i`
| One-time command to initialize or update database and configuration files and do *NOT* start.

| `-s`
| Command to initialize or update database and configuration files and start OpenNMS in the foreground.

| `-t`
| One-time command to run the config-tester against the configuration.
|===

== Directory conventions

The containerized version of {page-component-title} provides some extra mount points that can be used to persist data and configuration.

[options="header, %autowidth"]
|===
| Mountpoint | Description

| /opt/opennms-overlay
| Files placed here will be copied to `$\{OPENNMS-HOME}` on container startup.

| /opennms-data
| Directory with RRDTool/JRobin files and generated PDF reports sent to the file system.
|===

== Configuration settings

{page-component-title} containers utilize confd to apply select configuration options to the container.
These settings can either be set in the `docker-compose.yml` as environment variables, or through a mapped YAML file.
See the <<configuration-options>> section below for possible values.

If you want to use a separate YAML to define configuration, the following files must be mounted:

* A yaml file to the following path: `/opt/opennms-overlay/confd/{page-component-name}-config.yaml`.
* A file mapped to `/etc/confd/confd.toml` with the following contents:
+
[subs="attributes"]
----
confdir = "/etc/confd"
backend = "file"
file = ["/opt/opennms-overlay/confd/{page-component-name}-config.yaml"]
log-level = "info"
----

Make sure the path of the `file` property matches the location where you have mounted this file.

IMPORTANT: Directly overlaying specific configuration files overwrites corresponding configurations provided by confd.

When defining the `{page-component-name}-config.yaml` file, use the table below as a reference for the key values.
Replace any `_` with a tree structure using the following as an example.

.`OPENNMS_DBNAME` translates to:
[source, yaml]
----
opennms:
  dbname: opennms
----

.`OPENNMS_DATABASE_CONNECTION_MAXPOOL` translates to:
[source, yaml]
----
opennms:
  database:
    connection:
      maxpool: 50
----

== Configuration options

=== Java options

|===
| Environment variable | Description |  Default value

3+| *Optional*

| JAVA_OPTS
| Allows you to add additional Java options.
This option is only available as an environment variable, and not via a YAML config file.
|
|===

=== PostgreSQL connection configuration

These options are written to `$\{OPENNMS_HOME}/etc/opennms-datasources.xml`.

[options="header, %autowidth"]
|===
| Environment variable | Description |  Default value

3+| *Required*

| OPENNMS_DBNAME
| Database name used for {page-component-title} Core instance
|

| OPENNMS_DBUSER
| Username with access to the database
|

| OPENNMS_DBPASS
| Password for user with acccess to the database
|

| POSTGRES_HOST
| Host with the PostgreSQL server instance running
|

| POSTGRES_USER
| PostgreSQL super user to initialize database schema specified in `OPENNMS_DBNAME`
|

| POSTGRES_PASSWORD
| PostgreSQL super user password
|

3+| *Optional*

| POSTGRES_PORT
| PostgreSQL server port
| 5432

| POSTGRES_SSL_MODE
| PostgreSQL SSL connection mode.
See the link:https://jdbc.postgresql.org/documentation/ssl/[PostgreSQL documentation] for available options.
| disable

| POSTGRES_SSL_FACTORY
| PostgreSQL SSL socket factory
| org.postgresql.ssl.LibPQFactory

| OPENNMS_DATABASE_CONNECTION_POOLFACTORY
| Database connection pool factory
| org.opennms.core.db.HikariCPConnectionFactory

| OPENNMS_DATABASE_CONNECTION_IDLETIMEOUT
| Database connection pool idle timeout
| 600

| OPENNMS_DATABASE_CONNECTION_LOGINTIMEOUT
| Database connection pool login timeout
| 3

| OPENNMS_DATABASE_CONNECTION_MINPOOL
| Minimal connection pool size
| 50

| OPENNMS_DATABASE_CONNECTION_MAXPOOL
| Maximum connection pool size
| 50

| OPENNMS_DATABASE_CONNECTION_MAXSIZE
| Maximum connections
| 50
|===

=== Timeseries storage configuration

These options are written to `$\{OPENNMS_HOME}/etc/opennms.properties.d/_confd.timeseries.properties`.

[options="header, %autowidth"]
|===
| Environment variable | Description |  Default value

3+| *Optional*

| OPENNMS_TIMESERIES_STRATEGY
| Used Timeseries storage strategy
| rrd

| OPENNMS_RRD_STOREBYFOREIGNSOURCE
| Store timeseries data by foreign source instead of the database node id
| true

| OPENNMS_RRD_STRATEGYCLASS
| Java RRD Strategy class
| org.opennms.netmgt.rrd.rrdtool.MultithreadedJniRrdStrategy

| OPENNMS_RRD_INTERFACEJAR
| Java RRD Interface library
| /usr/share/java/jrrd2.jar

| OPENNMS_LIBRARY_JRRD2
| JRRD2 library path
| /usr/lib64/libjrrd2.so
|===

=== SNMP trap receiver configuration

These options are written to `$\{OPENNMS_HOME}/etc/trapd-configuration.xml`.

[options="header, %autowidth"]
|===
| Environment variable | Description | Default value

3+| *Optional*

| OPENNMS_TRAPD_ADDRESS
| Listen interface for SNMP Trapd
| *

| OPENNMS_TRAPD_PORT
| Port to listen for SNMP traps
| 1162

| OPENNMS_TRAPD_NEWSUSPECTONTRAP
| Create new suspect event-based trap recipient for unknown devices.
| false

| OPENNMS_TRAPD_INCLUDERAWMESSAGE
| Preserve raw messages in SNMP traps.
| false

| OPENNMS_TRAPD_THREADS
| Set maximum thread size to process SNMP traps.
| 0

| OPENNMS_TRAPD_QUEUESIZE
| Set maximum queue for SNMP trap processing.
| 10000

| OPENNMS_TRAPD_BATCHSIZE
| Set batch size for SNMP trap processing.
| 1000

| OPENNMS_TRAPD_BATCHINTERVAL
| Set batch processing interval in milliseconds.
| 500
|===

=== Karaf Shell configuration

These options are written to `$\{OPENNMS_HOME}/etc/org.apache.karaf.shell.cfg`.

[options="header, %autowidth"]
|===
| Environment variable | Description |  Default value

3+| *Optional*

| OPENNMS_KARAF_SSH_HOST
| Listen interface for Karaf shell
| 0.0.0.0

| OPENNMS_KARAF_SSH_PORT
| SSH port for Karaf shell
| 8101
|===

=== Cassandra and Newts configuration

These options are written to `$\{OPENNMS_HOME}/etc/opennms.properties.d/_confd.newts.properties`.

[options="header, %autowidth"]
|===
| Environment variable | Description | Default value

3+| *Optional*

| REPLICATION_FACTOR
| Set Cassandra replication factor for the newts keyspace if Newts is used.
| 1

| OPENNMS_CASSANDRA_HOSTNAMES
| A comma-separated list with Cassandra hosts for Newts
| localhost

| OPENNMS_CASSANDRA_KEYSPACE
| Name of the keyspace used by Newts
| newts

| OPENNMS_CASSANDRA_PORT
| Cassandra server port
| 9042

| OPENNMS_CASSANDRA_USERNAME
| Username with access to Cassandra
| cassandra

| OPENNMS_CASSANDRA_PASSWORD
| Password for user with access to Cassandra
| cassandra
|===

=== Daemon control

Select daemons are able to be enabled or disabled through the container definition with the following boolean variables.

[options="header, %autowidth"]
|===
| Environment variable

| *Optional*

| OPENNMS_DAEMONS_CORRELATOR

| OPENNMS_DAEMONS_ENLINKD

| OPENNMS_DAEMONS_SNMPPOLLER

| OPENNMS_DAEMONS_SYSLOGD

| OPENNMS_DAEMONS_TELEMETRYD

| OPENNMS_DAEMONS_TICKETER

| OPENNMS_DAEMONS_TRAPD
|===

=== RRD/RRA definitions

Data collection retention RRA definitions can only be defined via `{page-component-name}-config.yaml` and not by environment variables.
If RRA definitions are provided, any `<rra>` elements will be replaced across all `\*datacollection*` files and any files located in `$\{OPENNMS_HOME}/etc/\*datacollection*.d/` subdirectories.
This does not change the RRA definitions for pollerd services.

IMPORTANT: If you change the RRA definitions once datacollection has already run, you will need to manually delete any existing RRD/JRB files so they can be recreated with the new definition.
No new metrics will be collected until the files are deleted or the RRA definitions reverted back to their previous values.

WARNING: If you want to have different RRA definitions for different collections, do not use this setting and instead overlay the specific config files as necessary.

[source, yaml]
----
opennms:
  rrd:
    rras:
      - RRA:AVERAGE:0.5:1:2016
      - RRA:AVERAGE:0.5:12:1488
      - RRA:AVERAGE:0.5:288:366
      - RRA:MAX:0.5:288:366
      - RRA:MIN:0.5:288:366
----

=== Kafka broker configuration

Kafka broker settings can only be defined via `{page-component-name}-config.yaml` and not by environment variables.
These options are written to `$\{OPENNMS_HOME}/etc/opennms.properties.d/_confd.kafka.properties`.

[source, yaml]
----
opennms:
  instance_id: "<id>" <1>
ipc:
  kafka:
    bootstrap.servers: <2>
      - broker1:9092
      - broker2:9092
    key: value <3>
  sink: <4>
    initialSleepTime: 66666
    kafka:
      key: value <5>
----
<1> If modifying the instance ID, make sure to set the same ID on the Minion configs.
<2> If you have multiple Kafka brokers in your cluster, {page-component-title} will attempt to connect to each listed server in order.
The first broker server to respond will be used to provide a full list of all brokers in the cluster.
<3> Any settings defined within this section will be written as `org.opennms.core.ipc.kafka.key=value`.
<4> You can also define `ipc.rpc.kafka.\*`, `ipc.sink.kafka.\*`, and `ipc.twin.kafka.\*`, with a similiar structure, if you want to define different settings for each of those systems.
<5> Any settings defined within this section will be written as `org.opennms.core.ipc.sink.kafka.key=value`.

=== Kafka consumer configuration

Kafka Consumer settings can only be defined via `{page-component-name}-config.yaml` and not by environment variables.

[source, yaml]
----
opennms:
  kafka:
    consumer:
      topic: opennms-kafka-events <1>
      bootstrap.servers: <2>
        - broker1:9092
        - broker2:9092
      key: value <3>
----
<1> Topic will be written to `$\{OPENNMS_HOME}/etc/org.opennms.features.kafka.consumer.cfg`.
<2> If you have multiple Kafka brokers in your cluster, Kafka Consumer will attempt to connect to each listed server in order.
The first broker server to respond will be used to provide a full list of all brokers in the cluster.
This setting will be written to `$\{OPENNMS_HOME}/etc/org.opennms.features.kafka.consumer.client.cfg`.
`$\{OPENNMS_HOME}/etc/featuresBoot.d/kafka-consumer.boot` will also be created when bootstrap servers have been defined.
<3> Any settings defined within this section will be written as `key=value` to `$\{OPENNMS_HOME}/etc/org.opennms.features.kafka.consumer.client.cfg`.

=== Elastic flows configuration

Elastic settings can only be defined via `{page-component-name}-config.yaml` and not by environment variables.

[source, yaml]
----
opennms:
  instance_id: "<id>" <1>
elastic:
  flows:
    hosts: <2>
    - host: http://elastic:9200 <3>
      username: elastic
      password: e1@stic
    - host: broker2:9092
    key: value <4>
----
<1> If an instance ID is present, it will be used as an index prefix.
<2> If you have multiple Elastic servers in your cluster, {page-component-title} will attempt to connect to each listed server in order.
The first  server to respond will be used to provide a full list of all servers in the cluster.
<3> If your Elastic servers require credentials, you can define `username` and `password` values which will be written to `$\{OPENNMS_HOME}/etc/elastic-credentials.xml`.
Alternatively, you can define `globalElasticUser` and `globalElasticPassword` in the config section to define one set of credentials to use across all Elastic servers.
<4> Any settings defined within this section will be written as `key=value` to `$\{OPENNMS_HOME}/etc/org.opennms.features.flows.persistence.elastic.cfg`.

=== System properties

System properties can only be defined via `{page-component-name}-config.yaml` and not by environment variables.
These options are written to `$\{OPENNMS_HOME}/etc/opennms.properties.d/_confd.custom.properties`.
Any valid {page-component-title} property can be passed.

[source, yaml]
----
opennms:
  properties:
    key: value
----
